### ISSUE TITLE
Enable automatic encryption of state stores

### ISSUE THREAD

**Issue by jeffhollan** [dapr/dapr#1090]
## In what area(s)?

/area runtime

## Describe the feature
Today dapr enables you to store and fetch state and potentially encrypt yourself.  While feasible to encrypt and decrypt before `/state` calls, it's be great if dapr had a way to configure the `state` component with encryption and have it automatically be encrypted and decrypted for me.

**Comment by yaron2** [comment]
/cc @msfussell 

This is a low hanging fruit, can be implemented in the runtime itself (covering all current and future state stores) and encrypt data-at-rest for state stores as well as data-in-transit (mTLS).

**Comment by amanbha** [comment]
Use user provided key from secret store to encrypt the date before saving. Then use they same key to decrypt it before returning it to user on a get cakk.

**Comment by yaron2** [comment]
Triaged into 1.4. /cc @artursouza

**Comment by rovangju** [comment]
I'd be concerned about performance implications of an 'all or nothing' state store; or, I guess having to run two state store configurations to get around that, but ... Would it be worthwhile to entertain the ability to opt-in to an 'encryption enabled' state store via a parameter passed with the SDK state calls?

**Comment by yaron2** [comment]
> I'd be concerned about performance implications of an 'all or nothing' state store; or, I guess having to run two state store configurations to get around that, but ... Would it be worthwhile to entertain the ability to opt-in to an 'encryption enabled' state store via a parameter passed with the SDK state calls?

Encryption will be opt in, not enabled by default, and will be enabled either by configuring the state store component globally or on a per call basis using metadata.

**Comment by yaron2** [comment]
## Design proposal

### Overview

This design proposal aims to capture the following assumptions:

1. The configuration of automatic encryption should be *simple* for both developers and operators
2. Have "best practices" in mind regarding security of the encryption key
3. Automatic encryption should be a non-breaking change and an opt-in feature

#### Operator/Developer Workflow

1. Define a secret containing an AES256 encryption key. The secret can be stored in any Dapr supported secret store
2. Add a metadata key/value pair to a secret component, to explicitly specify the intention of binding the encryption key to the state store
3. Save state using the current, unchanged APIs

### Component schema

To enable automatic data encryption for a state store, the following metadata can be added to any Dapr state store:

```yaml
metadata:
- name: encryptionSecretRef
  value: encryptionKey
```

In order to promote best practices, users will not be able to put an encryption key in plain-text in the `value` field.

### Secret schema

Dapr will require a secret to be created that holds the encryption key. For secret stores that support multiple keys, any named key can be given to the field that holds the encryption key.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: encryptionKey
type: kubernetes.io/tls
data:
  key: MIIC2DCCAcCgAwIBAgIBATANBgkqh ...
```

### Runtime behavior

If an encryption key was referenced on a state store component, `daprd` will try to extract the secret. If it fails, the sidecar will log a fatal error and exit, as the user's intent was to encrypt data and further operations would conflict with the explicitly set security policy.

### Per call encryption

In the future, per call encryption can be enabled using metadata in the state call. I suggest to start with globally set, opt-in encryption and gather feedback to see if per-call encryption is needed and why.

**Comment by artursouza** [comment]
> ## Design proposal
> ### Overview
> This design proposal aims to capture the following assumptions:
> 
> 1. The configuration of automatic encryption should be _simple_ for both developers and operators
> 2. Have "best practices" in mind regarding security of the encryption key
> 3. Automatic encryption should be a non-breaking change and an opt-in feature
> 
> #### Operator/Developer Workflow
> 1. Define a secret containing an AES256 encryption key. The secret can be stored in any Dapr supported secret store, and only there
> 2. Add a metadata key/value pair to a state store component, to explicitly specify the intention of binding the encryption key to the state store
> 3. Save state using the current, unchanged APIs
> 
> ### Component schema
> To enable automatic data encryption for a state store, the following metadata can be added to any Dapr state store:
> 
> ```yaml
> metadata:
> - name: encryptionSecretRef
>   value: encryptionKey
> ```
> 
> In order to promote best practices, users will not be able to put an encryption key in plain-text in the `value` field.
> 
> ### Secret schema
> Dapr will require a secret to be created that holds the encryption key. For secret stores that support multiple keys, any named key can be given to the field that holds the encryption key.
> 
> ```yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: encryptionKey
> type: Opaque
> data:
>   key: MIIC2DCCAcCgAwIBAgIBATANBgkqh ...
> ```
> 
> ### Runtime behavior
> If an encryption key was referenced on a state store component, `daprd` will try to extract the secret. If it fails, the sidecar will log a fatal error and exit, as the user's intent was to encrypt data and further operations would conflict with the explicitly set security policy.
> 
> ### Per call encryption
> In the future, per call encryption can be enabled using metadata in the state call. I suggest to start with globally set, opt-in encryption and gather feedback to see if per-call encryption is needed and why.


Can the encryption algorithm also be a setting? We can say that AES256 is the only one supported for now. It also brings the topic about asymmetric encryption, which takes in a public (to encrypt) and private (to decrypt) keys. Maybe encryption can be its own CRD and allow it to be extensible for multiple algorithms.

**Comment by yaron2** [comment]
> > ## Design proposal
> > ### Overview
> > This design proposal aims to capture the following assumptions:
> > 
> > 1. The configuration of automatic encryption should be _simple_ for both developers and operators
> > 2. Have "best practices" in mind regarding security of the encryption key
> > 3. Automatic encryption should be a non-breaking change and an opt-in feature
> > 
> > #### Operator/Developer Workflow
> > 
> > 1. Define a secret containing an AES256 encryption key. The secret can be stored in any Dapr supported secret store, and only there
> > 2. Add a metadata key/value pair to a state store component, to explicitly specify the intention of binding the encryption key to the state store
> > 3. Save state using the current, unchanged APIs
> > 
> > ### Component schema
> > To enable automatic data encryption for a state store, the following metadata can be added to any Dapr state store:
> > ```yaml
> > metadata:
> > - name: encryptionSecretRef
> >   value: encryptionKey
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In order to promote best practices, users will not be able to put an encryption key in plain-text in the `value` field.
> > ### Secret schema
> > Dapr will require a secret to be created that holds the encryption key. For secret stores that support multiple keys, any named key can be given to the field that holds the encryption key.
> > ```yaml
> > apiVersion: v1
> > kind: Secret
> > metadata:
> >   name: encryptionKey
> > type: Opaque
> > data:
> >   key: MIIC2DCCAcCgAwIBAgIBATANBgkqh ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Runtime behavior
> > If an encryption key was referenced on a state store component, `daprd` will try to extract the secret. If it fails, the sidecar will log a fatal error and exit, as the user's intent was to encrypt data and further operations would conflict with the explicitly set security policy.
> > ### Per call encryption
> > In the future, per call encryption can be enabled using metadata in the state call. I suggest to start with globally set, opt-in encryption and gather feedback to see if per-call encryption is needed and why.
> 
> Can the encryption algorithm also be a setting? We can say that AES256 is the only one supported for now. It also brings the topic about asymmetric encryption, which takes in a public (to encrypt) and private (to decrypt) keys. Maybe encryption can be its own CRD and allow it to be extensible for multiple algorithms.

It could, but looking at bring-your-own-key solutions in the major cloud providers, an AES256 seems to be the only option (references [here](https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys.html) and [here](https://docs.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-tde-overview?tabs=azure-portal).

Since this is considered a standard encryption algorithm, I would rather not create a new CRD (with additional maintenance and RBAC considerations) just for this purpose. If in the future we do make the algorithm configurable, this can be an additional metadata setting.

**Comment by artursouza** [comment]
We might be able to change the design to incorporate multiple algorithms later on. One more thing that crossed my mind - which might be a bigger deal here - is key rotation. We need somehow be able to encrypt new values with the most recent version of the key while decrypting with an older version. Since data is persisted, this needs to be handled early on.

**Comment by yaron2** [comment]
> We might be able to change the design to incorporate multiple algorithms later on. One more thing that crossed my mind - which might be a bigger deal here - is key rotation. We need somehow be able to encrypt new values with the most recent version of the key while decrypting with an older version. Since data is persisted, this needs to be handled early on.

As discussed offline, we will append the key name used to encrypt the data record to the base64 encoded value using a separator. That way, both `daprd` and users consuming the data outside of Dapr can have the encryption key reference.
