### ISSUE TITLE
Move prometheus annotation from service to pod level

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1232]
## In what area(s)?

/area sidecar-injector

## What version of Dapr?

master

## Expected Behavior

1. oms agent for azuremonitor scrape prometheus endpoint

## Actual Behavior

1. oms agent for azuremonitor cannot scrape prometheus endpoint because azure monitor sees annotation in Pod level.

## Steps to Reproduce the Problem

1. deploy dapr to aks where azure monitor is enabled.

**Comment by yaron2** [comment]
We shouldn't move it, at minimum we should add to the pod level. but I wouldn't touch a user's resource on their behalf. Since Dapr managed the services, it's fine to do whatever we want with them.

I think that we should add in our docs an explicit saying that to use Azure Monitor + Prometheus, you need to add a pod level annotation.

**Comment by youngbupark** [comment]
> We shouldn't move it, at minimum we should add to the pod level. but I wouldn't touch a user's resource on their behalf. Since Dapr manages the services, it's fine to do whatever we want with them.
> 
> I think that we should add in our docs an explicit saying that to use Azure Monitor + Prometheus, you need to add a pod level annotation.

that makes sense. we can document it.
