### ISSUE TITLE
Windows powershell installer broken?

### ISSUE THREAD

**Issue by MistrBurns** [dapr/dapr#1658]
Hi!

I just tried to install the dapr cli onto my Windows 10 (64-bit Pro) machine, but  it seems the aws server determined by the script is unreachable and the script fails when trying to fetch the windows_amd64.zip.

## Expected Behavior

Execute Powershell script to install dapr cli.

## Actual Behavior

Script fails due to unreachable web server

## Steps to Reproduce the Problem

1. Open PS
2. from docs => execute: powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"

## Output from the script on my machine:
<pre>
PS C:\Windows\system32> powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"
Installing Dapr...
Creating c:\dapr directory
Downloading c:\dapr\dapr_windows_amd64.zip ...
Invoke-WebRequest : The remote name could not be resolved: 'github-production-release-asset-2e65be.s3.amazonaws.com'
At line:69 char:1
+ Invoke-WebRequest -Headers $githubHeader -Uri $windowsAsset.url -OutF ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
</pre>

**Comment by yaron2** [comment]
Can you try again so we can make sure this isn't a sporadic GitHub issue?

**Comment by MistrBurns** [comment]
I just tried again, same error. Seems to be a persistent issue.

**Comment by MistrBurns** [comment]
Just tried installing on a different machine, there it works. I will try to investigate the issue, might be a network/dns issue. Issue can be closed.

**Comment by tomgron** [comment]
Could you change the suggested command of 

powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"

to following :

powershell **-Executionpolicy RemoteSigned** -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"

The -Executionpolicy needs to be at least RemoteSigned when running the command as it should (also in developer machines) be on pretty high instead of just Bypass

**Comment by christian-be** [comment]
@tomgron I don't think this was the problem, because on both machines I had already set the ExecutionPolicy like you suggested. I also think if this would have been the case, powershell returns pretty specific error-messages.:
```
PowerShell requires an execution policy of 'RemoteSigned'.
To make this change please run:
'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'
```
But since this isn't reproducible anymore (on either machine), I think it was some kind of transient error.

**Comment by iamkut** [comment]
@tomgron  Thanks, your suggestion resolved my issue.
