### ISSUE TITLE
Consider making SetRequest.Value `[]byte` instead of `interface{}`.

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#1793]
## In what area(s)?

/area runtime

## Describe the proposal

Consider making SetRequest.Value `[]byte` instead of `interface{}`.

In some cases this may reduce the type conversions that are needed.

/cc @yaron2

**Comment by skyao** [comment]
I'm also confused by the type of SetRequest.Value:

- it always should be byte[] from http and gRPC sdk remote request
- but it's defined as interface{}, and we have to convert it to []byte

And I try to fix this issue and replace the interface{} with []byte, but there are too many unit test case need to fix. 

So, what's the conclusion for this data type of SetRequest.Value? Should it be interface{} (support not only []byte) or fixed to by []byte? 

@yaron2 This issue is open for so long time without any action.

**Comment by skyao** [comment]
So, in original design, this SetRequest.Value field should be an interface{} to support more than []byte, but later change to only support []byte.

I'm interested with this issue because now we need to support more data type: both for key (now only string is supported) and value (now only []byte is supported). Of cause we can convert anything to string and []byte, but since then we lost the data type information.
