### ISSUE TITLE
Refactor to move gRPC middleware code to components_contrib

### ISSUE THREAD

**Issue by Haishi2016** [dapr/dapr#1857]
The gRPC middleware code should be organized in the same way as the HTTP middleware.

**Comment by tcnghia** [comment]
Talked with @yaron2: the grpc core component living in dapr/dapr should stay there, so there isn't much that needs to be moved to component-contribs. @yaron2 Please correct me if my summary is incorrect.

If this is a pure refactoring effort, maybe the priority should be lowered to P2? E2E tests / unit tests / other stability improvements / important features should have a higher priority due to more tangle impact. We could also refactor as needed when adding unit tests, for example.

@msfussell @youngbupark WDYT?

**Comment by youngbupark** [comment]
@yaron2 I would think that we need to keep it open, but put it as P2.

**Comment by darren-fu** [comment]
any news about this topic？
