### ISSUE TITLE
dapr dashboard crashes in kubernetes env

### ISSUE THREAD

**Issue by vinayada1** [dapr/dapr#1878]
## In what area(s)?

> /area dashboard

## What version of Dapr?

>0.9.0

## Expected Behavior

Dapr dashboard should initialize properly

## Actual Behavior

Seeing this:-
NAME                                     READY   STATUS         RESTARTS   AGE
dapr-dashboard-66d748c75-bfdzs           0/1     ErrImagePull   0          42s
dapr-operator-7d85cc6fb4-45xls           1/1     Running        0          42s

Logs:-
~/dapr/dapr % k logs dapr-dashboard-66d748c75-bfdzs -n dapr-system
Error from server (BadRequest): container "dapr-dashboard" in pod "dapr-dashboard-66d748c75-bfdzs" is waiting to start: trying and failing to pull image

## Steps to Reproduce the Problem

1. Deployed dapr master branch using the steps below:
https://github.com/dapr/dapr/blob/master/docs/development/developing-dapr.md#developing-on-kubernetes-environment
2. Check the deployment
kubectl get pods -n dapr-system

**Comment by shalabhms** [comment]
@willdavsmith , can you take a look ?

**Comment by amanbha** [comment]
As per the development guide, for using locally built images, container registry is changed to users registry by using `export DAPR_REGISTRY=docker.io/<your_docker_hub_account>`. The build commands then pushes the images to that container registry. Dashboard is not built in this repo so its images are not pushed to user configured registry. dashboard images should always come from official registry, 
makefile taarget `docker-deploy-k8s` sets the registry to user configured repo https://github.com/dapr/dapr/blob/master/Makefile#L196
It would need a change in helm chart for dashboard to always pull from official repo rather than user configured repo.

**Comment by willdavsmith** [comment]
@amanbha , should we make that change along with Dashboard 0.2.0 release? Seems like it should be a simple fix.

**Comment by amanbha** [comment]
> @amanbha , should we make that change along with Dashboard 0.2.0 release? Seems like it should be a simple fix.

Yes, sounds good.
