### ISSUE TITLE
About AppChannel

### ISSUE THREAD

**Issue by hongjic** [dapr/dapr#2005]
Hi all, our team and I have been playing with Dapr for a while and we have a question about the `AppChannel`.

For the http channel implementation, all requests go through the `InvokeMethod` API and that works fine. For the grpc implementation, only service method invokation is implemented base on `AppChannel`, all other rpc calls like `ListTopicSubscriptions` simply go through the raw grpc client.  This makes mocking certain app api unnecessarily complex since we need to mock GRPC app and http app separately. 

Ideally, `AppChannel` should be the layer that abstract away all communications to the App Process and provide a set of APIs just like the grpc AppCallbackClient does (I mean same for http). 

Based on this cleaner layered abstraction, we can start experimenting with some more interesting ideas, such as:
1) use different transport/protocol implementation. HTTP is too heavy.
2) local message passing.

Any thoughts on this?

**Comment by youngbupark** [comment]
@hongjic That's good suggestion. e.g. Having the abstraction layer, you would probably use light protocol, e.g. unix-socket, to communicate with your app.

As you see, AppChannel design is pretty generic, which we could extend to the other protocol relatively easy. But we are heading to 1.0 release now so that we do not have the time to consider design change.

BTW, can you elaborate more on your application scenario ?

cc/ @yaron2 @orizohar @msfussell @mchmarny
