### ISSUE TITLE
Add ContentType to state 

### ISSUE THREAD

**Issue by mukundansundar** [dapr/dapr#2026]
## In what area(s)?

/area runtime

## Describe the proposal
For state changes, Add ContentType to state. 
This is allow for better abstraction and deserialization binary values if the SDKs know what type the value of the content is.

**Comment by artursouza** [comment]
I did a look at the runtime code and API to understand the implication of adding content-type to state and (potentially) other building blocks. Here are my findings:

0. `content-type` should be optional, otherwise it will increase the bar for adoption.

1. 'content-type' here does not mean the content of the `data` attribute, it means the language specific type that will help the SDK deserialize the data correctly. So, content-type is not a good name and quickly conflicts with 'content-type' header in the HTTP protocol. This header should be named something else, maybe `dapr-object-type`. We can come up with a list of "types" that can be generic across languages but that will probably not be perfect. I will still refer to it as `content-type` in this doc to avoid confusion but we should name it something else.

2. Adding `content-type` to state API will create a parallel need for storage (parallel to the data). Components will now need to create a way to persist `content-type` (or even other metadata attributes). It might become a new column or a new table, depending on the component. It raises the bar for contributing and maintaining components. In other words, this is a breaking change where components will (1) be non-compliant or (2) need to be re-designed to consider metadata storage.

3. Adding `content-type` opens a new problem: future and backwards compatibility for metadata. Adding to item above. Persisted metadata has a long support problem since they are harder to deprecate. A metadata key or value might need to be supported "forever" or allow to be extensible for new values for a given key.

4. [PubSub] Adding persisted metadata to PubSub is possible but only if component can support metadata (like Kafka does support custom headers, for example: https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers).

5. [Bindings] Binding is handled similar to [PubSub], where `content-type` can be handles as custom header or metadata if component supports it.

I see a few options for us to proceed here:

1. Document `dapr-object-type` as a "persisted" metadata that components can handle (persist) on any building block. Later on, we can add more "persisted" metadata.
2. Create `objectType` attribute in every request/response object in HTTP and GRPC (similar to what we do with eTag).
3. Do not change runtime and handle the byte deserialization problem in the SDKs. Users already provide the type they expect to get for deserialization, so the SDK can have a special check for `byte[]` and decode Base64 from JSON. GRPC is not affected today.

Given that this problem is limited to byte[] in JSON only, I recommend solution 3. Persisting metadata will open a can of worms and I do not see a big benefit to solve this problem. If we have a more compelling scenario later we can revisit this.

**Comment by yaron2** [comment]
lgtm on 3.

**Comment by rynowak** [comment]
> This is allow for better abstraction and deserialization binary values if the SDKs know what type the value of the content is.

Do we have examples of what we think **better deserialization of binary values** means?

**Comment by artursouza** [comment]
> > This is allow for better abstraction and deserialization binary values if the SDKs know what type the value of the content is.
> 
> 
> 
> Do we have examples of what we think **better deserialization of binary values** means?

Yes. It means getting a base64 encoded string from dapr's Java Http API and not knowing if it is supposed to be a String to decoded to byte[]. We can add a check to determine if users want a byte[] back and decode in the SDK prior to returning the value to the app.

**Comment by youngbupark** [comment]
Solution 3 looks good to me. @artursouza can you please create ADR once the decision is made?

**Comment by mukundansundar** [comment]
Solution 3 looks good.

**Comment by rynowak** [comment]
> > > This is allow for better abstraction and deserialization binary values if the SDKs know what type the value of the content is.
> > 
> > 
> > Do we have examples of what we think **better deserialization of binary values** means?
> 
> Yes. It means getting a base64 encoded string from dapr's Java Http API and not knowing if it is supposed to be a String to decoded to byte[]. We can add a check to determine if users want a byte[] back and decode in the SDK prior to returning the value to the app.

Makes sense, no concerns about option 3. `byte[]` <-> `base64 string` is something pretty much all JSON serializers do

**Comment by artursouza** [comment]
See PR above for ADR: https://github.com/dapr/dapr/pull/2053
