### ISSUE TITLE
Allow Freeform Component Metdata

### ISSUE THREAD

**Issue by RichiCoder1** [dapr/dapr#2030]
## In what area(s)?
/area runtime

## Describe the proposal
Currently `component.dapr.io/v1alpha1` `spec.metadata` must be structured as an array of `{ key: string, value: string }` entries. This constrains what information may be provided via metadata and arguable makes component definitions more verbose to read.

I propose `v1alpha2` that supports a `map[string]interface{}`-like freeform dictionary for the spec.metadata field. This would allow a cleaner component definition as well as rich values beyond strings.

**Comment by RichiCoder1** [comment]
It looks like this was done in part to support allowing secret values. I wonder if there's not a better way to enable that?

**Comment by yaron2** [comment]
Mostly due to this: https://github.com/kubernetes/gengo/issues/138

**Comment by RichiCoder1** [comment]
@yaron2 would a `JSON` field with https://github.com/kubernetes-sigs/controller-tools/issues/281 get close? That seems the be "recommendation" for arbitrary objects in a given field.

**Comment by RichiCoder1** [comment]
Apparently there's support for custom marshalling and unmarshalling: https://github.com/mongodb/mongodb-kubernetes-operator/pull/134/files#diff-49c488ba1252fd36602f98c8df647f9eR74

Not sure if that'd meet that same need.

**Comment by RichiCoder1** [comment]
Another option would be to have Dapr dynamically managed CRDs for components: https://github.com/open-policy-agent/gatekeeper/blob/master/pkg/controller/constrainttemplate/constrainttemplate_controller.go

But that seems like a massive amount of work 😅.

**Comment by yaron2** [comment]
Per component CRDs would result in 10s or 100s of CRDs, and user feedback has been that the single component CRD is a low maintenance preferred solution. 

There is a way to do this, basically patch up the generated files manually and write the correct deep copying logic. This is possible because k8s-codegen will still autogenerate the files, they just will not compile due to errors in the DeepCopy function for map[string]interface{} fields.

So essentially write a tool that generates and files and then patches up required places in the code.

**Comment by yaron2** [comment]
Closed with https://github.com/dapr/dapr/pull/2228
