### ISSUE TITLE
Actor Reminder not persisting

### ISSUE THREAD

**Issue by aktxyz** [dapr/dapr#2049]
## In what area(s)?

/area runtime

## What version of Dapr?

0.10.0-preview01

## Expected Behavior

reminder should persist and keep firing on restart and no error should be shown

## Actual Behavior

reminder does not keep firing on restart and an error is shown

## Steps to Reproduce the Problem

The test case is basically a fork of the dapr/dotnet-sdk repo ...

modified repo
https://github.com/aktxyz/dotnet-sdk

client changes to make it easier to add/remove reminder
https://github.com/aktxyz/dotnet-sdk/blob/master/samples/Actor/ActorClient/Program.cs#L79

actor change to make it easier to see reminder firing thru console messages
https://github.com/aktxyz/dotnet-sdk/blob/master/samples/Actor/DemoActor/DemoActor.cs#L77

run the server the same way the readme states
```dapr run --dapr-http-port 3500 --app-id demo_actor --app-port 5000 dotnet run```

run the client the same way the readme states
```dotnet run```

add the reminder via the client
```
$ dotnet run
Making call using actor proxy to save data.
Making call using actor proxy to get data.
Received data is PropertyA: ValueA, PropertyB: ValueB.
Making calls to an actor method which has no argument and no return type.
Got Correct Exception from actor method invocation.
Making calls without Remoting.

Enter command (ar=add reminder) (rr=remove reminder) (xx=exit)
ar
AddReminder ...
```

in the server console, you will see the ```!!!! reminder``` printout as the reminder fires
ctrl-c the server
run again
you will see the error 
```level=error msg="could not find active reminder with key: DemoActor||abc||TestReminder"```
and the reminder does not fire

**Comment by youngbupark** [comment]
@aktxyz Thanks for the report. I will reproduce and investigate it in my environment and then update the progress by this week.

**Comment by msfussell** [comment]
@aktxyz Can you try this out again on the v0.11.3 release and see if you can reproduce this?

**Comment by jigargandhi** [comment]
If it is reproducible and unassigned, I can take up the task to fix this.

**Comment by yaron2** [comment]
@jigargandhi I assigned you.

**Comment by jigargandhi** [comment]
The issue is reproducible as mentioned by @aktxyz 
What I see is that the reminder fires atleast once and then the error appears

`== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

== APP ==       Request starting HTTP/1.1 PUT http://127.0.0.1:5000/actors/DemoActor/abc/method/remind/TestReminder application/json 56

== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]

== APP ==       Executing endpoint actors/{actorTypeName}/{actorId}/method/remind/{reminderName} HTTP: PUT

== APP == Actor: abc Activated

== APP == !!!!!!!!!!!!!!!!!!!! ReceiveReminderAsync 637406041257468522

== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

== APP ==       Executed endpoint actors/{actorTypeName}/{actorId}/method/remind/{reminderName} HTTP: PUT

== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

== APP ==       Request finished in 87.6482ms 200

== DAPR == time="2020-11-10T11:22:05.8100291+05:30" level=error msg="could not find active reminder with key: DemoActor||abc||TestReminder" app_id=demo_actor instance=jgandhi-W01 scope=dapr.runtime.actor type=log ver=edge`

I will now look into why the error occurs
