### ISSUE TITLE
http to grpc test does not return error codes other than 2xx

### ISSUE THREAD

**Issue by vinayada1** [dapr/dapr#2121]
## In what area(s)?

> /area test-and-release

## What version of Dapr?

0.11

## Expected Behavior

If the caller side gets an error code, it should be propagated to the end app

## Actual Behavior

The caller side always get success. This is an infra issue and will cause problems for even existing e2e tests if we want to add negative tests

## Steps to Reproduce the Problem

RELEASE NOTE: NOT APPLICABLE

**Comment by mukundansundar** [comment]
Based on the documentation for httpClient.Do https://pkg.go.dev/net/http#Client.Do 

An error is returned if caused by client policy (such as CheckRedirect), or failure to speak HTTP (such as a network connectivity problem). A non-2xx status code doesn't cause an error.

A non-2xx status code from downstream, if not checked based on status code and propagated properly by the caller, will not be propagated as an error.
