### ISSUE TITLE
Better error handling on PubSub receiving a legacy message.

### ISSUE THREAD

**Issue by aronchick** [dapr/dapr#2273]
/area runtime

## Describe the feature
If the message on a pubsub is not a cloudevent (for example, because it was created by a legacy service, not dapr), dapr subscriber fails and does not inform the consumer what the message body is.

## Release Note
RELEASE NOTE: **FIX** Fix the dapr runtime to handle non-json/non-cloud event formatted messages from PubSub.

RELEASE NOTE:

**Comment by youngbupark** [comment]
@mchmarny @yaron2 I know this is by-design because we're expecting that all message subscribed by Dapr is CE formatted message. seems like HTTP and gRPC behavior is different here. HTTP bypass the data to request body and gRPC returns error and print out the error message with Debug level.

Shouldn't we make both behavior consistent or can we wrap non-CE message which the different system/service sends ?

cc/ @msfussell

**Comment by aronchick** [comment]
I'd like to propose that if the payload does not conform to the CE spec, it should just be passed through as is.

**Comment by yaron2** [comment]
> I'd like to propose that if the payload does not conform to the CE spec, it should just be passed through as is.

Just to be clear: today, if the payload does not conform to the CE spec, Dapr puts it in the .data field of a CE envelope and then sends it.

Do you mean that Dapr should not use CE at all?

**Comment by mchmarny** [comment]
@aronchick By design, pub/sub is intended to be used for message passing between services. CE are used there to add context to the content and enable routing without parsing the message. For triggering your code using events from outside of the application you may want to consider binding, which do not wrap the original content into CE.

**Comment by aronchick** [comment]
@yaron2 today, Dapr fails (and delivers nothing) if the payload does not conform to CE.

@mchmarny i'm not sure that's a great solution - are we really saying unless a publisher uses CE, you will get nothing as a subscriber? That seems to leave off an enormous amount of legacy publishers.
