### ISSUE TITLE
sidecar-injector failed to get authentication uid from service account on Typhoon K8s distro

### ISSUE THREAD

**Issue by Liriel** [dapr/dapr#2353]
## In what area(s)?

/area runtime

## What version of Dapr?

0.11.0

## Expected Behavior

`dapr init -k` should start all required components

## Actual Behavior

erverything starts except `dapr-sidecar-injector`

## Steps to Reproduce the Problem

    dapr init -k

wait a bit

    dapr status -k

returns

    NAME                   NAMESPACE    HEALTHY  STATUS                      REPLICAS  VERSION  AGE
    dapr-sidecar-injector  dapr-system  False    Waiting (CrashLoopBackOff)  1         0.11.3   9m 
    dapr-operator          dapr-system  True     Running                     1         0.11.3   9m 
    dapr-sentry            dapr-system  True     Running                     1         0.11.3   9m 
    dapr-dashboard         dapr-system  True     Running                     1         0.3.0    9m 
    dapr-placement         dapr-system  True     Running                     1         0.11.3   9m 

get the logs of the pod 

    kubectl logs -p dapr-sidecar-injector-55c5fbbb9-v2dmp -n dapr-system

brings **failed to get authentication uid from service account: serviceaccounts \"replicaset-controller\" not found**

    time="2020-10-29T12:43:55.22267316Z" level=info msg="log level set to: info" instance=dapr-sidecar-injector-55c5fbbb9-v2dmp scope=dapr.injector type=log ver=0.11.3
    time="2020-10-29T12:43:55.223719992Z" level=info msg="metrics server started on :9090/" instance=dapr-sidecar-injector-55c5fbbb9-v2dmp scope=dapr.metrics type=log ver=0.11.3
    time="2020-10-29T12:43:55.224864169Z" level=info msg="starting Dapr Sidecar Injector -- version 0.11.3 -- commit a1a8e11" instance=dapr-sidecar-injector-55c5fbbb9-v2dmp scope=dapr.injector type=log ver=0.11.3
    time="2020-10-29T12:43:55.230166822Z" level=info msg="Healthz server is listening on :8080" instance=dapr-sidecar-injector-55c5fbbb9-v2dmp scope=dapr.injector type=log ver=0.11.3
    time="2020-10-29T12:43:55.255863265Z" level=fatal msg="failed to get authentication uid from service account: serviceaccounts \"replicaset-controller\" not found" instance=dapr-sidecar-injector-55c5fbbb9-v2dmp scope=dapr.injector type=log ver=0.11.3

I am using [typhoon](https://github.com/poseidon/typhoon/) minimal and free Kubernetes distribution.

    dapr mtls -k

reports 

    Mutual TLS is enabled in your Kubernetes cluster

## Release Note

RELEASE NOTE:

**Comment by Liriel** [comment]
I looked at https://github.com/dapr/dapr/blob/master/pkg/injector/injector.go#L98c - looks like there is no `replicaset-controller` in my service account

    curl -s http://localhost:8001/api/v1/serviceaccounts|jq .items[].metadata.name

gives a short small list (compared to minikube)
```
"dapr-operator"
"dashboard-reader"
"default"
"default"
"my-release-ingress-nginx"
"default"
"default"
"calico-node"
"coredns"
"default"
"kube-proxy"
```

**Comment by XavierGeerinck** [comment]
+1 on this bug at the moment, created a DigitalOcean kubernetes cluster from scratch and just deployed Dapr through the helm charts and this pops up

**Comment by XavierGeerinck** [comment]
@Liriel figured it out and this solved it for me!

So the error that pops up is something like this:

```
time="2020-11-07T11:47:35.255144983Z" level=fatal msg="failed to get authentication uid from service account: serviceaccounts \"replicaset-controller\" not found" instance=dapr-sidecar-injector-55c5fbbb9-p2gn4 scope=dapr.injector type=log ver=0.11.3
```

Which is obviously due to the missing service account `replicaset-controller` which we can check through `kubectl get serviceaccounts -A` which doesn't list this service account. 

Now when going to https://kubernetes.io/docs/reference/access-authn-authz/rbac/#controller-roles it shows that the kubernetes controller manager runs the controllers but only creates the service account `system:controller:replicaset-controller` when it's started with the flag `--use-service-account-credentials`. Without this flag it will run the control loops using its own credential.

The resolution I used is to run this:

```bash
# Create the service account manually
kubectl create serviceaccount replicaset-controller -n kube-system

# Assign the clusterrole binding to it 
# clusterrole = system:controller:replicaset-controller
# check with kubectl get clusterroles
kubectl create clusterrolebinding dapr-replicaset-controller -n default --clusterrole=system:controller:replicaset-controller --serviceaccount=kube-system:replicaset-controller
```

Now the big question that pops up is why this is happening... it seems that in [Azure you have to enable RBAC for this](https://stackoverflow.com/questions/59353819/how-to-bind-roles-with-service-accounts-kubernetes#answer-63750891) but it's also happening for me on DigitalOcean where apparently RBAC is enabled by default... but it might be that they are missing this flag.

The question for @msfussell and team is if Dapr should "hijack" the uid here or create their own service account seeing the nature of Dapr which could benefit for this in terms of security? 

Looking for a more "permanent" resolution here and looking forward to other comments 😊

> Note: I am not a Kubernetes specialist, so I might be completely wrong or missing a command to actually enable this service account in an easier way, so I am definitely open for suggestions!

**Comment by Liriel** [comment]
@XavierGeerinck I can confirm that creating the `replicaset-controller` service account manually leads to the sucessful provisioning of the sidecar-injector pod.

Now get the empty error message when creating a new pod. The sidecar-injector log:
```
time="2020-11-08T10:54:31.212270892Z" level=error msg="<nil>" instance=dapr-sidecar-injector-547784c958-nqbpb scope=dapr.injector type=log ver=0.11.3
time="2020-11-08T10:54:31.212982831Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-547784c958-nqbpb scope=dapr.injector type=log ver=0.11.3
```
It seems that the `AdmissionReview` dies at some point.

**Comment by XavierGeerinck** [comment]
@Liriel indeed, I got the same issue here... looking forward to seeing a reply from the Dapr team 😊 it's a hacky solution in the end to manually create those controllers.

At my end I already contacted the Cloud Provider and they indeed acknowledged that the accounts should be there. Awaiting escalation now to get that resolved.

**Comment by Liriel** [comment]
this is definitly not only a permission issue. I gave the `dapr-operator` service account clusteradmin rights, but my pods still wont get a sidecar.
    kubectl create clusterrolebinding my-dapr-op-adm --clusterrole=cluster-admin --serviceaccount=dapr-system:dapr-operator
also tried to change the `failurePolicy` to "Fail" in the `MutatingWebhookConfiguration` but the sidecar injector still fails silently.

**Comment by yaron2** [comment]
Hi,

As mentioned correctly by both @XavierGeerinck and @Liriel, this is not a permissions issue.

Kubernetes distributions that do not have the service account for the replicaset-controller are exposing users to security risks, namely any pod in the cluster can fake a request to the admission controller which has no way to determine if the request came from the Kubernetes API or from a malicious actor.

Thus, the expected behavior is for failing injections for sidecars if the Dapr sidecar injector can't determine the valid identity of the request carrying the admission review.

**Comment by Liriel** [comment]
#### Starting the controller manager with the `--use-service-account-credentials=true` command line argument resolves the issue.

For **typhoon** in particular you have to alter the `kube-controller-manager.yaml` manifest in `.terraform/modules/mercury.bootstrap/resources/static-manifests/kube-controller-manager.yaml` after you did `terraform init` and before `terraform apply`. (see https://github.com/poseidon/terraform-render-bootstrap/blob/master/resources/static-manifests/kube-controller-manager.yaml)

Is there a way to check if this flag has been enabled when calling `dapr init -k` to return a more helpful error message?

**Comment by XavierGeerinck** [comment]
Thanks @Liriel and @yaron2 for the responses! This is indeed the issue! 

I am however wondering, what can be done in case these are not available by default?

**Comment by tomkerkhove** [comment]
I have the same on an AKS cluster which did not have RBAC enabled. Using a cluster with RBAC enabled fixed it for me.

**Comment by dereknex** [comment]
I have the same on digitalocean k8s cluster. k8s version is v1.19.3

**Comment by mhoad** [comment]
+1 Here on a local Talos managed K8s cluster

**Comment by robinmanuelthiel** [comment]
Still happens on AKS clusters without RBAC enabled...

**Comment by ls-2018** [comment]
+1

**Comment by Rahul-jll** [comment]
I am also facing the same issue on AKS
