### ISSUE TITLE
Improve troubleshooting and finding errors

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#2387]
I'd like to raise a discussion here about how we can make users more successful in finding out different errors in the Dapr sidecar.

An example of this would be the sidecar restarting on Kubernetes due to a failed health check while timing out on component initialization due to a bad config.
In that case, the pod will have restarted and the error log never shown, making it a tedious guess work to find the underlying cause.

**Comment by rynowak** [comment]
This is a similar issue to one I reported here from the last hackathon: https://github.com/dapr/dapr/issues/1868


Some ideas about how to make misconfiguration visible ... these are all my opinions and so I'm looking for more discussion and fleshing out.

**Best**

- Add the concept of a health check for a component (State Store) in this case - this would not affect runtime behavior but would be informational. 
- Add a service that checks the health of registered components and updates events inside the component object so that it can be viewed with Kubectl describe - need a think about how to best represent this for non-k8s 
- Surface this info in the dashboard UI - if we really don't want to have a service that monitors Component health, then it could be a feature of the dashboard (user can choose to query the health status of a component)
- Enrich error messages coming from the Dapr sidecar to reference the fact that the health status of a component *can* be viewed - possibly with a link to the documentation

*My thoughts: it's always bugged me that when I push a Component definition there's no way to check that it's actually working until I deploy some code. It feels like something I should validate up front, but there's no way to do so. Adding diagnostic avenues that allow a developer to follow their intuition is really useful.*

**Less good than this**

- Change to a readiness check for the sidecar rather than a liveness check
- This probably needs to come with the ability for the sidecar to *watch* component definitions because we can no longer rely on the liveness check restarting it
- Add logging around the places where do async initialization of components.. ex: log every 5 seconds, `still waiting for the state store to respond`

*My thoughts: the current assumptions around liveness for the sidecar are true, if your Component definition is wrong then restarting the sidecar *might* fix it. If we change to a model where sidecars are notified of Component definition changes then readiness is a better fit, and solves this problem because the sidecar doesn't get shut down.*

**Less good than that**

- Walk through all of the components and make sure they log a disgusting amount of content on failure
- Add the logging described above (log every 5 seconds while we're waiting for something to initialize)
- At some reasonable threshold of time after start (before the default liveness check would kill it) have the sidecar log its initialize status in table form - what are the things I'm still doing that make me not initialized?

*My thoughts: If we don't want significant changes in architecture and behavior then I think the major avenue we have is to be really intentional about providing logging. It's been the case for me with Dapr (and I think the user that started this discussion) that I go to the logs first when something is failing, but I don't see any information I can take action on - that info is usually buried in an HTTP response to the application.*

**Comment by tcnghia** [comment]
+1 to what @rynowak proposes about surfacing Component Status. On K8s Status Subresource is a common way to do this. If we follow the same practice it will make integration with tooling easier (like `kubectl wait`, `kubectl get`, etc, other Status-aware UIs), as well as making things easier for consumers familiar with K8s. 

The downside of Status Subresource is that there is a learning curve associated with it, and would be a nuisance for users not familiar with K8s.

Implementing a health checker that reaches out to distributed sidecars and collect their state regarding the components is not a trivial task (there are uncertainties due to network issues, stuck sidecar; how to handle sidecars that come up after the Component has declared Ready). However, allowing the users to reason about the state of the various components of their application will be a great value add. 

A common question about using something in production is _"am I comfortable carrying a pager for this infra?"_, which would be hard to say yes to if it is difficult to identify which component of my distributed application is unhealthy.

**Comment by trondhindenes** [comment]
from me:
- improve the "dapr run" output logs. Daprd logs are very readable, but "dapr run" logs are very messy
- implement request logging - at least in the debug and higher log-levels. It must be possible to log (service-to-service invocation, binding invocation etc) when developing apps locally (I tried the python sdk to build a grpc app, and since both the dapr sidecar and the grpc middleware itself is completely silent, there was no way to see what was actually going on, without manually implementing my own logging - I shouldn't have to)

**Comment by trondhindenes** [comment]
@yaron2 about this: 
> In that case, the pod will have restarted and the error log never shown, making it a tedious guess work to find the underlying cause.

kubernetes supports grabbing the log output from the previous container in case of restarts:
`kubectl logs abc -c def --previous`. So even if a pod container restarts, the output isn't lost. In addition, I would assume that most shops implement a centralized log solution based on filebeat or fluentd so that logs are persisted also after the emitting container is gone.
