### ISSUE TITLE
Devcontainer: Shared docker or docker-in-docker?

### ISSUE THREAD

**Issue by issacg** [dapr/dapr#2483]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
I saw that the devcontainer templates for dapr were recently moved to be hosted in the official repo at https://github.com/microsoft/vscode-dev-containers but I had a question around dapr and devcontainers in general...

I only started touching dapr in the last week or so, and spent a considerable amount of time getting stuck trying to run the intro/samples locally inside devcontainers (because that's how I partition my projects).  I'm honestly still not sure I have a handle on running it right; most attempts on the most basic example inside the dapr-node/typescript or a generic shared-docker devcontainer still give me errors at some point or another.

From what I can see, when "installing" dapr in standalone (non-k8s) mode, the expectation is for there to only be a single dapr ecosystem - binaries, config and containers - on a given host.  This makes sense for dedicated setups which use vanilla docker with dapr standalone.  But on a development machine it makes things difficult, as I might have different projects which aren't meant to co-exist within the same dapr environment.  

As such, it would seem to me intuitively that when running inside a devcontainer (where the design pattern of devcontainers is to fully host a given "project" in each devconainer) that sharing the host docker socket doesn't make sense.  A vanilla `dapr init` in devcontainer A would potentially conflict with a `dapr init` in devcontainer B because of container names (`dapr_placement`, `dapr_zipkin`, perhaps `dapr_redis`?) in a best case, and different configs in ~/.dapr in a worse case... 

The current devcontainer setup seeks to mitigate conflicts between the devcontainer and host, at least, by using docker-compose namespaces, but the devcontainer would still conflict with another devcontainer without modifications.

My question is, given the above, if it doesn't make sense to partition development environments with docker-in-docker setups rather than sharing the host docker socket?  Has this been discussed or explored in the past?

Thanks!

**Comment by CodeMonkeyLeet** [comment]
Hi @issacg I'm looking into this question now and would be interested in understanding your scenario. My experience is that the existing devcontainer aims for a "transparent" dev experience rather than providing an isolated test environment and I can see reasons for both. To clarify:

* Is isolation of the container cache for local `dapr init` deployments your primary concern? Or are there other isolation preferences here, for example, the existing devcontainer assumes it is mounted with `--net=host` for network transparency.
* Would you be comfortable with modifying the devcontainer.json contents if there were different options provided to toggle one mode over the other? There are already several there today, though none that provide a docker-in-docker experience.

**Comment by issacg** [comment]
Thank you! I know I haven't been able to be responsive as my day job had me busy, and haven't tried out the codespaces feature yet (because I'm *still* too busy :D) but wanted to say kudos for addressing it anyway 🙏🙏🙏

**Comment by CodeMonkeyLeet** [comment]
@issacg you're welcome! If you do get the chance to try out [Codespaces](https://github.com/features/codespaces/signup) or just the updated devcontainer definition, let me know what you think of the experience!
