### ISSUE TITLE
Dapr Component Reloading

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#2485]
I currently have the use-case where I am developing (sometimes on Kubernetes) an application and want to reload the Dapr sidecar to get a new binding in, or a new pub sub system. However when doing this, it seems that Dapr doesn't automatically detect this.

Some points I would love to discuss about:
* Automatic component reloading when a binding/pubsub/... gets changed through `kubectl apply -f ...` 
* Component specification per application (e.g. I would love to utilize a pubsub in app A but not in app B) - not sure if that's there already
* Versioning of the components

Interesting as well which could be a nice addition is just the reinitialization of the sidecar in a given pod / deployment

What are your opinions around this?

**Comment by XavierGeerinck** [comment]
@mchmarny ;)

**Comment by mchmarny** [comment]
Thanks for writing this up. The component scoping and versioning is already there (examples below). 

Versioning 

```yaml
spec:
  type: state.cassandra
  version: v1
```
Scoping

```yaml
scopes:
  - app2
```

We talked about component reloading a few times now. The tech around watching objects and reloading them in Dapr are actually well understood and not that really complex (I'm told). The complexity lies in in guessing user intend in accounting for the failure modes. For example:

* app breaks on restart because component was renamed
* app availability is impacted because there was 1 replica and we restarted the app 
* data returned by the component (e.g. binding) is in diff format, even though the component name is the same

Can you describe how this would ideally work in your use-case? The more detail around the app and component type the better. Thanks.

**Comment by XavierGeerinck** [comment]
Thanks a lot for providing that, I had no idea! :) 

In regards to the other part, how I currently work in terms of updating components is that I change it and then reapply it. I then would indeed expect a restart of the sidecar without affecting the app (the app would call an endpoint anyways, so I would not expect that one to restart).

For example, I have a pod that gets scaled out by KEDA automatically and reads from a RabbitMQ. I was however utilizing a PubSub component initially and switched it to utilize a Binding instead. 
* When I redeployed the app and the binding afterwards, I would have to re-kill the pod so it would restart with the correct sidecar injection there for the component interaction
* When I wanted to change parameters in the component (e.g. different RabbitMQ due to migration), the pod again had to be killed as in the previous point

In terms of lifecycle, it can indeed be that a wrong update is done of a component, making an unintended change (or impacting multiple components due to the forgotten scope). I honestly have no solution in mind for that, but a potential solution could be to utilize the Dapr CLI for that, triggering a warning when you want to redeploy a component with reloading enabled illustrating which changes will have a breaking change on the deployed cluster applications (I could imagine here that Dapr internally knows which applications use which bindings).

Is this what you were looking for in term of description?

**Comment by mchmarny** [comment]
Yes, thanks for the context

**Comment by artursouza** [comment]
Reopening this issue because this is a common ask. Right now, dapr does not offer auto reloading of components (or hot reloading) because it can be a dangerous behavior in production. There are different update strategies to handle with production changes to avoid a bad config to bring down the app. If we decide to go this route, this feature would only make sense for development scenarios but should be disabled in production.

**Comment by yaron2** [comment]
Tracked here: https://github.com/dapr/dapr/issues/1172.
