### ISSUE TITLE
Run dapr as gateway mode

### ISSUE THREAD

**Issue by qqeasonchen** [dapr/dapr#2500]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

Dapr can run as gateway is popular in some scenarios, can we consider about that? thx.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Can you elaborate? What does gateway mean here?

**Comment by qqeasonchen** [comment]
@artursouza Just like an api gateway, not only a sidecar.

**Comment by attiqeurrehman** [comment]
@artursouza I actually had the same question, because we can invoke application methods via Dapr do we still need an API Gateway for simple scenarios? I can understand the still need of them for BFF but for simple scenarios do we still need it?

Also, what is recommended approach here invoking methods via Dapr or directly or via API Gateway.

**Comment by artursouza** [comment]
@qqeasonchen @attiqeurrehman  This issue seems to be a duplicate of https://github.com/dapr/dapr/issues/1976#issuecomment-683893213

Please, refer to https://carlos.mendible.com/2020/04/05/kubernetes-nginx-ingress-controller-with-dapr/
