### ISSUE TITLE
Dapr does not support Daemonset 

### ISSUE THREAD

**Issue by pzou19741** [dapr/dapr#2637]
Add dapr related to annotation to Deemonset and rollout status indicates success but pod does not add daprd containers

**Comment by pzou19741** [comment]
I  install ingress-nginx as daemonset but without success.

export INGRESS_NAMESPACE="[your namespace]"
helm install nginx ingress-nginx/ingress-nginx \
     --set controller.replicaCount=2 \
     -f ingress-annotations.yaml \
     -n $INGRESS_NAMESPACE

Here is ingress-annotations.yaml 
controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "nginx-ingress"
    dapr.io/app-protocol: "http"
    dapr.io/app-port: "80"
    dapr.io/api-token-secret: "dapr-api-token"
    dapr.io/config: "ingress-config"
    dapr.io/log-as-json: "true"

**Comment by pzou19741** [comment]
I also did remove all the dapr related annotation. After that, I perform kubectl edit [nguix-ingress-ctl] and add dapr.io related parameters. there is no error but after restart daprd does not create.

**Comment by wcs1only** [comment]
If you are still experiencing this issue, can you please reply with the container logs:
```
willardstanley@CMAR-PC4 python-sdk % kubectl logs nginx-ingress-nginx-controller-9c99647b9-n27x4 -n dapr-test -c daprd                                                                                                                                                                     
{"app_id":"nginx-ingress","instance":"aks-agentpool-89343699-vmss000000","level":"info","msg":"starting Dapr Runtime -- version 1.2.0 -- commit 8e960e2","scope":"dapr.runtime","time":"2021-06-02T18:59:41.035809369Z","type":"log","ver":"1.2.0"}                                        
{"app_id":"nginx-ingress","instance":"aks-agentpool-89343699-vmss000000","level":"info","msg":"log level set to: info","scope":"dapr.runtime","time":"2021-06-02T18:59:41.035858469Z","type":"log","ver":"1.2.0"}                                                                          
{"app_id":"nginx-ingress","instance":"aks-agentpool-89343699-vmss000000","level":"info","msg":"metrics server started on :9090/","scope":"dapr.metrics","time":"2021-06-02T18:59:41.036021867Z","type":"log","ver":"1.2.0"}                                                                
{"app_id":"nginx-ingress","instance":"aks-agentpool-89343699-vmss000000","level":"info","msg":"loading default configuration","scope":"dapr.runtime","time":"2021-06-02T18:59:41.03734105Z","type":"log","ver":"1.2.0"}                                                                    
{"app_id":"nginx-ingress","instance":"aks-agentpool-89343699-vmss000000","level":"info","msg":"kubernetes mode configured","scope":"dapr.runtime","time":"2021-06-02T18:59:41.037376849Z","type":"log","ver":"1.2.0"}                                                                      
{"app_id":"nginx-ingress","instance":"aks-agentpool-89343699-vmss000000","level":"info","msg":"app id: nginx-ingress","scope":"dapr.runtime","time":"2021-06-02T18:59:41.037389049Z","type":"log","ver":"1.2.0"}                          
```

I was able to install with the following:
```
willardstanley@CMAR-PC4 deleteme % cat ingress-annotations.yaml 
controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "nginx-ingress"
    dapr.io/app-protocol: "http"
    dapr.io/app-port: "80"
    dapr.io/log-as-json: "true"
willardstanley@CMAR-PC4 deleteme % helm install nginx ingress-nginx/ingress-nginx \
     --set controller.replicaCount=2 \
     -f ingress-annotations.yaml \
     -n $INGRESS_NAMESPACE
```

**Comment by Ashnam1100** [comment]
Hi,
I added the same Dapr annotations to my Daemonset:
        `dapr.io/enabled: "true"`
        `dapr.io/app-id: "geneva-services"`
        `dapr.io/app-protocol: "http"`
        `dapr.io/app-port: "3500"`
        `dapr.io/log-as-json: "true"`
and ran `helm upgrade`, but am having the same issue of daprd containers not being created.

There are no daprd container logs, since the container was not created. 

The dapr-sidecar-injector pod logs regarding the geneva-services pod are as follows:
`time="2021-07-29T05:02:53.013755661Z" level=error msg="" instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-29T05:02:53.014217568Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-29T05:02:53.014246269Z" level=info msg="Sidecar injector succeeded injection for app 'geneva-services'" instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-29T05:03:36.573692604Z" level=error msg="" instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-29T05:03:36.574209112Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-29T05:03:36.574257113Z" level=info msg="Sidecar injector succeeded injection for app 'geneva-services'" instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-29T05:04:14.168237286Z" level=error msg="" instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-29T05:04:14.168743293Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-29T05:04:14.168772394Z" level=info msg="Sidecar injector succeeded injection for app 'geneva-services'" instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`

**Comment by artursouza** [comment]
> dapr.io/app-port: "3500"


@Ashnam1100 The app port should not be 3500, since it is the port used by Dapr sidecar. Please, pick another port for your app to listen to.

**Comment by Ashnam1100** [comment]
Thanks for catching that @artursouza. I updated the app port to 80, but the same issue persists. The dapr-sidecar-injector logs look the same:

`time="2021-07-30T15:00:37.618464498Z" level=error msg="" instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-30T15:00:37.618940404Z" level=info msg="ready to write response ..." instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`
`time="2021-07-30T15:00:37.618970805Z" level=info msg="Sidecar injector succeeded injection for app 'geneva-services'" instance=dapr-sidecar-injector-588ffddb78-mhqls scope=dapr.injector type=log ver=unknown`

**Comment by halspang** [comment]
I haven't been able to repro this either. Running through it I see my replicas both receive a daprd instance that is up and running. Could you post the config that you're referencing for it? Maybe that has an issue that is stopping dapr from starting?

Do you get an daprd logs from your nginx pods? Or do they not even get recognized as needing the injection? From the logs you posted it looks like you should at least have that, maybe we can see what they're waiting for?

**Comment by Ashnam1100** [comment]
@halspang thanks for your response! What are you referring to as the config? I don't have anything listed when I run `dapr configurations -k`, and below is the configuration CRD description: 
![image](https://user-images.githubusercontent.com/33374380/127695227-5e2f7a36-6891-4129-b37e-465f047b6a3d.png)

And unfortunately there are no daprd logs to look at because there is no daprd container at all. 
![image](https://user-images.githubusercontent.com/33374380/127695317-5da8c952-a78c-4e44-b267-60a78e79a73d.png)

**Comment by halspang** [comment]
Gotcha, in your original post's config you had this line:

> dapr.io/config: "ingress-config"

So I was wondering if the config didn't exist. However, I think if it doesn't exist, you would still get a dapr container with an error stating that it couldn't find it. I'll keep trying to think of reasons that the containers aren't starting.

**Comment by Ashnam1100** [comment]
Got it! The first post was actually @pzou19741, maybe they have more context.

Thanks so much!

**Comment by wcs1only** [comment]
So part of the problem is definitely that we're not correctly logging an error here that might have pointed us to the problem sooner. The other part of the problem is that the daemon-set-controler is not on the list of authorized controller accounts, and therefore we were denying the injection request.
