### ISSUE TITLE
Use streaming for response for bulk state API

### ISSUE THREAD

**Issue by xiazuojie** [dapr/dapr#2710]
## In what area(s)?

> /area runtime

## Describe the feature

change
```proto
  rpc GetBulkState(GetBulkStateRequest) returns (GetBulkStateResponse) {}
```
to 
```proto
  rpc GetBulkState(GetBulkStateRequest) returns (stream GetStateResponse) {}
```

Current API can only return response after all data are retrieved, which is inefficient (especially when the bulk is large). With streaming response, the client can start processing as soon as the first data is retrieved. What's more, streaming can support an unbounded sequence of data, such as log or state changes.
## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
This can be a new API for backwards compatibility. I am not sure if this will actually work end-to-end since the database must also stream the results back. Streaming between Dapr and app might not make a big difference if the database does not support it.

Can you have a PR just to demonstrate how one of the state stores can offer end to end streaming to bulk get?

**Comment by xiazuojie** [comment]
It's about batch processing vs stream processing.
* batch processing: collect a set of data, and then process it. Current API is batch processing.
* streaming processing: data is fed piece-by-piece and processed in real time. 
We have internal system that required streaming processing.

**Comment by ryou90** [comment]
I also looking for a stream processing integration

**Comment by artursouza** [comment]
I think this is a change we can make in the v2 API. v1 API must remain backwards compatible.
