### ISSUE TITLE
Dapr runtime crashes on subscriber with pubsub component

### ISSUE THREAD

**Issue by r1v3n** [dapr/dapr#2801]
## In what area(s)?
/area runtime

## What version of Dapr?

CLI version: 1.0.0-rc.4
Runtime version: 1.0.0-rc.3

pubsub provider: Azure Service Bus

## Expected Behavior

I was hoping that my original payload would be given to the subscriber in a CE envelop auto-generated by dapr with the .data set. Also, upon completion i would expect the runtime to protect itself from that payload by handling it so that the service can still use dapr.

## Actual Behavior

When the topic subscriber gets called, the CE object is not initialized and therefore has all members null. After that, regardless of the http response (200, 500, etc) that the subscriber sends back to dapr, it will crash the runtime.

`panic: interface conversion: interface {} is nil, not string
goroutine 180 [running]:
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).publishMessageHTTP(0xc0000ff440, 0xc00020ef30, 0x3c8b240, 0xc0005e0360)
        D:/a/dapr/dapr/pkg/runtime/runtime.go:1124 +0x17ed
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).beginPubSub.func1(0xc00020ef30, 0x3e96fac, 0x30)
        D:/a/dapr/dapr/pkg/runtime/runtime.go:443 +0xba
github.com/dapr/components-contrib/pubsub/azure/servicebus.(*subscription).getHandlerFunc.func1(0x43c14c0, 0xc000f7a000, 0xc0005b61e0, 0x0, 0x0)
        C:/Users/runneradmin/go/pkg/mod/github.com/dapr/components-contrib@v1.0.0-rc4/pubsub/azure/servicebus/subscription.go:122 +0x1d8
github.com/dapr/components-contrib/pubsub/azure/servicebus.(*subscription).asyncWrapper.func1.1(0xc000f6b560, 0xc0005b61e0, 0x43c14c0, 0xc000f7a000, 0xc000f5bda0)        
        C:/Users/runneradmin/go/pkg/mod/github.com/dapr/components-contrib@v1.0.0-rc4/pubsub/azure/servicebus/subscription.go:169 +0xfe
created by github.com/dapr/components-contrib/pubsub/azure/servicebus.(*subscription).asyncWrapper.func1
        C:/Users/runneradmin/go/pkg/mod/github.com/dapr/components-contrib@v1.0.0-rc4/pubsub/azure/servicebus/subscription.go:147 +0x6c`

## Steps to Reproduce the Problem
1. Have a topic subscriber that just returns 200 (Ok)
2. Publish a  non-cloud event to a topic on Azure Service Bus.
3. Runtime will crash when receiving callback after subscriber controller code has been completed.

## Release Note

RELEASE NOTE: **FIX** Bug in runtime.

**Comment by ravi-k4** [comment]
Is there a work around for this issue. I am seeing the same error 1.0.1 version as well.

**Comment by lynn-orrell** [comment]
Is this similar to this issue?

https://github.com/dapr/components-contrib/issues/507

**Comment by ravi-k4** [comment]
@lynn-orrell  Yes, the subscriber is receiving non-cloud events from external MQTT broker. After receiving few events a runtime crash is observed.

**Comment by jjcollinge** [comment]
PSA: The current issues related to non-CE message support have been marked for attention in the 6 month roadmap https://github.com/dapr/dapr/issues/2882

**Comment by yaron2** [comment]
This is now fixed in Dapr 1.2: https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-raw/

**Comment by kshitijcode** [comment]
@yaron2 : This issue is still reproducible on 1.2. 
The Dapr Sidecar still goes into a panic state if we are expecting a cloud event but a non CE is received. 


`panic: interface conversion: interface {} is nil, not string



goroutine 3137 [running]:
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).publishMessageHTTP(0xc0004bfd40, 0x3d9b968, 0xc000060038, 0xc000d38280, 0x38e3201, 0xc000d38280)
/home/runner/work/dapr/dapr/pkg/runtime/runtime.go:1238 +0x15f0
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).beginPubSub.func1(0x3d9b968, 0xc000060038, 0xc0004d0240, 0x0, 0x0)
/home/runner/work/dapr/dapr/pkg/runtime/runtime.go:487 +0x39d
github.com/dapr/components-contrib/pubsub/azure/eventhubs.(*AzureEventHubs).Subscribe.func1(0x3d9b9d8, 0xc0004d0210, 0xc000c30190, 0x0, 0x0)
/home/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.2.0/pubsub/azure/eventhubs/eventhubs.go:144 +0xb6
github.com/Azure/azure-event-hubs-go/eph.(*EventProcessorHost).compositeHandlers.func1.1(0xc0004f11f0, 0xc000c30190, 0xc000efc160, 0xc000b9e000)
/home/runner/go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/eph/eph.go:418 +0x4a
created by github.com/Azure/azure-event-hubs-go/eph.(*EventProcessorHost).compositeHandlers.func1
/home/runner/go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/eph/eph.go:417 +0x245`

**Comment by kshitijcode** [comment]
@yaron2 : Is there a way in Dapr 1.2 through which we handle unexpected non CE event while processing CloudEvents? 

We tried Dapr 1.2 with metdata.rawpayload as value true while subscribing. We are using .NET 5 Dapr SDK.  Dapr 1.1 used to automatically unwrap the payload to the CloudEvent object in .NET. 
But with the 1.2 release, converts the payload into a byte array and wraps it inside another cloud event object thus breaking our existing code flow.
