### ISSUE TITLE
Globally distributed deployment | DR/HA

### ISSUE THREAD

**Issue by morigs** [dapr/dapr#2827]
If I understand correctly currently Dapr stores its state inside crds. So having two separate k8s clusters it's impossible to keep them in sync. Are there any plans on multi-region deployment support? It might be very useful for DR and HA scenarios

**Comment by danbo** [comment]
I would like to raise this again. The dapr documentation is not clear whether or not the current version supports multiple clusters / datacenters. ie, distributing / replicating the placement, state and tracing components

https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-overview/
https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/

For example, akka talks about dealing with split brain scenarios but I don't see any reference to this with dapr, presumably because examples are still within the one data center.

https://doc.akka.io/docs/akka/2.6/split-brain-resolver.html

Would be great if someone could expand on this capability further, ie, out of scope for dapr, to be discussed for roadmap, etc.
