### ISSUE TITLE
Add content type to state operations

### ISSUE THREAD

**Issue by rynowak** [dapr/dapr#2892]
## In what area(s)?

/area runtime

## Describe the feature

We should add content type to state operations to allow callers to specify the representation of the data they are providing. There are some state stores where it's valuable to provide guarantees about the data representation. Since the state store does not know what kind of content its getting in the common case (gRPC) it has to make the most general assumption about how to store it.

For example in a database like CosmosDB it would be useful to be specify that the data is JSON so that it can be stored without additional encoding for querying. We changed this to base64 encode late in 1.0 and I heard about it from a number of users in discord.

Issues:

- https://github.com/dapr/components-contrib/issues/665
- https://github.com/dapr/dotnet-sdk/issues/614

----

Currently we don't provide any information about the type of content to a state store component. It's not possible for a user to influence this other than through their choice of protocol.

The state store gets a value of type `interface{}` which depends on the protocol used:

-  HTTP: a Go value (an `int`, `string`, or `map[string]interface{}` that was unmarshalled from JSON
- gRPC: a `[]byte` value

**Note:** in the case of HTTP the caller MUST provide JSON as part of the request.

---- 

How this would work in practice:

- `.proto` messages get a content type field added for each state item
- state component interfaces get a content type field added as well - this will be `application/json` in the case of an HTTP request, or whatever the caller provided for gRPC
- SDKs that perform serialization will provide a content type
- the state component implementations can now choose the best way to represent data based on the content type
- state component implementations can now reject data that they are unable to store
- the state component implementations now return a content type as part of GET operations - SDKs can use this for diagnostics and validation

## Release Note

RELEASE NOTE: Add the ability to specify a content type for state operations

**Comment by jigargandhi** [comment]
@rynowak @artursouza can metadata be used to specify content type of the payload, or does it have to be an additional field?

**Comment by artursouza** [comment]
@jigargandhi I like the use of metadata in runtime API. Although the SDKs might decide to handle it as a first class attribute.

**Comment by artursouza** [comment]
@jigargandhi I will assign it to you. Beware this is not an easy issue, and it has impacts across the codebase and must be done in a backwards compatible way. Also, consider the impact to the SDKs.

**Comment by jigargandhi** [comment]
I got a feedback on the [discord](https://discord.com/channels/778680217417809931/901141713089863710/914206213254823946) that we should add content type to more components, however not all components require a content type. On looking at a list of components here are the component types that require a content-type

So *apart from state management*, here are the places I think require content type
1. Pubsub: Pubsub sends opaque data to publisher and consumes opaque data, so both `PublishRequest` and `NewMessage` need content type [see](https://github.com/dapr/components-contrib/blob/master/pubsub/requests.go)
     Components like Azure service bus use content type from metadata right now. 
2. Bindings: Bindings also send data or receive opaque data so content type is necessary here too. So structs like `ReadResponse`, `InvokeResponse`, `AppResponse` will also need content type [see](https://github.com/dapr/components-contrib/blob/master/bindings/responses.go)
3. Secret Stores: IMO secret stores do not need content type as secrets are supposed to be opaque.
4. Nameresolution: does not need a content type because the return type is a DNS name. 

Regarding the choice of content type in these components for further processing.
- Currently some users may already be passing content types in `metadata`, so those behavior should not break and components should use that approach. 
- However, incase the content type is missing in `metadata`, then the content type property should be chosen. 
- If the SDKs are passing content type in `metadata`, then they should now start sending it via the property via metadata too, because passing it in `metadata` does not give strictness on the value. 

Plan of implementation:
1. Add the content type in the structs in components-contrib repo (as part of the above PR)
2. Use content type property in several components 
3. Add content type in protos in Dapr repo, and set the value of content type property in the translation code, i.e. from http/grpc api to component calls.
4. Update sdks as and when needed to use the newly added content type property.

The steps 2 and 3 can be done parallelly. and are not blocking each other.

Let me know what you think.

**Comment by artursouza** [comment]
I agree with the approach above. My ask would be to make the following adjustments for backwards (and forward) compatibility.

* Make content-type a string* to reflect it being optional in the structs, similar to how we do for eTag.
* When both contentType attribute and metadata["content-type"] is provided, contentType attribute should take precedence and overwrite value in metadata["content-type"] (log warning about conflict request).
* When contentType attribute is provided and metadata["content-type"] is not provided, metadata["content-type"] is populated for backwards compatibility.
* When contentType attribute is not provided and metadata["content-type"] is provided, contentType attribute is populated (forward compatibility).

/cc @yaron2 @msfussell

**Comment by artursouza** [comment]
Moving this to 1.7 so we have time to incorporate this in the SDKs with proper docs.

**Comment by dmitsh** [comment]
I propose a simple solution: using metadata to pass content type to the state store components, for example
```
metadata["Content-Type"] = "application/json"

For gRPC API, this entry is explicitly added to request metadata.
For HTTP API, content type is extracted from HTTP header and added to metadata programmatically.

I have put together PR #4121 with these changes.

**Comment by dmitsh** [comment]
@jigargandhi , I have a question about your PR. Copying it here:
What is the rationale behind having content type as a separate member as opposed to a part of metadata? We already list content type in the metadata. Why to duplicate?

**Comment by dmitsh** [comment]
I would suggest that we don't need any code change to add content type support.

Here is what I would propose:

For gRPC API, we include `contentType` entry in the existing metadata. (refer to https://github.com/dapr/components-contrib/blob/master/metadata/utils.go#L36)
 
For HTTP API, we append URL with `metadata.contentType` query parameter.
For example, `POST http://localhost:3500/v1.0/state/mystore?metadata.contentType=application/json ...`
This will invoke [getMetadataFromRequest](https://github.com/dapr/dapr/blob/master/pkg/http/api.go#L1520-L1531) function and populate metadata entry.

/cc @mukundansundar @artursouza @yaron2

**Comment by dmitsh** [comment]
> We had this discussion before. The rationale is to make contentType a first class property and not just part of metadata. The same can be said about eTag. Is contentType important enough to be "promoted" to an attribute? This issue is proposing so. I agree because IMO contentType should be mandatory.

I disagree. Nothing prevents us from defining mandatory parameters in the metadata. This approach will eliminate breaking changes in the future.

**Comment by artursouza** [comment]
> 

On the other hand, metadata was supposed to be used for component specific attributes. contentType is a cross cutting concern, similar to eTag.

**Comment by yaron2** [comment]
If Content Type is not required (as suggested by @artursouza and I agree with that), then I think what @dmitsh suggested is better (include in metadata) because it better matches how it's currently handled in existing protocols (HTTP).

**Comment by artursouza** [comment]
> If Content Type is not required (as suggested by @artursouza and I agree with that), then I think what @dmitsh suggested is better (include in headers/metadata) because it better matches how it's currently handled in existing protocols (HTTP).

Why eTag is not in metadata? This question is to mainly help surface the real criteria to "promote" attributes from metadata.

**Comment by yaron2** [comment]
> > If Content Type is not required (as suggested by @artursouza and I agree with that), then I think what @dmitsh suggested is better (include in headers/metadata) because it better matches how it's currently handled in existing protocols (HTTP).
> 
> Why eTag is not in metadata? This question is to mainly help surface the real criteria to "promote" attributes from metadata.

I absolutely think `eTag` should be in metadata as well. For historical reasons that didn't happen.

**Comment by yaron2** [comment]
To be clear, I don't think it's a make-or-break if Content Type is in the request body or in metadata - it feels more natural to be in metadata.

**Comment by jigargandhi** [comment]
@dmitsh Content type field in metadata is also fine. However, in that case we need standardization of what key means a content type. This standardization is necessary because we have many components and many SDKs and each can mean content type differently. For example Go SDK can add `contentType` in GRPC call and some http call may add `metadata.content-Type` as query string parameter. And one state component can use `content-Type` while other can use `ContentType`

Since we want a unique way to define content type  we might need to **hard code** the string `contentType`  (going by go's naming convention) in components-contrib, dapr, and all the SDK repos and also document this constant in docs.

If such hardcoding is fine, please let me know and will make the changes in that way.
@dmitsh @artursouza @yaron2

**Comment by msfussell** [comment]
For me it would be great to see the whole picture to assess this statement from @jigargandhi, which occurs everywhere.
"Since we want a unique way to define content type we might need to hard code the string contentType (going by go's naming convention) in components-contrib, dapr, and all the SDK repos and also document this constant in docs."

However if this is unachievable now, since content type is being used too diversely and would introduce breaking changes then I focus on this issue only in the scope of the state operations oply and in that case having content type in meta data makes sense. My reasoning mostly on the ease of use for HTTP as @dmitsh puts above.  May also be worth getting the opinion of @rynowak.

**Comment by yaron2** [comment]
I support using `metadata` query params for HTTP. @dmitsh what's the proposed gRPC implementation?

**Comment by dmitsh** [comment]
> I support using `metadata` query params for HTTP. @dmitsh what's the proposed gRPC implementation?

The gRPC API already has metadata as part of the request objects.
We would need to change some of the SDKs (including go-sdk) to allow passage of the metadata.
