### ISSUE TITLE
Support deployment of Dapr as a helm chart dependency

### ISSUE THREAD

**Issue by ooeygui** [dapr/dapr#2945]
/area runtime

## Describe the feature
When a customer deploys an application that depends on dapr, it is natural for the application to declare dapr as a helm dependency and expect helm to install or upgrade the dapr.

However, today there is a race condition, which prevents the dapr sidecar from being injected to the application when deployed this way. 

## Release Note
RELEASE NOTE:
Dapr now supports being deployed as a helm dependency, simplifying application deployment for your customers.

**Comment by artursouza** [comment]
Here are my concerns for installing Dapr as a dependency:

1. Helm does not support waiting for dependencies before moving on to application deployment as per https://github.com/helm/helm/issues/3173
This means that the app would need to fail readiness probe due to missing Dapr sidecar and sidecar injector should be able to inject into existing PODs once started (new feature?)

2. Single Dapr installation per cluster
A cluster will probably have multiple applications, which means that there might be conflicting installations for Dapr. Do not confuse Dapr installation with Dapr sidecar, Dapr sidecar is injected per POD.

3. Upgrades
Helm upgrades to not upgrade CRDs, so Dapr version cannot simply be updated in the dependency list and expect the upgrade to work without manual intervention. Maybe there could be a new feature where Dapr (sidecar injector? operator?) can automatically upgrade CRDs.

I am not necessarily against this feature, but I would like to bring up the scope of work to support this capability and we can decide if it is worth the investment.

**Comment by pkedy** [comment]
In conversation, I've heard that currently Dapr cannot be installed in multiple K8s namespaces. If that is the case, I believe that can be fixed. Regardless, like @artursouza pointed out, the Dapr control plane is currently considered to operate at the cluster or namespace scope and is a prerequisite installation prior to deploying a Dapr enabled app.

From a CI/CD perspective, I could see users having a deployment pipeline step that installs the Dapr control plane if it isn't already / or upgrades if the version is lower than X (side node: @DarqueWarrior mentioned this behavior once and I have dumbed it "upstalling"). After the "upstall", we could run some programatic checks to make sure that all the components are running and healthy. Some initial code for these types of checks exist in dapr/cli/pull/632. These might mitigate the issue that @artursouza pointed out w/ `helm --wait`. The important part here is that in this scenario, the Helm chart for Dapr itself and the Dapr-ized application would be separate and run in separate steps in the pipeline.

So taking a step back, what is the actual intent (e.g. facilitation of installation/upgrade in a CI/CD pipeline)? I agree with @ooeygui that we can probably achieve a higher degree of operational simplicity with "idempotent" deployment steps.
