### ISSUE TITLE
Dapr1.0.1 with Istio 1.5.9 -Error in loading components Issue.

### ISSUE THREAD

**Issue by kamesh1677** [dapr/dapr#2984]
> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
1.0.1

Istio version 1.5.9

## Expected Behavior

daprd sidecar should load the statestore componenet successfully when istio enabled .

## Actual Behavior

daprd sidecar  throwing error to load the component 

"failed to load components: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp Ip:80: connect: connection refused\"

## Steps to Reproduce the Problem

1.enabled istio injection in namespace istio-test.
2. Deployed redis instance and redis component by taking from Dapr/quickstart repo.
3. Deployed pythonapp and nodeapp to test the flow.
4. python app throwing error that not able to persist the state and daprd sidecar pod logs following error is dispalyed.
 "failed to load components: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp Ip:80: connect: connection refused\

Appliations and redis instnace and component yaml deplyoed in same namesapce istio-test where istio-injection is enabled.

**Comment by yaron2** [comment]
This is not a Dapr issue. Istio is blocking traffic to Redis, you should use Istio Traffic Policies to allow the traffic to the Redis service and port.

**Comment by kamesh1677** [comment]
Thanks a lot @yaron2 for clarifying this.

I am new to this can you provide any link to enable traffic setting pls.

Thanks,
kamesh

**Comment by slacksach** [comment]
@kamesh1677 depending on your Istio configuration there could be a few things going on here.

Istio blocks all outbound connections from pods until the envoy sidecar is started. Because all containers in the pod start at the same time if any of the pods requires outbound access at start-up then it will be blocked. If the pods fail to perform an internal retry then it will simply continue crashing and restarting the pod.

Potential fixes (Istio 1.8.x and newer, refer to the Istio documentation for how to implement in Istio 1.5.9):

Istio added a setting which you can apply at the Istio mesh level: 
    defaultConfig:
      holdApplicationUntilProxyStarts: true

or by adding this annotation to the pods.

`proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'`

**Comment by deepziyu** [comment]
approach discuss at  [App container unable to connect to network before sidecar is fully running](https://github.com/istio/istio/issues/11130)
