### ISSUE TITLE
[E2E Test] Kubernetes Job completes but subscriber fails

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3028]
This error is seen on Windows only so far.

The K8s Job for publisher completes but the subscriber never gets the message.

![image](https://user-images.githubusercontent.com/130954/113663006-1185b680-965e-11eb-9ca7-4b14b7d568f3.png)

**Comment by artursouza** [comment]
@Hugome Have you tested this feature on Windows? We get some issues in our E2E tests.

**Comment by Hugome** [comment]
@artursouza Unfortunately I've not tested this on windows.

I remember having hard time debugging the GH E2E tests because logs from the job pod was not saved on the XXXX_container_logs artifact, I didn't deep dive on "why" my search was stopped at those lines
https://github.com/dapr/dapr/blob/73a5b62d49ea3d473d9abeef685a23a9faf32261/tests/platforms/kubernetes/appmanager.go#L651-L657
I was thinking maybe the job pod(s) was not returned in `podList` (Job pod should noramally have `testapp=appName` label)

**Comment by wcs1only** [comment]
This is very very likely to be the same as dapr/components-contrib#852

**Comment by wcs1only** [comment]
So, there were ultimately two root causes we're seeing for these failures. One of them was dapr/components-contrib#852 and is confirmed fixed. The other is that due to a networking issue on our windows test clusters, sidecars are occasionally not being injected. This has to do with the kubernetes sidecar callback failing without retry. I have engaged the appropriate team and am working with them on a solution.

**Comment by artursouza** [comment]
We have not observed this issue anymore. Closing it.

/cc @wcs1only
