### ISSUE TITLE
Inject application port to dapr automatically

### ISSUE THREAD

**Issue by mstrYoda** [dapr/dapr#3040]
## In what area(s)?

/area runtime
/area operator

## Describe the feature

Currently we are providing application port using **dapr.io/app-port** annotation. I think we can set app port while injection dapr sidecar on mutating admission webhook. Taking first containers exposed port as app port should work for most of the applications. If it is not fit multi-container pods, they still use **dapr.io/app-port** annotation.

What are your thoughts? If this feature look feasible I am volunteer to implement it.

**Comment by mstrYoda** [comment]
Any thoughts on this @artursouza?

**Comment by yaron2** [comment]
Taking the first exposed container port is too non-deterministic. Many pods run multiple containers, and this makes the decision process much more difficult.

In addition, since in Kuberentes pod spec container ports are *not* necessary in order to expose the actual ports on the container, many people omit them.

I think the overall feature is useful, but here's a different spin on it:
What about we let Dapr automatically generate a port for the app, and inject as an environment variable on each container in the pod.

That way the app can be dynamically assigned ports by Dapr.

**Comment by mstrYoda** [comment]
> Taking the first exposed container port is too non-deterministic. Many pods run multiple containers, and this makes the decision process much more difficult.
> 
> In addition, since in Kuberentes pod spec container ports are _not_ necessary in order to expose the actual ports on the container, many people omit them.
> 
> I think the overall feature is useful, but here's a different spin on it:
> How about we let Dapr automatically generate a port for the app, and inject as an environment variable on each container in the pod.
> 
> That way the app can be dynamically assigned ports by Dapr.

I could not understand your suggestion exactly. How does Dapr will know what port is listening by application container? If I understand it, I am volunteer to implement that feature if it is okey.

**Comment by artursouza** [comment]
I agree with Yaron that the first container port (first port of the first container) is a strong assumption. Even when an app listens to an HTTP port, it might not use Dapr callback API.

Now regarding Dapr selecting a random port for the app seems to be crossing a line into provisioning. This feature seems to belong to an application model (like OAM) instead of a programming model.

I vote for this feature not to be implemented in Dapr.
