### ISSUE TITLE
Provide insights on actor provisioning and lifecycle

### ISSUE THREAD

**Issue by tomkerkhove** [dapr/dapr#3337]
## In what area(s)?

/area runtime
> /area operator
/area placement
> /area docs
> /area test-and-release
## Describe the proposal

It would be good if there would be insights on how actors are being provisioned, hydrated, dehydrated so that people can extend them. Ideally, this would be both through SDK as well as CloudEvents on which we can subscribe.

Concrete scenario - We are investigating issues related to performance on downstream service and would like to better understand how many virtual actors live on what nodes and what the spread ratio is. If the hooks would be there, then we could gain those insights ourselves.

**Comment by mhoad** [comment]
I'd love to see some documentation regarding how to instantiate actors WITHOUT using an SDK and just via gRPC and HTTP as well if possible.

**Comment by withinboredom** [comment]
> insights on how actors are being provisioned, hydrated, dehydrated so that people can extend them

> I'd love to see some documentation regarding how to instantiate actors WITHOUT using an SDK

I can give some insight here, at least in regards to the PHP-SDK (in which other SDKs follow a similar process):

On app startup, the sidecar [requests `/dar/config` or the GRPC equivalent](https://docs.dapr.io/reference/api/actors_api/#get-registered-actors). The app returns the registered actors and their requested configuration. The sidecar calls [`/healthz`](https://docs.dapr.io/reference/api/actors_api/#health-check) regularly to make sure it is up.

Eventually, the app receives a request to [invoke](https://docs.dapr.io/reference/api/actors_api/#invoke-actor-method-1)/[remind](https://docs.dapr.io/reference/api/actors_api/#invoke-reminder) an actor. At this point, the SDK will instantiate the actor instance and call the `on activated` hook. If the actor is already activated, then it looks up the actor in-memory and uses the existing actor instance. In the case of PHP, it uses a sentinel file on-disk to determine if an actor has been activated (since PHP is a shared-nothing language, there's no actor resident in memory). One downside to other languages keeping a reference to the actor instance, is that it could survive to Gen2 (in C#, or equivalent in other languages) Garbage Collection lifecycle, requiring a full GC to reclaim the memory when it gets deactivated; I personally haven't looked into it though.

Once the actor is activated, the SDK calls the requested method on the actor. If the method requests state, [that is retrieved](https://docs.dapr.io/reference/api/actors_api/#get-actor-state) one key at a time. There's no way to bulk retrieve state in an actor (which is a possible performance issue IMHO). In PHP, these retrievals can be cached to disk (via configuration) so a request isn't required if the actor is already activated.

Any changes to state are recorded in a transaction, and [eventually committed](https://docs.dapr.io/reference/api/actors_api/#actor-state-transactions). In the PHP SDK, commits are automatic once the method is completed, but you can rollback the transaction or commit it yourself if needed. Each SDK may implement this differently.

Eventually, the method completes and the result is returned to the sidecar.

At some point, the sidecar requests the actor [to be deactivated](https://docs.dapr.io/reference/api/actors_api/#deactivate-actor) and the SDK will call the `on deactivated` hook and release the reference to the actor's instance.

I may have missed some things, but I tried to be as detailed as possible :)

**Comment by tomkerkhove** [comment]
Thanks for explaining and I'm already aware of those, but having events for activation/deactivation and such would really be helpful.

**Comment by withinboredom** [comment]
> but having events for activation/deactivation and such would really be helpful.

As a workaround, it'd be pretty straightforward to do something like create a common base class for your actors:

```php
abstract class TrackedActor extends Actor {
  public function on_activate() {
    $this->client->publish('actor-activation-queue', ['id' => $this->id, 'actor-type' => $this::class, 'host' => hostname()]);
  }
  
  public function on_deactivate() {
    $this->client->publish('actor-deactivation-queue', ['id' => $this->id, 'actor-type' => $this::class, 'host' => hostname()]);
  }
}
```

It would look very similar in C#, but I'm not sure about other SDKs.

From there, creating a simple dashboard showing the distribution is decently straightforward (ignoring the potential sudden death of nodes). Though, this really should be in the dapr dashboard and not reliant on SDK/user implementation, IMHO.

**Comment by tomkerkhove** [comment]
While that's true, I don't think this gives enough insights as you'd want to know when it gets moved to other instances and such or what if an instance dies and the code was not called?

@msfussell has this come up before from others as well or is it just me?
