### ISSUE TITLE
support de facto standard

### ISSUE THREAD

**Issue by MoonShining** [dapr/dapr#3339]
there are de facto standard  in many situations:
- sql in RDBMS
- aws-s3 in Object Storage
- redis protocol in Key-Value Store
- ...

users are familier with these api and lots of applications already built on them.

GRPC api require users to change their code, which brings unacceptable cost.  

in order to let existing applications benifit from "mecha",   how about support the de facto standard protocols？

**Comment by CodeMonkeyLeet** [comment]
@MoonShining can you elaborate on which protocols you would like to see? On the HTTP API side, are the choices being discussed in #2817 along the lines of what you're interested in?

**Comment by MoonShining** [comment]
mysql for example, almost every web application needs to access database.

the common evolution is
- use single mysql instance at begining
- use client sharding sdk，connect to multiple instance to scale out
- use distributed mysql-competible database such as tidb
- ...

If dapr can provide mysql competible service, then we can do above evolution transparently. 

The new GRPC/HTTP API is awesome, but  there are tens of thousands of existing applications already use sql, migrate from sql to GRPC/HTTP is unacceptable.

**Comment by msfussell** [comment]
@MoonShining - Maybe this is what you are expecting, https://github.com/dapr/dapr/issues/1339 some form of query support on Dapr Statemanagement APIs. However this will never be a full replacement for ANSI SQL APIs or a full database API, since this are numerous and varied. Dapr does not prevent you from using DBs libraries in your code to access databases of your choice. You should however not expect Dapr to provide a universal data access layer, since this is the realm of ODBC, JDBC, ADO.NET and other DB libraries. Dapr enable you to build distributed apps from the start, rather than having to re-architecture these as the app scales, which generally is very costly. Start with a scalable microservices design from the start if you are able to take this approach.
