### ISSUE TITLE
Replace E2E pipelines for Kubernetes 1.17/1.18 with 1.20/1.21 

### ISSUE THREAD

**Issue by dmitsh** [dapr/dapr#3348]
As Kubernetes community releases new versions, we need to keep up and update our pipelines.
Kubernetes supports past 3 minor versions for up to 12 months (1.18 and older for up to 9 months).

Currently supported versions are 1.21, 1.20, 1.19.
https://kubernetes.io/releases/version-skew-policy/

I propose removing pipelines for versions 1.17 (and potentially 1.18), and replacing them with 1.20 and 1.21

**Comment by halspang** [comment]
I think we should definitely have tests for whatever is officially supported. As for removing old versions, I'd be OK with that if we, again, aligned directly with kubernetes. 

However, I think my ideal case would be to keep the most recent deprecated version(s) supported until we can align them with our own release/documentation cadence that gives the clear heads up we won't be testing it anymore.

**Comment by artursouza** [comment]
I agree to adding new versions of K8s to our tests. When it comes to removing, I am concerned about us removing versions that we have a "significant" number of users still using.

**Comment by dmitsh** [comment]
I agree that we should care about user base, but Dapr is an open source project. If Kubernetes (another open source project) stops supporting certain version, so should we.
It might be different for the managed Dapr service, where we would have a dedicated team supporting paying customers.

**Comment by halspang** [comment]
@artursouza it would be great to be able to get that kind of information, though I don't know how we could do that across all the different k8s platforms.

Deprecation is always a careful narrative. Balancing the new features (that can not function on older k8s) and supporting older versions which stops us from making new features. Since people are free to choose what version of dapr they want to use (unlike calling into a cloud service where they fully control the stack). With that, we should be providing new features that are compelling enough to have them upgrade. I understand that this isn't always the realistic case, but it's how I see it for now at least.

If we really want to, I think it'd be reasonable to try and have some less common legacy tests run. As this is all fairly straight-forward to automate, we could have a set of old clusters that we spin up once a week (month?) and see if we've caused any major regressions during a release. This can give us some guidance and confidence on our older story without cluttering our mainline development.

**Comment by msfussell** [comment]
There is a balance here. I tend to agree that we should only support the latest version of Kubernetes, however for widest adoption we have also been careful to make sure that Dapr can run on v1.17.x and above. To this extent we added this to the docs for v1.0 release. https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/#supported-versions. It would be good to be data driven here and determine how many K8s clusters are deployed for each version.

**Comment by dmitsh** [comment]
I tend to disagree :)

My concern is that once the support for a certain Kubernetes version is deprecated, the Kubernetes community stops patching fixes in that version. So, if, for example, there is a security bug, we would either have this vulnerability in Dapr, or would have to patch it ourselves (meaning that we would need to follow up on all issues and see if they apply to the deprecated versions still supported by Dapr).

For the same reason I would suggest changing the wording in https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/#supported-versions from `1.17.x and above` to `supported by Kubernetes` or something like that.

The current Kubernetes version is 1.21. Officially supported versions are 1.19, 1.20, and 1.21.
Kubernetes 1.17 was released in December 2019. The last patch 1.17.17 was published in January 2021. 
For comparison, the latest patch for v1.19 (1.19.12) was published a week ago.
This shows that v1.17 has already stopped getting updates. This at least should raise the issue of security, especially in this day and age.

Other service providers also follow same practices:
https://cloud.ibm.com/docs/containers?topic=containers-cs_versions
https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions

Another obvious but less critical argument in favor of not supporting deprecated Kubernetes versions, is that we will save significant amount of human and compute resources (considering that we are an open source project with limited resources and big plans).

**Comment by wcs1only** [comment]
What does it actually cost us to keep 1.17.x testing around? Is there any harm for us knowing that we broke something and making a decision based on that information? It is better for us as maintainers to know something doesn't work, and thus be able to exercise our judgement, and communicate to our users so that they know they need to upgrade?

I vote we keep running the tests until such time as we make an intentional decision about wether to make a change that breaks support. If there comes a future time where running the tests for 1.17.x becomes burdensome on us, we can revisit this. But it is no burden as of right now.

**Comment by dmitsh** [comment]
@wcs1only , I agree with you in general. Today it does not cost us much to test v1.17.x. But we are not testing v1.20 and v1.21.
Next month v1.22 will be available. At that point we should be testing 6 Kubernetes versions.
From my limited experience with Dapr testing pipelines, they fail on random errors relatively often. With doubled amount of the test pipelines, the chance of hitting random error will be higher, which will lead to longer development cycles. Hence the cost.

But you brought a valid point. Today we don't have a clear policy on Kubernetes version support. Perhaps it is a good chance to discuss one. IMO, it does not make sense to commit to a certain Kubernetes version (v1.17 in our case) in documentation.
Are we going to support it forever? Probably not. How often should we review/update it? It's all unclear.

And I still think that security of deprecated versions is a valid concern for users.

**Comment by wcs1only** [comment]
> From my limited experience with Dapr testing pipelines, they fail on random errors relatively often. With doubled amount of the test pipelines, the chance of hitting random error will be higher, which will lead to longer development cycles. Hence the cost.

Running the tests less is not an acceptable solution to intermittent test failures. The solution to intermittent test failures is to fix them, full stop.

**Comment by artursouza** [comment]
@dmitsh Can you send a PR adding the new K8s versions until we make a decision on deprecation?

**Comment by dmitsh** [comment]
> @dmitsh Can you send a PR adding the new K8s versions until we make a decision on deprecation?

https://github.com/dapr/dapr/pull/3367

**Comment by msfussell** [comment]
@dmitsh - You are right. Ensuring that we test and support the latest version of K8s is important and we should make this statement in the support policy for Dapr. We should also move to supporting just the current K8s support releases as per all the major cloud provider and the K8s ecosystem.  My only thoughts for keeping a test running for 1.17 were to identify any breaking changes and "minimal dependencies on K8s APIs", but given that 1.17 is deprecated this may be not as necessary.

**Comment by yaron2** [comment]
+1 on supporting the supported Kubernetes distros.

**Comment by artursouza** [comment]
> +1 on supporting the supported Kubernetes distros.

Do you mean *only* supporting those or *at least* those?
