### ISSUE TITLE
Design E2E test - Iteration 1: Build test tools/framework and create one e2e test

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#335]

**Comment by youngbupark** [comment]
**DRAFT**

# Dapr E2E test

Dapr E2E test will aim at the below:

* Platform independent - End-to-end test sets needs to run on any K8S clusters where Dapr can run
* [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle) - Use the standard go testing tool(`go test`) without leveraging the complicated test framework
* Easy to run - Run e2e test without the complicated setup and options

## Requirement - the first iteration

1. Design and implement e2e test tool and test utils for K8S cluster
2. Create the first e2e test to validate state management
3. Run the e2e test in the local dev environment as a presubmit test
4. Add E2E test in PR build as a presubmit test
5. Create document for e2e test

## Non-requirement - the first iteration

1. Automate K8S cluster setup
2. Genereate Test report e.g. junit-report
3. Collect container logs from daprd side car, placement, operator, and injector containers
4. Performance test
5. Conformance test

## Overview of E2E test structure

* **test/utils** : includes test utilities. For example, this package includes how to deploy and delete pods/deployment/services in kubernetes.
* **test/testapps** : includes test app docker images. Dapr e2e test will deploy test apps to kubernetes cluster and run the e2e go tests in `test/e2e` against the deployed test apps. Therefore, before running the tests, we need to build the test images and push them to docker registry. E2E test in `test/e2e` will automatically deploy the images to cluster and clean up the images once the tests are completed.
* **test/e2e** : includes e2e go test implemenation. Each test is written as the standard go test. Each E2E tests must have `e2e` build tag.

## Overall workflow

In order to test the current changes in Dapr, a test tool needs to build Dapr runtime and test apps from the current branch and then push them to e2e test docker registry. When running the e2e tests, the tests will deploy the required test app from the docker registry and run its test cases by using the deployed test apps. Instead of creating new test tool or script, we will add test targets to the existing makefile for e2e test.

1. Set environment variables

    ```
    export DAPR_REGISTRY=docker.io/<your_docker_hub_account>
    export DAPR_TAG=dev

    # if you don's specify DAPR_TEST_REGISTRY, it will be the value of DAPR_REGISTRY
    # export DAPR_TEST_REGISTRY=docker.io/dapriotest

    # if you don's specify DAPR_TEST_TAG, it will be the value of DAPR_TAG
    # export DAPR_TEST_TAG=test
    ```

2. Deploy dapr from repo to the cluster.

    ```
    make build-linux
    make docker-push
    make docker-deploy-k8s
    ```

3. Build test image

   Build all docker images for each apps in `test/testapps`

    ```
    make e2e-testapps-build
    ```

4. Push test app images to docker hub

   Push test app docker images to DAPR_TEST_REGISTRY with DAPR_TEST_TAG tag

    ```
    make e2e-testapps-push
    ```

5. Run e2e test

   For example, Use minikube cluster, clean all pods/deployment/services in dapr-system and dapr-test namespaces, load ~/.kubeconfig config, and deploy `test apps` to dapr-test namespace.

    ```bash
    make e2e-test E2E_ARGS="--kubeconfig ~/.kubeconfig --cluster_type minikube --cleanup_cluster true"
    ```

    `e2e-test` makefile target will execute the below command in the end.

    ```bash
    go test -tags=e2e ./test/e2e/ --kubeconfig ~/.kubeconfig --cluster_type minikube --cleanup_cluster true
    ```

## Preparation for e2e test (manual)

Before running test, Kubernetes cluster needs to be configured by following [environment-setup](https://github.com/dapr/docs/tree/master/getting-started/cluster) doc. Kubernetes cluster will be reused instead of creating new cluster before test is running. `e2e_test` makefile target will check if the cluster is in a cleaned state before starting the e2e tests.

* Local dev environment: Minikube
* Scheduled e2e test (via GitHub Actions) : Azure Kubernetes Service
* Helm needs to be configured in the cluster to deploy dapr.

## Writing E2E test

Dapr runtime is injected to the app pod as a side car. In order to test Dapr E2E scenarios from app deployment, we will implement 1) test app, which is deployed to cluster and running with dapr runtime, and 2) e2e go test code, which runs the e2e test cases by deploying the required **test app** and component yamls, calling its http endpoint to test Dapr runtime, validate the result from **test app**, then cleaning up **test app** and components.

### Test app design

* Most of test apps will be written in go, except for Actor tests, under test/testapps. e.g. test/testapps/helloworld
* A test app will expose :5000 http endpoint
  - This http endpoint will be exposed to the external by LoadBalancer type in kubernetes service.
  - It will allow `e2e go test` to call this endpoint to run the test and validate result.
* One test app can be used by multiple e2e go tests

### E2E go test design

E2E tests will use the standard `go test` with [a build tag](https://golang.org/pkg/go/build/#hdr-Build_Constraints). Each e2e test needs to set the `e2e` build tag at the first line of `*_test.go`, which excludes the tagged files from the normal unit-tests.

```go
// +build e2e

package e2e

import (
    ...
)

...
```

`*_test.go` includes the four parts:

1. Setup
   - Check if k8s cluster is working
   - Deploy the required components
   - Deploy test apps to k8s cluster
2. Get service endpoint
   - Get loadbalancer external ip address for the test apps
3. Validate the test result
   - Call service endpoint to test the dapr runtime functionalities
   - Check the test result
4. Tear Down
   - Clean up all test apps and components
