### ISSUE TITLE
Difference Between dapr and KrakenD or API Gateway

### ISSUE THREAD

**Issue by vikingcodes** [dapr/dapr#3351]
What is Difference Between dapr and KrakenD or API Gateway.

Can we can use dapr as API Gateway ?

**Comment by msfussell** [comment]
Questions like this are best asked on the Dapr Discord channel, here https://aka.ms/dapr-discord

Dapr is not intended to be used as an API gateway, since it does not have feature such as throttling etc and there are many different API gateway already available today. Dapr can be used to "Daprize" existing API gateway such as NGINX, Envoy, Kong and KrakenD  in that is can run as a sidecar to them and then provide capabilities such as secure service invocation and secrets management. This is a common usage of Dapr with API gateways.
