### ISSUE TITLE
add OWNERS to notify maintainers to review

### ISSUE THREAD

**Issue by daixiang0** [dapr/dapr#3378]
Now there are many PRs hung, most of them do not have maintainers review, contributor need ask for review, like ping @artursouza or @yaron2 . Slow feedback do not help Dapr great grow I think.

I notice that we do not have OWNERS file to notify, with it, we can split review work to specified maintainers, reduce direct ask, and speed up review and merge, make Dapr evolve faster.

WDYT? @dapr/maintainers-dapr

**Comment by yaron2** [comment]
We have the CODEOWNERS file as recommended to use by GitHub: https://github.com/dapr/dapr/blob/master/CODEOWNERS.

**Comment by AaronCrawfis** [comment]
@yaron2 it looks like the CODEOWNERS file is broken and not correctly assigning PRs to the maintainers-dapr and approvers-dapr teams.

**Comment by CodeMonkeyLeet** [comment]
I like the suggestion to more effectively split up the work between maintainers and improving code velocity, though I suspect that the bottleneck is in the very small number of existing approvers spread out across many repos. Minimally, dapr/components-contrib would need similar attention, and it's possible that the existing approvers are getting too many notifications rather than not enough.

@yaron2 dapr does have a [CODEOWNERS](/dapr/dapr/blob/master/CODEOWNERS) file which should notify the appropriate approvers but no source file in the repo seems to reference code ownership as [documented by GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#about-code-owners), so there may be something that needs to be fixed up there. 

If the explicit distribution of file paths to specific owners is not something that the existing maintainers are ready for, I would suggest using the CODEOWNERS mechanism to create a two-tier system of reviewers so that we can pull in more reviewers from the community while allowing the existing maintainers to retain their gatekeeping authority:

1. Update the [branch protection policy](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule) to require code owner approval if that's not already the case.
2. Add more reviewers to dapr project as [collaborators](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization) so that they can review and approve PRs, but do not add them to CODEOWNERS yet. This allows reviewers to iterate with the PR contributors until there's an initial approval and takes some load off the existing maintainers.
    - It doesn't change the requirement that maintainers are still needed to approve the PR for merge, but potentially reduces the wait time for when a PR is submitted and is getting feedback from a reviewer at least.

**Comment by daixiang0** [comment]
@AaronCrawfis thanks for fix, will close it as fix done in all repos.

**Comment by CodeMonkeyLeet** [comment]
@artursouza Were you still interested in updating Dapr use of the CODEWONERS files or can this issue be closed?

**Comment by yaron2** [comment]
Closing as fixed

**Comment by artursouza** [comment]
@CodeMonkeyLeet  Yes, we need that in contrib. Can you cut an issue in that repo for the proposal? We need to allow authors of components to review PRs before a maintainer spends time on it.
