### ISSUE TITLE
Another Dapr started.

### ISSUE THREAD

**Issue by zivfuture** [dapr/dapr#3393]
Why doesn't Dapr support service mesh?

Here is another "Dapr" started.  [layotto](https://github.com/mosn/layotto)  Because Dapr has no "service mesh" capability. and we need Service Mesh in reality。

![image](https://user-images.githubusercontent.com/49356505/124376373-4fd05780-dcd9-11eb-9d5f-c84d07264642.png)

**Comment by skyao** [comment]
Dapr has service invocation. 

As my understanding,  service-service communication is not the core value that dapr focuses, istio is a good chooise.

**Comment by yaron2** [comment]
@zivfuture the Mosn project is building on top of Dapr as a platform. The word "Service Mesh" often conveys the wrong meaning - instead of saying Service Mesh I think it's worth talking about feature sets. Dapr is slowly coming to support more SM like features, starting with 1.3 you'll have transparent gRPC proxying. Dapr's intended to work alongside service meshes, so if you want to use Dapr + Linkerd or Dapr + Istio that's all fine and well.

**Comment by nobodyiam** [comment]
@zivfuture 

Thanks for starting this discussion, MOSN layotto team member here 🙂

Dapr is a great project! It defines a very good abstraction layer between application code and the backend services, which makes `Write once, Run anywhere` possible. 

We really like this idea, so we started a discussion (#2817) and had a talk with the dapr team months ago. Given the current situation on our side: 200K+ pods in production with MOSN service mesh, it's not easy to migrate to dapr directly in the short term (considering service mesh and other legacy feature support). But we agreed we will work out a standard api spec based on current dapr api and MOSN implementation will follow this api spec and reuse dapr as much as possible, so that it would be very easy for us and other users to switch to dapr in the future.

So as for the title, I think a more precise version might be: `Another implementation of Dapr api started.` 🙂

Back to the implementation, it's not hard to reuse dapr, e.g. we are now reusing all the [dapr components](https://github.com/dapr/components-contrib) and are ready to contribute more. However, the api spec is challenging, e.g. we already spent 3 months discussing the proposal of configuration api(#2988). Yet we believe it's worth it and we hope more people could join so that we could truly realize `Write once, Run anywhere` soon!

**Comment by GuoYL123** [comment]
> @zivfuture the Mosn project is building on top of Dapr as a platform. The word "Service Mesh" often conveys the wrong meaning - instead of saying Service Mesh I think it's worth talking about feature sets. Dapr is slowly coming to support more SM like features, starting with 1.3 you'll have transparent gRPC proxying. Dapr's intended to work alongside service meshes, so if you want to use Dapr + Linkerd or Dapr + Istio that's all fine and well.

How to understand “transparent gRPC proxying”？

**Comment by yaron2** [comment]
> > @zivfuture the Mosn project is building on top of Dapr as a platform. The word "Service Mesh" often conveys the wrong meaning - instead of saying Service Mesh I think it's worth talking about feature sets. Dapr is slowly coming to support more SM like features, starting with 1.3 you'll have transparent gRPC proxying. Dapr's intended to work alongside service meshes, so if you want to use Dapr + Linkerd or Dapr + Istio that's all fine and well.
> 
> How to understand “transparent gRPC proxying”？Is it like iptables in istio？

See the demo and discussion here: https://youtu.be/B_vkXqptpXY

**Comment by skyao** [comment]
> [layotto](https://github.com/mosn/layotto) Because Dapr has no "service mesh" capability. and we need Service Mesh in reality。

Layotto is not start for service mesht. Even dapr has a wonderful service mesh, laytotto will still start, like istio/envoy and mosn.

And for "new dapr", you can have a look at this project: https://github.com/micro/micro

![](https://micro.mu/images/micro-3.0.png)
