### ISSUE TITLE
sidecar /healthz returns 204 before placement server can route to actors on running service

### ISSUE THREAD

**Issue by withinboredom** [dapr/dapr#3451]
## In what area(s)?

/area runtime

> /area operator

/area placement

> /area docs

> /area test-and-release

## What version of Dapr?

All

## Expected Behavior

`/healthz` to not return a `204` until it can actually activate actors.

## Actual Behavior

A `204` response is returned even though it isn't possible to activate any actors on the service.

## Steps to Reproduce the Problem

1. Start a simple service that can host an actor. On startup, have it check that `daprd` is healthy, if it is, invoke an actor method.
2. See the error: `error invoke actor method: error finding address for actor type SimpleActor with id actor_60f2d9a578f5d`

I discovered this while trying to remove the `sleep 10` from the [php integration tests](https://github.com/dapr/php-sdk/blob/main/.github/workflows/php.yml#L158-L159). [Here's an example failure](https://github.com/dapr/php-sdk/runs/3093199059)

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
The `healthz` means it self can work, if depend on others. error info is enough I think,

**Comment by shubham1172** [comment]
@daixiang0 can you please reopen this issue? Are you in favor of creating a separate `healthz` endpoint for actors?

**Comment by daixiang0** [comment]
@shubham1172 I perfer to optimize healthz.

**Comment by XavierGeerinck** [comment]
Agreed that this is crucial, we can never expect a server to startup correctly before placement has been checked

**Comment by ChristopherLenz** [comment]
Hello,

I really don't understand why the error isn't commented on here every day. For example, we use Dapr Actors to communicate between our services and jobs. These jobs are executed for exactly one task in Kubernetes. Unfortunately, neither of the two `health` endpoints can be relied upon.
So we have to artificially delay the job before it starts its work so that the actor can hopefully finally be reached.

Can one expect that this error will be processed soon or should one install a permanent workaround (e.g. provide one's own health actor that is called repeatedly)?

@shubham1172 can you please keep that alive?

Thanks

**Comment by shubham1172** [comment]
> @shubham1172 can you please keep that alive?

Unfortunately I don't have the permissions. A dapr/dapr maintainer has to.

**Comment by ChristopherLenz** [comment]
Hi @XavierGeerinck,

thanks for the tip. But unfortunately this looks not like a solution (at least for the dotnet sdk).
The metadata endpoint is available immediatally after the health endpoint is available. But a call to the actor will fail after that.

I think I will create a new issue because I think that my usecase is different from this one.
