### ISSUE TITLE
Enable gRPC based components

### ISSUE THREAD

**Issue by ewassef** [dapr/dapr#3513]
## In what area(s)?

/area runtime

## Describe the proposal

All of the components of the Sidecar must be pulled into the source code and built into a single binary. As more and more components are added, this will bloat the size of the repository and the artifact tremendously and will limit the ability of third parties or consumers to extend the component list.
The proposal is to extract the components into separate go binaries that are individually (or logically grouped) into their own Pods or instances and invoked via gRPC. The component interfaces would be published as proto files and the sidecar would invoke the pod endpoint as a passthrough. 

### Benefits:

1. Smaller and more stable sidecar artifact and code base
2. Infinitely extensible library of components that can be distributed via Dapr component repo or other "store" mechanism
3. Allows for customer extensibility without forgoing Dapr
4. Exposes component traffic to observability natively 
5. Solves new/upgraded component version issues
6. Allows for "Install only what you use" in your cluster or on metal. 

### Potential Issues:

1. Increased latency between sidecar and components
2. Additional overhead of serialization/deserialization between the app/sidecar/component pod 
> This can potentially be bypassed if we do not inspect the body and just forward the stream to the component
3. Communication interruptions or component performance mismatches with the Sidecar may introduce issues
> Utilizing the Dapr sidecar in and of itself to send the comm to the component may alleviate this
> HPA (for k8s) for components could resolve some of these issues

**Comment by daixiang0** [comment]
#3502 may fix the second issue.

**Comment by yaron2** [comment]
Thanks for opening this issue @ewassef, I edited the topic to more closely resemble what is being offered here. As a Dapr maintainer, I'm supportive of offering gRPC based component functionality. @artursouza please take a look here as well.

In order to mitigate the potential issues you raised as much as possible and to also address any security concerns that may arise with cross machine or cross pod communications, I highly encourage to keep gRPC components as containers inside the Dapr pod, being able to communicate *only* on localhost and using a unix domain socket for max performance and minimal latency.

**Comment by yaron2** [comment]
> @yaron2 can we alleviate your concerns using Network Policies in K8S or Spiffe? We should also be able to use the native Dapr sidecar-to-sidecar communication to connect to these other Pods

Then the question is: if the intention is to limit the connectivity anyway, why open it up to non-localhost access at all?
This leaves the door open to security holes that might be exploited by users targeting systems of non-security oriented Dapr users.

SPIFFE is used in Dapr today for an app identity, but I don't see how that in itself would help here, unless you're thinking about using certs for non-localhost  - which would make using gRPC components a lot harder to maintain and operate.

What's the use case for interacting with components not on localhost?

**Comment by lghinet** [comment]
being in the same pod makes things much easier, also giving the separation that you need,

**Comment by lghinet** [comment]
the idea of having each component into a separate process, or as others would put it, break the daprd monolith, 
should start from need of scaling, not from the concern of the daprd binary being too big,
or you do not want to independently scale each component/process into x replicas,  
what we want is a way to add custom code to daprd, without rebuilding, and I think a simpler way is to find somehow a way to efficiently load dynamic code into it

**Comment by ewassef** [comment]
> What's the use case for interacting with components not on localhost? @yaron2 
There isnt one really if we can modify the injection to add N sidecars. Ideally this would be easy enough to add custom sidecars too. The initial thought was to reduce the need for redundant containers (maybe via a daemonset or a common instance within the dapr namespace) but that would potentially cause bottlenecks as well and would need HPA. However, my initial thought was to replicate the Daprd to DaprD communications only over different Protos. I imagine the security and cert rotating is already accounted for there

> @lghinet what we want is a way to add custom code to Daprd, without rebuilding, and I think a simpler way is to somehow efficiently load dynamic code into it.
Absolutely, however, my understanding is that Go is not as good as other languages ( 'cough cough' .NET ) at doing that. However, this would probably not make as much sense for middleware as it would for components (i.e.. edge adapters either inbound or outbound)... 
My personal use case would be satisfied with a JSONNET interpreter on the Http pipeline for message transform etc. The only thing it wouldn't solve is external calls/lookups for augmentation but i think a component is a better fit for that

**Comment by jjcollinge** [comment]
Related: #3496 , #1311, #739, #3168, https://github.com/dapr/components-contrib/issues/297,

**Comment by ewassef** [comment]
Sorry, probably a novice question, but whats next here?

**Comment by yaron2** [comment]
> Sorry, probably a novice question, but whats next here?

@jjcollinge posted a really good summary here
 I think it's safe to agree that starting with gRPC based local components is the best way to go. ccing fellow maintainer @artursouza here.

Next steps are for someone to pick this work up, then create a design proposal here with the suggested proto interfaces and a general explanation of how the implementation is going to look like.

Once this is in place, we (maintainers) can Triage this into a milestone (likely 1.5 or 1.6).

**Comment by ewassef** [comment]
Any chance we can tag, pin or triage this @yaron2 ?

**Comment by yaron2** [comment]
I triaged this for 1.6 unless someone picks this up for 1.5.

**Comment by jjcollinge** [comment]
@yaron2 I had a couple of hours free this morning so I knocked together a very hacky PoC for external state stores over gRPC [here](https://github.com/jjcollinge/dapr-external-state). I was just playing with some ideas to see how it might work. This approach uses an `external` provider that is basically an adapter to call a remote gRPC service. In this case - the remote gRPC service is written in Go so it can just reuse the existing state stores but host them remotely (obviously other languages could be used too). The proto definition was just thrown together without much thought but it might provide a starting point (it doesn't yet use `commonv1pb` which will clean things up a bit. Lots of `TODOs` i.e. security, support unix sockets, tracing, refactoring, etc. but thought I'd share it in case it's useful to anyone who wants to play and I don't have time to come back to it. There's definitely bugs and shortcuts in here so beware :D. If we did go this approach I think we'd want to ensure every building block interface has a `Close()` method and has a `context` parameters - that way we can close the gRPC connection and propagate contexts.

I also think it probably is worth splitting this issue down into implementing gRPC based components for each building block individually.

**Comment by ewassef** [comment]
watching this...

**Comment by yaron2** [comment]
Also discussed here: https://github.com/dapr/dapr/issues/3787.

**Comment by ewassef** [comment]
Do we have a new milestone for this?

**Comment by georgestevens99** [comment]
This is an important feature and I encourage you all to make a new milestone for it.  If I am reading the comments correctly it was scheduled for 1.6 and that got delayed, and now it is sitting there awaiting.

Going back to the original proposal "The proposal is to extract the components into separate go binaries that are individually (or logically grouped) into their own Pods or instances and invoked via gRPC. The component interfaces would be published as proto files and the sidecar would invoke the pod endpoint as a passthrough."  Implementing this has "customer extensibility" benefits (among others) that have the potential to increase the customer base for Dapr.  Thus, this feature has strong tactical and strategic support for growing Dapr's customer base across many, many kinds of components.  This is why I strongly support getting it going again.  Thanks.

**Comment by artursouza** [comment]
> This is an important feature and I encourage you all to make a new milestone for it. If I am reading the comments correctly it was scheduled for 1.6 and that got delayed, and now it is sitting there awaiting.
> 
> Going back to the original proposal "The proposal is to extract the components into separate go binaries that are individually (or logically grouped) into their own Pods or instances and invoked via gRPC. The component interfaces would be published as proto files and the sidecar would invoke the pod endpoint as a passthrough." Implementing this has "customer extensibility" benefits (among others) that have the potential to increase the customer base for Dapr. Thus, this feature has strong tactical and strategic support for growing Dapr's customer base across many, many kinds of components. This is why I strongly support getting it going again. Thanks.

This issue is still in the POC stage. We will not add it to a milestone until there is clarify in the design for this feature. The design work does not fit into a milestone because is not an artifact delivered to the end user. We have no question that this feature is important. We are working on the design phase now and it will be added to a milestone at the right time.

**Comment by yaron2** [comment]
> > This is an important feature and I encourage you all to make a new milestone for it. If I am reading the comments correctly it was scheduled for 1.6 and that got delayed, and now it is sitting there awaiting.
> > Going back to the original proposal "The proposal is to extract the components into separate go binaries that are individually (or logically grouped) into their own Pods or instances and invoked via gRPC. The component interfaces would be published as proto files and the sidecar would invoke the pod endpoint as a passthrough." Implementing this has "customer extensibility" benefits (among others) that have the potential to increase the customer base for Dapr. Thus, this feature has strong tactical and strategic support for growing Dapr's customer base across many, many kinds of components. This is why I strongly support getting it going again. Thanks.
> 
> This issue is still in the POC stage. We will not add it to a milestone until there is clarify in the design for this feature. The design work does not fit into a milestone because is not an artifact delivered to the end user. We have no question that this feature is important. We are working on the design phase now and it will be added to a milestone at the right time.

Ditto

**Comment by ewassef** [comment]
> > > This is an important feature and I encourage you all to make a new milestone for it. If I am reading the comments correctly it was scheduled for 1.6 and that got delayed, and now it is sitting there awaiting.
> > > Going back to the original proposal "The proposal is to extract the components into separate go binaries that are individually (or logically grouped) into their own Pods or instances and invoked via gRPC. The component interfaces would be published as proto files and the sidecar would invoke the pod endpoint as a passthrough." Implementing this has "customer extensibility" benefits (among others) that have the potential to increase the customer base for Dapr. Thus, this feature has strong tactical and strategic support for growing Dapr's customer base across many, many kinds of components. This is why I strongly support getting it going again. Thanks.
> > 
> > 
> > This issue is still in the POC stage. We will not add it to a milestone until there is clarify in the design for this feature. The design work does not fit into a milestone because is not an artifact delivered to the end user. We have no question that this feature is important. We are working on the design phase now and it will be added to a milestone at the right time.
> 
> Ditto

How can I help here? I can bring a few dozen folks to assist with docs/designs etc if we can help get this done. We would very much like to standardize on Dapr more so that we are now, but only 1-2% of our developers are golang devs and contributing back is difficult. Having that flexibility of choosing your own language can allow us to extend and contribute back to the mainline, or if thats not desired, possibly into a Dapr extension registry for all kinds of third parties

**Comment by georgestevens99** [comment]
FYI -- The current work in this area is being done in Issue #3787.  And
thanks for your generous offer!

**Comment by ewassef** [comment]
@georgestevens99 That sounds great! this issue does mention State Stores only though, does it expand its pattern to other components as well? Our biggest gap is in the pubsub component at the moment and where we could use this the most

**Comment by georgestevens99** [comment]
@ewassef  Can you briefly state your needs in the area of pubsub?  What do you
need that is not there now, and how does that fit in to the area 3513 addresses?  Thanks. 

Also the State Store work in #3787 is about is intended to serve as a POC for plugins in general so as to understand the best ways to approach a multi building block plugin. 

Pardon the double response, but the first one had a typo and was sent by email which cannot be edited here.

**Comment by ewassef** [comment]
No problems @georgestevens99. 
Part of the pubsub additions we would like to make is integration with a schema registry (think of confluent and their interceptor in their clients) and secondly to allow for tokenizing or adding data to the cloud event payload. Most useful for us is the tokenization of the PII fields (marked so via their registered schema) that would submit the PII and return a token in place of the old data. This is helpful in "right to be forgotten" scenarios where we can simply delete the token lookup and not worry about the plethora of places our event may have been sent and/or stored
Furthermore, we want to utilize different products for our pubsub, #KubeMQ is a very high-performing and k8s native system that we find very useful. But in general, there are dozens of situations where we want to use dapr with a slightly different component but would need to fork the entire product. The [Bindings](https://docs.dapr.io/developing-applications/building-blocks/bindings/) potential is endless, but because it's all baked in, it is just limiting our options. 
Theoretically, a docker image tag in the component spec with the type being pubsub.external, would satisfy the configuration need. As for the code implementation, ( I am by no means a GoLang expert but I am speaking from a .NET background), if the component interfaces were mapped to protos and made public, any docker component can be built to implement that interface and be invoked using grpc. The mechanism to invoke the image could be the same [service invocation](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/) building block configured to go to a local sidecar with an internal port. this gives us retry and security with the sidecars-sidecar. Not only does this give us flexibility, but the dapr image would become minuscule and only load _exactly_ what is needed for that app. (Imagine the ease of updates) 
Ultimately, the biggest win would be to create a Dapr component registry where all vendors or private companies can self-host or reuse components from each other. This would theoretically provide endless combinations with a thriving and inclusive ecosystem allowing vendors to profit if they provide enough value and companies to adopt and extend to match with their particular needs

**Comment by georgestevens99** [comment]
@ewassef  Thanks for posting your pubsub wish list.  I will make some comments tomorrow evening, since some items may already be implemented or in the pipeline.

However, a key thing to point out to everyone reading this Plugin stuff is well summarized in your final sentence "Ultimately, the biggest win would be to create a Dapr component registry where all vendors or private companies can self-host or reuse components from each other. This would theoretically provide endless combinations with a thriving and inclusive ecosystem allowing vendors to profit if they provide enough value and companies to adopt and extend to match with their particular needs".  Thanks.

And, **having an effective plugin architecture** where people can implement components in .NET, or Java, or Go or what ever **will have the effect of drastically speeding up the rate of releasing of new Dapr features and capabilities which, in turn, will speed up Dapr's adoption rate as it provides more and more the key capabilities developers of distributed systems want and need**.  Keep your eyes on the prize!

**Comment by georgestevens99** [comment]
@ewassef  I have broken down your "pubsub additions" into separate parts below.  Then I comment on how to go about getting each part into Dapr.

1. Part of the pubsub additions we would like to make is:
    a. integration with a schema registry (think of confluent and their interceptor in their clients)
    b.	secondly to allow for tokenizing or adding data to the cloud event payload. 
        i.	Most useful for us is the tokenization of the PII fields (marked so via their registered schema) that would submit the 
                PII and return a token in place of the old data. 
        ii.	This is helpful in "right to be forgotten" scenarios where we can simply delete the token lookup and not worry about 
                 the plethora of places our event may have been sent and/or stored.
2.	Furthermore, we want to utilize different products for our pubsub
a.	#KubeMQ is a very high-performing and k8s native system that we find very useful. 
b.	But in general, there are dozens of situations where we want to use dapr with a slightly different component but would need to fork the entire product. 
c.	The [Bindings](https://docs.dapr.io/developing-applications/building-blocks/bindings/) potential is endless, but because it's all baked in, it is just limiting our options.
d.	An idea for implementation of this variety:
i.	Theoretically, a docker image tag in the component spec with the type being pubsub.external, would satisfy the configuration need. As for the code implementation, ( I am by no means a GoLang expert but I am speaking from a .NET background), if the component interfaces were mapped to protos and made public, any docker component can be built to implement that interface and be invoked using grpc. The mechanism to invoke the image could be the same [service invocation](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-services-grpc/) building block configured to go to a local sidecar with an internal port. this gives us retry and security with the sidecars-sidecar. Not only does this give us flexibility, but the dapr image would become minuscule and only load exactly what is needed for that app. (Imagine the ease of updates)

3.	Ultimately, the biggest win would be to create a Dapr component registry where all vendors or private companies can self-host or reuse components from each other. This would theoretically provide endless combinations with a thriving and inclusive ecosystem allowing vendors to profit if they provide enough value and companies to adopt and extend to match with their particular needs

**Comment by yaron2** [comment]
This work is now tracked in https://github.com/dapr/dapr/issues/3787.
