### ISSUE TITLE
workflow / azure storage

### ISSUE THREAD

**Issue by stepro71** [dapr/dapr#3526]
Dapr Workflow: will this be developed further and finished, e.g. the requirement to have azure storage (not local) removed?

**Comment by daixiang0** [comment]
Please share your use cases here :)

**Comment by stepro71** [comment]
The use case would be a customer in finance etc. and a workflow for accounts payable. Those customers do not want their solutions to “phone home” to Microsoft. So the requirement for azure storage is a problem.

**Comment by CodeMonkeyLeet** [comment]
@stepro71 Are you referring to the [Dapr Workflows example in the docs](https://docs.dapr.io/developing-applications/integrations/workflows/)? It should work with any supported Dapr state store and so is not specific to Azure Storage.

**Comment by stepro71** [comment]
@CodeMonkeyLeet: I have looked at this sample, but here you need an azure blob storage with an secret. I do not know, how to configure this locally.

**Comment by stepro71** [comment]
Hi, any pointers, how I could get this to running?

**Comment by CodeMonkeyLeet** [comment]
@stepro71 Sorry, I was mistaken. I thought that the support for arbitrary Dapr storage had been added to the repo by now based on the [community call](https://www.youtube.com/watch?v=7fP-0Ixmi-w&t=850s) but it looks like that work is still pending.

@artursouza Do we have any traction on this? This might be the first community request I've seen for this since the feature was discussed.

**Comment by yaron2** [comment]
@stepro71 the Azure Storage requirement is part of the Azure Logic Apps engine, and not Dapr - so changes would have to be made on that front first.

**Comment by stepro71** [comment]
@yaron2: thank you for your response.
