### ISSUE TITLE
how Dapr helps to implement Saga pattern ? 

### ISSUE THREAD

**Issue by masoud-shayan** [dapr/dapr#3532]
I am trying to implement Saga in my microservice project by myself but it is really hard and makes me stay away from the designing core business logic . 

Can Dapr help with implementation of Saga then I no longer have to worry about consistency between databases?

may you introduce some more tools to implement Saga in .Net ? 

Thanks.

**Comment by CodeMonkeyLeet** [comment]
You should think of the Saga pattern as an design tool for maintaining state consistency between microservices that each have their own data stores; defining state consistency requires domain knowledge about both the business logic and the factoring of microservices in your app, so most frameworks like Dapr do not deal with explicitly managing the _logical_ consistency of your data.

Where Dapr can help is as an accelerator for implementing your microservices, so that you can focus on application logic concerns like the state consistency, instead of the mechanical details of figuring out setting up endpoints, secure service-to-service invocation, writing against broker or service-specific SDKs etc. 

For example, if you want to prototype a version of your app using the Choreography approach to the Saga pattern, you could use a [Dapr pubsub](https://docs.dapr.io/developing-applications/building-blocks/pubsub/) which abstracts out the message broker implementation and lets you focus on the message and topic design for the choreography between the services first. Similarly for [state stores](https://docs.dapr.io/developing-applications/building-blocks/state-management/state-management-overview/) and other common microservices primitives that Dapr provides as [basic building blocks](https://docs.dapr.io/concepts/building-blocks-concept/). 

And Dapr does this in a way that tries to support the language of your choice, and will also work with other frameworks in this space. For example, if you are using .NET, it integrates nicely with [.NET Tye](https://github.com/dotnet/tye) which is powerful for building and deploying microservices apps in .NET.

If you're interested in how others have used Dapr, perhaps for the same kinds of problems you're interested in solving, consider asking the community on the [Dapr Discord](https://aka.ms/dapr-discord).
