### ISSUE TITLE
Enable route based proxying for HTTP in addition to gRPC

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#3546]
In 1.3, we improved developer experience for gRPC by allowing users to use their existing proto services and telling Dapr which service to discover using standard metadata headers.

Today, lift and shift scenarios or integrating Dapr into existing code requires users to change their URL paths to the following:

```
/v1.0/invoke/myservice/targetmethod
```

In the example above, `targetmethod` is the full URL endpoint of the target service, so for example:

```
/v1.0/invoke/myservice/api/products
```

I suggest to enable users to, like gRPC, call Dapr over `/` and specify the target service through HTTP headers.

In this case, users keep their existing HTTP clients and URL routes and in place, and make the following changes:

1. Change the address in the URL to `localhost`
2. Add a `dapr-app-id` header to specify the ID of the target service

**Comment by paulyuk** [comment]
I'd +1 @yaron2 to make the friction and lift much smaller for existing HTTP developers to immediately get value out of Dapr.  today you have to rewrite your HTTP code to tokenize and call our special dapr URIs

**Comment by rynowak** [comment]
We implemented something similar to this functionality in the .NET SDK and it really simplifies life for uses. Adding Dapr service invocation to an existing service can be a one line change! 

I'm strongly supportive of this being added to the runtime (rather than the SDK). This will make the functionality accessible to everyone without thick SDKs acting as a polyfill.

**Comment by artursouza** [comment]
I am supportive of this approach.

It probably means that the header will be handled in the runtime before the URL's path.

**Comment by yaron2** [comment]
> I am supportive of this approach.
> 
> It probably means that the header will be handled in the runtime before the URL's path.

Exactly!

**Comment by ewassef** [comment]
I don't understand the problem here; almost all settings require the base url to be passed as input. This is the same for any pre-packaged solutions that we are trying to add dapr to via annotations. We haven't had an issue changing the env/config/setting from https://tempuri.org/ to http://localhost:3500/v1.0/invoke/tempuri/method/ . It literally works like magic and suddenly we can make sense of the hundreds of systems in our environments. its the ease of use of a service mesh with added benefits

How would we do that with this proposal without modifying the code to add the header?

If we want to simplify, there is an alternative, how about 
http://localhost:port/dapr-id instead of http://localhost:port and adding a custom header

As an aside, we are primarily using Dapr as a way to bring our existing hundreds of polyglot microservices forward and getting some of the benefits of the observability, service location, mTLS, and retrys. We would not be able to do this without changing the code for all existing services. 

I do not support this.

**Comment by yaron2** [comment]
> I don't understand the problem here; almost all settings require the base url to be passed as input. This is the same for any pre-packaged solutions that we are trying to add dapr to via annotations. We haven't had an issue changing the env/config/setting from https://tempuri.org/ to http://localhost:3500/v1.0/invoke/tempuri/method/ . It literally works like magic and suddenly we can make sense of the hundreds of systems in our environments. its the ease of use of a service mesh with added benefits
> 
> How would we do that with this proposal without modifying the code to add the header?
> 
> If we want to simplify, there is an alternative, how about
> http://localhost:port/dapr-id instead of http://localhost:port and adding a custom header
> 
> As an aside, we are primarily using Dapr as a way to bring our existing hundreds of polyglot microservices forward and getting some of the benefits of the observability, service location, mTLS, and retrys. We would not be able to do this without changing the code for all existing services.
> 
> I do not support this.

Just to be clear, this will not replace the current service invocation format but will be an added option.

**Comment by ewassef** [comment]
Ah! That's a relief and makes much more sense. I don't see why that wouldn't be a great addition!

**Comment by artursouza** [comment]
I actually like the idea from @ewassef about not setting a header because it requires code change in the app do include the special Dapr header. If we can reuse the endpoint configuration, it makes adoption much easier. What if (in addition to HTTP header), we also allow this to be passed in via HTTP Basic Auth: `http://dapr-app-id:MyAppId@localhost:3500/any/path`

**Comment by yaron2** [comment]
The Dapr header is consistent with how we do it for gRPC (using metadata), but I'm ok with adding more options for users to best choose how they want to format their service invocation URL best.
