### ISSUE TITLE
dapr state&binding interfaces haven't destroy standard api.

### ISSUE THREAD

**Issue by 1046102779** [dapr/dapr#3599]
if I dynamicly update or add many binding or state component crds, old resources won't be freed, such as redis, mysql and etc  connection pool. 

So  how should we free old connection pool ?

**Comment by daixiang0** [comment]
Now pub/sub has close interfaces while state not, I am very happy to see it.

WDYT? @pkedy @artursouza

**Comment by CodeMonkeyLeet** [comment]
Binding and state components are expected to implement the `io.Closer` interface too. Daprd does attempt to invoke it where available and you should open [issues in dapr/components-contrib](https://github.com/dapr/components-contrib/issues?q=is%3Aissue+Close+author%3Apkedy) for components that need to release resources and are missing a `Close()` implementation. 

Both Redis and MySQL state components mentioned in the issue do have `io.Closer` implementations. The issue is when daprd invokes `Close()` which currently is only on shutdown ... it's not my understanding that Dapr supports CRDs being dynamically updated today without taking down Dapr, I thought that was what a lot of the [discussion around the config API](https://github.com/dapr/dapr/issues/2988) was around.

Specific to bindings at least, there are examples where the lifetime semantics for `Init()` and `Close()` are not independent of the process lifetime today (see #3555), which may create additional complications if we do expect components to be reconfigured without restarting Dapr.

**Comment by artursouza** [comment]
I agree with @CodeMonkeyLeet. We don't support component reloading without restarting sidecar. So, I am curious to know where is the need to handle closing resourced beyond the shutdown case.
