### ISSUE TITLE
How does the GRPC proxy use/provide state management, pub/sub etc all dapr capacity?

### ISSUE THREAD

**Issue by li1234yun** [dapr/dapr#3602]
> /area runtime

1.3

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Ask your question here
I found the dapr supports the grpc proxy to invoking raw grpc server, it's GREAT! Thank you for your great work!

But I can't find related docs to example the grpc proxy usage in all respects, such as state store, pub/sub etc. So I just want to ask   whether the grpc proxy can use those capacity. Maybe you can provide some detail docs.

Thanks!

**Comment by yaron2** [comment]
gRPC proxying is only applicable for service to service calls.

**Comment by li1234yun** [comment]
> gRPC proxying is only applicable for service to service calls.

Hello, @yaron2 
Do you think about expose pub/sub specific method. When grpc service need to pub/sub, grpc service can achieve this method that returns the pub/sub methods just like http pub/sub register. It is just an advise, I just want to use the grpc server and dapr at the same time :->

Thank you!

**Comment by yaron2** [comment]
If I'm understanding you correctly, you're talking about proxying in the consumer Dapr pub/sub sidecar and invoking arbitrary methods on the app side instead of using the AppCallback interface.

Since Dapr has a well defined API and structure, I think the AppCallback interface is actually better here as it has the Cloud Event properties and it's strongly typed - using an arbitrary gRPC function would require that user function to accept the Dapr proto message for the event, which would defeat the purpose of proxying.

**Comment by li1234yun** [comment]
Thank you! @yaron2
