### ISSUE TITLE
Dapr actor TTL in general

### ISSUE THREAD

**Issue by ovebastiansen** [dapr/dapr#3658]
Hi,

We have started using dapr with a keen interested of using the actor framework. We have also choosen Cosmos db as our store, both for actor state and other storage requirments for all of our "hot" data.

Now we have a requirement that we are hoping to solve with a "short-lived" actor. It gets a request and generate some state for that actor, and in case it get another request on that id in the next 3 hours we want to return the same state. And after 3 hours we want to generate new state, in the rare case of getting the same id, but in most cases it is never called again. In any case we want to both delete the generated state and get rid of the actor from any placement tables and such, since we dont want to have "dead" actors laying around somewhere, even though they are virtual.

Is there a generic way we can get this done, without either writing that state to cosmos with a TTL our self, and accept "dead" actors laying around, or writing something custom with reminders and call delete on the actor api? Essentially we are looking for TTL on the entire actor, that gets rid of everything related to that instance

**Comment by artursouza** [comment]
First, regarding the removal from placement service. Actors are virtual but there is no record of it in placement service. Placement service keeps tracks of which dapr sidecars are available to process actors for a given actor type. But, an actor is kept active (with state cached in memory) while it is active. You can configure how long actors deactivate in Dapr.

Now regarding the state saved. I do not recommend using TTL in cosmosDB to auto-delete actor state, it can create a race condition since actors can have the data cached in memory but eventually deleted in the database due to ttl. The state of an actor should be modified only by the actor itself. Instead, I recommend saving the expiration time as part of the state of the actor and when reading, automatically discard the data and continue processing as if the data did not exist - basically having this logic in the actor implementation in your app.

Let me know if this helps. Happy answer any further inquiries here.

Thanks,
Artur Souza

**Comment by artursouza** [comment]
If you really want to delete the record in the database due to inactivity, you can use a reminder with a trigger > 3h and check if the record is logically expired.

**Comment by ovebastiansen** [comment]
> If you really want to delete the record in the database due to inactivity, you can use a reminder with a trigger > 3h and check if the record is logically expired.

Triggers is another issue as well, since we are spotting "empty" rows in the database on triggers that have triggered and are now removed. Does not seem that the trigger row is completely removed when deregistered.

So the recommendation is to set up a trigger to invoke the actor and then delete the state and that would completely remove all records of that actor ever existing in all of dapr stores and services?

**Comment by Max-Eriksson** [comment]
We have a similar situation. We have an actor that, in worst case, will live for 7 days. The actor itself uses state stored in redis and has configured reminders to, by calling an external service, update its state.

If the desired state not is reached after 7 days all reminders will be unregistered and the actor will be deactivated (sooner or later). The problem/challenge is that its state still exists in the state store (redis).

What is the recommended approach to clean-up, remove, its state from redis?
