### ISSUE TITLE
Retry /dapr/subscribe in case of failure or wait for app to get into Ready state

### ISSUE THREAD

**Issue by mcrio** [dapr/dapr#3839]
Hi,

Posting a pub/sub related problem for discussion:

Problem:
In case `/dapr/subscribe` is not available when the sidecar starts, the app will not subscribe to the event queue.

Scenario (reproducible using Tye):

- App has readiness and liveness health-checks defined
- Dapr sidecar starts, App is not yet in `Ready` state
- Dapr sends `/dapr/subscribe` request but the connection is refused because the app is not in `Ready` state yet
- Dapr will not retry getting the subscriptions. App finally gets into `Ready` state. No events will be processed.

Possible solutions:
Retry logic for the `/dapr/subscribe` endpoint or wait until app gets into `Ready` state by monitoring health-check endpoints.

This problem was partly discussed in:
https://github.com/dapr/dapr/issues/2918
https://github.com/dapr/dapr/pull/3605

**Comment by rtrindvg** [comment]
I am seeing the same behavior on my environment, with the added problem of the super verbose stderr logging.

We are using a redis as a pub/sub service. We had to upgrade the node pool to a bigger instance and since all the pods were relocated to the new nodes, it seems the redis was late to be available to the pub/sub services. This is the sample line which logs nonstop (millions of lines per day) on the affecting services:
`time="2021-11-16T14:30:28.353396986Z" level=error msg="redis streams: error reading from stream svcname: NOGROUP No such key 'svcname' or consumer group 'svcname' in XREADGROUP with GROUP option" app_id=svcname instance=svcname scope=dapr.contrib type=log ver=1.4.3`

Redis pod was stable, 0 restarts since the move. After deleting/recreating the affecting consumer pods, each daprd sidecar was able to talk with the pub/sub service and the issue was gone. So beyond the service not working, it generated a couple thousand dollars of cost because of the log verbosity ingest on Azure.

**Comment by mcrio** [comment]
Hi @rtrindvg It seems like the problem you described deserves a separate issue. This one is just about the subscriptions discovery endpoint that the application provides, while the scenario you described is a sidecar <> pub/sub connection problem.

@Team-Dapr do you think it makes sense to have this retry logic. The subscriptions discovery procedure seems a bit unreliable at the moment.

**Comment by yaron2** [comment]
> Hi @rtrindvg It seems like the problem you described deserves a separate issue. This one is just about the subscriptions discovery endpoint that the application provides, while the scenario you described is a sidecar <> pub/sub connection problem.
> 
> @Team-Dapr do you think it makes sense to have this retry logic. The subscriptions discovery procedure seems a bit unreliable at the moment.

I think it does make sense. I'll look into that for 1.6.

**Comment by MargaretKrutikova** [comment]
We just experienced the same issue in prod on Dapr v1.10.2 after deploy:
```
level=error msg="redis streams: error reading from stream <topic-name>: NOGROUP No such key '<topic-name>' or consumer group '<app-id>' in XREADGROUP with GROUP option" app_id=<app-id> component="pub-sub (pubsub.redis/v1)" instance=<app-name>-7644d9548c-rdg9z scope=dapr.contrib type=log ver=1.10.2 |  
```

it was generating an enormous amounts of logs, around 100 000 per minute until we killed the pods, after restart everything went back to normal. Any idea on what might have caused the issue to appear again after the fix?
