### ISSUE TITLE
feature preview vs alpha API

### ISSUE THREAD

**Issue by dmitsh** [dapr/dapr#3942]
I'd like to raise a question about having a preview feature vs alpha API.
In both cases it indicates that the feature is not stable and there might be breaking changes.

So, why do we have both? Why not to have a uniformed way of indication of feature maturity?

I will give a concrete example.
Recently I delivered State Store Query API. After some deliberations it has been decided to release it as alpha API, i.e the invocation URL looks like `v1.0-alpha1/state/<store name>/query`

I'd like to argue that having this feature as the preview would make more sense.

My main argument is that when this API becomes stable, we would need to update every SDK that implements this API (as opposed to simply changing one field in dapr config). Potentially, changing an SDK might break existing user application.
So, to mitigate this problem we might need to gradually deprecate alpha API, i.e. maintaining both versions in our code.
All this make development more complicated and prone to bugs.
All this could be eliminated by using the preview flag.

I would like to get feedback from the community.
If there is a consensus, I would gladly change State Store Query API from alpha API to preview feature.
Please comment.
Thanks!

**Comment by artursouza** [comment]
I agree to use feature flag for alpha APIs so minimize breaking changes.

**Comment by yaron2** [comment]
I do not agree. The usage of a preview flag for APIs creates a horrible implicit behavior and inconsistency in almost all cases.

APIs need explicit maturity because URL paths, parameters, expected headers and data formats can change. You cannot reason about a transition from alpha to beta to stable based on a feature flag, nor can't you create multiple iterations of the API with a feature flag. (for example, v1.0-beta1 and v1.0 operating in parallel to give users the ability to migrate from beta to stable)

Once the API endpoint is v1.0, it means it cannot change its params, headers, format etc - certainly not the case for the query API specifically, and for any other API.

In terms of explicitness, I would rather be as explicit as possible and adhere to API versioning guidelines and industry standards which specify API versioning should occur on the endpoint itself (either in the path or as headers).

**Comment by beiwei30** [comment]
I agree with Yaron's opinion.
