### ISSUE TITLE
Investigate RocketMQ Increased goroutine Count

### ISSUE THREAD

**Issue by halspang** [dapr/dapr#4152]
RocketMQ had to be removed from the 1.6 release because importing caused an increase of ~30 goroutines. This was seen as too large an increase and should be investigated before we can include it in the dapr runtime.

![image](https://user-images.githubusercontent.com/70976921/150446835-03a763f9-519f-4b1a-a6a0-3a92f3822942.png)

**Comment by halspang** [comment]
@x-shadow-man, I saw you added RocketMQ, would you be a good person to investigate this as well?

**Comment by yaron2** [comment]
@shubham1172 did you end up taking a look at this?

**Comment by shubham1172** [comment]
No @yaron2, but I can track this going forward. Well, this looks like the root cause https://github.com/apache/rocketmq-client-go/issues/678

**Comment by shubham1172** [comment]
This issue has been fixed with the latest prelease by https://github.com/apache/rocketmq-client-go/issues/678. Here is a small example, the latest version does not cause any jump in go-routines.

### Baseline

```go
package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Printf("Number of goroutines: %d", runtime.NumGoroutine())
}
```

```ps1
Number of goroutines: 1
```

### RocketMQ v2.1.0

```ps1
go get github.com/apache/rocketmq-client-go/v2@v2.1.0
```

```go
package main

import (
	"fmt"
	"runtime"

	mqc "github.com/apache/rocketmq-client-go/v2/consumer"
)

func main() {
	_ = make(map[string]mqc.MessageSelector)
	fmt.Printf("Number of goroutines: %d", runtime.NumGoroutine())
}
```

```ps1
Number of goroutines: 31
```

### RocketMQ v2.1.1-rc2

```ps1
go get github.com/apache/rocketmq-client-go/v2@v2.1.1-rc2
```

Same code as above.

```ps1
Number of goroutines: 1
```

However, the latest version is still a pre-release - v2.1.1-rc2. Given that our Rocket MQ component will be alpha, it might be okay to use this (/cc @halspang). What do the maintainers think?

**Comment by yaron2** [comment]
Let's bring this back in 1.8.

**Comment by yaron2** [comment]
Closed via https://github.com/dapr/components-contrib/pull/1740.

**Comment by yaron2** [comment]
Reopening as not in `daprd` yet.
