### ISSUE TITLE
Pub/Sub permission for Service Account on Kubernetes

### ISSUE THREAD

**Issue by fdauri** [dapr/dapr#4168]
## In what area(s)?

/area runtime
/area test-and-release

## Ask your question here

Dear Dapr Team,

I'm trying to deploy a Pub/Sub component using Kafka on Kubernetes. The Kubernetes cluster has fine grain permession for service account. I obtain the following error:

components.dapr.io "pubsub" is forbidden: User "system:serviceaccount:dapr-poc:dapr-poc-sa" cannot get resource "components" in API group "dapr.io" 

It could be possibile to have a list of all permission needed?

Thanks.

Francesco

**Comment by yaron2** [comment]
Does this help? https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_rbac/templates/ClusterRoleBinding.yaml

**Comment by xendren** [comment]
Apologies for jumping in here, but I have the same issue trying to deploy a component in kubernetes.  We have installed dapr to our k8s cluster using the helm chart as instructed with the "dapr-system" namespace.  Our applications are deployed in other namespaces in the same cluster.  I have a secret created in my application namespace, and now I am attempting to setup the component so my app can access the secret.  I am receiving the following error executing kubectl with the component.yml file:
`Error from server (Forbidden): error when retrieving current configuration of:
Resource: "dapr.io/v1alpha1, Resource=components", GroupVersionKind: "dapr.io/v1alpha1, Kind=Component"
Name: "mat-dapr-dotnet-web", Namespace: "mat-dapr-dotnet-web-1"
from server for: "component.yml": components.dapr.io "mat-dapr-dotnet-web" is forbidden: User "u-9d8fc" cannot get resource "components" in API group "dapr.io" in the namespace "mat-dapr-dotnet-web-1"`

I'm guessing that our service account that is executing kubectl in our deployment pipeline needs some additional access to the API group "dapr.io" in order to deploy a component?  That account already has the "Cluster Owner" role.  I'm not confident I understand where components will be deployed in k8s.  Are they resources in the dapr-system namespace?  I'm not finding any clues in the Dapr Docs.

Any help would be appreciated.

**Comment by yaron2** [comment]
> Apologies for jumping in here, but I have the same issue trying to deploy a component in kubernetes. We have installed dapr to our k8s cluster using the helm chart as instructed with the "dapr-system" namespace. Our applications are deployed in other namespaces in the same cluster. I have a secret created in my application namespace, and now I am attempting to setup the component so my app can access the secret. I am receiving the following error executing kubectl with the component.yml file: `Error from server (Forbidden): error when retrieving current configuration of: Resource: "dapr.io/v1alpha1, Resource=components", GroupVersionKind: "dapr.io/v1alpha1, Kind=Component" Name: "mat-dapr-dotnet-web", Namespace: "mat-dapr-dotnet-web-1" from server for: "component.yml": components.dapr.io "mat-dapr-dotnet-web" is forbidden: User "u-9d8fc" cannot get resource "components" in API group "dapr.io" in the namespace "mat-dapr-dotnet-web-1"`
> 
> I'm guessing that our service account that is executing kubectl in our deployment pipeline needs some additional access to the API group "dapr.io" in order to deploy a component? That account already has the "Cluster Owner" role. I'm not confident I understand where components will be deployed in k8s. Are they resources in the dapr-system namespace? I'm not finding any clues in the Dapr Docs.
> 
> Any help would be appreciated.

Components need to be deployed in the same namespace of the apps that consume them.

**Comment by xendren** [comment]
> > Apologies for jumping in here, but I have the same issue trying to deploy a component in kubernetes. We have installed dapr to our k8s cluster using the helm chart as instructed with the "dapr-system" namespace. Our applications are deployed in other namespaces in the same cluster. I have a secret created in my application namespace, and now I am attempting to setup the component so my app can access the secret. I am receiving the following error executing kubectl with the component.yml file: `Error from server (Forbidden): error when retrieving current configuration of: Resource: "dapr.io/v1alpha1, Resource=components", GroupVersionKind: "dapr.io/v1alpha1, Kind=Component" Name: "mat-dapr-dotnet-web", Namespace: "mat-dapr-dotnet-web-1" from server for: "component.yml": components.dapr.io "mat-dapr-dotnet-web" is forbidden: User "u-9d8fc" cannot get resource "components" in API group "dapr.io" in the namespace "mat-dapr-dotnet-web-1"`
> > I'm guessing that our service account that is executing kubectl in our deployment pipeline needs some additional access to the API group "dapr.io" in order to deploy a component? That account already has the "Cluster Owner" role. I'm not confident I understand where components will be deployed in k8s. Are they resources in the dapr-system namespace? I'm not finding any clues in the Dapr Docs.
> > Any help would be appreciated.
> 
> **Components need to be deployed in the same namespace of the apps that consume them.**

@yaron2 Thank you for the reply.  If that is true, then I don't understand why I'm getting the forbidden error when trying to create the secretstore component in my namespace.  My user account has full access to that namespace.  I'm not sure what I am missing.  Also, shouldn't I be able to see the default "kubernetes" secretstore in the default namespace as a resource?  I am not seeing it in the UI.

**Comment by anobleperson** [comment]
@yaron2 I have the same issue as @xendren, unless I make a Role and RoleBinding Cluster wide, I get the error about forbidden. I note that in the example you sent that the role bindings are ClusterRole and ClusterRoleBinding. We're interested in Namespace scoped Roles and RoleBindings.  I've attached two sample yaml's to indicate what works and what gives the error. I'm sure I shouldn't have to give the CustomRole and CustomRoleBinding permissions, but I'm not sure what to use to avoid it
[working and not working yamls.zip](https://github.com/dapr/dapr/files/8338547/working.and.not.working.yamls.zip)
.
