### ISSUE TITLE
Why did remove PubSub / NATS component

### ISSUE THREAD

**Issue by zwq000** [dapr/dapr#4267]
pubsub components include nats-streaming and nats-jetstream, but remove  pubsub/nats .

In NATS documents, basic NATs is also called 'Core NATS', which is a basic subscription and publishing function.
Some existing systems also need to support 'Core NATS'

**Comment by yaron2** [comment]
Hi @zwq000, in accordance to the guidance issued by NATS maintainers, we will also deprecate NATS streaming (see [here](https://docs.nats.io/reference/faq#jetstream-and-nats-streaming) and [here](https://github.com/nats-io/nats-streaming-server#warning--deprecation-notice-warning) in the future, as this is now considered legacy and will stop receiving security fixes and patches.

Regarding Core NATS, it was replaced with NATS streaming at the time because it violated Dapr's pub/sub feature of at-least-once guarantee. This was unsupported by the underlying technology and wasn't fixable by changing the implementation.

**Comment by yaron2** [comment]
Closing this for now, but we can continue discussing here @zwq000 if you have further questions.

**Comment by zwq000** [comment]
@yaron2  Thank you very much. I also feel this through the documentation. Dapr's Pub / sub is designed based on load balancing, so a message can only be consumed once
