### ISSUE TITLE
"Subscription\" in version \"dapr.io/v2alpha1\""

### ISSUE THREAD

**Issue by dazhu6666** [dapr/dapr#4298]
time="2022-02-25T10:50:19.515414273Z" level=error msg="failed to list subscriptions from operator: rpc error: code = Unknown desc = error getting subscriptions: no matches for kind \"Subscription\" in version \"dapr.io/v2alpha1\"" app_id=dapr-test-api instance=dapr-test-api-77564cf9c7-gmsb6 scope=dapr.runtime type=log ver=1.5.0

in k8s

config

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: sub-dapr-test
spec:
  topic: sub-dapr-test
  route: /weatherforecast/get
  pubsubname: pubsub
scopes:
- dapr-test-api

code
  [Route("/weatherforecast/get")]

**Comment by yaron2** [comment]
It's possible you didn't update the CRDs when upgrading?

Try running `kubectl apply -f https://raw.githubusercontent.com/dapr/dapr/release-1.5/charts/dapr/crds/subscription.yaml` and see if the error repeats.

**Comment by dazhu6666** [comment]
@yaron2

**Comment by yaron2** [comment]
> # kubectl apply -f https://raw.githubusercontent.com/dapr/dapr/release-1.5/charts/dapr/crds/subscription.yaml
> Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply The CustomResourceDefinition "subscriptions.dapr.io" is invalid: spec.conversion.conversionReviewVersions: Invalid value: []string{"v1", "v2alpha1"}: must include at least one of v1beta1
> 
> not work

Download the YAML, and change this:

```yaml
conversionReviewVersions:
      - v1
      - v2alpha1
```

To this:

```yaml
conversionReviewVersions:
      - v1
      - v2alpha1
      - v1beta1
```

**Comment by dazhu6666** [comment]
Good。。it's work。。。thinks
@yaron2

**Comment by yaron2** [comment]
> 

@pkedy should we update the CRD to include this?

**Comment by relaxdiego** [comment]
For anyone else that ended up in this issue after Googling `spec.conversion.conversionReviewVersions: Invalid value: []string{"v1", "v2alpha1"}:`, the correct fix is to use `- v1` **and nothing else** because what `conversionReviewVersions` refers to is the version of the `ConversionReview` object that the k8s API server should send to the webhook and not the versions of the CRD. As per the docs:

> Webhooks are sent a POST request, with Content-Type: application/json, with a ConversionReview API object in the apiextensions.k8s.io API group serialized to JSON as the body.
>
> Webhooks can specify what versions of ConversionReview objects they accept with the conversionReviewVersions field in their CustomResourceDefinition:

See: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-request-and-response
