### ISSUE TITLE
Support UDS on Kubernetes

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#4309]
Today, Dapr supports unix domain sockets on self-hosted mode only. We should add a `dapr.io/unix-domain-socket-path` or similar annotation on Kubernetes and [mount a volume](https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/#creating-a-pod-that-runs-two-containers) (if possible; if not, instruct users to do so in the deployment YAML) for the given path.

cc @daixiang0

**Comment by daixiang0** [comment]
UDS share refers to https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume. 

Mark it as help wanted as I am busy recently, anyone interested can take it.

**Comment by iamhardikat11** [comment]
Sir, can you please describe more about this issue, I have fundamental knowledge regarding it, please elaborate a bit more?

**Comment by Taction** [comment]
Dapr now uses `unix-domain-socket` flag to define the unix domain dir, this should be exposed to service annotation. Better to add a mount volume (follow https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume.) to the helm and the path should be defined from `values.yaml`.

**Comment by jjaferson** [comment]
> Dapr now uses `unix-domain-socket` flag to define the unix domain dir, this should be exposed to service annotation. Better to add a mount volume (follow https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume.) to the helm and the path should be defined from `values.yaml`.

@Taction Not sure I follow how to add the volume mount to the helm, in my understanding the ask for this issue is to get the volume name from a pod annotation (`dapr.io/unix-domain-socket-volume-name`), mount a volume in the injected sidecar container and set the flag `--unix-domain-socket` with the path as argument to the service.

Added an exemple here in my fork https://github.com/jjaferson/dapr/commit/254ff111c5997187ff652f935dae65b4d6d2891c

**Comment by yaron2** [comment]
> > Dapr now uses `unix-domain-socket` flag to define the unix domain dir, this should be exposed to service annotation. Better to add a mount volume (follow https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume.) to the helm and the path should be defined from `values.yaml`.
> 
> @Taction Not sure I follow how to add the volume mount to the helm, in my understanding the ask for this issue is to get the volume name from a pod annotation (`dapr.io/unix-domain-socket-volume-name`), mount a volume in the injected sidecar container and set the flag `--unix-domain-socket` with the path as argument to the service.
> 
> Added an exemple here in my fork [jjaferson@254ff11](https://github.com/jjaferson/dapr/commit/254ff111c5997187ff652f935dae65b4d6d2891c)

What you did in your fork is the way to go about it. I think the volume would need to get mounted on all containers in the pod though.

**Comment by yaron2** [comment]
Looks like there's a PR in for this: https://github.com/dapr/dapr/pull/4348#event-6214701548

**Comment by daixiang0** [comment]
I have created a draft as #4348, it can share UDS volume among all containers.

**Comment by jjaferson** [comment]
I had a look at your PR @daixiang0 and it looks good, maybe something to consider is adding a check to verify if the volume already exists and instead of passing a path via the `dapr.io/unix-domain-socket-path` annotation only specify the name of the shared volume as apparently according to the [documentation](https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/#creating-a-pod-that-runs-two-containers) the volume mount name used in the sidecar container should match the volume name

**Comment by daixiang0** [comment]
The volume name is hard to conflict I think.
