### ISSUE TITLE
Method invocation error handling for invalid method name

### ISSUE THREAD

**Issue by shubham1172** [dapr/dapr#4344]
Related PR: https://github.com/dapr/cli/issues/909
Service invocation API reference: https://docs.dapr.io/reference/api/service_invocation_api/

### Invalid app-id

Whenever one makes a HTTP call to Dapr with invalid app ID, it handles it gracefully and returns a proper message.

<details>
<summary>Sample request</summary>

```bash
curl --location --request POST 'http://localhost:3500/v1.0/invoke/nodeapp1/method/neworder' \
--header 'Content-Type: application/json' \
--data-raw '{
    "data": {
        "orderId":"42"
    }
}'
```
</details>

<details>
<summary>Response (Status code: 404)</summary>

```json
{
    "errorCode": "ERR_DIRECT_INVOKE",
    "message": "fail to invoke, id: nodeapp1, err: couldn't find service: nodeapp1"
}
```
</details>

### Invalid method name

However, when the method name is invalid, the response is a generic one.

<details>
<summary>Sample request</summary>

```bash
curl --location --request POST 'http://localhost:3500/v1.0/invoke/nodeapp/method/neworder1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "data": {
        "orderId":"42"
    }
}'
```
</details>

<details>
<summary>Response (Status code: 404)</summary>

```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Cannot POST /neworder1</pre>
</body>

</html>
```
</details>

## Problem

The generic message makes it difficult for the consumer (including dapr/CLI) to figure out what's wrong with the request. 

There is an error message in place for `method not found`, but it's not consumed anywhere.

https://github.com/dapr/dapr/blob/48a26f3d180544952d329a1d3dc4317a83fe9ee0/pkg/messages/api_errors.go#L60-L64

## Discussion

Should we add a special handling for the same, and if yes, what are some recommended ways to do that?

**Comment by yaron2** [comment]
The Service Invocation methods should be as close to a transparent proxy as possible and not interpret any status codes or make decisions based on these that alter the returned response from the target endpoint.

cc @paulyuk

**Comment by shubham1172** [comment]
@yaron2 is there a more elegant way for Dapr CLI (or any other consumer) users to figure out what went wrong? 404 can be either the URL is itself broken, or the method name is incorrect.

**Comment by yaron2** [comment]
A method name is essentially a part of the URL, so broken URL == method name is incorrect.

If we accept that, then a consumer can interpret a `404` response as URL not found for the target app.

Of course, the Dapr itself can return 404 if you get the Invoke URL wrong, ie. `/invokexxx/order`. The CLI is free of such issues since the `invoke` command on the CLI uses a correct Dapr URL that cannot be changed by the user.

Over time, we will change all docs to show this method of service invocation: `curl -H 'dapr-app-id: checkout' 'http://localhost:3602/checkout/100' -X POST` which doesn't rely on a specialized URL endpoint.

More info [here](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/#additional-url-formats).
