### ISSUE TITLE
Actor samples are not working in dotnet-sdk

### ISSUE THREAD

**Issue by amulyavarote** [dapr/dapr#4457]
The way actors report their errors in the runtime has changed.

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Release Note

RELEASE NOTE:

**Comment by amulyavarote** [comment]
@halspang The issue is created for the actor samples in dotnet-sdk. Can you please add the description here?

**Comment by halspang** [comment]
The reason this is happening is .NET actors communicate errors with a header instead of sending failing requests. The SDK handles the error internally by inspecting for that header. With resiliency, we made that error a real error (so we could retry on it). It seems like .NET didn't like that so I'll fix the issue to no longer return an error after the retry loop.

Thanks for finding this @amulyavarote! I was worried we'd run into stuff like this when we started fiddling with the actor call path.

**Comment by yaron2** [comment]
@halspang Discord seems to be down, can you join a short call with me?

**Comment by halspang** [comment]
@yaron2 - Sure can.

**Comment by yaron2** [comment]
@halspang https://meet.google.com/qbe-eehz-yfc
