### ISSUE TITLE
Parallelize steps in KinD E2E workflow

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4495]
All the steps for Kind E2E are now sequentially and are taking a long time (about 37 minutes). Since these run on every PR, we could expedite time to merge approved PRs by reducing the overall time for these runs.

**Comment by ItalyPaleAle** [comment]
@artursouza I've looked into this but I'm afraid that this can't be optimized much with parallelization. The different KinD clusters are already running in parallel so that can't be improved much.

What could be done here, however, is increasing the use of caching. The second-longest task is building e2e test images, which could presumably be cached extensively. This is also connected to #4497
