### ISSUE TITLE
Actor client requires an actor state store even if not using actors.

### ISSUE THREAD

**Issue by withinboredom** [dapr/dapr#4509]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

- 1.5.2
- 1.6.1
- 1.7.0

## Expected Behavior

An actor client shouldn't need any access to state stores unless it is utilizing a state store.

## Actual Behavior

An actor client needs access to a state store configured for actors, not necessarily the same state store.

## Steps to Reproduce the Problem

The easiest way is to check out this [commit](https://github.com/dapr/php-sdk/pull/130/commits/6daf3ad736273305beed9872abb9ef42fbcc4c02) in the PHP repo where this issue was discovered. You can revert the changes in that example and run `make && make start` (see the example README). After `curl -s http://localhost:8080/method/hello_world/get_count | jq .`, you'll receive the error:

```
{\"errorCode\":\"ERR_ACTOR_RUNTIME_NOT_FOUND\",\"message\":\"actor runtime is not configured\"}"
```

Potentially related issues/PRs: #4273

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
@Taction can you look into this please?

**Comment by Taction** [comment]
@yaron2 Sure, I'll look into this.

**Comment by Taction** [comment]
This is because the `initActors()` func has checked if the actor state store is defined: https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L1771

To fix this issue, we can add the check of `actorConfig.EntityConfigs.Entities` to tell if it is server-side or client-side.
But consider #4273, we can turn this error into a warning log. If the actor server uses the state store and the actor state store is not defined, the error is `state store does not exist` (and we can add more info to that error).

**Comment by yaron2** [comment]
> This is because the `initActors()` func has checked if the actor state store is defined: https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L1771
> 
> To fix this issue, we can add the check of `actorConfig.EntityConfigs.Entities` to tell if it is server-side or client-side. But consider #4273, we can turn this error into a warning log. If the actor server uses the state store and the actor state store is not defined, the error is `state store does not exist` (and we can add more info to that error).

That's a great find, and agree about changing the error to a warning log.
