### ISSUE TITLE
broken backward compatibility for ttl feature of actor timers

### ISSUE THREAD

**Issue by javageek79** [dapr/dapr#4514]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

 1.5.x
 1.6.x
 1.7.x

## Expected Behavior

Actors working as before when migrating from rt v1.5 to v1.6 or v1.7

## Actual Behavior

_just make sure to keep backward compatibility in mind, so we need to ALSO accept ISO 8601 intervals._

_Originally posted by @yaron2 in https://github.com/dapr/dapr/issues/2513#issuecomment-820095976_

As we use java-sdk we now wanted to upgrade our rt from 1.5 to 1.6 and after that to 1.7. Unfortunatelly we get the following warning in our logs

``
2022-04-12 17:42:41.348 [http-nio-7070-exec-8]  ERROR c.r.p.a.dapr.MyActorImpl.lambda$registerTimer$1(68) - error on registering timer p-timer10 java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN: timer MyActor||b32e-4f6b-8c8e-2a2cc4123ead||p-timer10 has already expired: dueTime: 0h0m0s0ms TTL:  [anonymousUser, , fasthttp]
``

As there is currently no support in java sdk, see https://github.com/dapr/java-sdk/issues/569, is there maybe a workaround to avoid such errors?

## Release Note

RELEASE NOTE:

**Comment by halspang** [comment]
Just to clarify, on 1.5 you see no issues. It's when running 1.6 _or_ 1.7 that this failure comes up?

**Comment by halspang** [comment]
Also, what version of the Java SDK are you using?

**Comment by halspang** [comment]
@javageek79 - Are you using DueTimes at all? I was just playing around with this in .NET and ran into your error. Tracking it down I found my Timer was failing because it thinks the DueTime is in the past when in reality it was sent in as 0 to fire immediately.

This is a change that was introduced in 1.6. https://github.com/dapr/dapr/commit/0c070e1afb620987141443c18db0cd34817ad794

@yaron2 @artursouza - Do you have context on the above commit? Semantically it doesn't seem correct. The DueTime being "in the past" should just mean to fire immediately. We have an example in our docs of submitting a Timer with a DueTime of 0.

In the code, if the DueTime is 0, we set it to `time.Now` but then compare it to another `time.Now` for the check in the above commit. Seems destined to fail unless it can happen faster than a `time.Time` scale (nanoseconds?).

**Comment by halspang** [comment]
PR for that commit, not sure why it didn't associate directly: https://github.com/dapr/dapr/pull/4075

**Comment by artursouza** [comment]
@halspang  The commit you mentioned seem to be wrong because there is no guarantee that the timer will fire right away. We need some configuration to call a timer dueTime to be stale (1min, 5min or something). We would also need an E2E test to verify that. /cc @tanvigour

**Comment by yaron2** [comment]
> /cc @yaron2 I think this is a P0 and should be a hotfix in 1.6 and 1.7.

Yeah it looks like it.

**Comment by berndverst** [comment]
@artursouza @halspang that code is only for Timers and not Reminders though...

**Comment by berndverst** [comment]
Ah -- I was confused due to the title and original description -- yes Timers are broken here, not reminders.

**Comment by javageek79** [comment]
@berndverst sorry, I corrected the title, ofcourse, this affects timers.

@halspang yes, our actor has two timers, one has a duetime of 0 to start right away and a period, the other has a due time to `n`-min and a period of zero. The second timer we would like to get rid of once we can use the ttl feature as it is only a workaround to cancle the first timer after `n`-min
