### ISSUE TITLE
FOSSA scan fail

### ISSUE THREAD

**Issue by daixiang0** [dapr/dapr#4523]
See https://github.com/dapr/dapr/runs/6033380196?check_suite_focus=true#step:3:1.

@shubham1172 could you take a look and fix it?

RELEASE NOTE: N/A

**Comment by shubham1172** [comment]
All our FOSSA workflows are broken due to a recent change in the action repo. As an immediate work item, I have created a PR to fix the same https://github.com/fossas/fossa-action/pull/23

Going forward, we should stick to a particular version of the action, rather than using `@main`. 
We have a GH issue for moving common workflows to a separate repository (TODO: add link). FOSSA workflow can be pinned to a version during the migration.

**Comment by yaron2** [comment]
> All our FOSSA workflows are broken due to a recent change in the action repo. As an immediate work item, I have created a PR to fix the same [fossas/fossa-action#23](https://github.com/fossas/fossa-action/pull/23)
> 
> Going forward, we should stick to a particular version of the action, rather than using `@main`. We have a GH issue for moving common workflows to a separate repository (TODO: add link). FOSSA workflow can be pinned to a version during the migration.

Fixing it in FOSSA's main branch is right thing to do long term, but wouldn't the immediate action be to use a versioned release that doesn't have this change?

**Comment by shubham1172** [comment]
@yaron2 sure, that makes sense since it might take a while to be reviewed. Here we go:
1. https://github.com/dapr/kit/pull/15
2. https://github.com/dapr/cli/pull/967
3. https://github.com/dapr/dashboard/pull/203
4. https://github.com/dapr/dapr/pull/4530
5. https://github.com/dapr/components-contrib/pull/1676
6. https://github.com/dapr/java-sdk/pull/734
7. https://github.com/dapr/go-sdk/pull/282
8. https://github.com/dapr/js-sdk/pull/250
9. https://github.com/dapr/python-sdk/pull/390

**Comment by shubham1172** [comment]
FYI, the main branch of the fossa action is also fixed.

**Comment by artursouza** [comment]
All PRs are now merged. Thanks for fixing this @shubham1172. Another instance where fixing to "master" or "edge" or "latest" version of a dependency breaks us.

**Comment by daixiang0** [comment]
@shubham1172 https://github.com/dapr/components-contrib/runs/6406024654?check_suite_focus=true#step:4:39, does it fail again? No helpful info for contributors looks bad.

**Comment by shubham1172** [comment]
That is the problem with using push-only API keys. The FOSSA access is in process of being extended to Dapr maintainers so I won't be a bottleneck anymore. FYI, this failed because it started throwing false positive for github.com/chzyer/logex (it's already MIT licensed).

**Comment by daixiang0** [comment]
> That is the problem with using push-only API keys. The FOSSA access is in process of being extended to Dapr maintainers so I won't be a bottleneck anymore. FYI, this failed because it started throwing false positive for github.com/chzyer/logex (it's already MIT licensed) - I have resolved it.

@shubham1172 Hi, where Dapr maintainers can see the detailed error like https://github.com/dapr/dapr/runs/7601629813?check_suite_focus=true?

**Comment by shubham1172** [comment]
@daixiang0 you can check it here https://app.fossa.com/projects?teamId=1282

**Comment by daixiang0** [comment]
@shubham1172 now push-only keys make contributors no access to detailed error, is it safe to use other keys?

/cc @artursouza @yaron2

**Comment by shubham1172** [comment]
@daixiang0, we can configure a central key in Dapr organization for FOSSA (similar to Dapr bot). However, push-only keys were the recommended way for open source projects, and maintainers have access to triage/resolve the issues from the FOSSA portal. 

The only scenario in which other API keys might be useful can be when a contributor is introducing a new dependency which is incompatible and gets this error. Do you think we should change the API keys for this specific scenario?

**Comment by daixiang0** [comment]
Got, as a user, I want to FOSSA can report issues where it runs, at least a web link.

Now I know how FOSSA action work, it depends on maintainers, assume maintainers, not contributors to fix, different from other CI flow.
