### ISSUE TITLE
Add metrics for Resiliency

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#4524]
We need to add request count and error rates for:

* Retries
* Circuit Breakers
* Timeouts

The label should contain the component name and namespace.

Before Merging complete docs https://github.com/dapr/docs/issues/2401

**Comment by yaron2** [comment]
| Metric Name  | Description   | Type       | Tags         
| ------------- | -----------  | ---------- | -------------
| total  | Number of resiliency policies loaded | UnitDimensionless | name <br> namespace <br> policy
| count  | Number of times a resiliency policy has been executed | UnitDimensionless | name <br> namespace <br> policy

#### Tags

| Name  | Description   
| ------------- | ----------- 
| name | Name of the resiliency policy
| namespace  | The namespace of the policy
| policy | Values: `retry`, `timeout`, `circuitbreaker`

**Comment by artursouza** [comment]
`total` and `count` are not descriptive enough since they are measuring different things (loaded count vs execution count). Does it make sense to have total since there is always one policy per name, not? 

I propose we just have `count` or `execution_count` and it would avoid the confusion.

If we really think `load_total` is needed, we can have `loaded` or `load_count` and it would always emit this metric when the given policy is loaded.

**Comment by artursouza** [comment]
I think that removing the `policy` tag makes more sense now. LGTM.

**Comment by artursouza** [comment]
What is the meaning of `name` tag? Is it the policy's name?

**Comment by yaron2** [comment]
@artursouza updated the list based on convo.

**Comment by piotrkpc** [comment]
would it be useful to capture more detailed metrics for circuit breakers like, `number of times operation was called in half-open state` and `open state` ?

I declared on chat that I would work on  this but I had to take couple days off recently. Sorry for not starting this earlier.

**Comment by piotrkpc** [comment]
I was thinking about following metrics:
| Metric name                            | Description                                                                                    | Type              | Tags                                               |
|----------------------------------------|------------------------------------------------------------------------------------------------|-------------------|----------------------------------------------------|
| circuitbreaker_too_many_req/count      | The number of execution attempts in half-open state when request count is over maxRequest      | UnitDimensionless | app_id, namespace, operation_name, name (optional) |
| circuitbreaker_half_open/failure_count | The number of execution failures when cb is in half-open state and request count < maxRequest  | UnitDimensionless | app_id, namespace, operation_name, name (optional) |
| circuitbreaker_open/count              | The number of execution attempts in open state.                                                | UnitDimensionless | app_id, namespace, operation_name, name (optional) |

**Tags**:
`operation_name` - operation name for `Policy`
`name` - would be optional since it's `cb.Name` is part of `operation_name`

It might be useful to have those metrics for troubleshooting.

**Comment by yaron2** [comment]
> I was thinking about following metrics:
> 
> Metric name	Description	Type	Tags
> circuitbreaker_too_many_req/count	The number of execution attempts in half-open state when request count is over maxRequest	UnitDimensionless	app_id, namespace, operation_name, name (optional)
> circuitbreaker_half_open/failure_count	The number of execution failures when cb is in half-open state and request count < maxRequest	UnitDimensionless	app_id, namespace, operation_name, name (optional)
> circuitbreaker_open/count	The number of execution attempts in open state.	UnitDimensionless	app_id, namespace, operation_name, name (optional)
> **Tags**: `operation_name` - operation name for `Policy` `name` - would be optional since `cb.Name` is part of `operation_name`
> 
> It might be useful to have those metrics for troubleshooting.

@piotrkpc These are good metrics to have for troubleshooting as you pointed out. my only concern is in regards to making metrics volume size bigger. This is already an issue today, as Dapr metrics are already rather verbose and when sent to an out-of-cluster metrics store, this incurs some serious egress fees. Considering this is used for troubleshooting mainly (as opposed to monitoring aggregated data points), I'm asking myself if it won't be easier to diagnose issues using more verbose debug logs for resiliency which we're adding over time.

I suggest we do this in stages: would it be OK for you to open a PR that adds the metrics proposed [here](https://github.com/dapr/dapr/issues/4524#issuecomment-1142306821) while we continue the discussion?
