### ISSUE TITLE
proposal: make `metadata` in Dapr API more portable 

### ISSUE THREAD

**Issue by seeflood** [dapr/dapr#4603]
## In what area(s)?

 /area runtime

### The problem we want to solve: the APIs are not portable!
We use dapr API in production environment. When we want to deploy same app on different clouds, we are sad to find that the app is not portable due to the `metadata`. We can't make the app "Write once, run on any cloud".

I will give some scenarios below.

#### Scenario 1. an app wants to migrate from "Azure servicebus" to "Azure Event Hubs" component
Currently there are `metadata` fields in different Dapr API. For example ,we have a `metadata` in pubsub API:
```proto
message PublishEventRequest {
  // .......

  // The metadata passing to pub components
  //
  // metadata property:
  // - key : the key of the message.
  map<string, string> metadata = 5;
}
```

The `metadata` is a map,and different components know different keys.

For example, [Azure servicebus use these keys](https://github.com/dapr/components-contrib/blob/62c5a2b3d1964556bf7a281f401e0056095bcef2/pubsub/azure/servicebus/message.go#L48):
- PartitionKey
- Label
- ......

![image](https://user-images.githubusercontent.com/26001097/167749670-88bfb4b9-1993-4534-8fce-752b97e2aa54.png)

While [Azure Event Hubs use these keys](https://github.com/dapr/components-contrib/blob/62c5a2b3d1964556bf7a281f401e0056095bcef2/pubsub/azure/eventhubs/eventhubs.go#L45) :
- partitionKey (note: the corresponding key in Azure servicebus component is `PartitionKey`)

![image](https://user-images.githubusercontent.com/26001097/167750442-85955275-f141-4988-ae15-63163dbe1584.png)

This design looks good. But not that good when we look at portability.

When an app wants to migrate from Azure servicebus to Azure Event Hubs, the latter component does not know the key `PartitionKey` of the former component, so the app developer has to refactor their code and pass different `metadata` keys to dapr. We lose portability here.

![image](https://user-images.githubusercontent.com/26001097/167759323-5359bb67-d8df-49d9-b2ef-44ad473b70c1.png)

#### Scenario 2. "metadata explosion" when writing our own component
Even worse, in complex production environments(where we deploy our own message broker instead of open source MQ), we are sad to find that we have to define tons of metadata keys when writing our own components, and of course these "private" keys are of no portability. 

@skyao presented [an example in his blog(in chinese)](https://skyao.io/talk/202111-important-of-api-standardization-for-dapr/). In his case, they had to define the metadata keys below for their state component:

![](https://skyao.io/talk/202111-important-of-api-standardization-for-dapr/images/metadata-tair_hu9bcc4aa3d7891bef78748ebf65785be1_106321_1200x1200_fit_q75_lanczos.jpg)

We also encountered similar problems in our production environment.

### How to make it portable
Of course, we can ideally say that "to solve this problem, we just need to define a more powerful and richer dapr api". This sounds right, but it's a long way off, and there's an inevitable problem: we're designing APIs for the "intersection" of component features, but the "intersection" design philosophy can not meet all needs, so there will always be some special fields to be put in metadata.

![image](https://user-images.githubusercontent.com/26001097/167884430-38036a3b-2eb9-4e24-a9b9-91a84f5be7a6.png)

To solve this problem, I think we should implement some key features:
#### 1. define a spec for metadata keys

In real world, users might need "weak portability". For example ,they want to deploy their apps on AWS and Azure, and they don't care about Google cloud. So we can define a spec for the "feature set intersection" of AWS and Azure, which is the blue part below:

![image](https://user-images.githubusercontent.com/26001097/167886166-8b2b135b-dc39-4cf6-be54-2c953604af95.png)

I will give a detailed solution below.

#### 2. design a "feature discovery" mechanism
There are some solutions for "feature discovery"
A. app communicate with sidecar during startup and check whether the features are enough
I just found https://github.com/dapr/dapr/issues/4367 .
Not sure if it falls into this category

B. design an auto-binding mechanism to do "feature discovery" during deployment time
// TODO

**Comment by seeflood** [comment]
The disadvantage of the enumeration design is that It's an incompatible change. The key of metadata is modified from string to PublishRequestEnum:

```proto
message PublishEventRequest {
  // .......

  // The key is modified from string to PublishRequestEnum, which is incompatible !
  map<PublishRequestEnum, string> metadata = 5;
}

enum PublishRequestEnum {
  PARTITION_KEY = 0;
  XXXX = 1;
  // ......
}
```

So there's a compatible Solution B here:

We don't modify the proto. The key of metadata is still string.
```proto
message PublishEventRequest {
  // .......

  map<string, string> metadata = 5;
}
```

Instead, we define const for all metadata keys. For example, in `components-contrib/pubsub` package, we add const:
![image](https://user-images.githubusercontent.com/26001097/167801275-5da224ff-8354-4ce5-a81b-13fd151ad531.png)

When a component wants to read the metadata, it should refer to the const. For example, Azure eventhub component should be modified to :

![image](https://user-images.githubusercontent.com/26001097/167801949-74ba7784-260b-415c-bf45-2e7bb6c2f433.png)

When a component developer has to add a new key in metadata, he/she should check the existing const carefully before adding it.

**Comment by kevinten10** [comment]
What I'm curious about is how the user's program gets custom fields such as `partitionkey`.

Is it possible to move custom configuration(metadata fields) from the code into the `config component` in order to make the code "write once, run on any cloud".

My idea is to free the complex metadata custom logic from the code. Put it in the config component or in an external custom callback function like webassmbly.

This way, the metadata will continue to stay fresh.

### I think the fields in these metadata can be divided into 3 categories:

#### Similar to the design idea of ​​`Spring` : convention over configuration

Our components provide default configuration values(metadata fields). If the user wants to customize them, they will overwrite the corresponding files and configure them according to the agreed file name and file format.

#### 1. Static metadata fields

We can put this part of the configuration into the configuration file of the config component and bind it with the application.

For example, we define such a file in the config component.

_state-redis-static-config.json_
```json
{
   "partitionkey":...
}
```

The redis state component provides a default value. Users can override this file in config component if they need to customize it.

#### 2. Request-based static metadata fields

Is it possible to put it in the config component. For example, user request pass in <configKey: value> in the metadata, and then configure the following content in the config component:

_state-redis-key-config.json_
````
[
    {
        "configKey1": {
            "ttlInSeconds": 10
        },
        "configKey2": {
            "ttlInSeconds": 15
        }
    }
]
````

Use different configurations in different components:


_state-mysql-key-config.json_
````
[
    {
        "configKey1": {
            "key-type": varchar
        },
        "configKey2": {
            "key-type": int
        }
    }
]
````

#### 3. Request-based dynamic metadata fields

If the generation of the configuration depends on a piece of dynamically calculated logic, is it possible to provide such a callback method in the sdk:

E.g java-sdk:

````java
interface MetadataFunc<T> {
    Map<String, String> callback(T requestData);
}

<T> Mono<State<T>> getState(GetStateRequest request, TypeRef<T> type, MetadataFunc<GetStateRequest> callback);
````

Or in the future, when the `webassmbly` is mature, this callback function can be placed in webassmbly and executed by the `runtime`.

---

I don't know if I understand it clearly. Looking forward to continuing to communicate.

**Comment by olitomlinson** [comment]
A great example of this problem space is in bindings :

This is the `Local storage` binding 

![image](https://user-images.githubusercontent.com/4224880/169552659-86ed2d6d-c982-415a-b5bd-f335a0fac4e2.png)

This is the `AWS S3` binding :

![image](https://user-images.githubusercontent.com/4224880/169552810-a2d74ccd-0d76-42f5-a484-c5b82835540d.png)

This is the `Azure Blob Storage` binding : 

![image](https://user-images.githubusercontent.com/4224880/169553401-8095fed0-118f-470b-beba-e99d4bc03886.png)


The API surface is _almost_ identical here.

It only differs in `metadata.key` and `metadata.fileName` and `metadta.blobName` key name, which means the user-code is not portable even though the APIs are very close.

As it stands, I avoid talking too much about dapr from a `portability` and `write once` value proposition, because there is no construct to get parity. 

If there was a solution which allowed me to inject my own mappings (via a CRD?) then my user-code would not have to change depending on the environment, which would make it possible to really _sell_ the portability aspects of dapr building blocks.

**Comment by beiwei30** [comment]
I agree with @seeflood 's idea of promoting common used keys from metadata to fixed enum for each kind of component, since by doing this, I believe it will introduce a minimal acceptable portability among different component offers. 

For others keys unique to one specific component offer (impl), should we introduce an new API on daprd side so that the app has chance to realize the component offer is changed from a to b so that the the user code can handle metadata gracefully according to the query result from daprd sidecar. There are pro and con by doing this. The developers need to aware of all component offers the app may migrate from one to another in advanced, and write more code of cause, but at the same time, the operators are free to migrate the app from one component offer to the other. 

@yaron2 your opinion on this?

**Comment by bbrandt** [comment]
+1
