### ISSUE TITLE
How can I get into daprio/daprd:edge-linux-amd64 container

### ISSUE THREAD

**Issue by iweixubin** [dapr/dapr#4623]
docker run --net="host" --mount type=bind,source="$(pwd)"/components,target=/components daprio/daprd:edge ./daprd -app-id <my-app-id> -app-port <my-app-port>

images
daprio/daprd:edge-linux-amd64
daprio/daprd:1.7.2-linux-amd64

/bin/ash
/bin/bash
/bin/sh

all failed

**Comment by berndverst** [comment]
You cannot because it uses the distroless base image. So the question is really how you can get into any distroless container.

If you need to do this please build the debug containers yourself:

`make build-linux`  (or `make DEBUG=1 build` if you want to attach a debugger)
`make DEBUG=1 docker-build` (this builds the dapr containers but instead of distroless uses Ubuntu so you can get into the container etc)

```bash
# if you want to run these container in Kubernetes you'll need to publish them to a registry
export DAPR_REGISTRY=docker.io/<your_docker_hub_account>
export DAPR_TAG=dev
make docker-push
```

And then in your Dapr helm deployment (or installation via CLI) you need to specify the image registry and tag name to use these containers.

There are some convenience commands to do this:

```bash
kubectl create namespace dapr-system
helm uninstall dapr -n dapr-system
make docker-deploy-k8s
```


https://github.com/dapr/dapr/blob/5ef3864389d583e6f13fa54efc3d671f91a87916/docs/development/developing-dapr.md#developing-on-kubernetes-environment
