### ISSUE TITLE
Log app response for incoming invocation requests if API logging is enabled

### ISSUE THREAD

**Issue by berndverst** [dapr/dapr#4706]
/area runtime

Today it is difficult to troubleshoot failures related to service invocation. Most of the time these errors occur on the callee / receiver side but the sidecar logs no information there. This then causes a user or operator to unnecessarily investigate the caller / sender app or the transport layer.

I propose that whenever the existing `enable-api-logging` flag is enabled, we also log the response of incoming service invocation requests in the sidecar.

RELEASE NOTE:
**ADD** Additional logging for incoming service invocation requests when API logging is enabled.

**Comment by yaron2** [comment]
Logging responses can be very dangerous in terms of IO perf and creating bottlenecks (both for local IO and log sink like Elastic etc.) if there's a high throughput request rate with sizable responses. Another issue of course is creating noise in the logs making actual errors unable to spot.

The second issue here is with tying this functionality to the API logging. The declared, single purpose of the API logging feature is to produce an event log of all incoming calls to the sidecar. It seems unrelated to now say that API logging produces a log of all events AND call responses of target apps for the Service Invocation building block only.

The third issue I have is with this:

> Most of the time these errors occur on the callee / receiver side but the sidecar logs no information there. This then causes a user or operator to unnecessarily investigate the caller / sender app or the transport layer.

Errors from your business apps should not be diagnosed through the proxy/sidecar/dataplane, and in most proxies it's also not doable for that purpose.
If the Dapr sidecar on the other side is erroring, then this error should be logged. If a target app is erroring, users know to examine the status code and response that comes back as this is a non Dapr, business domain related error. Without Dapr/another proxy in place, this is what happens.

**Comment by berndverst** [comment]
@yaron2 the problem is that if the target app is erroring this isn't sufficiently clear in the service invocation response today. You never know just how far the request actually made it.

This is what I want to address somehow. It doesn't have to be this logging feature here, but we need something better than what we have today.

**Comment by yaron2** [comment]
> You never know just how far the request actually made it.

I'd argue that rarely do you not know how far the request actually made it. The most common example is the app trying to invoke Dapr before the sidecar is running, resulting in `connection refused`. Clearly, the request never made it to Dapr.

The second most common example is invoking an app and due to a network error or any failure in either Dapr sidecar, which results in Dapr returning a Dapr specific error `ERR_DIRECT_INVOKE` with the actual error on the response based on a well known return object.

When a call goes through fine as far as Dapr's concerned and the target app returns an error, developers can examine the response to tell if this was a Dapr error or not.
