### ISSUE TITLE
Support namespace isolation/multi-tenancy for Dapr Actors

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#4711]
## In what area(s)?

> /area runtime

> /area operator

## Describe the feature
_Apologies in advance, this issue probably needs a better title!_

In the same vein as this [issue - Option to prefix state key with namespace](https://github.com/dapr/dapr/issues/4676), we want to deploy many copies of our entire system to our dev test cluster. However, Dapr Actors do not currently support this level of namespace isolation/multi-tenancy, so we are blocked on adopting Dapr Actors across the board of of developments.

**Comment by olitomlinson** [comment]
@yaron2 

Do I understand correctly that [this](https://github.com/dapr/dapr/issues/4226) change would be a pre-requisite for this particular ticket?

**Comment by yaron2** [comment]
> this

Not a pre-requisite per-se, but yes, this needs to be done together with the runtime changes.

**Comment by yaron2** [comment]
Not directly related, but a project like [VCluster](https://www.vcluster.com/) allows you to create virtual clusters as namespaces inside a parent cluster. You can then install Dapr (or any other platform) in the virtual cluster for a multi-tenant architecture.

**Comment by danielgerlag** [comment]
Any news on this issue?

**Comment by MargaretKrutikova** [comment]
We actually implemented something similar in our system on our own, since we were using a single instance of Redis on Azure for the state store and were storing actor state from different k8s environments in it. In the dev environment we create  a separate namespace per branch so we wanted to have each actor state prefixed with the branch name (or namespace name), and in prod we have blue/green so we wanted to achieve the same setup (prefix state with blue/green or live/staging). We achieved the setup by hijacking the k8s namespace value into a custom `IActorProxyFactory` to prefix each actor name with the namespace, and also added some DI magic, and everything worked as we expected nicely separating the actors for each namespace, since now the actor names contained the name of the namespace. If someone is interested I can create a public repo with this setup, or post it here (it is a lot of code though). Let me know if there is still interest in this!

**Comment by olitomlinson** [comment]
> We actually implemented something similar in our system on our own, since we were using a single instance of Redis on Azure for the state store and were storing actor state from different k8s environments in it. In the dev environment we create a separate namespace per branch so we wanted to have each actor state prefixed with the branch name (or namespace name), and in prod we have blue/green so we wanted to achieve the same setup (prefix state with blue/green or live/staging). We achieved the setup by hijacking the k8s namespace value into a custom `IActorProxyFactory` to prefix each actor name with the namespace, and also added some DI magic, and everything worked as we expected nicely separating the actors for each namespace, since now the actor names contained the name of the namespace. If someone is interested I can create a public repo with this setup, or post it here (it is a lot of code though). Let me know if there is still interest in this!


@MargaretKrutikova 

I would appreciate it if you could upload a public repo of this and link it to this comment! Thanks so much!

**Comment by MargaretKrutikova** [comment]
No problem! I will do it later today in the evening 🙂

**Comment by MargaretKrutikova** [comment]
Hello @olitomlinson ! Apologize for a week's delay, [here](https://github.com/MargaretKrutikova/DaprActorMultiTenancy) is a small github repo implementing actor namespace isolation. Please let me know if it works/doesn't work or if you have ideas/want to discuss something 🙂

**Comment by jeremylcarter** [comment]
@MargaretKrutikova How is your solution going? I came up with something similar:
https://github.com/dapr/dapr/issues/4226#issuecomment-1837855629

**Comment by MargaretKrutikova** [comment]
The solution I provided in that github repo worked for us and we were able to isolate feature environments for each branch via different k8s namespaces and namespaced actors. Unfortunately, we are moving away from Dapr since we have had a lot of struggle with bugs that were breaking a lot of actor functionality with almost every Dapr update, lack of functionality that we had to work around that eventually proved to be too complex and very unstable setup for local development.

**Comment by jeremylcarter** [comment]
@MargaretKrutikova Thanks for your feedback.
I feel there is still some value in that Dapr provides language agnostic virtual actors, to be able to *sprinkle* actors and state on top of existing nodejs and java applications is a nice touch.

**Comment by olitomlinson** [comment]
Hi @MargaretKrutikova 

> Unfortunately, we are moving away from Dapr since we have had a lot of struggle with bugs that were breaking a lot of actor functionality with almost every Dapr update, lack of functionality that we had to work around that eventually proved to be too complex and very unstable setup for local development.

You mention that you had bugs which broke functionality, and have ultimately ended in a lack of confidence to continue with Dapr. This is absolutely not the experience that anyone adopting Dapr should have, so I feel compelled to ask how we (the Open Source community) could have served you better?

Just so I understand, did you raise any of these particular bugs anywhere? i.e. GitHub / Discord etc ?

Also with regards to the local development set-up being too complex/unstable, did you feed this back anywhere? Dapr has been investing heavily in the local dev experience over the last couple of iterations, and I'm wondering if your feedback has been captured and is visible to the right people who are working on that improved experience.

Many thanks!

**Comment by cicoyle** [comment]
Closing as done, per the PR ^
