### ISSUE TITLE
Block calls from sidecar to app when app is not healthy

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#4883]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## Describe the feature

Dapr sidecar should proactively ping a health endpoint on the app and block forever any calls into the app channel until app is healthy again. This should be configurable via K8s anotations and sidecar command line args:

`dapr.io/app-readiness-path` - path for health check via HTTP endpoint or method name for gRPC. Example: `/health` or `health`. No default - feature is off if this is not provided.
`dapr.io/app-readiness-probe-period-seconds` - how often (in seconds) to perform the app liveness probe. Defaults to 5.
`dapr.io/app-readiness-probe-period-threshold` - number of consecutive failures for app to be considered not ready. Defaults to 3.

New E2E test scenario:
Validate that bindings, pubsub subscription and service invocation block and do not call into the app's endpoint while it is down.

## Release Note

RELEASE NOTE:  **ADD** support for app's channel readiness probe from sidecar.

**Comment by kevinten10** [comment]
Hey, I want to ask: In k8s, why not use the k8s native health check probe?

**Comment by artursouza** [comment]
> Hey, I want to ask: In k8s, why not use the k8s native health check probe?

This is a good point. I think we can have the sidecar injector to use the K8s settings first and only override with the ones above if those are set.

**Comment by ItalyPaleAle** [comment]
As per discussion, I have two proposed designs to address this problem. They are not necessarily either-or options, as we may support both (users would be able to choose the behavior).

# Path 1

This requires users to create an health endpoint in the app. Could be either:

- a `/healthz` API (name is configurable) that must respond with 200 OK if the app is all healthy
- a gRPC call that returns an OK response if the app is healthy. This could also be implemented as a stream, so we can immediately identify failures if the stream is closed prematurely

The sidecar probes the app regularly, at a configurable interval (e.g. every 5 seconds). If a failure is detected (there can be a configurable threshold, such as "3 consecutive failures"), then the app is considered unhealthy.

However, we will not rely on the health endpoint alone to determine if the app is unhealthy. The problem is that it can take too long for Dapr to make the determination that the app is unhealthy: for example, if we probe every 5 seconds and require 3 failures, we have 10-15 seconds when the app is unhealthy and yet we are still delivering messages to it. Our pubsub components can deliver thousands of messages per second, so this is not acceptable.

In addition to relying on the health endpoints, then, we can also determine if the app is unhealthy by looking at **network** failures when delivering messages (in this case, we're only considering network-level failures). For example, if a network error happens while the runtime is trying to deliver a pubsub message to the app, that is added to the number of detected failures. Likewise, a network error while receiving a message from service invocation would be counted in the same bucket as well (all go in the same bucket, including health probes). When the consecutive failures (no matter the source) are >= threshold, then we consider the app to be un-healthy.

When the app is determined to be un-healthy:

1. All incoming messages are stopped. This is done for pubsub and input binding (the latter pending #4846) via context cancellation, which also terminates the subscription to the queue/broker. For service invocation, the runtime stops accepting calls meant to this app and returns an error.
2. Health probes continue (e.g. every 5 seconds). The app remains in an un-healthy state until the health probes begin to pass again.
   - Note: apps can be determined to be in an un-healthy state by health probes and other sources (service invocation, input bindings, pubsub), but ONLY health probes can move back apps to a healthy state (because the other activities are stopped while the app is considered un-healthy).
3. When the app gets back into a healthy state, subscriptions are automatically re-started.

# Path 2

This path has the advantage of not requiring a health endpoint, so no changes needed in the app. However it only works in Kubernetes.

Apps are determined to be unhealthy if they fail to respond to invocations (pubsub messages, input binding messages, or incoming service invocations) for N consecutive times **with a network error** (only network errors are considered here).

When apps are determined to be unhealthy, the runtime (by virtue of invoking the action on the operator service) kills the pod. Kubernetes will then be responsible for recreating the pod.

We call this the "nuclear option".

**Comment by artursouza** [comment]
I am in favor of path1 since it is not coupled with K8s.

**Comment by yaron2** [comment]
Path 1 is the only viable option. Path 2 is 100% non-idiomatic for how users expect k8s health probes to operate in regards to pod lifecycle, and, we should do our best to avoid k8s only features.

**Comment by ItalyPaleAle** [comment]
My only concern with path 1 is that it does require users to opt into this feature.

Can you think of any other signal we could use to probe when the app is "back to life" that wouldn't require users explicitly creating a new endpoint?
