### ISSUE TITLE
Pubsub for actors proposed implementation

### ISSUE THREAD

**Issue by DiegoAJR** [dapr/dapr#5079]
## In what area(s)?

/area runtime

## Describe the proposal

To dive into more detailed information about the proposed implementation, refer to the following PRs where you will find the changes made and files added to Dapr:

Feature request: #501 
1. Dapr/dapr: #4844 
2. Dapr/components-contrib: dapr/components-contrib/pull/1875
3. Dapr/python-sdk: dapr/python-sdk/pull/438 and dapr/python-sdk/pull/425
4. Dapr/docs: dapr/docs/pull/2735
5. Dapr/blog: dapr/blog/pull/85

### Proposed Solution
The solution that I developed describes the following: 
- A new API endpoint to publish messages specifying the actor to invoke. 
- Handling of CloudEvents to call a specific actor’s method.   
- A new field in the Actor Runtime Configuration that enables declaration of subscriptions for specific actor types. 

![actor-pubsub](https://user-images.githubusercontent.com/74429439/186493222-c0e5bf65-fd83-4837-92db-9cf03a1ba9c6.png)

### Why make pub/sub for actors
Pub/sub for actors was developed to let users interact and incorporate actors to their applications based on pub/sub architectures. At this point, actors can only be activated and invoked with the API endpoint. Additionally, pub/sub only supports service subscriptions. The new functionality is an increment to helping the user build applications with actors and call them based on published events.  
The proposed functionality was requested from Dapr users to extend actors usability with other building blocks.

### Publish for Actors
To start using pub/sub for actors, the user will need to have a publisher service or actor, and at least one actor type as a subscriber. 

Use the HTTP/gRPC endpoint to create a Publish Actor Event:
```bash
POST http://localhost:3500/v1.0-alpha1/actors/<actorType>/<actorId>/publish/<PubsubName>/<Topic>
```
> Alternatively use the Python SDK event implementation
```python
import json
import time

from dapr.clients import DaprClient
with DaprClient() as d:
resp = d.publish_actor_event(
            pubsub_name='mypubsub',
            topic_name='mytopic',
            actor_id= '1000',
            actor_type='DemoActor',
            data=json.dumps(req_data),
            data_content_type='application/json',
        )
```
This request will be published in the specified topic as a CloudEvent that stores the declared actor type and actor id. 

### Subscribe for actors
To subscribe an actor to a topic, it is required to include a pub/sub configuration in the Actor Runtime Configuration. Include the "pub/sub name", "topic", "actor type", "method", and optionally include an "actorIdDataAttribute" to use an attribute in the message as an actor id.
>Python SDK
```python
from dapr.actor.runtime.config import PubsubConfig
# Actor Runtime Configuration with pub/sub subscriptions
config = ActorRuntimeConfig(pubsub=[PubsubConfig(
    pubsubName="mypubsub",
    topic="mytopic",
    actorType="DemoActor", # Actor must exist in the Actor Runtime
    method="mymethod1", # Actor must have this method
    actorIdDataAttribute= "id"
    ), PubsubConfig(
        pubsubName="myPubsub",
        topic="mytopic",
        actorType="AnotherActor",
        method="mymethod2"
    )])
```
>GO e2e test
```go
var daprConfigResponse = daprConfig{
    Entities:                 []string{"DemoActor"}
    ActorIdleTimeout:         "1h",
    ActorScanInterval:        "30s",
    DrainOngoingCallTimeout:  "30s",
    DrainRebalancedActors:    True,
    Pubsub: []config.PubSubConfig{ // Subscription
        {
            PubSubName:  "myPubsub",
            Topic:       "myTopic",
            ActorType:   "DemoActor",
            Method:      "mymethod1",
            actorIdDataAttribute: "id",
        },
    },
    EntitiesConfig: []config.EntityConfig{
        {
            Entities: []string{"DemoActor"},
            Reentrancy: config.ReentrancyConfig{
                Enabled:       true,
                MaxStackDepth: 5,
            },
        },
    },
}
```

The Dapr Runtime will automatically check if there exists a pub/sub subscription for actors in the Actor Runtime Configuration. When an event is published, Dapr will match the actor type and id, then it will call the declared method. This logic follows the pub/sub consumer group principles. Multiple sidecars with the same consumer and actor types will compete for the event. If the sidecars have different consumer groups, they will all receive the message.    

### Actor Pubsub Features
Some of the pub/sub for actor features are:  
- Activate actors based on events sent through a pub/sub component without interacting with the actors API.  
- The user is not required to include the actor type and actor id in the published event (This scenario will require an actorIdDataAttribute in the subscription configuration).
- Integration with existing pub/sub architecture. 
- Pub/sub component will handle failure when sending events.  

### Python SDK
Pub/sub for actors is currently in development. If you want to start using the functionality, you can use the Dapr endpoints or the Python SDK integration in the python SDK PR.

### Limitations
Due to functionality being in alpha version, there are some limitations:
- Implementation doesn’t guarantee in-order processing. Other Sidecars won’t wait until another sidecar has finished processing an event to continue receiving more events.
- Publish actor fields are optional, but the Actor Runtime Configuration must have the matching attributes to find the correct actor. 
- Dead Letter topics are not supported yet.
- Events published before the Placement table configuration, throw an error, and retry sending. 

## Looking ahead
The next steps for “pub/sub for actors” will be targeted at optimizing the way subscriptions are handled. Make the process more efficient when searching for a subscription in a big number of actor subscriptions. Also, enable pub/sub for actors with raw data handling (when dapr is not the actual publisher).

Additionally, incorporate the new endpoint and configurations to all the SDKs supported by Dapr. SDK implementations will make the functionality agnostic of the programming language used to build the application and reach more users.

This implementation follows the discussion and design ideas from issue #501
I am happy to take any questions and feedback from you

**Comment by olitomlinson** [comment]
Will it be possible to use the normal pub/sub HTTP syntax to publish a message.

i.e. instead of

` POST http://localhost:3500/v1.0-alpha1/actors/<actorType>/<actorId>/publish/<PubsubName>/<Topic>`

will you be able to do

` POST http://localhost:3500/v1.0/publish/<PubsubName>/<Topic>`

and will it be possible to bind the topic to the Actor via a traditional `subscription` component yaml?

i.e. something like this

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: <PubsubName>
spec:
  topic: <Topic>
  pubsubname: <PubsubName>
  actorType: <ActorType> # Actor must exist in the Actor Runtime
  Route: /mymethod1 # Actor must have this method
```

**Comment by DiegoAJR** [comment]
> 
1. You can still use the normal publish API and route events to services. The new API will only be used when you want to include actors as subscribers. 
```
POST http://localhost:3500/v1.0/publish/<PubsubName>/<Topic>
```
When using the normal publish API, events will arrive only to the subscribed services.

```
POST http://localhost:3500/v1.0-alpha1/actors/<actorType>/<actorId>/publish/<PubsubName>/<Topic>
```
This request will route the event to any service and declared actor subscribed to the topic.

2. Declarative subscriptions for actors are not supported yet. Using a yaml won't subscribe actors.

**Comment by olitomlinson** [comment]
@DiegoAJR Whats the reasoning for introducing a new Actor Publish API and not just extending the existing PubSub API?

**Comment by artursouza** [comment]
> @DiegoAJR Whats the reasoning for introducing a new Actor Publish API and not just extending the existing PubSub API?

I personally think there is value in having an actor specific API  so the ActorProxy implementation can have a native interface. It is a better user experience than asking the user to hand-craft the CloudEvent object to include ActorType and ActorId.

**Comment by olitomlinson** [comment]
> > @DiegoAJR Whats the reasoning for introducing a new Actor Publish API and not just extending the existing PubSub API?
> 
> I personally think there is value in having an actor specific API so the ActorProxy implementation can have a native interface. It is a better user experience than asking the user to hand-craft the CloudEvent object to include ActorType and ActorId.

I guess when I think about PubSub as general concept, I'm thinking of the publisher being completely unaware of the potential subscribers. 

Yet here we have an Actor PubSub API that specifically links the Publisher to the Consumer - can this really be classed as conventional PubSub? To me it's not conventional and thats where my confusion comes from.

To me, it makes more sense to use the standard PubSub API and augment with CloudEvent properties which can be used to Route to specific Actor instances / Actor Types.

Happy to be wrong on this, just sharing my opinion as a user :)

**Comment by LionTao** [comment]
> > > @DiegoAJR Whats the reasoning for introducing a new Actor Publish API and not just extending the existing PubSub API?
> > 
> > 
> > I personally think there is value in having an actor specific API so the ActorProxy implementation can have a native interface. It is a better user experience than asking the user to hand-craft the CloudEvent object to include ActorType and ActorId.
> 
> I guess when I think about PubSub as general concept, I'm thinking of the publisher being completely unaware of the potential subscribers.
> 
> Yet here we have an Actor PubSub API that specifically links the Publisher to the Consumer - can this really be classed as conventional PubSub? To me it's not conventional and thats where my confusion comes from.
> 
> To me, it makes more sense to use the standard PubSub API and augment with CloudEvent properties which can be used to Route to specific Actor instances / Actor Types.
> 
> Happy to be wrong on this, just sharing my opinion as a user :)

I agree.

**Comment by berndverst** [comment]
Somehow you have to specify which Actor Type (and optionally Actor Instance) should receive a certain message. So there needs to be a field on the cloud event to infer the Actor Type. The `actors/<actorType>/<actorId>/publish/<PubsubName>/<Topic>` endpoint does just that for mere convenience. It sets an `ActorType` field on the CloudEvent envelope.

With this design here you still can always send your own cloud event (with content-type `application/cloudevents+json` and manually set an attribute `ActorType`. Such a cloud event could still be sent to the regular pubsub publish endpoints.

Keep in mind that by default Dapr manages a Cloud Event envelope for you -- this happens when you submit in any other content type. And in that case the dedicated Actor Pubsub methods are required to set the field on that cloud event envelope.

**Comment by olitomlinson** [comment]
@berndverst Understood.

Are you able to provide the proposed `CloudEvent` envelope that lights up delivery to an actor Type and delivery to a specific Actor Instance?

**Comment by theperm** [comment]
So how do you broadcast a message to all actors of all actortypes?

Typical scenario is you have an actor that represents some business domain of a user, but user belongs to a company as well. While its great to be able send an individual message to a a specific actor, how would you publish a message to be received by all actors that are a set of actors of a particular company. 
This is whats also required. Actors need to

Subscribe to topic events routed to specific <actortype>/actorid   (youve got this covered)
Subscribe to topic events routed to specific <actortype> and deliver to all actors, not just one.
Subscribe to topic events routed to any <actortype> and deliver to all actors, not just one.

Lets assume topic would be used for CompanyId but i havent seen any mention of publishing without an actorid to deliver to all actors?

So i think your publish API just needs to be extended

```
resp = d.publish_actor_event(
            pubsub_name='mypubsub',
            topic_name='mytopic',
            actor_id= '*',   // either wildcard or emitting this data indicates send to all actors of actortype
            actor_type='*', // either wildcard or emitting this data indicates send to all actors
            data=json.dumps(req_data),
            data_content_type='application/json',
        )
```
Simples?

And for the case where we don't care about actorid or actortype I dont see why regular pubsub can't be used on the subscription side, else a message would have to be published twice, once to services and once to actors - thats kind of redundant.

With pubsub, when u publish to topic /mycompany you expect everyone that is subscribed to receive whether a service or an actor. The difference with actors is there is only 1 instance of any actorid and all actors must receive same message where as services form a competing consumer group.

Right now we create an .net actor host service but also make it a web service to handle service pubsub, When we receive a company topic message, we have to send it to all actors with the same company, not very elegant, but its the only way to do pub sub for actors at present. A bit dubious how ordering would be enforced as well given the service is load balanced, so we've been waiting for this implementation to solve that issue.

One other concern i have is does a publish to an actor activate an actor because we have scenarios where we only want active actors to receive messages, perhaps an actor is only active when a user is present, we don't want to activate dormant users.
Perhaps initially routing to actortype/actorid activation is desirable else why route in the first place but i think this should be controlled at the subscription, unless we can remove subscriptions on deactivation. Definitely for the wildcard options this is more important.

**Comment by theperm** [comment]
Is this issue inactive? Thoughts on my feedback above @DiegoAJR

**Comment by DiegoAJR** [comment]
> Is this issue inactive? Thoughts on my feedback above @DiegoAJR ? I'm concerned this issue will fall short of the mark as currently proposed.

The issue is still active and as far as I know, a team is working to deal with the limitations and feedback received. 

I understand the concern about broadcasting to all actor types, this is only possible if the actor types are in different consumer groups or instances of the application. If you have all actors in the same consumer group and the publisher doesn't send the actor type, only one actor type will receive it. 
The problem with sending to all actors instances is that they are virtual and infinite. That's why the actor id should be somewhere either in the event or the data. 
About waking inactive users, the subscription could control if Actor instances should be activated. 

I am not currently working on Dapr, that's why I don't have a complete answer on when a new version of Pubsub for actors will come. Sorry.
