### ISSUE TITLE
Unhandled exception. Dapr.DaprApiException: error invoke actor method: failed to invoke target 10.39.1.36:50002 after 3 retries

### ISSUE THREAD

**Issue by rojamajor** [dapr/dapr#5090]
I installed dapr on kubernetes, created 2 namespaces, each namespace installed redis and the storage component of type state.redis, then I deployed the same application in these 2 namespaces, the problem is to create The code of the actor can only run successfully in one namespace, that is, the one deployed first can run successfully, and the prompt for running the code in another namespace is: "Unhandled exception. Dapr. DaprApiException: error invoke actor method: failed to invoke target 10.39.1.36:50002 after 3 retries"，what is the reason? Thank you!

**Comment by bossan** [comment]
I have the exact same problem. To make this issue a bit more descriptive, I'll give a bit more details about our setup and what we've tried so far.


# Our setup
Let's say we have `namespace-a` and `namespace-b` for the application and `dapr-system` as the namespace for the generic Dapr stuff. The app runs as two separate instances in `namespace-a` and `namespace-b` as we want them to be completely isolated from each other. Both have a different app-id/label for Dapr and have their own pub/sub and state components  within the namespace (Redis for state and RabbitMQ for pub/sub). The Dapr Dashboard correctly shows both apps with their own components.

# The issue
I get the following message in the application and daprd sidecar logs: `ERR_ACTOR_INVOKE_METHOD error invoke
actor method: failed to invoke target x.x.x.x:50002 after 3 retries`. This happens a few times per second, continuously.

Weirdly enough, the Dapr Dashboard thinks both apps are healthy even though one of the deployments clearly does not function properly.

## The root cause
In my case, I found by running `kubectl get pods -o wide` that `x.x.x.x` is the IP address of the pod to which the application is deployed in the **other namespace**. Which means that the daprd sidecar in `namespace-a` tries to connect to the application in `namespace-b` or vice versa. As soon as I delete that namespace the error is gone, however immediately after a re-deployment the error occurs again with the IP address of the new pod (still on the wrong namespace).

The problem seems to occur in only one of the two namespaces at a time, and a clean `helm install` in both namespaces does not solve this. At random, one of the two installs will throw this error and the other seems to run fine.

It looks like there is a problem within our configuration. However, I've checked it multiple times and cannot find anything that seems to be improperly configured.

# Possible solution (that didn't work)
In [Common Issues](https://docs.dapr.io/operations/troubleshooting/common_issues/#im-getting-timeoutconnection-errors-when-running-actors-locally) I found that a possible solution would be to set the `DAPR_HOST_IP` environment. This environment variable has been set to `127.0.0.1` in both deployments to make sure it only connects to the daprd sidecar in the same pod. Unfortunately, this did not help.

**Comment by bossan** [comment]
I've been looking through the closed issues and I came to the conclusion that the above error might have to do with Dapr not supporting [namespace isolation for actors](https://github.com/dapr/dapr/issues/4711). Can anyone confirm this?

**Comment by Flern** [comment]
I can 100% confirm that you are correct.  The placement server doesn't respect namespace placement of actors.  This makes the actor-based solutions in any cluster with namespace-based network segregation (which is every cluster I've ever worked in) a lot more difficult and non-intuitive to work with.  We add namespace-based suffixes programmatically to our actors to resolve the namespace scoping manually.  It's very ugly and prone to error.  Example in .NET 6 SDK follows, assuming an environment variable for `ActorNameEnvironmentSuffix` is injected into the containers.

Registering actor types in the actor hosting service (in .NET 6 minimal `Program.cs`):
```
var actorNameEnvironmentSuffix = builder.Configuration.GetValue( "ActorNameEnvironmentSuffix", "" );
options.Actors.RegisterActor<ActorType>(nameof(ActorType) + actorNameEnvironmentSuffix);
```

Invoking the actor proxy:
```
public class ActorProxyExample
{
    private readonly IActorProxyFactory _actorProxyFactory;

    private readonly IConfiguration _configuration;

    public ActorProxyExample(IActorProxyFactory actorProxyFactory, IConfiguration configuration)
    {
        _actorProxyFactory = actorProxyFactory;
        _configuration = configuration;
    }

    public IActorType GetProxy()
    {
        var actorId = ActorId.CreateRandom();
        var actorNameEnvironmentSuffix = _configuration.GetValue("ActorNameEnvironmentSuffix", "");
        var actorName = nameof(ActorType) + actorNameEnvironmentSuffix;
        return _actorProxyFactory.CreateActorProxy<IActorType>(actorId, actorName);
    }
}
```
Again, it's ugly, and it's a workaround for something most people think dapr should support out of the box.  Cross-namespace actor placement seems like it should be exceptional instead of the default behavior.

**Comment by harikumars** [comment]
how to solve this java sdk ? we are getting same issue when running in two namespace. the latest deployed namespace is working and other one is failing with the Unhandled exception. Dapr.DaprApiException: error invoke actor method: failed to invoke target after 3 retries. We tried change the app id but didn't work.

**Comment by jeremycartergf** [comment]
Hi. There are a few options, but firstly is there just 1 placement service?
Are your Dapr services inside the Dapr namespace? If so consider making two
placement services (one for both environments). This isolated the placement
logic and is the easiest way to achieve the result you want. Could you
share some more details?
