### ISSUE TITLE
Proposal: Middleware Pluggable Components design

### ISSUE THREAD

**Issue by mcandeia** [dapr/dapr#5135]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release
## Describe the proposal

> If you don't have context about pluggable components, start from here [Pluggable Components Proposal](https://github.com/dapr/dapr/issues/4925)

As preparation for 1.9 arrival, we should agree on proto definitions for pluggable components. A separate discussion might be necessary for some components that has performance and usability as a priority, middleware is one of those because it would be potentially invoked for every http request. Currently, we provide a simple way of intercepting the request/response context by just implementing a [fasthttp middleware function](https://github.com/dapr/components-contrib/blob/master/middleware/middleware.go#L22). There are some limitations for doing the same for pluggable components, let's address some of them.

### Middleware context problem

You can think a middleware as a man-in-the-middle proxy that intercepts the requests and can provide custom response, headers, changing status code or whatever a proxy can do. To provide the same functionality for pluggable components we have few options, one of those are implementing middleware over http rather than gRPC and make our runtime as a client and the pluggable component as a proxy/server.

This would bring some complexities, for instance, the middleware should keep state to support post-response received executions (i.e. app responded and the middleware has logic to apply on the response) or more complex logic when deciding to handle request body or not (streaming large bodies when not necessary would add performance issues).

```golang
func (h, c) {
    newReq := onRequest(c.Request)
    setReq(&c)
    h(&c)
    newResp := onResponse(c.Response)
    setResp(&c)
}
```

As you can see, delegating the execution to another application would result in security issues (sharing context) and performance issues.

### Middleware execution proposal

That's why my proposal is to leverage gRPC streams to create a command-based stream issued by the component and handled by dapr runtime. This would provide per-request context, removing the necessity of stateful middlewares, and allow extensibility for new operations. 

<img width="923" alt="image" src="https://user-images.githubusercontent.com/5839364/188659925-8db56647-933c-463c-9996-2dd57c5998a3.png">

> For go SDK: Unfortunately, the fasthttp request context provides a lot of operations that might not be covered by this approach, which would deviate the idea of having the same interface from components-contrib as a base for the pluggable components - at least for middlewares.

The proto definition will look like:

```proto
syntax = "proto3";

package dapr.proto.components.v1;

import "google/protobuf/empty.proto";
import "dapr/proto/components/v1/common.proto";

option go_package = "github.com/dapr/dapr/pkg/proto/components/v1;components";

// HttpMiddleware service provides a gRPC interface http middlewares.
service HttpMiddleware {
    rpc Init(MetadataRequest) returns (google.protobuf.Empty) {}
    rpc Handle(stream CommandResponse) returns (stream Command) {}
    // Ping the state store. Used for liveness porpuses.
    rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message GetRequestHeadersCommandResponse {
    string method = 1;
    string uri = 2;
    map<string, string> headers = 3;
}

message GetResponseHeadersCommandResponse {
    map<string, string> headers = 1;
    int32 status_code = 2;
}

message GetRequestBodyCommandResponse {
    bytes data = 1;
}
message GetResponseBodyCommandResponse {
    bytes data = 1;
}

// Operations responses
message CommandResponse {
    oneof response {
        GetRequestHeadersCommandResponse get_req_headers = 1;
        GetRequestBodyCommandResponse get_req_body = 2;
        GetResponseHeadersCommandResponse get_resp_headers = 3;
        GetResponseBodyCommandResponse get_resp_body = 4;
    }
}

message GetRequestHeadersCommand {}
message GetRequestBodyCommand {}
message GetResponseHeadersCommand {}
message GetResponseBodyCommand {}

message SetRequestHeadersCommand {
    string method = 1;
    string uri = 2;
    map<string, string> headers = 3;
}

message SetRequestBodyCommand {
    bytes data = 1;
}

message SetResponseStatusCodeCommand {
    int32 status_code = 1;
}

message SetResponseBodyCommand {
    bytes data = 1;
}

message SetResponseHeadersCommand {
    map<string, string> headers = 1;
}

message ExecNextCommand {}

// All allowed operations
message Command {
    oneof command {
        GetRequestHeadersCommand get_req_headers = 1;
        GetRequestBodyCommand get_req_body = 2;
        GetResponseHeadersCommand get_resp_headers = 3;
        SetRequestHeadersCommand set_req_headers = 4;
        SetRequestBodyCommand set_req_body = 5;
        SetResponseBodyCommand set_resp_body = 6;
        SetResponseStatusCodeCommand set_resp_status = 7;
        GetResponseBodyCommand get_resp_body = 8;
        SetResponseHeadersCommand set_resp_headers = 9;
        ExecNextCommand exec_next = 10;
    }
}
```

Notice that the complexity related to invoking commands and receiving responses will be transparent for the sdk-user. The idea is provide a simple interface for the pluggable component implementer that hides the complexity of issuing commands and getting responses.

> [here](https://github.com/mcandeia/dapr-components-go-sdk/compare/main...feat/middleware-sdk#diff-fcdcfaa93336c48a8719f6b321915215ca5a0bc41bcf5dd712a626bbf8d8f6d7R33) you can see a POC of it.

The pluggable component implementer will receive the middleware controller as a function parameter (pretty much the same as fasthttp) and it will run as a common middleware execution. All the complexities are totally hidden by the sdk.

The `MiddlewareController` will encapsulate the logic behind issuing commands and receiving its responses for the user, any error will be handled by the controller under the hood. The user will feel like coding in a local middleware context.

```golang
type MiddlewareController interface {
	GetRequestBody() []byte
	SetRequestBody([]byte)
	GetResponseBody() []byte
	SetResponseBody([]byte)
	GetRequestHeaders() HTTPHeaders
	SetRequestHeaders(HTTPHeaders)
	GetResponseHeaders() map[string]string
	SetResponseHeaders(map[string]string)
	GetStatusCode() int
	SetStatusCode(int)
	Next()

	Context() context.Context
}
```

the user code will look like
```golang
type myMiddleware struct{}

func (m *myMiddleware) GetHandler(metadata contribMiddleware.Metadata) (func(httpMiddleware.MiddlewareController) error, error) {
	return func(mc httpMiddleware.MiddlewareController) error {
		mc.Next()
		reqBody := string(mc.GetResponseBody())
		mc.SetResponseHeaders(map[string]string{
			"x-arbitrary-header": "value",
		})
		mc.SetResponseBody([]byte(strings.ReplaceAll(reqBody, "a", "x")))
		return nil
	}, nil
}
```

This way, handling body and headers would be avoided for middlewares that don't need to handle them, for instance, authorization middlewares.

And dapr runtime will continue to have control over the request flow/pipeline middlewares without sharing context with the pluggable component.

In addition to that the per-request stream allows pluggable component to be implemented as a simple function without needing to keep state.

A clear disadvantage of this is the difficulty of reusing middleware already created by the languages/framework's community. Those need to be adapted (or wrapped) to properly work as a pluggable component.

**Comment by yaron2** [comment]
We have initial support today for WASM middleware. Wouldn't it be best to see how we can enable that for the s2s middleware too?

**Comment by yaron2** [comment]
cc @daixiang0

**Comment by mcandeia** [comment]
>We have initial support today for WASM middleware. Wouldn't it be best to see how we can enable that for the s2s middleware too?

If you mean: have the same interface, I totally agree!

Actually now I'm wondering if the WASM middleware won't compete with pluggable component middleware. Maybe having just one is enough? Do we have a use-case where one is applicable and the other is not?

**Comment by yaron2** [comment]
My opinion is that one is enough and two will be confusing. WASM is more performant and secure (theoretically) and our strategy for pluggable components in general is WASM when the tech is mature enough.

**Comment by mcandeia** [comment]
Yes, it makes sense to me. However I'm afraid that pluggable components might become an easy-to-go way as a short-term solution, but if we don't have any strong reason to have a full-compatible middleware working in a short-term I'm also ok with it


cc: @tmacam @johnewart @artursouza

**Comment by mcandeia** [comment]
To be honest I think we can hide the implementation details from the final-user (component implementer) and switch between WASM-gRPC when it gains tech maturity.

That's why I support having pluggable components over gRPC even for middleware. But I agree with you that the interfaces to interact with the request/response should be the same, not only for middleware but for the rest of the components that would be implemented over WASM in the future.

**Comment by codefromthecrypt** [comment]
drive-by due to wasm.

## near-maybe performance

There's a lot of talk about near metal performance in wasm and I would say that's plainly marketing unless proven otherwise. It can be faster than I/O :) The HTTP middleware needs to be carefully designed including avoiding rebuffering entire request/response bodies in memory (which has a hard size limit due to 32bit addressing). In some cases, depending on the ABI (callback style used) and compiler, wasm can be so slow that it feels like it is doing I/O. In other words, to decide if something is performant, we'll need to have benchmarks with the actual runtime (ex wazero) and guest code (ex tinygo) in use.

Even before benchmarking, functional tests are needed. @anuraaga has been doing some interesting tests also to ensure the host ABI in a similar project are functional.  https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/proxywasm/proxytest

## plugin and gRPC

@knqyf263 began a plugin to allow swapping between gRPC and wasm and it is pretty cool, as it allows people to have familiar programming style despite protobuf not being the fastest way to move things in and out of memory https://github.com/knqyf263/go-plugin

hope this helps, and thanks for thinking hard about this!

**Comment by codefromthecrypt** [comment]
You should eventually expect a "shout-out to Karmem" comment on anything marshaling performance related in wasm, so I'll beat the fans to it by plugging the link now https://github.com/inkeliz/karmem

**Comment by tmacam** [comment]
### Regarding middleware as a pluggable component

I talked before with @mcandeia and the biggest challenge I see defining a middleware pluggable component is how different it is from the request-response proxy model of other components. For a state store, for instance, the component is _just translating a `GET`_ from Dapr to the underlying datastore it is acting as an adaptor layer for ;)  For middleware, there is _potentially_ a lot of back and forth between Daprd and the component (give me the headers, now add this one, set the status code to this and modify body to that... Oh, we are in the response path? Add this header and remove this one.... ).

I think that excluding middleware from the initial (dapr 1.9)  pluggable components model will help getting them out of the door while we settle on the appropriate model for middleware. 

### Regarding WASM as a solution for middleware components 

I think WASM has the potential to be great, specially for middleware components. What I don't know is whether the technology mature for using it in the short/middle term? How feasible would it be to just re-compile the existing middleware solutions written in Java and .Net to WASM? Is sandboxing of the WASM runtime environment and its isolation form the rest of daprd something we have to worry about?

**Comment by daixiang0** [comment]
My concern is about the scale and ecology of gRPC middleware for HTTP, WASM as a middleware become popular in the service mesh world. I see some use cases that use gRPC as an external service but not middleware, one reason I can think of is that gRPC services need always running but WASM just runs when necessary.

Now we only have HTTP middleware, also I wonder about the status of gRPC middleware(https://github.com/dapr/dapr/issues/4153).

**Comment by codefromthecrypt** [comment]
my 2p

> Regarding middleware as a pluggable component

If we split by control-plane data-plane, I think the former type of middleware is less risky from a technical design POV due to being bounded and unable to hurt real requests. That said I agree that classifying the middleware technically is better than assuming functional groups are more or less risky to include in the first cut. Maybe a chart with middleware and each fasthttp function they call as a start?

> Regarding WASM as a solution for middleware components
https://github.com/dapr/components-contrib/pull/1833 is a trivial middleware made mostly to help folks build experience. Folks are using wasm in practice for HTTP middleware (envoy, fastly, etc)

I would suggest that Java and .Net compiling to wasm isn't likely to be efficient in-place. I think dapr would need to pick up to three languages to start with, such as tinygo, rust, clang, to control the support load of people asking about things. Maybe just TinyGo to start with as people here are more likely to support it.

Sandboxing (memory usage) is controllable, or a bug, unless configuration allows breaking the sandbox (ex opening network sockets). There also should be a writable directory for compilation cache to avoid slow inits.

Finally, though you didn't mention yet, how to distribute the wasm and if/how updates decoupled from dapr are handled. This can be later change.

**Comment by anuraaga** [comment]
I've been working on writing middleware for Envoy with TinyGo and wasm and can share some anecdotes - they're just personal experience so hopefully just a source of information.

## Using off the shelf libraries in plugins

I am taking a off-the-shelf Go library for WAF, [Coraza](https://github.com/corazawaf/coraza) to introduce a WAF firewall filter to Envoy. [It](https://github.com/anuraaga/coraza-wasm-filter) works! But there was significant work to get there - the most noticable is replacing the stdlib `encoding/json` with `gjson` in places it could be used because the former doesn't work with TinyGo yet. Unfortunately, there is still a known feature gap with XML processing as we haven't found a simple non-reflection library for XML yet. I'm definitely expecting TinyGo support for reflection to improve over time, but it may take some time.

The biggest gap especially for dapr middleware may be the lack of support for `net/http` - while WASI defines interfaces for socket, they are not used by most wasm compilers yet from what I understand. While this can be worked around by offering HTTP interfaces in the plugin SDK itself, it's limited to zeroish-dep plugins. For example, I can imagine having a lot of trouble writing a Firebase authentication middleware with TinyGo because I would want to use the Firebase SDK for it, but it's use of `net/http` to access Firebase would be a blocker, and it's unlikely the SDK would be refactored to support pluggable HTTP clients, especially for languages like Go with HTTP in the standard library. Eventually we can expect `net/http` to be supported, but libraries like gRPC-go that don't use `net/http` may or may not work.

These are all anecdotes based on TinyGo. Other languages will be different, and `GOOS=js` will also be able to compile more libraries including using json or net/http (though I don't think it'd support grpc-go). `GOOS=js` has its own issues related to performance from what I've heard that I'm not intimately familiar with as I've only used TinyGo so far.

## Wasm performance

We have not done scientific performance analysis of the wasm WAF filter yet but will be doing so in the next couple of weeks so I can probably share something more concrete then if it would help. In the meantime, we do have the infrastructure to run unit tests and microbenchmarks both directly with Go and through wazero with compiled wasm to compare these. The WAF filter starts by parsing a lot of firewall rules, most of them complex regular expressions - back-of-the-hand estimate, the wasm takes around 10x time to parse the rules, with it mostly being in `regexp.Compile`. We will be looking into why this might be much slower on wasm, but it's an example where we had no reason to expect `regexp.Compile` to be much slower, but happened to find it when running code. So indeed, the only way to really know what code performs well within wasm and what doesn't is benchmarking, and unfortunately this may often be not on the middleware SDK side by itself but also on the user implementation side. 

## Wasm brings in-process plugins to Go

With those out of the way, just want to reiterate that the Coraza WAF filter works, and that feels great. It is much easier to distribute a compiled wasm without needing a goreleaser to handle all the archs out there, the mental model of in-process communication vs RPC is simpler, and whatever performance gaps we have now I'm sure will improve over time, while RPC has a theoretical bound due to the nature of network transmission (I think). So while I think it's important to be aware of the kinks that exist, and it does require extra work right now, I am bullish on wasm being a great way to extend Go apps in the long term (have even submitted a conference talk on it :) ). The more folks and projects we have involved in this, the better it will get for sure.

Creating a plugin SDK that allows both models to be supported without significant changes in the implementer experience is probably a good way of managing the gaps for dapr. One thing to keep in mind is that it's not only code but toolchain as well - so I guess I could imagine a "dapr plugin archive" format, which can either have platform-specific RPC plugin executables or a single wasm file in a recognizable file scheme and dapr would orchestrate appropriately based on what's in the archive. If both were supported, then I could definitely imagine myself executing `dapr-plugin-build` in wasm mode first, but if finding myself needing a library with no practical way to load with TinyGo, would switch it to grpc mode, and hopefully the end result is still the same plugin archive to deploy in the same way.

**Comment by tmacam** [comment]
As @mcandeia pointed out, we are discussing two related but distinct topics in this issue and this is diverging from this issue's main target. While interesting and all, it might be more productive if we untangle this discussion and move the WASM as an alternative for middleware pluggable components to a separate issue. Both alternatives can coexist. Anyway. if someone opens one, please let me know, I want to follow it.

Back to the question this issue addresses:  can we define pluggable components for middleware components using gRPC? Yes, it is a proven technology and we know we can make it work and take it to production today. We are proposing the same for other components so why no to middleware too? I think we should probably in the first moment limit the API to the surface of the fasthttp library we effectively use in todays middleware components but I don't see a problem with the API defined by @mcandeia.

**Comment by yaron2** [comment]
gRPC plugins are not the right fit for chatty scenarios like middleware that operate per-request. Since this is still in debate, we should remove gRPC middleware support from 1.9.

cc @artursouza

**Comment by artursouza** [comment]
I agree. Let's discuss middleware for a later release - it might not be ideal for pluggable components.
