### ISSUE TITLE
Is there any feature which supports manual ack in pub/sub based on redis stream

### ISSUE THREAD

**Issue by suxi** [dapr/dapr#5364]
Short description is as the title.
Long description is when I do something async task which takes about 5m. if I try to return status code 200 after the task has been finished. It always makes Dapr to resend the msg. Surely, I can set the pub/sub timeout. But it is also difficult to set a good timeout for all the tasks.

**Comment by ItalyPaleAle** [comment]
Dapr doesn't support manual ACKs. The idea is that the runtime ACK's a message when the app responds with a success message, or NACK's otherwise.

When possible, Dapr tries to continuously renew locks for messages that it acquires. However, I don't believe that's possible for Redis Stream-or at least, I couldn't find a command to do that in the Redis docs.

Your best option would be to set `processingTimeout` in the component to a high value (for example 10m if the average processing time is 5m), so there's enough time for your app to process the message.

Or, consider using a different pubsub broker if that's an option.

**Comment by suxi** [comment]
> Dapr doesn't support manual ACKs. The idea is that the runtime ACK's a message when the app responds with a success message, or NACK's otherwise.
> 
> When possible, Dapr tries to continuously renew locks for messages that it acquires. However, I don't believe that's possible for Redis Stream-or at least, I couldn't find a command to do that in the Redis docs.
> 
> Your best option would be to set `processingTimeout` in the component to a high value (for example 10m if the average processing time is 5m), so there's enough time for your app to process the message.
> 
> Or, consider using a different pubsub broker if that's an option.

thank you for the explain
