### ISSUE TITLE
why did dapr not support mariadb?

### ISSUE THREAD

**Issue by ggjjlldd** [dapr/dapr#5477]
## In what area(s)?

> /area runtime

## Describe the feature

why did dapr not support mariadb? 
## Release Note

RELEASE NOTE:**ADD**

**Comment by mcandeia** [comment]
Hey @ggjjlldd how are you?

As one of the main goal of Dapr is being community-driven and supporting a variety of databases would be certainly a desired future and a metric of success for the entire community.

Offering support to MariaDB as a statestore is a matter of implementing the statestore component, and if you think this is important for you - as part of the community, raising the flag as you are doing now when opened this issue is the right way to get there.

As I don't have previous knowledge about how many people or how many "flags" were raised for MariaDB I would suggest two ways for getting this done:

1) Open the same issue on the https://github.com/dapr/components-contrib repository and ask for the community feedback, hence for help to implement it in the next releases (or at least adding it on roadmap to be prioritized later)
2) Implement your own pluggable component (https://docs.dapr.io/operations/components/pluggable-components/pluggable-components-overview/) - keep in mind this is a preview feature
