### ISSUE TITLE
[Discussion] Why Dapr runtine subscribe to topics 1 by 1?

### ISSUE THREAD

**Issue by DeepanshuA** [dapr/dapr#5571]
In Dapr runtime, we see that for a particular PubSub component, if there are n topics to be subscribed, then these calls are made 1 by 1, rather does it make sense, if the component is made aware of topics to be subscribed along with respective metadata in 1 go.

https://github.com/dapr/dapr/blob/5a17813a159ec68965c58406a0915d74a3ada2c5/pkg/runtime/runtime.go#L904

Right now, due to multiple calls, the resources vested in subscribing topics are cancelled/closed and are re-opened with an additional topic to subscribe, which seems like an overhead.
Rather, runtime should take necessary steps to take care of at its end and inform component about topics to be subscribed at once, along with respective metadata.

Along with overhead, following scenarios can definitely keep occuring in components:

Start subscribers S1, S2 and S3:::::: S1 -> S2 -> S3

Topics are formed

Stop subscribers

Publish Messages on these topics S1, S2 and S3

Start back subscribers. 

- Subscribe for S1 is called.
	- Added to topics list.
	- Create connection and S1 receives pending message.
- Subscribe for S2 is called.
	- Add to topic List. Now, there are S1 and S2 topics to be subscribed. Disconnection for S1 is triggered before any ACK could be sent for pending message.
	- Create back connection and subscribe for S1 and S2. Pending message(s) received for S1 and S2.
- Subscribe for S3 is called.
	- Add to topic list. Now, there are S1, S2 and S3 topics to be subscribed. Disconnection for S1 and S2 is triggered before any ACK could be sent for pending message.
	- Create connection again and subscribe for S1, S2 and S3. Pending message(s) received for S1, S2 and S3.

- In all, 3 times pending message received for S1, 2 times for S2 and 1 time for S3.

Thoughts?

P.S.: I will try to take out some more time tomorrow and show with some visual diagrams, in case description above doesn't create clarity.

**Comment by ItalyPaleAle** [comment]
> > Right now, due to multiple calls, the resources vested in subscribing topics are cancelled/closed and are re-opened with an additional topic to subscribe, which seems like an overhead.
>
> That's an unfortunate implementation detail for the components that do this. There are components that do the "right thing".

I rewrote how this works in each component and can say that it depends on the component and what the SDKs support.

For some SDKs, first the connection is established, and then subscriptions are added (or removed) on top of that connection. Sadly, some services require the full list of subscriptions to be passed right when the connection is established and that’s why we have to re-connect. I don’t remember off the top of my head which components were doing that, but if that’s the case, it’s because we didn’t have an option.

The current implementation is the best we can have given how the interaction between the runtime and component. Perhaps something that is more “batched” would indeed be helpful in this case, as long as we can continue to return errors individually.
