### ISSUE TITLE
What happens if dapr sidecar fail?

### ISSUE THREAD

**Issue by MotaOcimar** [dapr/dapr#5599]
## In what area(s)?

/area runtime

## Ask your question here
I would like to know what happens if Dapr fails. For example, if my service's sidecar or even the Control Plane fails, what is the expected behavior of my application?

Oh, and would there be any way for me to simulate these error cases?

### Context:
In my application I have a service that uses Dapr, but in a non-critical way. Therefore, I would like to ensure that it continues to run normally even if its sidecar or Dapr fails.

**Comment by ItalyPaleAle** [comment]
It's a pretty complex question to answer because it depends on:

- What kind of failure you're encountering
- What are the circumstances that cause the failure
- Your environment

I'll assume that you're using Dapr on Kubernetes as that's probably the most-common scenario in production. If you're not using K8s, similar principles may apply.

1. On K8s, if any container crashes, K8s restarts it automatically. This means that if the sidecar, or a control plane service, crashes, the platform will restart it.
2. Dapr sidecars have been designed to continue operating even if the control plane is unavailable. Of course, certain capabilities could be degraded; the exact impact depends on what control plane service is unavailable and the stage of your application (e.g. the Dapr operator, sentry, and injector are almost only relevant when a new Dapr sidecar comes online)
3. If the sidecar crashes, whatever operation was in process will be aborted. The sidecar will come back online and your application can resume talking to it.

**Comment by MotaOcimar** [comment]
@ItalyPaleAle thanks for the reply!

Is there any way I can simulate some failures?

For example, a way to exclude the control plane pod. Or kill dapr sidecar processes.

**Comment by ItalyPaleAle** [comment]
Yes you can kill the control plane pods, which will cause K8s to restart them. Or scale the deployments to 0 which will delete them until you scale back.

For the Dapr sidecar process, you can invoke the `shutdown` method (`POST /v1.0/shutdown`, which is not clearly documented as it's primarily used in tests) which will tell the sidecar to perform a clean shutdown. There's currently no way to kill the daprd container only in the pod, as our containers do not have a shell.
