### ISSUE TITLE
Redis output binding operation of get

### ISSUE THREAD

**Issue by liililil** [dapr/dapr#5679]
**Environment:**
Kubernetes: v1.22.15
Dapr: v1.9.5

**Operate:**
Using Redis Output Binding
`http://localhost:3500/v1.0/bindings/my-redis`
```
{
  "operation": "get",
  "metadata": {
    "key": "test"
  }
}
```
Return 500
`{"errorCode":"ERR_INVOKE_OUTPUT_BINDING","message":"error when invoke output binding my-redis: binding my-redis does not support operation get. supported operations:create"}`

But the documentation writes that the 1.9 version supports get and delete (https://docs.dapr.io/reference/components-reference/supported-bindings/redis/#binding-support)

**Comment by ItalyPaleAle** [comment]
Seems to be a documentation error. In the [source code for 1.9](https://github.com/dapr/components-contrib/blob/release-1.9/bindings/redis/redis.go#L69), only the "create" operation is supported.

Other operations such as GET are being added in 1.10: https://github.com/dapr/components-contrib/blob/master/bindings/redis/redis.go

Can I ask however how come you're using the binding instead of the state store?

**Comment by liililil** [comment]
> Seems to be a documentation error. In the [source code for 1.9](https://github.com/dapr/components-contrib/blob/release-1.9/bindings/redis/redis.go#L69), only the "create" operation is supported.
> 
> Other operations such as GET are being added in 1.10: https://github.com/dapr/components-contrib/blob/master/bindings/redis/redis.go
> 
> Can I ask however how come you're using the binding instead of the state store?

Thank you for your suggestion! I missed the state store before, and I will try to use this.
