### ISSUE TITLE
Can't connect DAPR sidecar after service restart

### ISSUE THREAD

**Issue by smartnet-club** [dapr/dapr#5718]
## In what area(s)?

/area runtime

## What version of Dapr?

1.9.5

## Expected Behavior

```
services:
  myservice:
    image: ...
    restart: always

  myservice-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:myservice"
```
If myservice crashes and restarted by docker it should has an ability to restore connection to DAPR

## Actual Behavior

myservice failed to connect to DAPR sidecar

## Steps to Reproduce the Problem

kill myservice by timer

The problem described in [this issue](https://github.com/docker/compose/issues/6626)

Suggested solution: do not use `network_mode: "service:[service-name]"` for sidecar container and pass `app-endpoint` to `daprd`. DAPR must restore app connection in case of application crash and restart.

## Release Note

RELEASE NOTE:

**Comment by thielepaul** [comment]
If I see correctly there is currently no option to pass an `app-endpoint` to dapr, it seems that `127.0.0.1` is hardcoded: https://github.com/dapr/dapr/blob/b74b7d92b0821149bd61ed7f12f8c86f1e5972a9/pkg/runtime/runtime.go#L2879

**Comment by smartnet-club** [comment]
> 127.0.0.1 is hardcoded

Yes. This is the main problem.
And I can't understand the motivation for using the "sidecar" pattern. All parts of the system communicate with each other over the network.
Also, the absence of a broadcast notification about the connection / disconnection of the service.

**Comment by yaron2** [comment]
Your issue is not related to the sidecar pattern. Dapr sidecars discover and communicate with other sidecars over the network on behalf of your application to make the connectivity more robust, secure and reliable. The sidecar pattern helps avoid a single point of failure and noisy neighbor.

**Comment by smartnet-club** [comment]
> Your issue is not related to the sidecar pattern
No. The only issue is the need to place the dapr on the same host as the application.

**Comment by thielepaul** [comment]
@yaron2 thanks for your reply,

As far as I can see the sidecar pattern requires the concept of pods and thus does not work with docker (compose).
The `network_mode: service` approach has the described issue because the two containers do not have a common lifecycle.

My question would be: is there any plan for dapr to support docker (compose/swarm) for production deployments or is kubernetes a requirement?

**Comment by thielepaul** [comment]
Another possible solution might be to run both `daprd` and the service in a single container as described in the docker documentation: https://docs.docker.com/config/containers/multi-service_container/

However, the dapr documentation says that this is suitable "For development purposes ONLY": https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/#run-both-app-and-dapr-in-a-single-docker-container

Maybe someone with more insight can explain, why this is a problem in production?

**Comment by glitch452** [comment]
For another use case for a feature like this, check out the Gluten project (<https://github.com/qdm12/gluetun>). 

It's a VPN container that routes all the network traffic in the namespace through a VPN tunnel. So, any containers connected via the `network_mode:container-name` have their network traffic routed through the tunnel.  This is great for applications which do not support proxy routing at the application level. 

A feature that allows the child network to be re-connected automatically if the parent is restart would be fantastic for those containers that are dependent on `gluetun` for a secure connection to somewhere else.

**Comment by niltor** [comment]
I use dapr as an auxiliary implementation of microservices, but we don't have a k8s environment. I deploy the application through docker-compose. When I update my application container through CICD, the service cannot function properly because dapr cannot be connected.


Can anyone give feedback on whether this issue will be addressed or not treated as an issue?

BTW,I'm using dapr1.10.

**Comment by zlzforever** [comment]
My workaround : change the service/dapr network_mode order

```
services:
  myservice:
    image: ...
    restart: always
    network_mode: "service:myservice-dapr"

  myservice-dapr:
    image: "daprio/daprd:edge"    
```
Because dapr instance is more stable than my service app... 

1. myservice re-create: OK
2. myservice re-start: OK
3. myservice-dapr  re-start: ERROR
4. myservice-dapr re-create: OK, because my CD script is docker compose up -d myservice, if dapr instance re-create cause myservice instance re-create

It's not a 100% fix solution
