### ISSUE TITLE
[Workflow] Improvements to existing workflow management APIs

### ISSUE THREAD

**Issue by cgillum** [dapr/dapr#5911]
## In what area(s)?

> /area runtime

## Describe the feature

The initial release of the Workflow management API in v1.10 included APIs for starting workflows, querying their status, and terminating workflows. However, there are some problems with the implementation that can make them a bit hard to use.

### Start Workflow

The URL template is as follows: `POST workflows/{workflowComponent}/{workflowType}/{instanceId}/start`

#### Proposed improvements
* **Make the instance ID optional**  
Today it's required, but we shouldn't force users to come up with instance IDs. If one isn't provided, we should let the component generate a random ID. This will likely require a new HTTP route.

* **Return `Location` and `Retry-After` response headers from the HTTP handler**  
Today we return a HTTP 202 response but without a `Location` header. We should add this header to the response and have it point to the GetWorkflowStatus API. The goal is to natively support the [asynchronous request-reply pattern](https://learn.microsoft.com/azure/architecture/patterns/async-request-reply) out of the box when invoking workflows. The `Retry-After` header can be mainly to ensure that consumers of this pattern do not try to poll too frequently.

* **Return more information in the response**  
The current response payload is very sparse: `{"instance_id":"..."}` and doesn't follow our existing JSON field casing conventions. We should enrich this with more information and use consistent casing for JSON fields. Here's an example:

```json
{
  "workflow": {
    "instanceID": "{instanceID}"
  },
  "httpManagement": {
    "status": {"method":"GET","url":"http://localhost:3500/v1.0-alpha1/workflows/{componentName}/{instanceID}"},
    "terminate": {"method":"POST","url":"http://localhost:3500/v1.0-alpha1/workflows/{componentName}/{instanceID}"},
    "suspend": {"method":"POST","url":"http://localhost:3500/v1.0-alpha1/workflows/{componentName}/{instanceID}/suspend"},
    "resume": {"method":"POST","url":"http://localhost:3500/v1.0-alpha1/workflows/{componentName}/{instanceID}/resume"}
  }
}
```  

  Note that `{componentName}` and `{instanceID}` would be filled in with the relevant values. Also, the HTTP scheme and hostname will match the schema and hostname of the incoming request (with overrides allowed by using `X-Forwarded-*` request headers). Users (or code) should be able to simply use the URLs as-is to manage the created workflow instance.

* **Don't parse the input in the implementation**
Today we parse the input in the API handler, assuming that the payload is JSON. This API should actually just pass-through the payload to the component without trying to interpret it. Otherwise, we're adding unnecessary performance overhead and restricting all implementations to only support JSON.

### Get Workflow

The URL template is as follows: `GET workflows/{workflowComponent}/{workflowType}/{instanceId}`

#### Proposed improvements

* **Remove the `{workflowType]` segment from the URL**  
This segment is not needed. The only thing that's needed is {workflowComponent} and {instanceID}.

* **Rename "WFInfo" to "workflow"**  
This is to 1) make the payload similar to the proposed "Start Workflow" response payload and 2) follow are more conventional model for JSON payloads.

* **Change timestamp** fields in protobuf contract from string/int to `google.protobuf.Timestamp`**
This is a more proper way to represent timestamp information and will help avoid compatibility issues between SDKs and components.

* **Surface more metadata to the top-level `"workflow"` JSON object**  
Today the response payload returns an instance ID, a created timestamp, and a bag of metadata values. Many of these metadata values should be promoted to be 1st-class fields in the `workflow` object. This will make the JSON easier to parse and deserialize into rich types by the SDKs.  Here's an example:

```json
{
  "workflow": {
    "instanceID": "order123",
    "createdAt": "2023-02-02T07:00:00Z",
    "lastUpdatedAt": "2023-02-02T12:00:00Z",
    "runtimeStatus": "RUNNING"
  }
}
```

As an aside, the internal implementation should remove the `WorkflowReference` struct and just use `instanceID` (string) to identify workflow instances.

## Release Note

RELEASE NOTE: **UPDATE** workflow management APIs

/cc @nyemade-uversky

**Comment by ItalyPaleAle** [comment]
A few thoughts:

## General

- Although this is an alpha API, the changes listed here are very much breaking. Should these be released under "v1.0-alpha2"? or should we just wait for "v1.0"?

## Start workflow

I don't think our APIs need to return links for clients to follow-up, we don't do it anywhere else in Dapr.

1. First, there's the problem that we don't really know what the hostname is. Responding with `"url":"http://localhost:3500/v1.0-alpha1/workflows/{componentName}/{instanceID}"` may not be correct if the user is running Dapr not on `localhost`.
2. On a more general level, because these APIs are not meant to be invoked by a human, but rather by a Dapr SDK, we shouldn't need to be concerned with giving clients URLs that they can use to perform follow-up actions. Developers will just need the workflowId (good call that it should be auto-generated if missing) and then they use the SDK methods to check the status, suspend it, etc

## Asynchronous pattern

Rather than encouraging clients to poll on a regular interval, I think we could (maybe even should) offer "blocking" variants. That is, after you get the workflowId, you can call:

- `GET /workflows/{componentName}/{instanceID}` will respond right away with the status
- `GET /workflows/{componentName}/{instanceID}/notify` will block while the status changes from RUNNING to something else

The polling method works fine for workflows that are expected to take a long time (many minutes or hours), but it makes the app less reactive if the workflow is shorter and can be completed in a matter of seconds or a few minutes.

- A notifier can be safely implemented on the gRPC APIs by making an endpoint that has a server stream (client calls, and then just waits for the server to respond over the stream).
- For HTTP, this is a bit more challenging right now as our web server doesn't ([yet](https://github.com/dapr/dapr/issues/4979)) support HTTP/2, and doing this with HTTP/1 is not ideal (due to lack of support for multiplexing over a single connection). But someone is already working on this.

**Comment by cgillum** [comment]
Thanks for the feedback @ItalyPaleAle. Some of my thoughts on your feedback:

> Although this is an alpha API, the changes listed here are very much breaking. Should these be released under "v1.0-alpha2"? or should we just wait for "v1.0"?

I wouldn't want to wait for `v1.0` but I'd need to defer to standard Dapr project conventions to know how exactly we should version this. For example, do we have an option of a `v1.0-beta1`? I can be flexible here.

> I don't think our APIs need to return links for clients to follow-up, we don't do it anywhere else in Dapr.

It's true that we don't do this anywhere in Dapr but I don't think that implies we *shouldn't*. The primary benefit of this is that it makes the API more self-describing. The secondary benefit is that someone could build automation around this, for example, a dynamic UI to manage created workflows without needing to hardcode routes - which is especially important when workflow instance IDs are auto-generated.

> First, there's the problem that we don't really know what the hostname is

We do know what the hostname is - [it's part of the incoming request](https://stackoverflow.com/a/23152483/2069). And if the Dapr API is behind a reverse proxy, we can use the [Forward](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) HTTP request headers to learn the original hostname/schema/port. We apply these techniques successfully in multiple Azure services today.

> On a more general level, because these APIs are not meant to be invoked by a human, but rather by a Dapr SDK,

One of the selling points of Dapr is that you don't require an SDK to use the HTTP APIs. This design is in that spirit and is particularly helpful for developers using a language that we don't have an SDK for (the Dapr maintainers can only maintain so many SDKs...).

> Rather than encouraging clients to poll on a regular interval, I think we could (maybe even should) offer "blocking" variants.

I agree that blocking variants would be useful and that we should consider adding blocking variants to this proposal. However, blocking can be more expensive than polling in some cases because it requires maintaining an active TCP connection. Polling, on the other hand, is stateless and well-suited to a wider range of clients. I would prefer we do both rather than only have a blocking variant.

> A notifier can be safely implemented on the gRPC APIs by making an endpoint that has a server stream (client calls, and then just waits for the server to respond over the stream).

I'm curious to understand this better. Is a server stream better than a blocking request-reply gRPC call? I suppose one thing it offers is the ability to subscribe to multiple lifecycle events for those who want to build more reactive-style clients?

**Comment by ItalyPaleAle** [comment]
> For example, do we have an option of a v1.0-beta1? I can be flexible here.

We don't have any "beta1", or even "alpha2". Not sure what the best way to approach this would be. CC: @artursouza @yaron2 may have more thoughts

> We do know what the hostname is - [it's part of the incoming request](https://stackoverflow.com/a/23152483/2069). And if the Dapr API is behind a reverse proxy, we can use the [Forward](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) HTTP request headers to learn the original hostname/schema/port. We apply these techniques successfully in multiple Azure services today.

TIL, thanks :)

(But still don't think our APIs have to be self-describing, especially in situations like these - my .02)

> However, blocking can be more expensive than polling in some cases because it requires maintaining an active TCP connection. Polling, on the other hand, is stateless and well-suited to a wider range of clients. I would prefer we do both rather than only have a blocking variant.

Yup, that's why I specifically mentioned requiring HTTP/2, where all calls would be streams on top of the same TCP socket.
gRPC is based on HTTP/2 so that works fine too.

> 'm curious to understand this better. Is a server stream better than a blocking request-reply gRPC call? I suppose one thing it offers is the ability to subscribe to multiple lifecycle events for those who want to build more reactive-style clients?

So the interesting fact is that internally, all gRPC calls are managed as streams. When a RPC is defined as "unary" in a proto file, the gRPC library offers some "convenience methods" so that developers can write code that resembles a unary RPC, but then on the wire everything is handled as a stream.  And without knowing the proto files, in fact, you have no way to know if it's unary or not. (Don't ask me how I know this, those were some painful days in my life :) )
The reason why I suggested going with a gRPC that uses server-stream is because clients may set timeouts on unary RPCs, while if you declare your RPC as a stream there's no expectation. It's more of a "UX reason" than a technical one, really.

**Comment by yaron2** [comment]
> Responding with "url":"http://localhost:3500/v1.0-alpha1/workflows/{componentName}/{instanceID}" may not be correct if the user is running Dapr not on localhost.

Correct, we shouldn't assume localhost.

> We don't have any "beta1", or even "alpha2". Not sure what the best way to approach this would be. CC: @artursouza @yaron2 may have more thoughts

We don't today, but doesn't mean we can't have these. However specifically for what's being discussed here, it's OK to perform the breaking change because Dapr 1.10 has 0 components to back this API. First component, if at all, would come in 1.11. Even if that wasn't the case, making changes for an Alpha API for the next release should be ok. For example, had we wanted to perform a breaking change to the distributed lock API, I'd have advocated for alpha-1, as it's been a few releases and we know of users that use it actively.

> One of the selling points of Dapr is that you don't require an SDK to use the HTTP APIs. This design is in that spirit and is particularly helpful for developers using a language that we don't have an SDK for (the Dapr maintainers can only maintain so many SDKs...).

Correct

**Comment by yaron2** [comment]
> Polling, on the other hand, is stateless and well-suited to a wider range of clients. I would prefer we do both rather than only have a blocking variant.

I would opt to support polling due the fact it's a more descriptive and well known method than blocking. The client that's blocked cannot make informed decisions about timeouts and when to reestablish a connection or reason about it's state in a deterministic way.

**Comment by olitomlinson** [comment]
There will be scenarios where end-users want to explicitly `Allow` or `Deny` which specific calling Apps can perform management operations (`start`, `terminate`, `status` `sendEvent`, `suspend`, `resume`) against each registered workflow _Type_.

> **Remove the {workflowType] segment from the URL**
> This segment is not needed. The only thing that's needed is {workflowComponent} and {instanceID}.

The above proposal needs considering in light of how ACLs will be implemented.

If we take the `WorkflowType` _out_ of the URL, how does the **source/calling** sidecar make a quick decision on if the caller is allowed to perform a management operation against that particular workflow Type? 

If the `WorkflowType` isn't included in the URL, I can only assume that the sidecar would have to resolve the underlying `WorkflowType` from the workflow Id, which could be a inefficient task if network hops are necessary i.e. to the placement service to get the Type / Or to the target service itself to get the Type?

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/4224880/221553037-b2967a0f-8bcc-46a9-9035-63863d185e8e.png">

**Comment by cgillum** [comment]
Thanks @olitomlinson, I hadn't considered ACLs when writing this proposal, but I agree it's important for us to think about this.

To give a concrete example, I think you're saying that we'd want something like the following (using a fictional ACL declaration language):

```
ALLOW userA Start, Terminate on WorkflowA
DENY userB Get on WorkflowA
```

Or maybe instead of having workflow types as resources in this ACL language, we can just make it URL based (kind of like ACLs in Azure Resource Manager, which I'm somewhat familiar with), in which case it could be a feature that exists beyond just workflow:

```
ALLOW userA POST on /workflows/dapr/WorkflowA/*
DENY userB GET on /workflows/dapr/WorkflowA/*
```

Does that sound about right?

/cc @yaron2 @nyemade-uversky since I'll need some input on whether we can do this today and/or whether we think this would be a valuable feature to have.

**Comment by olitomlinson** [comment]
@cgillum 

To your provided examples, yes, they are in the ballpark. However, replace the word ‘User’ with ‘App’. This is about which workflow management operations, for each workflow type, are exposed to other Apps in the mesh.

There is a concept of ACLs in dapr. Probably worth digesting this and see if something can be done which is similar, as to keep the DevEx some-what consistent.

https://docs.dapr.io/operations/configuration/invoke-allowlist/

**Comment by cgillum** [comment]
@olitomlinson I like this proposal. Would you be willing to open an official Dapr proposal to better track and discuss this idea? I worry that it might get lost since this issue is primarily about making changes to existing HTTP/gRPC APIs.

**Comment by olitomlinson** [comment]
@cgillum of course, sorry, I forget that this isn’t a general issues thread.

Done https://github.com/dapr/dapr/issues/6072
