### ISSUE TITLE
Cascade the outcome of the App health check to the daprd container health check

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#5925]
/area runtime

## Describe the feature

**cc @yaron2 - probably missed something here, so please review**

**Context** 

A failing [App Health check](https://docs.dapr.io/developing-applications/building-blocks/observability/app-health/) does not currently remove the pod from service discovery, and it is understand that Invocation requests will continue to reach the daprd sidecar. 

It is desirable to remove the pod altogether from Service Discovery if the App Health Check fails, so requests can be load balanced to other available and healthy pods.

![image](https://user-images.githubusercontent.com/4224880/218448474-aebe414a-1122-4574-ad43-f7a9bdb44ddd.png)

**Comment by ItalyPaleAle** [comment]
If the app exposes a healthcheck endpoint that is queried by K8s directly, that would make the entire pod appear un-healthy, correct?

If that's true, my preference would be for encouraging users to do that rather than relying on Dapr .... relaying the health checks to the app, so the action is more immediate too.

**Comment by chronologisch01** [comment]
Maybe I'm misunderstanding but shouldn't Health Check also register when the app is healthy again? Otherwise, I could also direct the Kubernetes liveness probe to the endpoint, right? Also, this would restart the entire pod, which is probably not what you want to do when using a Health Check. Do you think it might be possible for the sidecar to remove itself from the load balancer when the app is unhealthy and add itself back in when it is healthy? If this is feasible I would like to create an issue for this, because I think this would be more appropriate for a health check.

**Comment by ItalyPaleAle** [comment]
> shouldn't Health Check also register when the app is healthy again

Yup, that's how it works today.

> Do you think it might be possible for the sidecar to remove itself from the load balancer when the app is unhealthy and add itself back in when it is healthy?

I'm afraid that is not possible :(

In K8s, we use the standard K8s Service load balancer, so we can't exclude an instance from the load balancer unless it reports itself as un-healthy (which as you say, would cause the pod to be restarted)

**Comment by olitomlinson** [comment]
Maybe related https://github.com/dapr/dapr/issues/5234

**Comment by chronologisch01** [comment]
> In K8s, we use the standard K8s Service load balancer, so we can't exclude an instance from the load balancer unless it reports itself as un-healthy (which as you say, would cause the pod to be restarted)

But doesnt the sidecar is also called with a readiness probe? Shouldn't the readiness probe on the sidecar fail if the app health check fails? Because otherwise I would have to point a kubernetes readiness probe and the app health check to the same endpoint. Why should the dapr sidecar get traffic, when we know that it will throw an error because the app is not healthy?
