### ISSUE TITLE
Discussion - Standardize TLS usage in components

### ISSUE THREAD

**Issue by akhilac1** [dapr/dapr#5957]
Posting a few thoughts on mTLS support in Dapr, for community feedback. Please share your thoughts.This does not include design details yet.

## Current state of mTLS/TLS support in Dapr  :
- No global policy to mandate mTLS/TLS in a cluster 
> --enable-mtls setting while installing Dapr is applicable for internal sidecar - sidecar traffic. For Dapr - external component communication, this policy does not apply. It is driven by individual configuration setup for the sidecar.

- Non standard configuration for TLS - 
>  We use flags, which are component specific, e.g. [enableTLS](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-pulsar/), [disableTls](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/) etc

- TLS is not mandatory for production ready `stable` components
> TLS is an optional feature for a component today. mTLS is a well accepted method to authenticate connections. For certifying a component as stable - which means that it can run in production, mTLS support should be mandatory. 

- Documentation for understanding mTLS/TLS support 
> Once attributes are standardised it will be easy to specify mTLS Attributes in the configuration. Having a clear documentation on the support status for mTLS for a component will help developers assess the component capabilities better.

## Proposed high level approach : 

1. To enforce a global policy for mandating or flexing mTLS, TLS in the cluster, a centralised component should be setup to manage the 'enableMTLS' option. Dapr sidecar should be able to validate this setting, before connecting with the components with/without mTLS.

1. All components should adhere to a Least common denominator for TLS settings to allow portability across components, standardise usage and simplify adoption. This will require change in many components

1. Clear documentation and tagging 'TLS supported' along with the certification status of the component, will enable easier assessment of the component readiness for production scenarios.

**Comment by akhilac1** [comment]
Tagging @pravinpushkar

**Comment by pravinpushkar** [comment]
@akhilac1 May be we can enhance the `api-allowlist` configuration to provide more fine grained control on apis https://docs.dapr.io/operations/configuration/api-allowlist/. 
For example - 
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myappconfig
  namespace: default
spec:
  api:
    allowed:
    - name: state
      version: v1.0
      protocol: http
      tlsMode: STRICT | PERMISSIVE // new option
```

**Comment by yaron2** [comment]
Out of the 4 bullet points you outlined here, the second one re: TLS standardization in components and the third re: documentation make a lot of sense to me, and these should probably be transferred to components-contrib and docs respectively for further discussion.

> No global policy to mandate mTLS/TLS in a cluster

You are conflating and mixing up two different concepts in this issue: mTLS  (or client side TLS) and server side TLS.

After you correctly edited your issue to change mTLS to TLS in some occurrences, this bullet point becomes irrelevant as Dapr has a global policy for mTLS where it is applicable, meaning - for sidecar to sidecar interactions. mTLS is not supported through the great majority of Dapr components irrespective of Dapr, with the most obvious example being AWS/GCP/Azure components.

> Non standard configuration for TLS

I agree that we might want to (in a backward compatible way) change metadata keys across the relevant components to create a consistent naming scheme for those that do support TLS configuration.

> For certifying a component as stable - which means that it can run in production, mTLS support should be mandatory.

As explained before, mTLS is not supported in the great majority of our components, irrespective at all of Dapr. If you want to suggest we add a requirement that a components that *can* support mTLS needs to support it in order to become stable, I think that makes sense. This would need further discussion in components-contrib.

> To enforce a global policy for mandating or flexing mTLS, TLS in the cluster, a centralised component should be setup to manage the 'enableMTLS' option. Dapr sidecar should be able to validate this setting, before connecting with the components with/without mTLS.

Dapr should not enforce a global policy for components, as there is no consistent authentication scheme even between the components that do support TLS or mTLS. Dapr today has no knowledge of the different authentication schemes of its components and they are decoupled. Introducing a policy across a fraction of components that support different variations of TLS will result in a non-consistent UX and actually hamper portability, including giving developer and infrastructure teams the wrong notion that components support this policy as a blanket statement. In addition, it will create a strong coupling between the Dapr runtime and components metadata. This is unlike mTLS for sidecar to sidecar interactions, where mTLS is consistent, governed and controlled centrally, with a single implementation that sits inside the sidecar.

> All components should adhere to a Least common denominator for TLS settings to allow portability across components

Portability in components is done via the Dapr runtime APIs, not through component specific authentication schemes. As described before, the majority of components do not support client side TLS, most of them probably support server side TLS, and trying to reason a least common denominator would result in the opposite effect and hamper portability.

> Clear documentation and tagging 'TLS supported' along with the certification status of the component, will enable easier assessment of the component readiness for production scenarios.

This we can and should do.

--------------

In general, coupling the Dapr runtime to component metadata, specifically to different and unconjoined authentication schemes would result in a major UX/DX regression and might create the opposite effect by providing security "false positives" to Dapr users. Standardizing the TLS configuration for components that support it and making clear what type of TLS connectivity each component supports in documentation are both valid options and need to be opened for further discussion with relevant maintainers in components-contrib and docs.
