### ISSUE TITLE
v1.11 Release Planning

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#5966]
## Release team
Release lead: @artursouza
Release lead shadow(s): @nyemade-uversky @robertojrojas 
Perf test lead: @JoshVanL @robertojrojas
Longhaul test: @halspang
Build manager: @JoshVanL

Read about the [Dapr release lifecycle](https://github.com/dapr/community/blob/master/release-process.md)

## Milestone dates
Feature definition starts: 21st Feb 2023
Feature definition ends: 14th March 2023
Feature freeze: 10th April 2023
Code freeze (Endgame starts): ~24th April 2023~ 1st May 2023
Release day: ~10th May 2023~ 17th May 2023
Announcement day: ~11th May 2023~ 18th May 2023

## Feature proposals that impact multiple repos, that maintainers can use to triage
v1.11 Progress tracking board: https://github.com/orgs/dapr/projects/70

## Priorities for this release
- Fundamentals
  - Configuration API as stable: https://github.com/dapr/dapr/issues/5522
  - 1 AWS and 2 GCP components as stable:
    - https://github.com/dapr/components-contrib/issues/2247
    - https://github.com/dapr/components-contrib/issues/2461
    - https://github.com/dapr/components-contrib/issues/2460
  - Validate binary size and virtual memory usage for sidecar: https://github.com/dapr/dapr/issues/6066 (DONE)
  - Validate number of go routines for sidecar: https://github.com/dapr/dapr/issues/6067 (DONE)
  - Do not install Dashboard by default: remove Dashboard from dapr/dapr's Helm chart and create a new dedicated chart: https://github.com/dapr/dapr/issues/4724 (IN PROGRESS)
  - ~Multiple flavors of images for Dapr sidecar, starting with "everything" and "just stable components": https://github.com/dapr/dapr/issues/3168~
  - ~Port existing longhaul tests (nightly and release) to external Azure subscription: https://github.com/dapr/test-infra/issues/167~
  - Metrics for Actor timers and reminders: https://github.com/dapr/dapr/issues/6032
  - New API in placement service to retrieve placement table: https://github.com/dapr/dapr/issues/6033
  - [STRETCH] Improve mTLS certificate rotation: https://github.com/dapr/dapr/issues/5756
      - To have one root CA instead of 3.
      - Improving how sentry authenticates sidecars
      - Control plane services request their own SPIFFE Id
  - ~[STRETCH] Support cert manager to own root CA in addition to self-signed: https://github.com/dapr/dapr/issues/3968~
  - Support minTLS configuration: https://github.com/dapr/dapr/issues/6031~
  - ~[STRETCH] Allow automatic root CA rotation: https://github.com/dapr/dapr/issues/5958~
  - ~[EPIC] Create Dapr specific error codes in gRPC and HTTP APIs: https://github.com/dapr/dapr/issues/6068~
  - ~[STRETCH] Replace `FastHTTP` with `Chi` to support streaming and other use cases (HTTP/2.0, etc):https://github.com/dapr/dapr/issues/4979~
- ~[STRETCH] User-(easily)-reproducible performance benchmarks (DOCS/Readme)~
- External service-to-service invocation: https://github.com/dapr/dapr/issues/4549
- [STRETCH] Component hot-reload: https://github.com/dapr/dapr/issues/1172
- ~[EPIC] Resiliency not to duplicate retries with components' built-in retries ("component resiliency")~
- Workflow improvements
  - https://github.com/dapr/dapr/issues/6111
  - Workflow built-in component must not duplicate retries when resiliency policy is used
- ~Scale actor reminders registration (improves workflow performance) https://github.com/dapr/dapr/issues/6121~
- Crypto(graphy) (not currency) API: #6147 
- ~Re-design of state store encryption: https://github.com/dapr/dapr/issues/6027~
- ~[STRETCH] Dynamic subscriptions for pubsub~
- [CLI] Multi app run (better logging, other improvements): https://github.com/dapr/cli/issues/1238
- ~[EPIC] SDKs to allow TLS configuration for remote Dapr API: https://github.com/dapr/dapr/issues/6035~
- [Contrib] Refactor metadata parsing to allow metadata spec YAML to be validated and up to date (DONE)
- ~[STRETCH] [Discussion] Use SQLite as default state store for local development because Redis is not actually transactional (hence should not be used as actor state store)~
  - ~Should we deprecate `transaction` / `actor state store` support for Redis?~
  - ~See https://github.com/dapr/components-contrib/issues/2071~

## Repo milestones
Dapr - https://github.com/dapr/dapr/milestone/18
CLI - https://github.com/dapr/cli/milestone/12
Docs - https://github.com/dapr/docs/milestone/14
Components-contrib - https://github.com/dapr/components-contrib/milestone/12
Java-SDK - https://github.com/dapr/java-sdk/milestone/9
Python-SDK - https://github.com/dapr/python-sdk/milestone/10
Dotnet-SDK - https://github.com/dapr/dotnet-sdk/milestone/16
Js-SDK - https://github.com/dapr/js-sdk/milestone/12
Go-SDK - https://github.com/dapr/go-sdk/milestone/8
Dashboard: - NOT TO BE RELEASED
Quickstarts (aka Tutorials) - https://github.com/dapr/quickstarts/milestone/7

**Comment by mukundansundar** [comment]
Feature Freeze decisions

## Feature proposals that impact multiple repos, that maintainers can use to triage
v1.11 Progress tracking board: https://github.com/orgs/dapr/projects/70

## Priorities for this release
- Fundamentals
  - Configuration API as stable: https://github.com/dapr/dapr/issues/5522
  - 1 AWS and 2 GCP components as stable:
    - https://github.com/dapr/components-contrib/issues/2247
    - https://github.com/dapr/components-contrib/issues/2461
    - https://github.com/dapr/components-contrib/issues/2460
  - Validate binary size and virtual memory usage for sidecar: https://github.com/dapr/dapr/issues/6066 (DONE)
  - Validate number of go routines for sidecar: https://github.com/dapr/dapr/issues/6067 (DONE)
  - Do not install Dashboard by default: remove Dashboard from dapr/dapr's Helm chart and create a new dedicated chart: https://github.com/dapr/dapr/issues/4724 (DONE)
  - ~Multiple flavors of images for Dapr sidecar, starting with "everything" and "just stable components": https://github.com/dapr/dapr/issues/3168~
  - ~Port existing longhaul tests (nightly and release) to external Azure subscription: https://github.com/dapr/test-infra/issues/167~
  - Metrics for Actor timers and reminders: https://github.com/dapr/dapr/issues/6032
  - New API in placement service to retrieve placement table: https://github.com/dapr/dapr/issues/6033
  - Improve mTLS certificate rotation: https://github.com/dapr/dapr/issues/5756
      - To have one root CA instead of 3.
      - Improving how sentry authenticates sidecars
      - Control plane services request their own SPIFFE Id
  - ~[STRETCH] Support cert manager to own root CA in addition to self-signed: https://github.com/dapr/dapr/issues/3968~
  - Support minTLS configuration: https://github.com/dapr/dapr/issues/6031~
  - ~[STRETCH] Allow automatic root CA rotation: https://github.com/dapr/dapr/issues/5958~
  - ~[EPIC] Create Dapr specific error codes in gRPC and HTTP APIs: https://github.com/dapr/dapr/issues/6068~
  - ~[STRETCH] Replace `FastHTTP` with `Chi` to support streaming and other use cases (HTTP/2.0, etc):https://github.com/dapr/dapr/issues/4979~
- [STRETCH] User-(easily)-reproducible performance benchmarks (DOCS/Readme)
- External service-to-service invocation: https://github.com/dapr/dapr/issues/4549
- [STRETCH] Component hot-reload: https://github.com/dapr/dapr/issues/1172
- ~[EPIC] Resiliency not to duplicate retries with components' built-in retries ("component resiliency")~
- Workflow improvements
  - https://github.com/dapr/dapr/issues/6111
  - Workflow built-in component must not duplicate retries when resiliency policy is used
- Scale actor reminders registration (improves workflow performance)
- Crypto(graphy) (not currency) API: #6147 
- ~Re-design of state store encryption: https://github.com/dapr/dapr/issues/6027~
- ~[STRETCH] Dynamic subscriptions for pubsub~
- [CLI] Multi app run (better logging, other improvements): https://github.com/dapr/cli/issues/1238
- [EPIC] SDKs to allow TLS configuration for remote Dapr API: https://github.com/dapr/dapr/issues/6035
- [Contrib] Refactor metdata parsing 
- [Discussion] Use SQLite as default state store for local development because Redis is not actually transactional (hence should not be used as actor state store)
  - Should we deprecate `transaction` / `actor state store` support for Redis?
  - See https://github.com/dapr/components-contrib/issues/2071

**Comment by mukundansundar** [comment]
@dapr/maintainers-dapr This ideally needs to be resolved to some extent before release https://github.com/dapr/dapr/issues/6265

**Comment by yaron2** [comment]
> @dapr/maintainers-dapr This ideally needs to be resolved to some extent before release #6265

Agree, triaged to 1.11

**Comment by mukundansundar** [comment]
Release blocker https://github.com/dapr/cli/issues/1289

**Comment by mukundansundar** [comment]
@artursouza can this be closed?
