### ISSUE TITLE
[Discussion] Who is using Visual Studio (or other IDEs) for Dapr application development?

### ISSUE THREAD

**Issue by philliphoff** [dapr/dapr#6097]
A [question](https://discord.com/channels/778680217417809931/781585912802050078/1085877826735054909) was posted on the Dapr tooling Discord channel about plans for Dapr integration with Visual Studio.

I'm not aware of any specific plans but, having spent a lot of time doing exactly that kind of integration, I'm curious what level of interest there is from Dapr users for additional tooling integration beyond what exists in, for example, [VS Code](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-dapr).  

- Who is using Visual Studio today for Dapr application development?  If not Visual Studio, what other IDEs or development tools are you using?  For what development stacks (e.g. Java, Python, .NET, Go, JavaScript, etc.)?
- What's the most significant challenge you have today, as part of your daily development process, when using Dapr with those tools?  What kind of Dapr integration would you like to see?

Notes:

There was some earlier discussion about this in [dapr/dotnet-sdk#401](https://github.com/dapr/dotnet-sdk/issues/401).

**Comment by mcrio** [comment]
Hi. 

Using Rider for .NET development.
I don't have any need for tools within the IDE. CLI or Dapr Dashboard is fine. When debugging I attach the debugger to an existing process.

Using [Tye](https://github.com/dotnet/tye) to start all the services and their Dapr sidecars locally.

Pros: 
 - Start all services by using one command `tye run`.

Cons:
 - `Tye` is no longer maintained

Would like to have:
 - Ability restart one particular service and it's Dapr sidecar. That would allow me to start all services, do development on one service, and on change restart (rebuild) just that one service instead of all of them.

**Comment by philliphoff** [comment]
@mcrio

> When debugging I attach the debugger to an existing process.

How do you find the process(s) for a given service, and then how do you attach to them?  Would it be helpful to do those tasks (e.g. find/attach to one ore more services) in a more direct and/or automated way?

> Ability restart one particular service and it's Dapr sidecar. That would allow me to start all services, do development on one service, and on change restart (rebuild) just that one service instead of all of them.

Tye has a "watch"-like feature that should restart just the changed service's replicas; have you used this feature and, if so, is it not sufficient for your needs?

**Comment by mcrio** [comment]
Hi @philliphoff 

My setup is rather simple as I am running the services as local processes. Also I have no need to attach to a container so attaching the debugger is just a matter of attaching it to a locally running process.

> Tye has a "watch"-like feature that should restart just the changed service's replicas; have you used this feature and, if so, is it not sufficient for your needs?

Sorry my bad. I wasn't aware of this feature. It probably would have helped.

My use case with Tye was the easy start/stop of all configured services, and the logs analysis through the dashboard.

Migrated now the config to Dapr Multi-Runner, which I was not aware of until recently. From what I see, compared to Tye Multi-runner has a faster startup time, which is great. It still lags some configurability, like setting the logs directory path instead of the hard coded one. Multi-Runner has also no support for replicas.

**Comment by leandromonaco** [comment]
I wanted to give the MultiApp feature a try to see if this could replace Tye

I've run `dapr run -f .\dapr.yaml` in a similar way I'm running `tye run` and the first issue I found is `The run command with run file is not supported on Windows`

Another thing that was very convenient when using Tye is that we could launch the dashboard and run the apps with a 1-liner `tye run --port 10000 --dashboard`

Dapr requires `dapr dashboard -p 10000` apart from `dapr run`

On a separate note, is it possible to run an application that has no sidecar?

**Comment by mcrio** [comment]
@leandromonaco The docs state the feature is in preview and currently available on Linux and MacOs only.

**Comment by chewy02** [comment]
I'm using Visual Studio Pro 2022 to develop with Dapr. I almost never use VS Code.

Unfortunately I've found the development experience with VS and Dapr to be clunky. I'm used to just clicking "F5".

Fortunately Dapr.Sidekick provides the "F5" dev experience. It would be great if something like Sidekick was part of the Dapr .NET SDK, or just built into Visual Studio. 

Maybe make Dapr a "Connected Service", and adding Dapr as a service will automatically add a Sidekick-like service to your project.

**Comment by philliphoff** [comment]
@chewy02 That's good feedback, thanks.  Do you typically run several services from a single VS solution that each need a Dapr sidecar, or do you tend to have single-service solutions?  If the former, how are you currently managing startup of multiple services?

**Comment by chewy02** [comment]
Hi Phillip - I mostly have single-services solutions.

I've tried running several services from a single solution in the past, and Tye was helpful with this. However, it still feels like setting up and launching Dapr sidecars should be automated.

**Comment by MRRQX** [comment]
I (my team) are developing .NET 7, Dapr services. I am doing so on a MBP with JetBrains Rider. I rarely use VS Code, OmniSharp has not proven adequate (for me) in the past.

I undertook the R&D task to evaluate Dapr (recommended it). Ultimately found using Docker, Docker Compose the cleanest way to dev, debug.

I would welcome better integration in Rider. The friction depending on Docker Compose becomes more apparent when iterating fast.

FWIW, I was not aware of Tye, will be giving it a look.

**Comment by philliphoff** [comment]
@MRRQX Thanks for the feedback!  Are you typically working with single service solution/repos, or multi-service solution/repos?

**Comment by MRRQX** [comment]
@philliphoff We are (very) early in a greenfield project, this is based on what I have done to date.

We are not using a mono repo, we will be using Dapr with all services (components will vary), individual solutions may have multiple projects using Dapr (ex: prototype had an API and API worker service using Dapr) and we will be deploying to Azure App Containers, using Microsoft's Dapr support.

For Rider and the prototype project, I created two Docker Compose configurations and would launch each in Debug in turn, then test. There may be a better way to accomplish that but I haven't had the time to investigate further.

**Comment by alexdresko** [comment]
I basically have to wait until VS has better Dapr support (and multi-app run for Windows) until I can effectively start using Dapr in our organization.

**Comment by philliphoff** [comment]
@alexdresko Thanks for the feedback!  I'm curious, is that due to organization guidelines related to use of certain development tools, technical or usability limitations of other, non-VS tools, or just a preference of the team?  What kind of "Dapr support" would you expect/want in VS?

**Comment by tomasKosar** [comment]
I think I am mostly in the similar situation as @chewy02 

I use the latest Visual Studio(VS) 2022 (preview) Enterprise. Right now I actively develop .NET services in mono repo where also some Python services lives. I am interested in "F5 experience". My dev machine is Windows 11 but ideally I would prefer to start and debug services in Docker Linux.

For my day to day development I implemented the approach that is described in linked Github issue "Visual Studio development of Dapr apps #401". So its that VS Extension "Microsoft Child Process Debugging Power Tool". That works well enough with running one service. So that is using Dapr but not running service in Docker.
When I need to run bigger part of solution with multiple services that send messages from one to another then I start them from script/cli and then attach debugger to those that I need to debug if there are any issues. That is again not running services in Docker. I did not figure how to start multiple services with dapr from VS on "F5" yet. I am not sure how to achieve this together with Python services.
I somehow missed Dapr.Sidekick project. I might give it a go.

With some limited success I am able to run dapr and side car in a single container. I do not use it much. I think I was not able to figure connection to other services or third party services.
The separate issue in case of starting service on F5 in Docker, that is tracked elsewhere, is how Docker authenticates with various third party services. Depending on the scenario then it might not work. There are some workarounds. I think its improving but might not be quite there yet. 
https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/#run-both-app-and-dapr-in-a-single-docker-container

When I need to run bigger part of solution in Docker then we have some scripts/cli and custom tooling that starts everything with Kubernetes but that is a time consuming process for local development so I do not use it for my day to day work.

I read a bit about Tye but we already have some scripts and custom tooling for running the solution, so then the VS extension with child processes fits me quite well.

From my perspective it would be great if I could start multiple services from VS on F5 and be able to send messages between them and debug them. Ideally if that works from VS by default or through some extension that ideally does not require much of additional configuration.

**Comment by philliphoff** [comment]
@tomasKosar Thanks for the detailed feedback!

> My dev machine is Windows 11 but ideally I would prefer to start and debug services in Docker Linux.

Do you mean you'd prefer to start/debug your services within WSL, or in Windows but having built/run the services within individual Docker containers (e.g. as part of a composition)?

> I am not sure how to achieve this together with Python services.

Are your Python services part of your VS solution, or just exist within the same repo?

**Comment by tomasKosar** [comment]
> Do you mean you'd prefer to start/debug your services within WSL, or in Windows but having built/run the services within individual Docker containers (e.g. as part of a composition)?

I think I don't mind whether those services run in WSL or Windows as long as each service runs in it own container that is based on Linux image. I would prefer if that would work mostly out of the box so that ideally I don't have to provide install or setup anything or provide any extra configuration for this. In our Production environment everything runs with Kubernetes and that I might not want to use locally on daily basis. 
 
> Are your Python services part of your VS solution, or just exist within the same repo?

Technically part of solution but practically mostly just part of repo. I am not Python expert and there are other people working on those. Python developers would mostly use Visual Studio Code which I use only when I have to work with Jupyter notebooks.

**Comment by philliphoff** [comment]
> I think I don't mind whether those services run in WSL or Windows as long as each service runs in it own container that is based on Linux image.

@tomasKosar Is there a technical reason why you'd need/prefer the services to run in their own containers vs. "on the metal" (whether on Windows or in WSL)?  Trying to debug applications running within a container, while certainly possible, comes with caveats of its own (e.g. slower to start, requires different images than "production" anyway (to facilitate debugging), has restrictions on hot reload, complicates sidecar arrangements (due to Docker network setup), etc.).

**Comment by tomasKosar** [comment]
> @tomasKosar Is there a technical reason why you'd need/prefer the services to run in their own containers vs. "on the metal" (whether on Windows or in WSL)?

Well in general I would say it would be better if I would run services locally as close as its possible to production environment. Obviously this needs to be smooth otherwise It wont be used.
So if I use Visual Studio then I use Windows and then my "on the metal" approach is running processes in Windows but in production services run in Docker Linux. I think it works quite well in .NET core.
It can get more tricky in Python as the support for both Windows and Linux there is not the same. We had to implement some fixes and workarounds to make it work "on my metal" although there is no value in those fixes for production.

**Comment by chewy02** [comment]
@philliphoff - does Microsoft have any plans to integrate Dapr into Visual Studio?

**Comment by nanderto** [comment]
The question excludes those of us that might choose Dapr if it worked "properly" in Visual Studio. That is to say I would expect it to just work like all of the other programming solutions in VS do. There would be templates to create everything I need both at the solution level and at the project level. I should be able to add a new building block as a project and have all of the files in place so I can F5 debug, deploy easily and set up CI/CD etc. I would also expect it to support building with Dapr with seperate repos with individual microservices, but still be able to connect to a Dapr cluster for debugging. From memory Service Fabric had a better experience and solved many of these problems (without need of a side car), it's a shame it has fallen by the wayside. Dapr has already been chosen for my team and now we have to figure out how to use it without the flagship tool we have been using for 20 years. This is such an old issue that it seems likely it will never be fixed, but I would like to add 1 more voice for supporting Visual Studio.

**Comment by NateB2** [comment]
Adding another vote for adding a first-class debugging experience inside Visual Studio.  It's hard to believe it doesn't exist for this product, given the developer audience this initiative is targeting.

**Comment by jedjohan** [comment]
I would LOVE for the entry to be easier for old plain coders ppl, vs code is fine though. But I just hate when I see a portnumber or networky stuff. I don't know and I don't care, I just want to start using the awesome Actor building block. Been testing it 3 times now (podman/docker) and always end up in boring things. I want to code 😅

"the state store is not configured to use the actor runtime. Have you set the - name: actorStateStore value: "true" in your state store component file?" --> YES I have, its because of portnumbers, docker networking and irrelevant stuff. (and so on and on and on)

**Comment by philliphoff** [comment]
@chewy02 I can't speak to Microsoft's future plans, but what would that integration look like to you?  How do you typically work with your Dapr projects/solutions, and what features would you want to see?

@nanderto That's fair, and thanks for those details about what you'd like to see in Visual Studio.  What's the relative importance of local debugging vs. deployment via Visual Studio (or at least, perhaps, scaffolding the deployment assets)?  When you say "connect to a Dapr cluster for debugging", what do you mean exactly (e.g. a local k8s instance, AKS, individual Dapr applications and sidecars, etc.)?  How are you starting/using Dapr now (e.g. with VS Code, startup scripts, etc.)?

@NateB2 When you say "first-class", what does that mean to you in terms of how you want to setup your project/solution and debug its services?  E.g., are you interested in just starting Dapr services, or do you also have a front-end that uses those services that need starting as well?

@jedjohan Thanks for the feedback. (I believe you've said this in the Dapr Discord as well.). I believe there are some new features (e.g. Dapr run files) that can help reduce/eliminate the need to keep networking/port settings in sync across multiple configuration files).

**Comment by NateB2** [comment]
@philliphoff By a first-class experience, I mean a comparable experience to Service Fabric - ability to "F5" on a specific project and have VS build/publish the code to the Dapr cluster and enable debugging across all the Dapr services in the solution. Having it start other associated non-Dapr services (like a front-end project) would be a bonus, but we could do that now with minimal effort.

**Comment by philliphoff** [comment]
@NateB2 When you say publish to a "Dapr cluster" for debugging, can you expand on how you typically develop and test your Dapr applications on your local machine?  Are you running all of the services and Dapr sidecars "on the metal", or do you prefer to create images and deploy them to a (local) Dapr-enabled k8s cluster?  (Or both?). I ask because there's quite a bit of difference between "run/debug everything locally" and "run/debug everything in a (potentially remote) cluster" in terms of build/deploy/startup time and complexity and caveats (e.g. generation/deployment of intermediate images).

**Comment by philliphoff** [comment]
@chewy02
@alexdresko
@tomasKosar
@nanderto
@NateB2

FYI, in the Dapr Community Call on 4th October 2023, we presented a sneak peek of a new Dapr extension for Visual Studio.

Link to presentation: https://www.youtube.com/watch?v=L_S98bRGfCQ&t=668s

**Comment by chewy02** [comment]
The Visual Studio extension looks great .. finally!

**Comment by philliphoff** [comment]
More information on the Dapr extension for Visual Studio can be found at: https://github.com/microsoft/vs-dapr

**Comment by para2402** [comment]
I see that the VS Code extension is archived. Is there any other version being developed? Or are you discouraging the use of the extension and just using the Dapr CLI? Just wanted to know the path forward

https://github.com/microsoft/vs-dapr

**Comment by WhitWaldo** [comment]
@para2402 Not at this time. It was developed by the previous Dapr .NET SDK maintainer and was archived since it was generally rendered obsolete (for .NET development) by other tools like Aspire.

If you're developing against the .NET SDK, I might suggest taking a look at the various [integration options](https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-integrations/).
