### ISSUE TITLE
Decoding slash in url

### ISSUE THREAD

**Issue by Skreet2k** [dapr/dapr#6418]
/area runtime

## Expected Behavior

dapr doesnt decode request before invoke.
`curl --header "dapr-app-id: appId" http://localhost:3500/api/v1/files/Icon/icons%2F24%2FHU.png
`

## Actual Behavior

I think dapr decode request and make it to 
`http://localhost:3500/api/v1/files/Icon/icons/24/HU.png
`

## Steps to Reproduce the Problem

After update from 1.10.4 to 1.10.7 all requests, with encoded slash return 404.

1.10.6 doesnt have issue.

## Release Note

RELEASE NOTE:

FIX decode url before invoke

**Comment by berndverst** [comment]
Appears to be related to https://github.com/dapr/dapr/pull/6335

**Comment by yaron2** [comment]
> Should result in the same call into the app as calling it without Dapr:
curl http://appId.svc:3000api/v1/files/Icon/icons%2F24%2FHU.png 

Agree with this. Dapr should not decode on behalf of the app.

**Comment by JoshVanL** [comment]
Since fasthttp [normalizes slashes together with segment contents](https://github.com/valyala/fasthttp/blob/master/uri.go#LL575C3-L575C3), we need to duplicate that logic in dapr and disable normalization in fasthttp (assuming we still want to slash normalization to address https://github.com/dapr/dapr/issues/6324).
