### ISSUE TITLE
Add Strict-Sandbox Configuration CRD to Dapr for Enhanced WASM Security

### ISSUE THREAD

**Issue by Taction** [dapr/dapr#6422]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

### Background
Dapr supports WASM middleware and output binding features, allowing users to run custom WASM code to extend the functionality of Dapr without modifying the Dapr runtime. However, this introduces potential security threats, such as having access to the current time accurately, which could be used to perform timing attacks on the rest of Dapr, similar to the Spectre/Meltdown vulnerabilities. 

### Proposal
Adding a new configuration CRD to Dapr that enables a strict sandbox mode for all WASM components. This will enforce limits on time and file access to prevent potential attacks.

Strict Time Access
Set walltime to 2022-01-01 UTC and increment it by 1ms on each reading, set nanotime to 0 and increment it by 1ms on each reading, nanosleep returns immediately(These are the behaviours wazero runtime already supports).

Limited File Access
The strict sandbox will provide an actual mount point inside the /tmp directory for each WASM component, and mount to wasm's root file system. The floder name could be `dapr-wasm-${random}`.

An example of configuration:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: wasm
spec:
  wasm:
    strictSandbox: true
```

#### Component Implementation
Adding `wasmStrictSandbox` metadata for every wasm component, and if `strictSandbox` is setted to true in configuration CRD, the dapr runtime should override this metadata.

## Release Note

RELEASE NOTE: Add Strict-Sandbox Configuration CRD to Dapr for Enhanced WASM Security

//cc @codefromthecrypt @ItalyPaleAle The basic idea is from you, I open this issue to have further discussion.

**Comment by ItalyPaleAle** [comment]
Thanks for opening this issue.

I recommended making this option into the Configuration CRD (rather than in each component's metadata) for 2 reasons:

1. This way it applies to all and any WASM component that may be loaded.
2. To separate concerns, so the people that operate the cluster (which may be different from the people who deploy components) have control over this.

We currently don't pass options from the Configuration CRD to components, so some wiring will need to happen in [pkg/components](https://github.com/dapr/dapr/tree/master/pkg/components) to change what's passed to components' `Init()` methods.

As for this:

> Strict Time Access
> Set walltime to 2022-01-01 UTC and increment it by 1ms on each reading, set nanotime to 0 and increment it by 1ms on each reading, nanosleep returns immediately(These are the behaviours wazero runtime already supports).

@Taction @codefromthecrypt what do you think about setting walltime to the time the WASM code is first launched, maybe with a 1s resolution? And then do not increment the time at all. I am concerned that otherwise by not having the time _at all_, users may end up disabling the strict sandbox entirely. FWIW, other runtimes like Cloudflare Workers behave the same way: the code gets the current time when the invocation starts, but it's never increased.

**Comment by codefromthecrypt** [comment]
> And then do not increment the time at all.

Wazero began with not incrementing time, but had to change that because certain code expects time to increment. I think a very specific offering like Cloudflare workers isn't a diverse enough citation because usually, there are very specific SDKs that have to be used. I would expect basically all types of code to work with the output binding. Wouldn't it be better to wait for someone to complain about wazero's default rather than rediscover why it was designed the way it was? It would feel a lot better to special case the initial value than re-discover why time should increment in other word as a bug about time is extremely hard to debug.

**Comment by codefromthecrypt** [comment]
@ItalyPaleAle I think special-casing the initial value to current time makes a lot of sense, especially with the 1s resolution as that feels harder to game as a side channel.

**Comment by Taction** [comment]
Agree with returning the current time with a 1s resolution, this should be easier to implement also.

> We currently don't pass options from the Configuration CRD to components, so some wiring will need to happen in [pkg/components](https://github.com/dapr/dapr/tree/master/pkg/components) to change what's passed to components' Init() methods.

For this part, how about passing this config via context? For example, define a `type wasmStrictSandboxKey struct{}` in component package and expose set get functions.
```go
func WithWasmStrictSandbox(ctx context.Context, enable bool) context.Context {
	return context.WithValue(ctx, wasmStrictSandboxKey{}, enable)
}

func GetWasmStrictSandbox(ctx context.Context) bool {
	v := ctx.Value(wasmStrictSandboxKey{})
	if v == nil {
		return false
	}
	enable := v.(bool)
	return enable
}
```
In this way, we can pass it to all components in runtime without telling if the component is a wasm component and only wasm component needs to get this value and handles it.

**Comment by codefromthecrypt** [comment]
@Taction "Limited File Access" section is actually loosing today, as we currently don't mount /tmp at all. Maybe we should not have that in scope of this PR?

**Comment by codefromthecrypt** [comment]
https://github.com/dapr/components-contrib/pull/2884 begins the backend of this change, and can be integrated like @Taction mentions with context config, or otherwise.

**Comment by Taction** [comment]
@codefromthecrypt Thanks for your contribution!

> "Limited File Access" section is actually loosing today, as we currently don't mount /tmp at all. Maybe we should not have that in scope of this issue?
I'm ok with this. strictSandbox mode can have no access to the file, we can reconsider this with the end user's request.

**Comment by Taction** [comment]
Added a draft pr for dapr configuration based on the previous discussions. As we have configuration needs to be passed to components, this provides a base implementation to discuss.

**Comment by codefromthecrypt** [comment]
*Note for the future on filesystem support and sandboxing*

Not trying to over-solve, just sharing notes from wazero for when things become relevant here.

Some binaries like python require files. It is possible to re-bundle read-only files into the wasm binary, but there are still some use cases such as external libs or writing to /tmp.

So  @evacchi's work on wazero+windows reminded me we probably need a disclaimer on FSConfig. Basically, if you ever return a real file, there's little point in faking the clock etc. files can leak the real clock with access timestamps, also poll events can be used for timing attacks etc. I think it is worth a note because probably some people think that exposing a subdirectory is sandboxing.. it is'ish, but exposing a real one while using fake clocks for security isn't very sensible.

Probably when we get to files, we want to consider completely fake, possibly like [Trivy's MapFS](https://github.com/aquasecurity/trivy/tree/93996041b2d6d0af50a69314e813f569c0786661/pkg/mapfs), to achieve both strict sandbox and also file support. wazero's upcoming file api will also allow masking, so other options will be possible. It may even include a fake filesystem...

**Comment by ItalyPaleAle** [comment]
@codefromthecrypt thanks for sharing this, it's very interesting (on a related note, network access can allow getting time etc, and with enough measurements you can remove the noise).

I think proxying the FS to remove things like access timestamps (or making them the same as the clock that is passed) makes sense.

**Comment by codefromthecrypt** [comment]
> on a related note, network access can allow getting time etc, and with enough measurements you can remove the noise

Agree in general, and it is a good point. What's constantly on my mind is that the wasm itself is embedded. So, for example, if someone gets a hold of an interpreter they can run something without the network noise (by injecting code). I don't mean to get too foil hat, but basically when we get to interpreters (python, ruby, etc) it can become different.

> I think proxying the FS to remove things like access timestamps (or making them the same as the clock that is passed) makes sense. I would even get to suggesting that the proxied FS be enabled in all cases even when strict sandboxing is off.

When we update on filesystems we can control a lot of it. The hardest thing to do is around poll events (non-blocking i/o), basically the whole poller may need to be virtualized. OTOH, could be that this sort of thing can be deferred or sponsored by a user who really needs that level of isolation.

**Comment by ItalyPaleAle** [comment]
> OTOH, could be that this sort of thing can be deferred or sponsored by a user who really needs that level of isolation.

Yes, when we get to specific things like polling, that may be a lesser priority.
