### ISSUE TITLE
Limit amount of data that can be stored in actor reminders to 48 bytes

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6424]
## Description

Currently, when creating a reminder it's possible to store arbitrary amounts of data in them. This data is stored alongside the reminder, and it gets serialized in the same document as all the reminders.

Storing large amounts of data in reminders has a significant negative performance impact, as it increases the amount of data that is retrieved from the state store, unserialized, re-serialized, and stored every time there's an operation on reminders. Just like more reminders negatively impact perf, reminders with lots of data have the same effect.

For actors, state should ideally be stored as actor state (or stored in an external state store), and not as data attached to a reminder.

I would recommend then limiting the amount of data that can be stored in a reminder to 48 bytes, encouraging that do need to attach data to reminders to just store a reference to data in the actor state store (or a reference to data stored somewhere else). 48 bytes is enough to store a SHA-384 hash as a reference to data.

> The same applies to timers, but this is not a particular concern in that space.

## Backwards compatibility

This is potentially a breaking change. Assuming this lands in Dapr 1.12, the proposed rollout would be:

- Dapr 1.12 would continue to accept arbitrary amounts of data but show a warning if the data exceeds 48 bytes
- Dapr 1.13 would reject data larger than 48 bytes by default, but using a feature flag we can still allow it temporarily (with a warning)
- Dapr 1.14 or 1.15 would reject data larger than 48 bytes with no feature flag to allow it anyways

**Comment by berndverst** [comment]
Should the actor reminder API perhaps store a separate state store entry for each state, and then in the reminder data just the reference (e.g. the state store key) to the reminder data? We could use a new internal prefix to avoid collisions -- similar to the way we store actor reminder data itself.

This way we could still support arbitrary size data, but we don't save the data itself in the actor reminder data - the Dapr runtime just shifts that to state store entries and references to those (within the reminder data)

**Comment by ItalyPaleAle** [comment]
Although that is an option, it becomes more documents that we need to track and update every time, in the same transaction. It would still have a negative performance impact, and it has the risk of creating garbage that needs to be collected.

I also do think that state for actors should be stored as actor state store.

**Comment by yaron2** [comment]
I do not support limiting the data to a certain size for several reasons.

First, 48 bytes (or to be more accurate, any number that you choose) is a non-defensible magic number. non-defensible in the sense that there's no logic that can be explained to end users when faced with the question of "why 48 bytes and not 55, or 60, or 81, ...". Arbitrary numbers are something we want to avoid as much as we can; when a magic number is introduced as an internal implementation detail that interfaces with contributors of the codebase only, its existence can be justified to serve a purpose even if the reasoning behind it might not necessarily be. 
When end users are presented with an arbitrary number, it becomes impossible to justify the logic behind the choice.

Second, I think that the claim of `Storing large amounts of data in reminders has a significant negative performance impact` is itself subjective and cannot follow a one-size-fits all statement. This is due to the following:

1. Negative performance impact is decided by the end user scenario. For one user, storing 10Mb inside a reminder might work very well because its within the accepted performance goals for their specific project, while other users can do fine with many reminders that store 1kb. This is very much dependent on the actual usage and system requirements, and blanket limiting won't work to the benefit of all users.
2. For other use cases, limiting the data and enforcing a reference value as an alternative might actually cause a performance degradation that's worse than what they would have experienced if stored data with the reminder. This might happen, as one example, because the system is single threaded and what used to be two I/O calls (store reminder and get triggered on reminder) are now 4 calls (store data, store reminder, get triggered on reminder, get data). More so, depending on their choice of underlying database, this might cause throttling or any number of issues that can result from multiple access operations. So again, this is too dynamic and use case specific.
3. Whether performance is negative is not only dependent on the end user scenario as described above, but in many cases, also the underlying database. This adds even more to the different permutations that would ultimately decide whether or not storing reminder data meets application requirements or not.

Third, in the case that users want to use reminders without data or store references, they can simply do that today with nothing stopping them. Considering this and the above, it feels like this can be converted to guidance rather than imposing a strict limitation that will definitely not be applicable to all users and all scenarios, and would ultimately serve to limit more than to assist.

I also agree with @berndverst that there are opportunities to provide further reminder optimizations (either by the methods outlined in the comment or others), especially now as we're looking to a redesign of the reminders subsystem, which renders this proposal inopportune at this point in time.

**Comment by ItalyPaleAle** [comment]
> Second, I think that the claim of Storing large amounts of data in reminders has a significant negative performance impact is itself subjective and cannot follow a one-size-fits all statement. This is due to the following:

I probably should have explained this more, but it actually is a one-size-fits-all statement.

The main issues with the actor reminder implementation we have today is how the data is serialized. Essentially every reminder is stored in a single JSON document (there could be N documents if partitioning is enabled, but it's still a small number - having too many partitions causes other negative perf impacts).

For simplicity, let's focus on the operation of creating a new reminder. The Dapr sidecar in this case must:

1. Request the document with the list of reminders
2. Unserialize the JSON document
3. Make the updates
4. Re-serialize the document as JSON
5. Send it to the data store

Data stored in reminders is included in the same JSON. So if a user were to store 10MB of data, it'd be encoded in the same JSON with all the reminders (after being base64-encoded, so it becomes about 13.5MB). At this point every sidecar has to pay that tax when performing operations on any reminder.

This means that even if for _that_ specific reminder having the data included with the reminder may offer a small performance gain, every sidecar now has to pay that tax when performing operations on any reminder. Could be creating a reminder, executing a reminder, etc, even for unrelated reminders.

To back this with data, I have run the actor_reminder perf test The current tests do not store any data with reminders, so in my test cluster (as a baseline, using Redis) I am getting this:

```text
Baseline:
99th percentile: 427.44ms
90th percentile: 357.04ms
Actual QPS: 38.07
```

Now, if I change the actor_reminder_perf test to store 1KB of data with each reminder, we only get 42% QPS:

```text
With 1KB data:
90th percentile: 842.90ms
99th percentile: 941.23ms
Actual QPS: 16.12
```

I believe users should rely on actor state rather than keeping data in a reminder. I have suggested allowing a small amount of data to be able to keep a reference to something if needed (I am open to setting something else if 48 bytes isn't good).

- First, it seems more appropriate in general, as keeping data in a reminder means having another place where state is stored
- Actor state is normally cached by the SDK so there should be no much issue there.

**Comment by yaron2** [comment]
> I probably should have explained this more, but it actually is a one-size-fits-all statement.

I remain unconvinced. This is still dependent on the actual use case and above all, the application requirements. To piggyback on the example you gave here, the performance numbers you outlined might be perfectly reasonable for an entire class of users, and there is no deterministic decision that Dapr can or should take on behalf of users.

Combine that with the fact users can simply not store reminders data at all if they don't like the performance, and it becomes clear why imposing an artificial limitation on users that is based on an arbitrary number shouldn't be done.

**Comment by artursouza** [comment]
Is there a way we can start by publishing this as a doc where users are aware of performance hit by reminder payload size? It is fair to publish this information first before we impose a limit. If the application does not register many reminders and is OK to have the perf hit with large payloads, why making it harder?

One thing to also consider is that we are not comparing apples to apples in this perf. We should consider the higher level throughput from the app's perspective: register reminder with large payload vs (set state + register reminder with reference key to state)

If we want to have this limit in the new implementation of reminders, that is a fair point. But then,  the runtime can still have the entire placement payload and save it in a more efficient way that does not have the limit exposed in the API.

**Comment by yaron2** [comment]
> If the application does not register many reminders and is OK to have the perf hit with large payloads, why making it harder?

Exactly, this is super subjective. Its imprudent to limit all users everywhere based on our (in this point in time, one person's) idea of what an acceptable level of performance is. Especially when the alternative is to simply not store data in reminders.

**Comment by alrz** [comment]
Shouldn't reminders regarded as a "persistent delayed message to self" (at least from the implementation perspective)? Actors by definition only send or receive messages, so however the actor's mailbox is handled, scheduled messages i.e. reminders would be too and therefore they have the same limitations. Does that make sense?
