### ISSUE TITLE
[Workflow] System quietly hangs when calling workflows or activities that aren't registered

### ISSUE THREAD

**Issue by clintsinger** [dapr/dapr#6443]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

dapr runtime: 1.11.0-rc.7
dotnet SDK: 1.11.0-rc01

## Expected Behavior

When scheduling a workflow or calling an activity that hasn't been registered the the SDK doesn't give any kind of indication that it isn't registered.   The runtime just causes the workflow to quietly hang.   What I would expect would happen is that if I call something that isn't registered with the runtime, an exception should be thrown indicating the error. 

This will help developers remember that one of the steps they need to take is to register the workflow or activity with the runtime.

## Actual Behavior

Nothing happens, and that is the problem.

## Release Note

RELEASE NOTE:

**Comment by RyanLettieri** [comment]
@clintsinger is this issue still occurring for you? If so, can you please provide steps to reproduce the issue?
In my investigation, this issue is no longer occurring. When we attempt to call an activity in a workflow that has not been registered, the following error is output from the console:
![image](https://github.com/dapr/dapr/assets/67934986/68d0d55c-54d9-4d93-9877-192534549e19)

This was achieved by commenting out the following line in the .NET example program and running through the example:
https://github.com/RyanLettieri/dotnet-sdk/blob/17f849b17505b9a61be1e7bd3e69586718b9fdd3/examples/Workflow/WorkflowConsoleApp/Program.cs#L21

When commenting out the registration of the workflow itself and running the example, a separate error is output from the console:
![image](https://github.com/dapr/dapr/assets/67934986/79eaf904-6bb1-429c-a83e-3c668f615931)
This was achieved by commenting out the following line in the .NET example program and running through the example:
https://github.com/RyanLettieri/dotnet-sdk/blob/17f849b17505b9a61be1e7bd3e69586718b9fdd3/examples/Workflow/WorkflowConsoleApp/Program.cs#L18

**Comment by shubham1172** [comment]
I have similar observations as Ryan. Using the latest Dapr and SDK versions

- Dapr version: 1.12.0-rc.5
- Dapr Dotnet SDK version: 1.12.0-rc01

## When the workflow registration is commented out
App logs:
<img width="1133" alt="image" src="https://github.com/dapr/dapr/assets/22132944/a255809e-f073-43b1-9b18-fe1f34593805">
Dapr logs:
```
INFO[0042] cars-55da46c9: starting new 'OrderProcessingWorkflow' instance with ID = 'cars-55da46c9'.  app_id=wfapp instance=Shubhams-MBP-3.domain.name scope=wfengine.backend type=log ver=1.12.0-rc.5
INFO[0042] cars-55da46c9: 'OrderProcessingWorkflow' completed with a FAILED status.  app_id=wfapp instance=Shubhams-MBP-3.domain.name scope=wfengine.backend type=log ver=1.12.0-rc.5
```

## When an activity is commented out
App logs:
<img width="1576" alt="image" src="https://github.com/dapr/dapr/assets/22132944/4be1e6b6-c070-4dbb-88dd-10db92ff13c7">
Dapr logs:
```
INFO[0232] cars-7a8f161a: starting new 'OrderProcessingWorkflow' instance with ID = 'cars-7a8f161a'.  app_id=wfapp instance=Shubhams-MBP-3.domain.name scope=wfengine.backend type=log ver=1.12.0-rc.5
INFO[0232] cars-7a8f161a: 'OrderProcessingWorkflow' completed with a FAILED status.  app_id=wfapp instance=Shubhams-MBP-3.domain.name scope=wfengine.backend type=log ver=1.12.0-rc.5
```

@clintsinger could you please try again and see if you can still reproduce the issue?

Using the sample from https://github.com/dapr/dotnet-sdk/blob/master/examples/Workflow/WorkflowConsoleApp
