### ISSUE TITLE
Bring in gotestsum and use --rerun-fails flag in CI and automation

### ISSUE THREAD

**Issue by sicoyle** [dapr/dapr#6578]
## In what area(s)?
All Dapr repo builds where we are using go test.

> /area test-and-release

## Describe the proposal
I recently came across the [gotestsum](https://github.com/gotestyourself/gotestsum) go test runner that includes a `--rerun-fails` flag. I've noticed some flakiness here and there on some of the test cases, so I think this could be a big value add to our build pipelines if we use the `gotestsum` tool with that flag to apply free built in retries for contributors.

Pros:
- Obfuscate flakiness from Dapr contributors leading to a better Dapr contributor experience
  - More Dapr beginner friendly to contribute
- _Potentially_ incentivizes adding tests on features as would make the existing tests more reliable to run and build on top of in CI.
- Improved CI stability!

Cons:
- May hide flakiness that should be fixed
  - work around could be to add a script or see if `gotestsum` has something to document flaky tests that were reran

Extra Thoughts:
- `gotestsum` defaults to 2 retries at a maximum. Is this sufficient for Dapr?

Resources:
https://github.com/gotestyourself/gotestsum
https://github.com/gotestyourself/gotestsum#re-running-failed-tests

**Comment by sicoyle** [comment]
I think this would benefit this issue if we implemented:
https://github.com/dapr/dapr/issues/5885

specifically wrt `In the case of flaky tests, how are new contributors supposed to know which failures are valid (that they need to investigate to fix) if their PR is being impacted?`

**Comment by JoshVanL** [comment]
For Dapr, I am quite strongly against us adding re-runs to `gotestsum`. From my experience, the only time I have seen a CI job fail due to transient errors which are generally out of our control is when we are uploading artifacts or waiting for some kind of infra to become available. These things are *outside of gotestsum*.

The flakes I see in our gotestsum runs are real errors; those tests are either showing that the code itself is buggy or the test itself is. For example, we are not even running unit tests with `--race` (!) and missing things like [this](https://github.com/dapr/dapr/pull/6558) before merging code.

I think we would be better to spend time to improve our test coverage and fix the buggy code, rather than obfuscate it.

I appreciate that as an end developer is really frustrating so see red everywhere all the time, causing dev cycles to be bogged down and not being able to see the woods from the trees, but hiding these problems is not the way to go imo.

**Comment by ItalyPaleAle** [comment]
This is probably related to #3595. I agree with the comments there and with @JoshVanL that retrying should not be automatic in the CI. For example, it was thanks to investigating a flaky unit test that last week I found a large number of bugs in the Configuration APIs (Josh linked to one of the 3 issues/PRs). Most of those are due to race conditions. (As a side note, we do not run tests with `-race` by default because it’s a lot slower and because it requires CGo)

However, where automatic retries could be helpful, perhaps, is when we are publishing a build, after creating a tag. This could make our release process more efficient.

> PS: Most flakiness in our unit tests is due to either race conditions (real bugs that should be investigated and fixed) or bad synchronization techniques: things like using a wall clock to wait for an effect. (A small number is due to network stuff-like failure to bind to a port). For example, @JoshVanL and I rewrote the unit tests for actors to use a mock clock, those tests which used to be very flaky are now very stable.
