### ISSUE TITLE
Add Support for ServiceMonitor in helm-chart

### ISSUE THREAD

**Issue by brunocascio** [dapr/dapr#6579]
## In what area(s)?

> /area operator

## Describe the feature

Implement `ServiceMonitor` instead of the Prometheus annotations. With this, Dapr can be integrated with the Prometheus Operator which uses CRDs for service discovery instead of annotations.

Today, most of the public charts expose a `serviceMonitor: false` flag in the `values.yml`.

## Release Note

RELEASE NOTE: **ADD** ServiceMonitor support for Prometheus Operator

**Comment by maulindesai** [comment]
Hello @brunocascio, 

I’d like to clarify whether the chart should include only Dapr’s own metrics, or also the metrics from applications that use Dapr. ServiceMonitors for applications are highly dependent on the application developers, since they decide which services should expose Dapr metrics and which should not.

I am also working on the Dapr Helm chart with ServiceMonitor support. In the current Helm chart structure, each subchart might have its own ServiceMonitor. Happy to sync on this and align approaches if that would be helpful
