### ISSUE TITLE
Change in API behaviour/breakage.

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#6588]
After https://github.com/dapr/dapr/pull/6461 it looks like we have some breakages in the API. After rebasing the [integration tests PR](https://github.com/dapr/dapr/pull/6573), they are consistently failing when before they would consistently pass.

- Service invocation HTTP looks to no longer pass-through the HTTP method from the caller to the app.
- Secret HTTP GET responses now include a newline at the end of the message.
- State store HTTP request parsing seems totally broken on fuzzed inputs

This is only the stuff which the [integration tests](https://github.com/dapr/dapr/pull/6573) have caught, though they don't cover everything so there well may be more.

/cc @yaron2

**Comment by ItalyPaleAle** [comment]
I am looking into it

> Service invocation HTTP looks to no longer pass-through the HTTP method from the caller to the app.

Confirmed this is not broken. The issue instead is that for service invocation only, we do not support an extra slash after `/v1.0//`. This is something that we knew and we discussed on Discord with @yaron2 a few weeks back. It was due to the need of managing quirks with external HTTP service invocation (to support external URLs that use slashes encoded as `%2F` or not encoded as `/`).

![image](https://github.com/dapr/dapr/assets/43508/e997ace0-ba29-461e-8497-3492d99022b1)

>Secret HTTP GET responses now include a newline at the end of the message.

Looking into why this is happening, but at a first glance it doesn't seem like something of concern, since the newline is outside of the JSON-encoded message:

![image](https://github.com/dapr/dapr/assets/43508/709f4e3f-c74e-4db5-be90-785b7e82b321)

In JSON, whitespace like that is ignored by parsers so it should not matter.

I will still look into why this is happening.

> State store HTTP request parsing seems totally broken on fuzzed inputs

Those URLs seem to have been invalid to begin with:

![image](https://github.com/dapr/dapr/assets/43508/4914f43a-8fd5-4c42-b4ea-a58d6618076a)

I am not sure why the old router was accepting them, but the fact that we are getting an error with invalid URLs seems to be working fine.
