### ISSUE TITLE
E2E tests failing 100% on Windows due to postgres failing to deploy

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/dapr#6780]
Currently E2E tests are failing 100% on Windows because the Helm chart for Postgres is failing to deploy. We may need to add affinity rules so Postgres is always installed on Linux nodes.

**Comment by shubham1172** [comment]
@ItalyPaleAle looks like the postgres helm charts are already configured to be scheduled on Linux https://github.com/dapr/dapr/blob/master/tests/config/postgres_override.yaml

Also pasting this for reference

<pre>
Summary (past 3 days):
Successes: 0
Failures: 15
    Success rate: 0.00%

Job-wise summary:
Job: Deploy test infrastructure
  -  success: 10
  -  failure: 5
Job: Build for  linux on amd64
  -  success: 10
  -  failure: 5
Job: Build for  windows on amd64
  -  success: 11
  -  failure: 4
Job: End-to-end linux on amd64 tests
  -  success: 6
  -  failure: 3
Job: End-to-end windows on amd64 tests
  -  failure: 9
Job: Clean up Azure resources
  -  success: 15
Job: End-to-end ${{ matrix.target_os }} on ${{ matrix.target_arch }} tests
  -  skipped: 6


Failed steps summary:
Job: End-to-end windows on amd64 tests
  -  Preparing AKS cluster for test: 9
Job: End-to-end linux on amd64 tests
  -  Run E2E tests: 3
Job: Build for  linux on amd64
  -  Login to Azure Container Registry for Linux or Mac: 5
Job: Deploy test infrastructure
  -  Deploy the test cluster: 5
Job: Build for  windows on amd64
  -  Login to Azure Container Registry for Windows: 4
</pre>

**Comment by ItalyPaleAle** [comment]
@shubham1172 you can see here that on Windows postgres is failing to install: https://github.com/dapr/dapr/actions/runs/5784407172/job/15675542979

**Comment by shubham1172** [comment]
> @shubham1172 you can see here that on Windows postgres is failing to install: https://github.com/dapr/dapr/actions/runs/5784407172/job/15675542979

Yes, @ItalyPaleAle the AKS clusters deployed for e2e tests on Windows should have both Windows and Linux nodes, and the Postgres charts are already configured to be scheduled on Linux (with `requiredDuringSchedulingIgnoredDuringExecution`).

**Comment by ItalyPaleAle** [comment]
Could you please check why it's not working then? Something's happening and causing the postgres Helm chart to fail being installed on Windows AKS tests.

**Comment by shubham1172** [comment]
Able to reproduce it on an AKS cluster. The root cause is invalid values being set in the override file.
```
helm upgrade
          --install dapr-postgres bitnami/postgresql \
          --version 12.8.0 \
          -f ./tests/config/postgres_override.yaml \
          --namespace dapr-system \
          --wait \
          --timeout 5m0s 
Release "dapr-postgres" does not exist. Installing it now.
Error: timed out waiting for the condition
helm.go:84: [debug] timed out waiting for the condition
```

Results from `k describe pod dapr-postgres-postgresql-0 -n dapr-system`:

<pre>
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               5m43s                default-scheduler        Successfully assigned dapr-system/dapr-postgres-postgresql-0 to akswinnp000000
  Warning  FailedMount             5m42s                kubelet                  MountVolume.SetUp failed for volume "kube-api-access-8wz64" : chown c:\var\lib\kubelet\pods\a07e3987-d0fc-4c8a-ab0a-0064df0b33de\volumes\kubernetes.io~projected\kube-api-access-8wz64\..2023_08_07_16_36_23.3351872838\token: not supported by windows
  Warning  FailedMount             5m42s                kubelet                  MountVolume.SetUp failed for volume "kube-api-access-8wz64" : chown c:\var\lib\kubelet\pods\a07e3987-d0fc-4c8a-ab0a-0064df0b33de\volumes\kubernetes.io~projected\kube-api-access-8wz64\..2023_08_07_16_36_23.2412019966\token: not supported by windows
  Warning  FailedMount             5m41s                kubelet                  MountVolume.SetUp failed for volume "kube-api-access-8wz64" : chown c:\var\lib\kubelet\pods\a07e3987-d0fc-4c8a-ab0a-0064df0b33de\volumes\kubernetes.io~projected\kube-api-access-8wz64\..2023_08_07_16_36_24.2275594915\token: not supported by windows
  Warning  FailedMount             5m39s                kubelet                  MountVolume.SetUp failed for volume "kube-api-access-8wz64" : chown c:\var\lib\kubelet\pods\a07e3987-d0fc-4c8a-ab0a-0064df0b33de\volumes\kubernetes.io~projected\kube-api-access-8wz64\..2023_08_07_16_36_26.3570437595\token: not supported by windows
  Warning  FailedMount             5m35s                kubelet                  MountVolume.SetUp failed for volume "kube-api-access-8wz64" : chown c:\var\lib\kubelet\pods\a07e3987-d0fc-4c8a-ab0a-0064df0b33de\volumes\kubernetes.io~projected\kube-api-access-8wz64\..2023_08_07_16_36_30.2684002187\token: not supported by windows
  Warning  FailedMount             5m27s                kubelet                  MountVolume.SetUp failed for volume "kube-api-access-8wz64" : chown c:\var\lib\kubelet\pods\a07e3987-d0fc-4c8a-ab0a-0064df0b33de\volumes\kubernetes.io~projected\kube-api-access-8wz64\..2023_08_07_16_36_38.407669271\token: not supported by windows
  Warning  FailedMount             5m10s                kubelet                  MountVolume.SetUp failed for volume "kube-api-access-8wz64" : chown c:\var\lib\kubelet\pods\a07e3987-d0fc-4c8a-ab0a-0064df0b33de\volumes\kubernetes.io~projected\kube-api-access-8wz64\..2023_08_07_16_36_55.2870623688\token: not supported by windows
  Warning  FailedMount             4m38s                kubelet                  MountVolume.SetUp failed for volume "kube-api-access-8wz64" : chown c:\var\lib\kubelet\pods\a07e3987-d0fc-4c8a-ab0a-0064df0b33de\volumes\kubernetes.io~projected\kube-api-access-8wz64\..2023_08_07_16_37_27.3259462580\token: not supported by windows
  Normal   SuccessfulAttachVolume  4m36s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c01eb17e-15e9-4311-942a-64d0785a9f09"
  Warning  FailedMount             3m40s                kubelet                  Unable to attach or mount volumes: unmounted volumes=[kube-api-access-8wz64], unattached volumes=[kube-api-access-8wz64 custom-init-scripts dshm data]: timed out waiting for the condition
  Warning  FailedMount             82s (x3 over 3m34s)  kubelet                  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[kube-api-access-8wz64], unattached volumes=[custom-init-scripts dshm data kube-api-access-8wz64]: timed out waiting for the condition
</pre>
