### ISSUE TITLE
[PubSub] Dapr generates invalid CE envelope

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6801]
⚠️  This ticket is **entirely** predicated on the assumption that my analysis in https://github.com/dapr/docs/issues/3677 is correct - please do not make a decision on this issue until the linked docs issue has been confirmed to be correct.

---

Given the following request : 

```
> POST /v1.0/publish/redis-pubsub/orders HTTP/1.1
> Host: localhost:3501
> User-Agent: insomnia/2023.4.0
> dapr-app-id: myapp3
> Content-Type: application/cloudevents+json
> Accept: */*
> Content-Length: 34

{
	"data": {
		"some": "body"
	}
}
```

Produces the following CE envelope :

```json
{
  "data": {
    "some": "body"
  },
  "pubsubname": "redis-pubsub",
  "source": "Dapr",
  "specversion": "1.0",
  "time": "2023-08-13T19:40:24Z",
  "topic": "orders",
  "traceid": "00-00000000000000000000000000000000-0000000000000000-00",
  "traceparent": "00-00000000000000000000000000000000-0000000000000000-00",
  "tracestate": "",
  "type": "com.dapr.event.sent"
}
```

**Actual behaviour**

The resulting CE envelope (despite Daprs augmentation) is technically invalid according to the CE spec, as the `Id` property is not present (It wasn't provided by me, and it wasn't provided by Dapr)

**Expected behaviour**

The resulting CE envelope should also include a Dapr provided `Id` field, to make the CE envelope valid.

**Comment by berndverst** [comment]
Dapr does not provide CE envelope validation in case of `application/cloudevents+json` payload. Hence cannot reject an event.

Generating an ID could be risky because there is a tiny chance it could clash with IDs provided by the user - Dapr has no knowledge of the user provided ID space.

I suggest cloud event validation is performed prior to sending the request to the Dapr sidecar. Preferably in the SDKs - and ideally by using the Cloud Event SDKs not the Dapr SDKs.

**Comment by olitomlinson** [comment]
> Generating an ID could be risky because there is a tiny chance it could clash with IDs provided by the user - Dapr has no knowledge of the user provided ID space.

A simple GUID/UUID should be sufficient to mitigate this (same as what Dapr does with the auto-generated CE envelop)

**Comment by olitomlinson** [comment]
Pls reopen

**Comment by olitomlinson** [comment]
Pls reopen
