### ISSUE TITLE
Reviewing Placement Metadata table

### ISSUE THREAD

**Issue by JoshVanL** [dapr/dapr#6812]
In [this PR](https://github.com/dapr/dapr/pull/6536), we added support for getting the placement table from the unauthenticated healthz endpoint.

Although this server is enabled only when opted-in by users, it means that unauthenticated users with access to the healthz endpoint now have full access to the placement table. This was not the case before this PR. It is also not clear to users that enabling option may have security implications in that any client with access to that endpoint can discover the entire actor table set, regardless of whether they are a member of the Dapr cluster or not.

I would like to have a larger discussion in `v1.13` about what the security boundaries are in Dapr, what client generated data in Dapr may contain PII/sensitive data or not, and what privacy/security guarantees users can expect. In lieu of this discussion, since it is more difficult to remove features than add features, I am in favor of the project removing having the placement table being available on an unauthenticated endpoint and instead reserve this information for only fully authenticated gRPC clients.

**Comment by artursouza** [comment]
I would like to clarify that the placement table maps actor types to sidecar endpoints (host + port) and DOES NOT contain any Actor Id. So, it contains things like:

ProductActor -> 10.0.0.2:3501 10.0.0.3:3502 10.0.0.4:3505
CreditCardActor -> 10.0.0.2:3501 10.0.0.3:3502

The calculation to map a given actor ID to a sidecar is a local decision of each sidecar based on the list of hosts of a given actor type. Each sidecar keeps a local cache of the placement table.

The reason [that PR](https://github.com/dapr/dapr/pull/6536) was merged is because that does not give access to any actor invocation or disclose PII information (no actor ID is present). The security of Dapr does not rely on hiding Actor Types or IP addresses, we rely on private certificates for that. IMO, Actor Types are part of the exposed API of the app, the same way a service has a document HTTP endpoint. The security comes from certificates and credentials to access those and not from not documenting the endpoint.

**Comment by JoshVanL** [comment]
@artursouza I hear you on Actor _Types_ being equivalent to REST APIs or similar. I do think that this is problematic for trying to achieve a zero trust architecture in Dapr. It also still poses a _privacy_ consideration for users who would like to use a single Dapr cluster in a multi-tenant scenario. A user will not be able to have multiple teams or organizations access to the same Dapr cluster without them being able to discover implementation details (like `CreditCardActor` above) of another. I think that supporting multi-tenant scenarios which have constraints on privacy is a worth while goal.

> The security of Dapr does not rely on hiding Actor Types or IP addresses, we rely on private certificates for that. 
> Regarding privacy, actor types (today) are considered part of the app's exposed API 

I think there is a distinction between privacy and authn/z. While I agree that we rely on crypto for enforcing authenticity of peers, privacy of data is a separate concern. An adversary can get further in an attack by gaining information about the target. I include IP addresses here- I don't think any unauthenticated client on the network should be able to list the IP addresses of all actor apps in the cluster. 

[Currently](https://github.com/dapr/dapr/blob/43bb1abbaa716012cd61f00de010bff80a1abf19/pkg/placement/tables.go#L22) this endpoint is also returning the App ID of all registered actors. I think this must be removed at a minimum.

---

Question: why is only exposing this API on an authenticated endpoint not good enough for now? What is the use case for a client which cannot join the Dapr cluster but must fetch all actor information in the system?

**Comment by artursouza** [comment]
One of the scenarios is for local development and debugging. Knowing which instances are serving a given actor since people do get errors trying to resolve a given actor.

**Comment by JoshVanL** [comment]
@artursouza As a solution we could make a debugging CLI command which calls the gRPC endpoint?
