### ISSUE TITLE
dapr init failed even if docker command is not running as sudo

### ISSUE THREAD

**Issue by yrong** [dapr/dapr#683]
`
For Linux users, if you run your docker cmds with sudo, you need to use "sudo dapr init"
`
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

➜  ~ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

➜  ~ dapr init
⌛  Making the jump to hyperspace...
❌  Error moving dapr binary to path: open /usr/local/bin/daprd: permission denied

## What version of Dapr?
➜  ~ dapr --version
cli version: 0.1.0 
runtime version: n/a%

**Comment by Haishi2016** [comment]
Hi yrong: I don't think this issue has anything to do with how Docker is launched on your machine. The message suggests your current user doesn't have write permission to /usr/loca/bin folder.

**Comment by msfussell** [comment]
we need more info

**Comment by LMWF** [comment]
@yrong - sudo is required to run `dapr init` on Ubuntu because it will copy to /usr/local/bin by default.  If you wish to use an alternative install location (`dapr init --install-path [your path]`) you may not need sudo.

Do you have any special settings or is this running in a particular way (e.g using Windows Subsystem for Linux)?

**Comment by LMWF** [comment]
Closing.

Please reopen if you still need help.
