### ISSUE TITLE
Consider introducing the Entities programming model 

### ISSUE THREAD

**Issue by olitomlinson** [dapr/dapr#6842]
The [Durable Entities](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities) programming model was introduced off the back of Azure Durable Functions.

Now that Dapr supports Workflows (which is the Durable Functions concept reimplemented for Dapr) it seems reasonable to extend Workflows to support the Entities programming model too. A quick chat with subject matter expert Chris G tells me there is no _technical_ blocker to this.

We get *many* folks asking on the Discord Actor channel about how to make Dapr Actors operate like true async Actors (Fire & Forget, rather than blocking callers). [The Actor PubSub proposal is a potential answer to this](https://github.com/dapr/dapr/issues/501) but I'm not so sure, my worry with this approach is that forcing an async layer between Actors (via PubSub) won't fix in the problem, it will just move the problem, in that there still has to be a transition from Async to Sync at the point the Actor method is called, and if that gets bottlenecked, surely that will create noisy neighbours and other undesirable back pressure effects?

However, With the Entities programming model, you still get single threaded execution (like Dapr Actors) but you also get the benefit of real async message passing between Entities, and the DevEx will be first class from day 1.

There are other good things that come from combining Workflows and Entities. Such as [Critical sections](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp#entity-coordination), and various [1-way & 2-way comms between](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp) between Entities and other things, but more on that later...

Thoughts?

**Comment by ItalyPaleAle** [comment]
> We get many folks asking on the Discord Actor channel about how to make Dapr Actors operate like true async Actors (Fire & Forget, rather than blocking callers)

Have you considered using actor reminders as the way to perform a "fire and forget"? This is also what Workflow uses internally.

**Comment by olitomlinson** [comment]
> Have you considered using actor reminders as the way to perform a "fire and forget"? This is also what Workflow uses internally.

On Discord we get many folks asking about fire and forget, and I nearly always suggesting a Reminder, as you've described.

However this still causes problems (while the reminder is processing, the Actor can't receive new work / methods are blocked)

Dapr Actors need to support async message passing natively IMO. 

However at this point, one should consider if its worth introducing the Durable Entities programming model instead, rather than trying to rearchitect Dapr actors to support async message passing.

**Comment by ItalyPaleAle** [comment]
> However this still causes problems (while the reminder is processing, the Actor can't receive new work / methods are blocked)

Yes, this is how actors work. Is this not what you wanted?

**Comment by olitomlinson** [comment]
> Yes, this is how actors work. Is this not what you wanted?

I'm not an expert, but In traditional Actor models, communicating to actors is typically done with non-blocking async message passing. 

This is why so many people ask for Fire and Forget support for Dapr Actors.

The problem with Dapr Actors (which has been inherited from Service Fabric actors) is that they block callers when calling them.

**Comment by ItalyPaleAle** [comment]
So:

- Actors in Dapr are single-threaded, so they can only process one message at a time (invocation, reminder, or timer).
- Scheduling of reminders/timers can be done outside of an actor (_although, thinking about it, I don't believe our SDKs support that today_), as long as you're making the call to a sidecar that is an actor host for the given actor type
- The idea is that if you want to do a "fire and forget", rather than invoking the actor, you create a reminder (with "0s" as execution time). The call to create the reminder will return right away, and the actor will be invoked asynchronously from the reminder.

**Comment by AndyPook** [comment]
yep all true (in terms of how dapr does things)

An Actor is not really an Actor if it is not "single threaded". The whole point is to remove the need to think about concurrency.
But there are several ways of handling this.
In dapr it is (kind of) like a single threaded Controller (a group of methods with a big fat lock around them). Call a method, everyone else has to wait until the call finishes.

In many other Actor systems the Actor is more like a consumer of a Q. Callers just put messages on that Q. Which is non-blocking. The Actor consumes these one at a time. (ie multi writer, single reader)
The Q is generally called a mailbox.

As others have said... Messaging, not RPC.

Using Reminders is a hack to simulate that mailbox behaviour.
Does having multiple callers creating "0" reminders actually behave the same way? (ie like a durable Q)
Probably? 

It's really not nice. It's a hack.
The semantics are weird and make it harder to reason about "how the system works"

**Comment by olitomlinson** [comment]
> - Scheduling of reminders/timers can be done outside of an actor (although, thinking about it, I don't believe our SDKs support that today), as long as you're making the call to a sidecar that is an actor host for the given actor type

Yeah, I don't think the Reminders/Timers is exposed in the SDKs.

So if I'm understanding what you're saying, calling the Timer/Reminder API directly (via HTTP) is always possible and not blocked, regardless of if the Actor is idle or doing work (executing a reminder/timer or invoke) ?

Although that may be a good solution from a technical perspective, this would leave the Developer Experience much to be desired. Ideally, a developer should just be able to use the existing `Invoke` SDK methods to do this and not have directly interface with Reminders/Timers.

**Comment by ItalyPaleAle** [comment]
> Does having multiple callers creating "0" reminders actually behave the same way? (ie like a durable Q) Probably?

Perf issues aside (we're working on them), no, you can register as many reminders with "0" deadline as you want, as long as their name is different.

Another trick is to make the reminders repeating, so if the processing fails, they are retried automatically. When the processing is successful, the handler can return a message indicating that the repeating reminder is to be dropped

> So if I'm understanding what you're saying, calling the Timer/Reminder API directly (via HTTP) is always possible and not blocked, regardless of if the Actor is idle or doing work (executing a reminder/timer or invoke) ?

Yes:

- It's always possible to ask a Dapr sidecar (via HTTP/gRPC) to register a reminder for an actor
- That operation is performed by the sidecar _without_ invoking the actor, so it works even if the actor is locked
- However, this must be done in a sidecar that is currently hosting actors of the given type. So, it must be done in a sidecar that is an actor host (not just actor client) and which is hosting actors of the type that the reminder is to be executed on.
- It's not really something we document, but it does work, and we have tests for that behavior.

> It's really not nice. It's a hack. The semantics are weird and make it harder to reason about "how the system works"

Also:

> Although that may be a good solution from a technical perspective, this would leave the Developer Experience much to be desired. Ideally, a developer should just be able to use the existing Invoke SDK methods to do this and not have directly interface with Reminders/Timers.

I would agree with you. However, any messaging solution we implement would likely be based on this, since it does work. Perhaps what we need to do is just to wrap this "trick" into a nicer API that users can consume without having to worry about these concerns.

**Comment by ItalyPaleAle** [comment]
I have a design proposal here: https://github.com/dapr/dapr/issues/7122
