### ISSUE TITLE
Security Attributes for DAPR Operator - Sentry - Sidecar Injector

### ISSUE THREAD

**Issue by 3rk1n** [dapr/dapr#6847]
Hi,

I want to close security recommendations for Kubernetes Cluster in Microsoft Defender for Cloud.

One of them is "**Kubernetes clusters should disable automounting API credentials**" and it can be solved by added "`automountServiceAccountToken: false`" for _POD security_ "**spec** --> **template** --> **spec**"

```
spec:
  template:
    metadata:
    spec:
      automountServiceAccountToken: false
```

But when I am adding this value for the operator, sentry and sidecar injector, the pods give me **CrashLoopBackOff** status and that logs in below.

I try to add "**volumes:**" and "**volumeMounts:**" but there is nothing change for sentry and sidecar injector.
I try to add "**env:**" but there is nothing change for operator

How can I solve this?

**DAPR Operator** logs

```
level=info msg="log level set to: info" instance=dapr-operator-6f879fbff6-clhsr scope=dapr.operator type=log ver=1.10.8
level=info msg="metrics server started on :9090/" instance=dapr-operator-6f879fbff6-clhsr scope=dapr.metrics type=log ver=1.10.8
level=info msg="starting Dapr Operator -- version 1.10.8 -- commit e59b71de19bcb0625a3c7d1e8388c81742fdca42" instance=dapr-operator-6f879fbff6-clhsr scope=dapr.operator type=log ver=1.10.8
level=fatal msg="Unable to get controller runtime configuration, err: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable" instance=dapr-operator-6f879fbff6-clhsr scope=dapr.operator type=log ver=1.10.8
```

**DAPR Sentry** logs

```
level=info msg="starting sentry certificate authority -- version 1.10.8 -- commit e59b71de19bcb0625a3c7d1e8388c81742fdca42" instance=dapr-sentry-67d6ff6d46-qqv56 scope=dapr.sentry type=log ver=1.10.8
level=info msg="log level set to: info" instance=dapr-sentry-67d6ff6d46-qqv56 scope=dapr.sentry type=log ver=1.10.8
level=info msg="metrics server started on :9090/" instance=dapr-sentry-67d6ff6d46-qqv56 scope=dapr.metrics type=log ver=1.10.8
panic: stat /home/nonroot/.kube/config: no such file or directory

goroutine 1 [running]:
github.com/dapr/dapr/utils.GetConfig()
        /home/runner/work/dapr/dapr/utils/utils.go:54 +0x85
github.com/dapr/dapr/pkg/sentry/config.getKubernetesConfig({0x1af7f28, 0xa})
        /home/runner/work/dapr/dapr/pkg/sentry/config/config.go:105 +0xc8
github.com/dapr/dapr/pkg/sentry/config.FromConfigName({0x1af7f28, 0xa})
        /home/runner/work/dapr/dapr/pkg/sentry/config/config.go:70 +0xf2
main.main()
        /home/runner/work/dapr/dapr/cmd/sentry/main.go:103 +0xacf
```

**DAPR Sidecar Injector** logs

```
level=info msg="log level set to: info" instance=dapr-sidecar-injector-76c494c55f-kmghh scope=dapr.injector type=log ver=1.10.8
level=info msg="metrics server started on :9090/" instance=dapr-sidecar-injector-76c494c55f-kmghh scope=dapr.metrics type=log ver=1.10.8
level=info msg="starting Dapr Sidecar Injector -- version 1.10.8 -- commit e59b71de19bcb0625a3c7d1e8388c81742fdca42" instance=dapr-sidecar-injector-76c494c55f-kmghh scope=dapr.injector type=log ver=1.10.8
panic: stat /home/nonroot/.kube/config: no such file or directory

goroutine 1 [running]:
github.com/dapr/dapr/utils.GetConfig()
        /home/runner/work/dapr/dapr/utils/utils.go:54 +0x85
github.com/dapr/dapr/utils.initKubeConfig()
        /home/runner/work/dapr/dapr/utils/utils.go:36 +0x1d
github.com/dapr/dapr/utils.GetKubeClient(...)
        /home/runner/work/dapr/dapr/utils/utils.go:64
main.main()
        /home/runner/work/dapr/dapr/cmd/injector/main.go:48 +0x296
```

**Comment by JoshVanL** [comment]
The security policy `automountServiceAccountToken: false` is generally a great default to have for your deployments in Kubernetes as it means every workload won't have access to the Kubernetes API server by default, limiting blast radius due to a container file system leak or malicious access to a pod. However, this _must_ be enabled on deployments which _do_ intend to access the Kubernetes API server, because without it, they have no way to authenticate to the API server. This is why you are seeing the error you are.
 The operator, sentry, and sidecar injector all require this setting to be true for this reason. It is also the case that the Dapr sidecars must also have this setting if you intend to use the Kubernetes API server as part of a component, like the Kubernetes Secret store for example https://docs.dapr.io/reference/components-reference/supported-secret-stores/kubernetes-secret-store/


I am going to close this as this is “working as expected”, but please feel free to reopen if you have any more questions 🙂
