### ISSUE TITLE
Enhanced Tracing for Workflows via Python SDK

### ISSUE THREAD

**Issue by cchanley2003** [dapr/dapr#6906]
## In what area(s)?

 /area runtime

## Describe the feature
Would like to enhance the existing tracing for workflows with two main additions:

1. Be able to add attributes to existing activity spans. For instance add the name of the pod that executed the activity
2. Add child spans to the activity span.  If the activity interacts s3 for instance we would like to capture that as a sub-span.

Seems like the WorkflowActivityContext in the python sdk would be an obvious place to add that additional info.

**Comment by cgillum** [comment]
Thanks @cchanley2003 for this suggestion. You mentioned wanting to do this in Python - can you expand on your feature description by providing some sample code that illustrates what it might look like to add new attributes to existing spans? That would help further clarify things for us.

**Comment by cchanley2003** [comment]
So ideally this would be an example: 
```
def model_properties(ctx: WorkflowActivityContext, input):
  ctx.span.set_attribute("pod_name", os.getenv("POD_NAME")
  tracer = trace.get_tracer(__name__)

  # Start a child span using the parent span object
  with tracer.start_as_current_span("child-span", parent=ctx.span) as child_span:
    # talk to s3
```

**Comment by cgillum** [comment]
I think this is a good proposal that would greatly improve the tracing/diagnostics story for workflows. We would ideally do this for each SDK. In terms of runtime changes, I think we'll need to update the gRPC protocol used by `durabletask-go` to flow the distributed trace information as part of orchestration and activity work items so that the workflow SDKs can pick them up.

/cc @rabollin
