### ISSUE TITLE
[Release Enhancement] GHA Workflows to Update Versions Automatically

### ISSUE THREAD

**Issue by cicoyle** [dapr/dapr#6956]
It would be nice to have an automated process that listens for a new tag to be pushed to the `dapr/kit` repo && `dapr/components-contrib` that updates the `go.mod` version accordingly so we are always up to date on changes and can automate our release candidate testing. This should be automated to minimize the manual steps in the release process.

I propose adding a GitHub Action Workflow to `dapr/dapr` that listens for a new tag on the `dapr/kit` repo && `dapr/components-contrib` and auto creates a Pull Request that updates that line in the `go.mod` file and other relevant changes (`go.sum`) as a result of `go mod tidy`.

**Comment by mukundansundar** [comment]
I agree that this has to be only for RCs and release tags though, since normal master versions might contain breaking changes which will need a manual intervention. We ideally should not have a breaking change during tag cuts in dapr/kit or dapr/components-contrib. That should be handled before the tag creation by updating dapr with the right master versions of components-contrib and kit.
