### ISSUE TITLE
Add capability to configure pubsub CloudEvent fields in an Outbox pattern.

### ISSUE THREAD

**Issue by GFlisch** [dapr/dapr#7048]
## In what area(s)?

/area runtime

Outbox Pattern.

## Describe the feature
Add the capability to configure the CloudEvent values in the PubSub event published like with pubsub.

I propose to do this via the metadata by adding the cloudevent.x and pass them from the state store to the pubsub component like:

await _dapr.ExecuteStateTransactionAsync("contract-outbox", requests, cancellationToken: cancellationToken, metadata: new Dictionary<string, string> { { "cloudevent.type", "licmanager.contract.company.created" } }).ConfigureAwait(false);

**Comment by olitomlinson** [comment]
+1 for this.

I would be inclined to use an `outbox.` prefix on the metadata, such as `outbox.cloudevent.type`

Reason being so that the state store implementation knows exactly what metadata headers it needs to forward on to the PubSub metadata, i.e. anything that begins with `outbox.*` (Otherwise it has to forward everything, which may end up capturing state store metadata that do not apply to PubSub)

**Comment by GFlisch** [comment]
Yes, agree with you. After adding the enhancement I had the same idea to avoid confusion.

I am more in favor of pubsub than outbox because we are providing settings for the pubsub part and we never know what Dapr will invent for the outbox pattern 😏 in the future by adding another components. It could be also a standard regarding component composing with other components...
