### ISSUE TITLE
daprd:1.12.0 Fails to Retrieve the Initial Identity Certificate due to SENTRY_LOCAL_IDENTITY length > 64 characters

### ISSUE THREAD

**Issue by a-shoemaker** [dapr/dapr#7078]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.12.0

## Expected Behavior

Ability to use dapr version 1.12 when SENTRY_LOCAL_IDENTITY is greater than 64 characters in length.

Sentry should be making adjustments to the request ID to turn it into an app ID before validating or alternatively adjust validation knowing of this possibility.  Potentially should change the code so the SignCertificateRequest always provides the app ID as the request's Id.

## Actual Behavior

daprd fails to startup when the SENTRY_LOCAL_IDENTITY is greater than 64 characters in length.

```
time="2023-10-22T14:55:46.984217502Z" level=fatal msg="Fatal error from runtime: failed to retrieve the initial identity certificate: error from sentry SignCertificate: rpc error: code = PermissionDenied desc = invalid request: app ID must be 64 characters or less" app_id={app ID} instance={instance name} scope=dapr.runtime type=log ver=1.12.0
```

## Steps to Reproduce the Problem

Upgrade to dapr 1.12.0 and restart a deployment with a SENTRY_LOCAL_IDENTITY (namespace + service account name) greater than 64 characters in length.

x509source.go provides ID as SENTRY_LOCAL_IDENTITY in requestFromSentry.  In pkg/sentry/server/validator/kubernetes/kuberentes.go validates the request at the beginning of Validate, which checks that the request Id is <= 64 characters, assuming it's the app ID.  Later in the method, it changes the request Id to the app ID when it was provided in the form of the SENTRY_LOCAL_IDENTITY:
```
	// TODO: @joshvanl: Before v1.12, the injector instructed daprd to request
	// for the ID containing their namespace and service account (ns:sa). This
	// is wrong- dapr identities are based on daprd namespace + _app ID_.
	// Remove this allowance in v1.13.
	if req.Namespace+":"+pod.Spec.ServiceAccountName == req.Id {
		req.Id = expID
	}
```

## Release Note

RELEASE NOTE:

**Comment by JoshVanL** [comment]
To add a little bit more context from the the other issue: https://github.com/dapr/dapr/issues/7079

In [1.12](https://github.com/dapr/dapr/pull/6171/files#diff-55f40c1a9290a2f2fd78c25e5c7e8962f95132359cfc61fed88a76bfbda41c73R47) we added a check to the sentry auth server that intended to ensure requested app IDs are no longer than 64 characters. The issue however is that sentry also accepts requests from Daprd's who set their ID as the requesting Pod's <namespace>:<service account> which can be a valid maximum of 507 characters in length (253 is the maximum Kubernetes object name length, plus the : character).

We need to update sentry to account for this discrepancy by both ensuring app IDs conform to the 64 character limit, whilst still allowing the "legacy" <namespace>:<service account> identifier.

This bug needs to be backported to 1.12 release. This issue does not affect 1.11.

This is not a security vulnerability as the bad state "fails closed" whereby users cannot deploy Dapr applications with sufficiently large namespace/service account names, rather than Daprd's being issued incorrect identities etc.
