### ISSUE TITLE
Hi, I'm new here, so just wanted to know that how can i apply for Dapr badges on holopin?

### ISSUE THREAD

**Issue by iprattham** [dapr/dapr#7107]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

**Comment by mikeee** [comment]
Hey, I'm not sure there are any attainable badges at the moment other than the one set up for the Grace Hooper Celebration - even then I'm not sure how that was attained.

No doubt there will be plenty of opportunities for you to grab badges by contributing coming soon - I see a community supporter badge already added since I last checked.

**Comment by cicoyle** [comment]
Hey @iprattham, The Holopin Dapr Community Supporter badge link can be found in the Dapr Discord, [in the general channel here](https://discord.com/channels/778680217417809931/778680217417809934/1169344816832843786).

**Comment by LenStaley** [comment]
Welcome :)
