### ISSUE TITLE
Outbox message should be in the Cloudevent format

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#7113]
## In what area(s)?
/state

## What version of Dapr?
v1.12

## Expected Behavior
Not in cloud format structure. 

## Actual Behavior
When receiving a message from the outbox it is wrapped in an additional "data" structure like this.

```
{
  "data": {
    "data": "{\"orderId\":1}",
    "datacontenttype": "text/plain",
    "id": "outbox-3bce7f67-4b6b-4745-8eef-57204ae85a70",
    "pubsubname": "orderpubsub",
    "source": "order-processor",
    "specversion": "1.0",
    "time": "2023-10-29T17:12:51-07:00",
    "topic": "",
    "traceid": "",
    "traceparent": "",
    "tracestate": "",
    "type": "com.dapr.event.sent"
  }
}
```

This also prevents this code in the .NET SDK from running. 
// Dapr will send serialized event object vs. being raw CloudEvent
//app.UseCloudEvents();

Additionally there are several empty fields in the message example above that either need to be completed with content or removed. Topic IMO should be included.
```
    "topic": "",
    "traceid": "",
    "traceparent": "",
    "tracestate": "",
```

## Steps to Reproduce the Problem
See sample here https://github.com/msfussell/samples/tree/outbox/outbox

## Release Note
RELEASE NOTE: **FIX** Bug in runtime preventing outbox messages as cloudevent

**Comment by olitomlinson** [comment]
Just tested this using 1.12 and my payload doesn't have the additional `data` wrapper. I've taken this payload straight from Kafka UI :

```json
{
	"data": "map[data:map[some:body2]]",
	"datacontenttype": "text/plain",
	"id": "d6918f0f-556a-4769-8849-8133ab59bab7",
	"pubsubname": "kafka-pubsub",
	"source": "workflow-a",
	"specversion": "1.0",
	"time": "2023-11-11T21:42:31Z",
	"topic": "outbox",
	"traceid": "",
	"traceparent": "",
	"tracestate": "",
	"type": "com.dapr.event.sent"
}
```

**Comment by GaTechThomas** [comment]
This seems to be related to or same as #7047.

**Comment by BADF00D** [comment]
This issue was closed last year, but I still have the error: 
Steps to reproduce:

- open outbox folder from [samples repository](https://github.com/dapr/samples.git): ``samples\outbox\``
- remove ``samples\outbox\resources\statestoresql.yaml``
- upgrade packages in both projects to use dapr version 1.15.2
- run ``dapr run -f .``
- connect to the redis db

![Image](https://github.com/user-attachments/assets/b8cfeafd-59f8-471c-b955-3c64366c9c83)

```json
{
  "data": "{\"orderId\":2}",
  "datacontenttype": "text/plain",
  "id": "outbox-38b21821-de9a-4454-8532-9c31f0a23168",
  "pubsubname": "orderpubsub",
  "source": "order-processor",
  "specversion": "1.0",
  "time": "2025-03-27T08:39:17+01:00",
  "topic": "orders",
  "traceid": "00-03fd76d59cb8663d8d131c5d2e0dfc66-a8a90350f3b22316-01",
  "traceparent": "",
  "tracestate": "",
  "type": "com.dapr.event.sent"
}
```
Problems:

- The ``data`` property should contain a valid json, not a serialized json. 
- The ``datacontenttype`` property should be ``application/json``

Even when I pass metadata, to correct the ``datacontenttype``, I still get an serialized json in the data property

```csharp
new(orderId.ToString(), bytes, StateOperationType.Upsert, metadata: new Dictionary<string, string>
        {
            ["datacontenttype"] = "application/json",//I thougt this should be cloudevent.datacontenttype, but only this works
        })
```

![Image](https://github.com/user-attachments/assets/57a73915-3f44-481d-adb3-8969ced688ef)

```json
{
  "data": "{\"orderId\":2}",
  "datacontenttype": "application/json",
  "id": "outbox-cf87e681-3a69-4df0-8e60-c6a051038fea",
  "pubsubname": "orderpubsub",
  "source": "order-processor",
  "specversion": "1.0",
  "time": "2025-03-27T08:45:20+01:00",
  "topic": "orders",
  "traceid": "00-0d74c1aabce6fe7f5053096c86fa953f-00c5f5359f9b4891-01",
  "traceparent": "",
  "tracestate": "",
  "type": "com.dapr.event.sent"
}
```
What am I doing wrong? How can I save the order as json?

**Comment by BADF00D** [comment]
I did some more investigation. When I POST my request directly to the HTTP endpoint of my sidecar, I was able to successfully deliver my event (with correct data property) to the target app.
```json
POST http://localhost:63710/v1.0/state/statestore/transaction
{
  "operations": [
    {
      "operation": "upsert",
      "request": {
        "key": "order1",
        "value": {
            "orderId": "7hf8374s",
            "type": "book",
            "name": "The name of the wind"
        }
      }
    },
    {
      "operation": "upsert",
      "request": {
        "key": "order1",
        "value": {
            "orderId": "7hf8374s",
            "name": "test"
        },
        "metadata": {
           "outbox.projection": "true"
        },
        "contentType": "application/json"
      }
    }
  ]
}
```
Results in
```json
{
  "data": { "name": "test", "orderId": "7hf8374s" },
  "datacontenttype": "application/json",
  "id": "outbox-8c2616de-e69f-419e-b3d6-bb5213ec02df",
  "pubsubname": "orderpubsub",
  "source": "order-processor",
  "specversion": "1.0",
  "time": "2025-03-28T09:03:02+01:00",
  "topic": "orders",
  "traceid": "00-1c136139bef16fbaa7f28ff4517ee44c-33047d41b89cae04-01",
  "traceparent": "",
  "tracestate": "",
  "type": "com.dapr.event.sent"
}
```

So it looks like the problem lies within the C# client. The only problem with my hack is, that I don't know how to retrieve the dynamic port of my sidecar at runtime.

**Comment by WhitWaldo** [comment]
@BADF00D I'm the maintainer of the Dapr .NET SDK. 

It's not clear to me what the issue is that you're reporting.

> The data property should contain a valid json, not a serialized json.
I don't follow. Valid JSON is serialized data. Are you saying that if you're taking data you've already serialized to JSON and encoded into (presumably) UTF-8 bytes, you're finding that it's re-serializing the data so that when you deserialize it downstream, it's not working properly?
 
> The datacontenttype property should be application/json
Just as if you did `Encoding.UTF8.GetBytes("abc123");` or pass in pre-encoded bytes, the SDK has no trivial way to discern what the format of the bytes are to set a more appropriate `datacontenttype` value. Rather, it's up to you to override the value yourself in the metadata argument:
```cs
var metadata = new Dictionary<string, string>
{
  {"cloudevent.datacontenttype", "application/json"}
}();
```

**Comment by WhitWaldo** [comment]
I think what you're expecting of the CloudEvent payload isn't accurate. Reading the [specification](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md) and observing the example at the end, all values are represented as strings, not as arbitrary JSON-compatible values. 

As such, I would expect that the `data` property in the CloudEvents message would embody a JSON string precisely as it's doing. When you parse the `datacontenttype` and observe that the string represents a JSON value, you can then parse, unescape and deserialize accordingly, but if this were an open ended value, and not a strong, I can see how that might be awfully difficult to parse from a JSON perspective when encoding non-JSON data.

**Comment by BADF00D** [comment]
@WhitWaldo ,
I just read about [Event data](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#event-data) and the [data section](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#data) in general. Unfortunately, the way I read these sections, they don't specify exactly what should be in Data.

Given that your your right, then I have two other question:
Why does ``await client.PublishEventAsync("orderpubsub", "orders", new Order(1000));`` produce
```json
{
  "data": { "orderId": 1000 },
  "datacontenttype": "application/json",
  "id": "9eab46c7-8a6f-41d0-93ee-d1a70d42323c",
  "pubsubname": "orderpubsub",
  "source": "order-processor",
  "specversion": "1.0",
  "time": "2025-03-31T07:14:38+02:00",
  "topic": "orders",
  "traceid": "00-35475e7f8f0d097a1333838d06961c73-fc6a0d2ded4277b5-01",
  "traceparent": "00-35475e7f8f0d097a1333838d06961c73-fc6a0d2ded4277b5-01",
  "tracestate": "",
  "type": "com.dapr.event.sent"
}
```
And why does ``app.UseCloudEvents`` on the client side unpack event published via ``client.PublishEventAsync``, but throws an exception if I use the state store. Shouldn't both API (``PublishEventAsync`` and ``ExecuteStateTransactionAsync``) produce the same event?

**Comment by WhitWaldo** [comment]
@BADF00D It definitely could be clearer, so I'm leaning heavily on the example given that shows an XML value escaped and placed in a string. This avenue make sense to me as applied to JSON since it clearly defines where the boundaries of the data payload start and stop in a way that an object wouldn't (especially a non-JSON value like XML or even binary values). 

Here I read the spec in the [Types section](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#type-system) to articulate that binary would be expected to be in a base64 encoding precisely because it can be readily stored in a string and perhaps it's just an oversight of the specification not to more clearly articulate that _all_ values are expected to be stored in a string. I have only this vague language to rely on:
> This specification defines a canonical string-encoding for each type that MUST be supported by all implementations.

With regards to your question regarding the .NET SDK, that's an excellent question and I'd say that not only was that code written before I became a maintainer, I don't know that the author is around any longer to even ask how they interpret the spec. Given my reading of it (and how it's how I've been implementing it), I would categorize this as a bug (going to file this issue in a few) and will ask around to validate my reading.

In theory yes. In practice, the two were written at very different points in time and the SDK has seen.. quite a lot in terms of serialization choices over time. To this end, I'm working as part of this next release to split out existing functionality from `Dapr.Client` into block-specific NuGet packages and clean this up a bit. To that end, I'd certainly appreciate any thoughts you have on a [draft POC](https://github.com/dapr/dotnet-sdk/pull/1378) I put together and have been soliciting comments on to improve the serialization approach in the .NET SDKs. I'll likely drop the validation aspect of that approach in practice, but I would like to make all serialization, encoding, and optional compression and encryption done via an entirely pluggable and consistent approach across all Dapr SDKs rather than the inconsistent approach taken today, as you've noted. And if you've got any additional thoughts on it, please don't hesitate to reach out to me over PM on Discord (my username is Xaniff) or ping me in any of the [Dapr Discord](http://bit.ly/dapr-discord) channels.

**Comment by BADF00D** [comment]
@WhitWaldo,
At first I thought you had a point, as the enumeration under Type System does not actually mention a JSON object. However, I found a few other sections that make me doubt this.

First, the [Type System](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#type-system) section is a section under [Context Attributes](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#context-attributes), which I believe describe the top-level attributes of the CloudEvent. The Data attribute is not named here.

Secondly, the following is written about the ``datacontenttype`` attribute in the spec

> In some event formats the datacontenttype attribute MAY be omitted. For example, if a JSON format event has no datacontenttype attribute, then it is implied that the data is a JSON value conforming to the “application/json” media type. In other words: a JSON format event with no datacontenttype is exactly equivalent to one with datacontenttype=“application/json”.

For me, this means that data is a JSON value by default. [RFC-8259](https://www.rfc-editor.org/rfc/rfc8259#section-3): 

> A JSON value MUST be an object, an array, a number or a string, or one of the following three literal names ...

Third: The Payload Serialization section distinguishes between two variants: data can be something binary, or a Json value:

> If the datacontenttype declares the data to contain JSON-formatted content, a JSON serializer MUST translate the data value to a [JSON value](https://tools.ietf.org/html/rfc7159#section-3), and use the member name data to store it inside the JSON representation. The data value MUST be stored directly as a JSON value, rather than as an encoded JSON document represented as a string. An implementation MAY fail to serialize the event if it is unable to translate the runtime value to a JSON value.

Is the sentence, 

> The data value MUST be stored directly as a JSON value, rather than as an encoded JSON document represented as a string.

not the exact opposite of what is happening in the transaction API?
