### ISSUE TITLE
Change the name to avoid conflicting with Dapper

### ISSUE THREAD

**Issue by LarsKemmann** [dapr/dapr#715]
## Describe the proposal
Because of [Dapper's](https://github.com/StackExchange/Dapper) widespread use and name recognition, "dapr" is a problematic naming choice for this project.

Since Dapr is currently just an (admittedly clever) acronym of "Distributed APplication Runtime", it seems like there's room to be creative and come up with something new. :)

**Comment by yaron2** [comment]
Hi Lars,

Name changing was not even brought up by the founders of Dapper, and in all honesty, we have had zero feedbacks over the name in the past week and half.

Also, we've witnessed no actual conflicts out there.. as in, not a single one.

Considering the above, I suggest to not delve deeper on this.

**Comment by LarsKemmann** [comment]
Hi @yaron2 -- thanks for the quick reply!

You mean zero aside from [this feedback](https://channel9.msdn.com/Shows/Azure-Friday/Learn-all-about-Distributed-Application-Runtime-Dapr-Part-1#c637076226927937270)?

**Comment by yaron2** [comment]
Yep.

**Comment by LarsKemmann** [comment]
Yeah -- seeing that comment was actually the reason I felt I wasn't crazy and posted this.

It's not that you've got a hard conflict of some kind, but you just don't have the unique name recognition that you might otherwise have. Just a thought. Naming is hard and on top of being hard, it doesn't happen in a vacuum. :)

**Comment by lukekim** [comment]
Hi @LarsKemmann - thanks for the comment.

You raise a valid issue, which is why we met with the Dapper team to resolve this. We jointly decided to address this by adding banners to our site to direct people who are looking for the Dapper project and not changing the name.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/80174/67896999-bbcce680-fb1a-11e9-96ff-079c0bd9d842.png">

Thanks!

**Comment by ShawnMcGough** [comment]
My two cents - it is a clever but poor name choice. 

Since the announcement last week, I've brought _dapr_ up in conversation a few times and every single time the person thought I was talking about the Dapper ORM. Maybe it is just in the 'dot net world', but the pronunciation of 'dapper' will always mean Dapper ORM (Dapper ORM currently has 28,973,495 total downloads on NuGet). 

It's not a poor choice because of conflicts, it is a poor choice because of _name recognition_. A banner will not fix that.

More time and consideration should be given to this issue - citing 'zero feedback' only _**4 days**_ after public announcement is a bit premature. After all, community feedback was specifically requested. I suspect other members of the community will have the same concern as the learn about _dapr_.

**Comment by yaron2** [comment]
> always mean

That's a very bold saying, and in my opinion, very much a point in time thing. Lets bring this up again a year from now :)

I am being completely honest here, we're getting amazing feedback from the cloud native community, besides a post here and there by dotnet people, this doesn't come up.

**Comment by ShawnMcGough** [comment]
Fair enough. Like I said, just adding my feedback. It sounds like we at least agree that it is a concern coming from the dotnet group. 

I'll check back on this issue in a year and see how it played out. Maybe at that time Dapper ORM will have a banner on _their_ site asking "Looking for Dapr?" 😁

**Comment by yaron2** [comment]
> Maybe at that time Dapper ORM will have a banner on their site asking "Looking for Dapr?"

Per my understanding, this is coming.

**Comment by ardalis** [comment]
News to me that dapr isn't just some clever way of shortening the micro-ORM dapper. And of course impossible to distinguish when heard. But yeah, it's too bad we ran out of other ways to arrange syllables to make sounds that weren't already taken by popular open source projects.

**Comment by sigpop** [comment]
> News to me that dapr isn't just some clever way of shortening the micro-ORM dapper. And of course impossible to distinguish when heard. But yeah, it's too bad we ran out of other ways to arrange syllables to make sounds that weren't already taken by popular open source projects.

Well, it's been a year-ish, and I just saw DAPR on the Msft Microservice conference at the end of July and was wondering how the micro-ORM fit into Microservices other than they both start with the prefix "micro".  Then I remembered the goofy naming choice...Msft has always struggled with naming their stuff.

**Comment by Sigi-os** [comment]
I'm very surprised of the stubbornness of that team to not change the name to something that's all their own. Maybe I should create a browser search called Gooogle and a software company called MyCrowSoft.  Unless you are trying to use Dapper's success - the confusion will create traffic and then maybe people looking for Dapper will read about Dapr, I don't get it?  Why make a name where a banner is needed on anyone's page?   I would think marketing would want to make sure your project is recognizable as your product.  

Honestly, this may cost a developer time (a sprint) if he has a research spike and researches the wrong tool (Dapper instead of Dapr or vice versa), or he may move away from the Dapr tool because he researches Dapper instead of Dapr and says - nope that's not what I need and may never look at Dapr again.  Honestly after seeing the microsoft presentation, I had to do such research - has Dapper rebranded, changed its name due to litigation, is now owned by Microsoft...Anyway, that's my two cents.  Good luck.
