### ISSUE TITLE
error creating/deleting actor reminder: error saving reminders partition and metadata: transaction failed due to operation 0/1 which failed with status code 412

### ISSUE THREAD

**Issue by anna-jankowska** [dapr/dapr#7162]
## In what area(s)?

 /area runtime

## What version of Dapr?

 1.11.4

## Expected Behavior

We used version 1.10.5 earlier and reminders were working as expected.

## Actual Behavior

After update to the version 1.11.4 we observe 4 errors:

- error deleting actor reminder: error saving reminders partition and metadata: transaction failed due to operation 0 which failed with status code 412
- error creating actor reminder: error storing reminder: error saving reminders partition and metadata: transaction failed due to operation 0 which failed with status code 412
- error deleting actor reminder: error saving reminders partition and metadata: transaction failed due to operation 1 which failed with status code 412
- error creating actor reminder: error storing reminder: error saving reminders partition and metadata: transaction failed due to operation 1 which failed with status code 412

## Steps to Reproduce the Problem

We're using dapr upstream version on AKS (k8s version 1.25.11) and cosmos db as a state store. We're observing the problems with creating and removing reminders, data stored in cosmos-db seems to suggest everything is stored in single partition now:

We see debug message in logs:
`starting to read reminders for actor type AppSessionActor-qa (migrate=false), with metadata id 00000000-0000-0000-0000-000000000000`

```
"id": "actors||AppSessionActor-prod||metadata",
        "value": {
            "id": "00000000-0000-0000-0000-000000000000",
            "actorRemindersMetadata": {
                "partitionCount": 0
            }
        },
```

This is contradictory to the configuration in the code:
```
    // Configure default settings
    actorRuntimeOptions.ActorIdleTimeout = TimeSpan.FromMinutes(10);
    actorRuntimeOptions.ActorScanInterval = TimeSpan.FromSeconds(30);
    actorRuntimeOptions.DrainOngoingCallTimeout = TimeSpan.FromSeconds(60);
    actorRuntimeOptions.DrainRebalancedActors = true;
    actorRuntimeOptions.RemindersStoragePartitions = 7;
    actorRuntimeOptions.ReentrancyConfig = new()
    {
        Enabled = true,
        MaxStackDepth = 10
    };
```

None of these were changed ever, the problem started with the dapr update 1.10.5 -> 1.11.4

## Release Note

RELEASE NOTE: **FIX** Fixed errors creating and deleting reminders

RELEASE NOTE:

**Comment by berndverst** [comment]
Unfortunately Dapr 1.10.X releases prior to 1.10.8 had a variety of actor reminder related problems. In particular 1.10.5 which you are using caused a variety of problems and resulted in some corrupt actor reminder data. This was fixed in 1.10.6 but an issue for MongoDB remained which was not fixed until 1.10.8.

I strongly encourage you to first upgrade to the latest 1.10.X release 1.10.9 at this time.

If you experience errors related to actor reminders then unfortunately this actor reminder data will need to be deleted as it is stored in a way that cannot be recovered.

Once all is good with 1.10.9 feel free to proceed to upgrade to the latest 1.11.X or 1.12.X release.

See:
https://github.com/dapr/dapr/releases/tag/v1.10.5
https://github.com/dapr/dapr/releases/tag/v1.10.6
https://github.com/dapr/dapr/releases/tag/v1.10.8

**Comment by berndverst** [comment]
As an aside, the 412 error from CosmosDB you are seeing relates to ETAG mismatches - this error has come up in Dapr when serialization requests and responses is incorrect (as was the case in 1.10.5)

**Comment by anna-jankowska** [comment]
@berndverst could you walk me through deletion of these reminders? I see plenty of records in cosmos db. New stuff always appear when we restart k8s pods. 

```
SELECT count(c) FROM c WHERE STARTSWITH(c.id, 'actors') AND c.id LIKE '%reminders%' 
-- 7364
```

a) Do these need to be deleted while dapr actors are inactive?
b) How do I narrow down the query to delete what needs to be deleted, nothing more, and nothing less?

**Comment by joshuadmatthews** [comment]
@berndverst  I am seeing this issue again on 1.13.4

any ideas what might be wrong? I saw the other issue being worked on for 1.14 about multiple workflow apps running, but in my case there’s just one, yet I am getting

“Failed with o non-recoverable error: failed to invoke ‘AddWorkflowEvent’ method on workflow actor: error from internal actor: error saving reminders partition and metadata: transaction failed due to operation 1 which failed with status code 412

**Comment by KrylixZA** [comment]
Hi @berndverst / @yaron2 

Hoping to revive this thread a little. We are seeing this issue with Dapr 1.14.4. It's not very common, but once is enough to peak our interest in a solution.
