### ISSUE TITLE
dapr 1.11 invoking dapr 1.12 got error

### ISSUE THREAD

**Issue by heavenwing** [dapr/dapr#7227]
## In what area(s)?

 /area runtime

## What version of Dapr?

1.11.x
1.12.x

## Expected Behavior

dapr 1.11 sidecar can invoking dapr 1.12 sidecar successfully 

## Actual Behavior

After upgraded dapr version into 1.12 in AKS cluster, I just restart some applications (it's be injected dapr 1.12), but don't restart others (still keep dapr 1.11).

When un-restarted application send invocation to restarted application ,I got x509 error like this
![60bb6dfbfa313f95abf0bb5f7b3b940](https://github.com/dapr/dapr/assets/2920062/b9bcadf3-ad66-4517-98b5-45e9e088f67b)

## Steps to Reproduce the Problem

follow up above description

**Comment by ItalyPaleAle** [comment]
seems related to mTLS

CC @JoshVanL

**Comment by Admiralkheir** [comment]
We also noticed this issue. I got the error in the kubernetes cluster I run with kind in my locale. The reason is that when we upgrade dapr to version 1.12.2 with helm, the tls cert under dapr-trust-bundle is also updated and does not use the old one. When I upgrade to version 1.11, it uses the old tls cert, this secret does not update. Until this time, we normally did not have a problem with upgrades, it always used the old cert, but this secret to be updated with 1.12.
