### ISSUE TITLE
workflow engine not started if `/TaskHubSidecarService/GetWorkItems` is not called

### ISSUE THREAD

**Issue by famarting** [dapr/dapr#7449]
## In what area(s)?

/area runtime

## What version of Dapr?

> edge: v1.11.3-549-gcc9d51e1-dirty

## Expected Behavior

I'm testing the the upcoming workflow go sdk and I was getting an error like `did not find address for actor dapr.internal.myns.myapp.workflow/a7a4168d-3a1c-41da-8a4f-e7f6d9c718d9` when my app tried to start a workflow. Its expected to not have any errors and my workflow to start successfully.

## Actual Behavior

As I said I was getting an error like  `did not find address for actor dapr.internal.myns.myapp.workflow/a7a4168d-3a1c-41da-8a4f-e7f6d9c718d9`

Digging into my dapr sidecar logs I noticed only two requests were being made in my test:
- first a request to `/TaskHubSidecarService/Hello`
- then a request to `/dapr.proto.runtime.v1.Dapr/StartWorkflowBeta1`

The error I was getting means that the internal actors used for workflow were not actually registered, and looking at the workflow engine code, the internal actors are only registered when the workflow engine is started and I wasn't seeing this log entry https://github.com/dapr/dapr/blob/master/pkg/runtime/wfengine/wfengine.go#L160C17-L160C40

So the root cause must have been that the go sdk was not making a request to `/TaskHubSidecarService/GetWorkItems` and because of that this callback was not being executed https://github.com/dapr/dapr/blob/master/pkg/runtime/wfengine/wfengine.go#L90, resulting in the workflow engine not being initialized...

A simple solution I can propose consists of adding a callback to autoStart the workflow engine to https://github.com/dapr/dapr/blob/master/pkg/runtime/wfengine/component.go#L53 and that callback would be called on every function of `workflowEngineComponent` except for the `Init` function, this way whenever a request to the workflow management APIs it will be guaranteed that the workflow engine is started

## Steps to Reproduce the Problem

Try the workflow example included here https://github.com/dapr/go-sdk/pull/487

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
cc @cgillum @RyanLettieri

**Comment by cgillum** [comment]
Indeed, this is related to the work we did to start the workflow engine only after we've detected that an app has connected to it. This is unfortunately one of the side effects of that design decision. I think your proposed solution sounds like a good one that still maintains the spirit of the original delayed-start design.

One thing I'll note about that sample, however, is that we strongly discourage developers from using the DaprClient to manage workflows since that API was designed to be generic for any arbitrary workflow engine (a strategy we have since abandoned). They should instead use the `DaprWorkflowClient` (or equivalent for their language), which has access to the full feature set and metadata for Dapr workflows. I'll need to double check the Go SDK contribution to see whether it's properly exposing this functionality.

**Comment by famarting** [comment]
Thinking of this, if a client has not called `GetWorkItems` before it tries to start a new workflow if that fails that is a problem of the application.

I've got my sample go application finally working and the source of my problems was that the `GetWorkItems` was silently failing for me
