### ISSUE TITLE
Sidecar not injected into pods in namespace labelled with kubernetes.azure.com/managedby: aks

### ISSUE THREAD

**Issue by tobycouchmanmicrosoft** [dapr/dapr#7513]
## In what area(s)?

> /area runtime

> /area operator

 /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.12.x

## Expected Behavior

Deploying pod into non-default namespace in AKS cluster results in the sidecar being injected correctly

## Actual Behavior

For new namespace in AKS, they have the label `kubernetes.azure.com/managedby: aks`, and for some reason this prevents the sidecar being injected into a pod.

## Steps to Reproduce the Problem

- Create dapr app and deploy to a custom (non-default) namespace in AKS - dapr itself should be deployed to the default
- observe that the injection doesn't happen

## Release Note

**FIX**: an issue where dapr sidecar injection doesn't happen for pods in non-default namespaces in AKS where the namespace is annoted with kubernetes.azure.com/managedby: aks

RELEASE NOTE:

**Comment by berndverst** [comment]
Do you use the AKS extension or do you deploy manually via helm?

**Comment by berndverst** [comment]
@tobycouchmanmicrosoft I suggest filing this issue against the AKS team (or the AKS extension at least if that's what you are using).

Dapr uses a mutating admissions webhook for deployment objects. This modifies any deployment object created in K8s. We even specify the `reinvocationPolicy` so that if multiple mutating webhooks exist, ours gets reinvoked after another webhook (for example an AKS system component - for example AKS Workload Identity) makes changes.

I don't think there is anything Dapr OSS can do here.

How does AKS create and manage these `managedby: aks` namespaces? Maybe it deletes everything from those namespaces which didn't go through a particular AKS tool / process. If so, you really should direct this request at the AKS team.

**Comment by tobycouchmanmicrosoft** [comment]
Thanks for the response and insight @berndverst.  I will try and find out a little more about this managedby label and under what circumstances it gets added.  The reason I raised this here first was just in case there was an 'aha' moment from someone with knowledge of the admissions webhook.
