### ISSUE TITLE
Dapr Sidecar Missing on Some Pods After AKS Node Pool restarts/scales

### ISSUE THREAD

**Issue by mohit-clootrack** [dapr/dapr#7552]
## In what area(s)?

/area runtime

/area operator

## What version of Dapr?

1.12.1

## Expected Behavior

After restarting or scaling the AKS node pool, I expect all deployments annotated for Dapr to start with their respective Dapr sidecar containers. The pods should show as 2/2 containers ready, indicating both the application and the Dapr sidecar are running.

## Actual Behavior

Randomly, some deployments do not get the Dapr sidecar container after an AKS node pool restart or scale operation. The pods for these deployments show as 1/1 containers ready, indicating only the application container is running without the Dapr sidecar.

## Steps to Reproduce the Problem

1. Use Dapr version 1.12.1 in an AKS environment.
2. Annotate several deployments with Dapr sidecar injection.
3. Manually scale down and then scale up the AKS node pool or restart the node pool.
4. Observe that randomly, some deployments will not have the Dapr sidecar container running.

## Release Note

RELEASE NOTE: **FIX** Dapr Sidecar Missing on Some Pods After AKS Node Pool restarts/scales

**Comment by yaron2** [comment]
This is a known issue that might see an improvement in 1.13. However, the recommended mitigation is this: https://docs.dapr.io/concepts/dapr-services/operator/#injector-watchdog.

**Comment by mohit-clootrack** [comment]
Thank you, @yaron2. The suggestion to use the injector watchdog was effective and resolved our issue.

**Comment by joshuadmatthews** [comment]
@yaron2 we recently experienced something that seems like this in production, after a node_pool version upgrade we saw that some of our pods were struck in a crashloop and we had to delete the pods to fix it. Looking at the logs, it appears the pods were failing due to no sidecar existing. The containers attempted to restart over and over, but the pods remained static without a sidecar so the restarts were ineffective.

Does this sound like a typical failure state that watchdog is meant to address? It mentions scale operations and full cluster outages, would a node version upgrade fall into the possible causes?

**Comment by yaron2** [comment]
> [@yaron2](https://github.com/yaron2) we recently experienced something that seems like this in production, after a node_pool version upgrade we saw that some of our pods were stuck in a crashloop and we had to delete the pods to fix it. Looking at the logs, it appears the pods were failing due to no sidecar existing. The containers attempted to restart over and over, but the pods remained static without a sidecar so the restarts were ineffective.
> 
> Does this sound like a typical failure state that watchdog is meant to address? It mentions scale operations and full cluster outages, would a node version upgrade fall into the possible causes?

Yes, the watchdog should cover for these cases.
