### ISSUE TITLE
HPA on deployments containing dapr sidecar cpu issue

### ISSUE THREAD

**Issue by IQHT-DGH** [dapr/dapr#7813]
We have enabled HPA for deployments in out development cluster with a view to implementing on our production clusters.  We have noticed that all our deployments that do not use dapr are working fine seeing both cpu and memory utilisation and therefore scaling the pods as necessary, however this is not the case for any workload that includes a dapr sidecar those only see memory utilisation, and we receive the following message for every sidecar enabled workload.

failed to get cpu utilization: missing request for cpu in container daprd

I have spent a lot of time trying to workout what the issue is, but I cannot spot a problem in the configuration, is there something obvious that I'm missing here, as I'm sure I can't be the only person that has seen this issue.

Thanks in advance for any pointers.

![image](https://github.com/dapr/community/assets/88787465/f57445c0-a800-40fd-82ea-e0b7f7066f7c)

![image](https://github.com/dapr/community/assets/88787465/71c63ad7-c052-4114-b0cd-8854d9919530)

**Comment by masmontanas** [comment]
Related to issue #4718 .

We just ran into this issue ourselves -- surprised it hasn't come up more often.

When the are multiple containers defined in a deployment resource, those containers need to have the resource settings defined under the 'spec' field in order for the HPA to calculate the utilization average across all pods/containers for a given deployment, and trigger a scale out.  What's interesting is that this only seems to be the case for memory, as when we were using cpu based scaling with the native HPA this issue did not come up.

If others are experiencing stability issues because of an inability to scale, as we are, I would recommend using the gatekeeper project (or otherwise leverage the mutating admission controller) to define a constraint template to mutate the deployment resource dynamically. Given the breadth of configuration data related to running the daprd sidecar in kubernetes I don't think it would be feasible to explicitly configure everything in a given deployment manifest.

I will reply to the issue if I find anything promising, though need to prioritize the mitigation.

For a summary of impact (needs research, but there's some strong anecdotal data here):  When using the kubernetes integration to run daprd as a sidecar, and configuring all the sidecar/integration parameters via annotations as is the recommended approach, the default HPA will not be able to trigger a scale out when the average memory utilization trigger is being used.

We are using the AKS service and running k8s v1.28.5.

**Comment by masmontanas** [comment]
Related to issue https://github.com/dapr/dapr/issues/4718 .

We just ran into this issue ourselves -- surprised it hasn't come up more often.

When the are multiple containers defined in a deployment resource, those containers need to have the resource settings defined under the 'spec' field in order for the HPA to calculate the utilization average across all pods/containers for a given deployment, and trigger a scale out. What's interesting is that this only seems to be the case for memory, as when we were using cpu based scaling with the native HPA this issue did not come up.

If others are experiencing stability issues because of an inability to scale, as we are, I would recommend using the gatekeeper project (or otherwise leverage the mutating admission controller) to define a constraint template to mutate the deployment resource dynamically. Given the breadth of configuration data related to running the daprd sidecar in kubernetes I don't think it would be feasible to explicitly configure everything in a given deployment manifest.

I will reply to the issue if I find anything promising, though need to prioritize the mitigation.

For a summary of impact (needs research, but there's some strong anecdotal data here): When using the kubernetes integration to run daprd as a sidecar, and configuring all the sidecar/integration parameters via annotations as is the recommended approach, the default HPA will not be able to trigger a scale out when the average memory utilization trigger is being used.

We are using the AKS service and running k8s v1.28.5.
