### ISSUE TITLE
issue webhook "sidecar-injector.dapr.io" sentry SignCertificate

### ISSUE THREAD

**Issue by tupt100** [dapr/dapr#7874]
i am using eks verson 1.30 and suddenly today I got an issue: Error creating: admission webhook "sidecar-injector.dapr.io" denied the request: error from sentry SignCertificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing : dial tcp 10.16.113.43:443: connect: connection refused"
for all my replicas

**Comment by ytimocin** [comment]
I started running into this on AKS:

> kubectl run -i --tty --rm debug --image=busybox --restart=Never -- sh
**Error from server: admission webhook "sidecar-injector.dapr.io" denied the request: error from sentry SignCertificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 172.16.53.236:443: connect: connection refused"**

![image](https://github.com/dapr/dapr/assets/5220939/02c0bfc1-baf5-4aaf-ac0b-b09d27125225)

**Comment by ytimocin** [comment]
Were you able to find a workaround for this @tupt100?

**Comment by tupt100** [comment]
> Were you able to find a workaround for this @tupt100?

Not yet

**Comment by rtomchinsky** [comment]
@tupt100 were you able to resolve this?

In my case, the Sentry deployment only has one desired replica, and its ReplicaSet can't spin it up because the sidecar injector fails due to there being no Sentry pods to work with. Was the IP 10.16.113.43 for the Sentry service?

In other places that I see, there are always at least two Sentry replicas, so if one goes down, the other can still respond to requests, but with there only being a single replica, when it went down, it can't come up again.

I believe it's because of [this piece of code](https://github.com/dapr/dapr/blob/635dc49f9548130435a15286e03a3389fdb62801/pkg/injector/service/pod_patch.go#L54-L57). From what I'm reading, it tries to get the trust anchors from Sentry to do the injection even for pods that don't require injection.
