### ISSUE TITLE
Support Helm v3.0 for deployments into Kubernetes

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#793]
> /area runtime
> /area operator
> /area docs

With the release of Helm v3.0 https://www.cncf.io/news/2019/11/13/helm-reaches-version-3/ need to ensure that Helm charts and deployments can use this.

**Comment by lukekim** [comment]
A lot of people will stay on Helm 2 for some time, so we should support both for probably the next 6 months or so.

**Comment by yaron2** [comment]
Yes, actually the charts under the `helm` org themselves have not moved to Helm 3..

For example, a few components that Dapr is using, still with Helm 2 on their docs: (`--name` has been removed from Helm 3)

https://github.com/helm/charts/tree/master/stable/nats#installing-the-chart
https://github.com/helm/charts/tree/master/stable/redis#installing-the-chart
https://github.com/helm/charts/tree/master/stable/mongodb#installing-the-chart

**Comment by youngbupark** [comment]
JFYI, @lukekim @yaron2 

Dapr chart is installable by helm2 and helm3 without any changes. We can use helm3 for kafka and redis charts without any changes.

For helm 3, `--name` is not required and `--namespace` doesn't create namespace unless it exists. other than these changes, helm3 works as expected for dapr project. 

cc/ @artursouza

**Comment by yaron2** [comment]
It's not that --name is not required, it's not supported.

Thus, every place in our docs that uses --name and/or --namespace does not work with Helm 3.

**Comment by youngbupark** [comment]
> It's not that --name is not required, it's not supported, and will throw an error if used with Helm 3.
> 
> Thus, every place in our docs that uses --name and/or --namespace does not work with Helm 3.

yeah right. helm3 changed the flags and options without backward compat. e.g. `--name` option is dropped. 

With the latest helm3, `--namespace` option can still install dapr to `dapr-system` namespace, but `dapr-system` namespace needs to be created by kubectl before running helm3 install. `creation` of namespace is dropped due to the [security reason](https://github.com/helm/helm/issues/5753#issuecomment-502163585), but we can still install app to the namespace at least. 

```
helm install dapr dapr/dapr --namespace=dapr-system
```

My point is that we do not need to change our charts especially for helm3 even if we need to update docs for helm3

**Comment by yaron2** [comment]
Yeah, the chart itself does not need changing.

**Comment by dbarkol** [comment]
gave this a try today and it worked with helm 3: helm install --repo https://daprio.azurecr.io/helm/v1/repo mydapr dapr

**Comment by youngbupark** [comment]
Closing.
