### ISSUE TITLE
Dapr - Secret scoping for components

### ISSUE THREAD

**Issue by rochabr** [dapr/dapr#8176]
## In what area(s)?

/area runtime

## Describe the feature

Currently, Dapr allows developers to limit the secrets that can be read from component secret stores by defining scopes in a configuration file. However, even by setting a deny clause for all secrets from a store, these secrets can still be referenced from another component.

Dapr should add allow/deny access to components to reference secrets, as well.

**Comment by artursouza** [comment]
We need to reach a decision here. To clarify:
1. Secret store S is configured and denies access to app A.
2. Component C references a secret from S.
3. Today, app A loads component C successfully.

In my opinion, this is a security vulnerability because app A can configure any component that will expose the secrets it does not have access to.

There is a scenario where app A is only allowed to have access to one or more specific secrets from S, but not all - this would be a new feature. Basically, give fine grained access control to secrets in a secret store.

**Comment by rochabr** [comment]
Works as intended.
