### ISSUE TITLE
Connection Error: Failed to Watch Scheduler Jobs in Dapr 1.14.4

### ISSUE THREAD

**Issue by ernstc** [dapr/dapr#8214]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.14.4

## Expected Behavior

Scheduler jobs should be watched without connection errors.

## Actual Behavior

Receiving the following error message:

`level=error msg=“failed to watch scheduler jobs, retrying: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:6060: connectex: No connection could be made because the target machine actively refused it."” app_id=web instance= scope=dapr.runtime.scheduler type=log ver=1.14.4`

## Steps to Reproduce the Problem

1. Run Dapr version 1.14.4 on a local machine using Docker Desktop.
2. Attempt to watch scheduler jobs.

## Release Note

RELEASE NOTE: **FIX** Bug in runtime causing scheduler job watch failures due to connection errors.

**Comment by cicoyle** [comment]
Hi @ernstc - The error message suggests that the Dapr sidecar is having trouble connecting to the Scheduler service, likely because the Scheduler instance is down or unreachable. Do you know if the Scheduler might have been down when this error occurred?

Additionally, it could be related to the port not being open or listening, or there may be network or firewall issues preventing communication between the sidecar and the Scheduler. Could you provide more details about the environment where you encountered this issue?

**Comment by ernstc** [comment]
Hi @cicoyle, I am running Dapr locally with Docker. It seems that the ports used by the scheduler were reserved by another process. Running the commands below in the Terminal with elevated privileges, I have been able to resolve the issue:

1. Uninstalled Dapr with `dapr uninstall`
2. Run `net stop winnat`
3. Run `net start winnat`
4. Install Dapr with `dapr install`

Now the issue is not happening again. So, I close the issue.

**Comment by emmanuel-messegue** [comment]
Hi,
I triec this workaround but it didn't work
