### ISSUE TITLE
Unable to push forked repo due to workflow permissions

### ISSUE THREAD

**Issue by stather** [dapr/dapr#854]
## In what area(s)?

> /area git

## What version of Dapr?

> 0.2.x

## Expected Behavior

push from local to forked repo should work to a allow sync from upstream. 

## Actual Behavior

Fails due to permissions on workflow in .github directory

## Steps to Reproduce the Problem

Pull from upstream/master
push to origin/master

**Comment by fbeltrao** [comment]
@stather I had the same problem. My solution was to use GitHub Desktop.

**Comment by stather** [comment]
Hi. Sadly I am using git desktop and have the problem.

**Comment by artursouza** [comment]
Here is what I do to update my forked repo:
$ git clone <My forked repo>
$ cd dapr
$ git remote add upstream <main repo>
# After upstream moves ahead due to any change:
$ git checkout master # to make sure I am in the master branch, tracking origin/master
$ git fetch upstream
$ git merge upstream/master
$ git push

What is the difference in your workflow?

**Comment by stather** [comment]
Ok, I deleted my fork and started again, so seems fine now.
