### ISSUE TITLE
Proposal: Automatic mTLS

### ISSUE THREAD

**Issue by yaron2** [dapr/dapr#882]
# Proposal: Automatic mTLS

This proposal looks to add automatic, on by default mutual tls between Dapr sidecars to provide secured in-transit encryption of traffic when running in zero-trust network scenarios.

Core goals of the solution are to enable transparent encryption that does not force any change or update on user application code, keeping it simple to configure with explicit, well known behaviors.

The solution should work across all hosting platforms, Kubernetes and self-hosted, and design-wise accommodate future work like authorization policies.

Differing from mTLS found in Service Meshes like Linkerd, Consul Connect or Istio, mTLS in Dapr will be used for the application layer, applying for Dapr to Dapr traffic and not for network requests that do not go through the Dapr sidecar.

## Architecture

The following parties participate to provide mTLS:

* **Existing** Dapr Sidecar - running next to the user app, communicating over localhost in the same shared network namespace. Communicates with the Security Service.

* **New** Security Service - A separate process acting as a certificate authority. The Security Service receives CSR (Certificate sign request) requests from the Dapr sidecar, validates and signs the request, and returns a valid certificate for a configurable time window (default to 1 hour).

### Sidecar
The Dapr sidecar contacts the Security Service on startup, and uses a root cert from a local mount to identify with the Security Service over a secured gRPC connection.
The identity of the Dapr app, provided by `dapr.io/id` on Kubernetes or the `--app-id` flag to the `daprd` process acts as an identify subject on the CSR and will be used in the future for authorization policies.

The sidecar generates a private key which is *never* stored on disk and kept in memory, and together with the root cert is bundled into a CSR that is sent over gRPC to the Security Service. Once the response comes back, assuming validated and signed, a certificate is extracted from the response and used for the local Dapr gRPC server, authenticating cross-sidecar communications.

The sidecar proto service in [daprinternal](https://github.com/dapr/dapr/blob/master/pkg/proto/daprinternal/daprinternal.proto) will add a new method for updating a certificate. This method is invoked by the Security Service when certificates gets rotated.

### Security Service (Sentry)

The security service is a process that acts as a certificate authority and rotation mechanism.
On startup, it examines for the existence of an issuer on disk. If a exists, the CA is created and can start receiving CSR requests from the Dapr sidecars.

The security service will fail if an issuer cert is not found.

The security service will watch for any changes for the root cert and issue a new issuer certificate if needed.

The root certificate (trust anchor) will be created automatically by Dapr using the Helm chart or the Dapr CLI, and a user can bring their own root cert.

The Security Service exposes a gRPC connection that authenticates requests from sidecars using the root cert.
After successfully validating a request, the service will generate a certificate and return it to the sidecar, storing the workload certificate on a secret store.
The workload cert is valid for a default of one hour, and is configurable by the cluster operator using the Dapr Configuration CRD.

The Security Service will rotate the certificates for the sidecars and update them by calling into the sidecar.

#### Enable/Disable

mTLS will be enabled by default. To opt-out, the following configuration will be applied:

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: cluster-config
spec:
  mtls:
     enabled: false
```

### Solution Diagram

<a href="https://ibb.co/nkSkgGc"><img src="https://i.ibb.co/0J3JD7M/Screen-Shot-2020-01-15-at-5-24-56-PM.png" alt="Screen-Shot-2020-01-15-at-5-24-56-PM" border="0"></a>

**Comment by youngbupark** [comment]
Thanks for writing this proposal :) I have some questions and feedback on this proposal:

1. system clock-skew on each node - in this proposal, we may not need to consider the clock-skew on each node because secret service will notify each app of new cert.

2. fallback workload cert when it is rotated - in the time window where the cert is rotated, caller app could not get the notice from security service while callee app could get it. then caller app will use the old cert, but callee app will use new cert then auth step will be broken.

3. Instead of introducing new Security service, can Dapr runtime process handle the cert by itself for the simplicity? for example, let's store two certs, such as`primary-cert` and `secondary-cert` into secret store because each dapr can access the same secret store. caller and callee load two certs into the valid cert pool. cert has 1 hour expiry. Assume caller uses `primary-cert` as a valid cert(if two certs are valid, it will pick the soonest expired cert). Its expiry left 10 to 15 minutes (considering clock-skew margin). the caller updates another cert `secondary-cert` if `secondary-cert` is expired. The other callers can update secondary-cert simultaneously, but it doesn't matter because `primary-cert` will be used for the current grpc request. so in this situation, `primary-cert` and `secondary-cert` are both valid. callee also has primary-cert and secondary-cert in its cert pool. callee will use the valid cert, but the soonest expired cert (`primary-cert`); callee could have expired cert in `secondary-cert` secret in this time window because callee didn't load the latest cert from secretstore (maybe worker loop inside dapr runtime needs to read both certs regularly). I don't describe all scenarios but I think it is doable without security service. Then we do not need to maintain additional root cert, either. This is just another idea to implement the safe cert rotation without additional service because dapr runtime side car can access the shared secret store.

**Comment by yaron2** [comment]
> 1. system clock-skew on each node - in this proposal, we may not need to consider the clock-skew on each node because secret service will notify each app of new cert.

Yes, we do not need to consider system clock skew.

> 2. fallback workload cert when it is rotated - in the time window where the cert is rotated, caller app could not get the notice from security service while callee app could get it. then caller app will use the old cert, but callee app will use new cert then auth step will be broken.

The caller will have retries for errors relating to certificate mismatch

> 3. stead of introducing new Security service, can Dapr runtime process handle the cert by itself for the simplicity?

Unfortunately, because of security reasons it's required to have a separate service with it's own RBAC permissions and it's own access to a specified secret store.
This is essentially the same architecture as other service meshes have in regards to CA, where the sidecar does not act as it's own CA. Users with access to manage the sidecars don't always need to have the same level of access to manage the CA. If we have the CA inside the sidecar, we make the surface of attack on the sidecar bigger.

The sidecars should not have access to where the root cert resides. The information of where to take the root cert from should be visible only to the CA, which can and should be deployed to it's own namespace with access to a namespaced secret that the sidecars can't access. On Kubernetes this can be done with RBAC for a secret, for self hosted this is configuration that's deployed with the Security Service.

In addition, later features like strong identities and policy authorization will be easier to manage through a discrete service that handles security.

Separating the concerns of authorization of the runtime from the runtime itself, IMO, is preferred.

**Comment by yaron2** [comment]
^ also related to 2, the CA updates the certificates when they *near* expiry and not after they've expired.

**Comment by youngbupark** [comment]
Thanks for the explanation. For 3, Yeah that makes sense if security service has its own rbac permission and solely access to the secretstore without sharing it with dapr sidecar. I was thinking it would share the same secrete store with dapr runtime and cert secret could be isolated by dapr runtime with some prefix.

**Comment by yaron2** [comment]
Need to name the security service. Suggested names: sentinel, defender, sentry, guardian, gatekeeper.

**Comment by yaron2** [comment]
tracking:

#889

**Comment by artursouza** [comment]
I have a few questions:

1. Why is the auto-generated root cert valid for 10 years? I would expect it to be valid for up to 2 years and rotated. Also, can you detail how to rotate the root cert? I assume there is a manually uploaded option and an auto-generated option.

2. It seems that the private key and signed certificate are kept in memory, right? Is there a way to secure this in-memory content from a memdump? Probably it is not possible since we would need to have another key to encrypt the certificate and have, again, a secret in memory. Maybe optionally integrate with an HSM to have an zero-unencrypted secret solution?

3. We should probably have a time window where the sidecar has two valid certificates to have a zero-downtime rotation.

4. What is the surface attack for the communication between dapr sidecar and the security service? Can the request be intercepted by man-in-the-middle type of attack?

**Comment by igalfsg** [comment]
Thanks for this awesome proposal :)  I have a few questions:

> system clock-skew on each node - in this proposal, we may not need to consider the clock-skew on each node because secret service will notify each app of new cert.

1. how does the secret service notify each app?

2. It seems that the root private key is used by the node to get the first certificate (for bootstrap) is that the case? or is there a "bootstrap certificate" pre-installed in the nodes to request the first cert?

3. I agree with @artursouza on the software key should not be valid for 10 years. Usually Root CAs that are valid for that long are offline CAs with HSM backing, Online CAs and more with software based keys should be short lived to avoid a long lasting effect of a compromise. 

4. Is the previous cert being used to generate the cert request? is the same key allowed or each time a new key is generated?

**Comment by yaron2** [comment]
> how does the secret service notify each app?

The diagram here isn't updated, it doesn't notify each app. The Dapr sidecar requests a new cert once the current cert reaches 70% (or configurable) of its lifetime, with the exact same mechanism it uses when it comes up to request a cert.

> 2. It seems that the root private key is used by the node to get the first certificate (for bootstrap) is that the case? or is there a "bootstrap certificate" pre-installed in the nodes to request the first cert?

the private key is generated inside the Dapr sidecar, for each Dapr sidecar and is kept in memory. this is the workload certificate that's valid for a configurable amount of time (4h by default). There's a root cert that's mounted on each Pod in a read only volume to establish mTLS between the Dapr sidecar and the security service

> 3. I agree with @artursouza on the software key should not be valid for 10 years. Usually Root CAs that are valid for that long are offline CAs with HSM backing, Online CAs and more with software based keys should be short lived to avoid a long lasting effect of a compromise.

We'll make that configurable. I put 10 years because that's what [Istio uses](https://istio.io/news/releases/1.2.x/announcing-1.2/change-notes/#security) and we'd like to provide a similar experience.

> 4. Is the previous cert being used to generate the cert request? is the same key allowed or each time a new key is generated?

on each CSR request from the Dapr sidecar to the security service (CA), a new private key is generated.

**Comment by yaron2** [comment]
Updated diagram.

**Comment by igalfsg** [comment]
> the private key is generated inside the Dapr sidecar, for each Dapr sidecar and is kept in memory. this is the workload certificate that's valid for a configurable amount of time (4h by default). There's a root cert that's mounted on each Pod in a read only volume to establish TLS between the Dapr sidecar and the security service

is this just the public key? if so how is the initial trust created?

**Comment by yaron2** [comment]
> > the private key is generated inside the Dapr sidecar, for each Dapr sidecar and is kept in memory. this is the workload certificate that's valid for a configurable amount of time (4h by default). There's a root cert that's mounted on each Pod in a read only volume to establish TLS between the Dapr sidecar and the security service
> 
> is this just the public key? if so how is the initial trust created?

The trust between the sidecar and the security service is made with the root cert that gets mounted to every dapr sidecar.

**Comment by artursouza** [comment]
Proposal has been accepted. Closing.

**Comment by yaron2** [comment]
Re-opening for visibility.

**Comment by yaron2** [comment]
Solution architecture text and diagram updated.

**Comment by rverma-nikiai** [comment]
Why can't we use istio(or other service mesh) for auto mtls. I am wondering what dapr is targeting, is it to become another service mesh?

**Comment by yaron2** [comment]
> Why can't we use istio(or other service mesh) for auto mtls. I am wondering what dapr is targeting, is it to become another service mesh?

You can certainly use a service mesh to do mTLS. Dapr cannot assume the existence of a service mesh for secured communications, and at the same time needs to provide users with in transit encryption.

So the goal is to enable secured communications for Dapr users, not becoming a service mesh.

**Comment by exosapp** [comment]
For us its critical to get mtls with dapr. why should we use Istio which is too bloated if dapr gives us mtls..

**Comment by yaron2** [comment]
This is now feature complete for 0.4.0.

**Comment by artursouza** [comment]
Thanks!
