### ISSUE TITLE
Integration Dapr with the API Management gateway (managed & self-hosted)

### ISSUE THREAD

**Issue by MedAnd** [dapr/dapr#955]
## Vision & Rationale

The API Management gateway helps organizations publish APIs to external, partner, and internal developers to unlock the potential of their data and services. Given DAPR is the future of distributed apps in Azure, first class integration with the API Management gateway will unlock numerous Azure integration scenarios and best practices such as: 

- Decoupling APIs and presenting facades
- Getting developers up and running quickly
- Securing access
- Analytics and metrics
- Gaining control and insight with an API Management platform
- Caching

> The self-hosted gateway expands API Management support for hybrid and multi-cloud environments and enables organizations to efficiently and securely manage APIs hosted on-premises and across clouds from a single API Management service in Azure.

## Feature

Implement efficient, native DAPR request routing and integration with the API Management gateway (managed & self-hosted options) supporting:

1. AKS clusters / ARC clusters
2. Service Fabric clusters
3. Actors
4. Partitioned & stateful services (for platforms that support this functionality)
5. Response caching
6. SSL termination
7. Azure AD integration

etc

**Comment by yaron2** [comment]
Thanks for this issue.

I agree (and can see others agree too..) that advanced API capabilities are indeed lucrative for developers using Dapr.

I think that because of the way we model our building blocks, there's a good chance we already cover  some of the features here, and will soon cover others.

> Securing access

Dapr will have automatic mTLS with managed cert rotation in the next release.

> Analytics and metrics

Dapr already integrates with OpenCensus for tracing, and we have an issue open for emitting metrics from the Dapr runtime. Analytics could then be formed on top of the overall metrics and tracing data.

> Caching

This would be something quite easy to add to Dapr, caching state in memory for ultra fast access in each sidecar.

Dapr today supports rate limiting requests.

I think the two main things that would be challenging to tackle are API routes and securing APIs using tokens.

**Comment by MedAnd** [comment]
Having the above capabilities eventually and directly in DAPR will add to DAPR’s flexibility however feel the trend is towards meshes & gateway architectures that offer best in-class features? Would be great to hear from Vladimir’s team and also wider community... this feature request could just as easily refer to Kong etc.

**Comment by xewn** [comment]
Can api gateway use apisix?

**Comment by MedAnd** [comment]
For anyone following this feature request... hot off the press: [Announcing Dapr integration in Azure API Management Service](https://cloudblogs.microsoft.com/opensource/2020/09/22/announcing-dapr-integration-azure-api-management-service-apim/)

**Comment by mchmarny** [comment]
As @MedAnd said, this is straight of the press. We look forward to your feedback on the [initial Dapr integration in APIM](https://github.com/dapr/samples/tree/master/dapr-apim-integration). There is a lot more we could still do there, so real-world use-cases are instrumental in prioritizing. Thanks!

**Comment by xdmushui** [comment]
> Can api gateway use apisix?

Have you tried it? Could you share your experience?

**Comment by anhldbk** [comment]
@xdmushui I see a related blog here: https://medium.com/@ApacheAPISIX/how-to-integrate-with-dapr-to-build-apache-apisix-gateway-controller-28464b12b13f
