### ISSUE TITLE
Registering a reminder with the same name as an existing one should overwrite the first

### ISSUE THREAD

**Issue by LMWF** [dapr/dapr#973]
## In what area(s)?

/area runtime

## What version of Dapr?

0.3
## Expected Behavior

Registering reminders with the same `name` from the same actor should result in the 2nd registration overwriting the first.

## Actual Behavior

Subsequent reminder registrations using the same name (but different state/duetime/period) result in additional registered reminders.

## Steps to Reproduce the Problem

Call register reminder 3 times, eg
```
    super.registerReminder(
        name,
        "40",
        Duration.ofSeconds(1),
        Duration.ofSeconds(2)).block();

      System.out.println("registering again");
      super.registerReminder(
        name,
        "42",
        Duration.ofSeconds(1),
        Duration.ofSeconds(2)).block();

      System.out.println("registering again again");
      super.registerReminder(
        name,
        "41",
        Duration.ofSeconds(2),
        Duration.ofSeconds(2)).block();
```
All 3 reminders will fire.

When unregister is called using `name`, only 1 is removed - the other 2 keep firing.

**Comment by garretmagin** [comment]
Possibly slightly related, when a reminder is registered after being unregistered there appears to be state from the previous reminder reused. The reminder does not fire at dueTime instead it fires on the period.

**Comment by vinayada1** [comment]
I was able to repro this issue by using a modified version of the dotnet sdk sample. I modified the ActorClient code to register the reminder 3 times in quick succession. I changed the DemoActor::RegisterReminder() implementation to modify the due to a random number between 1-10 (to ensure the reminder data changes in every registration).

By adding logs in the code, I found two issues:-
Issue#1: The existing logic, inside CreateReminder code, when sees the same reminder is re-registered but needs update, calls DeleteReminder on the old one and then continues as if a new reminder is added. The DeleteReminder code cancels the old reminder values by calling a.activeReminders.Load(reminderKey) and then calling delete. However, the activeReminders is updated by the CreateReminder in a go routine inside startReminder func. Since the reminders were called in quick succession, the sequence was this:-
1. Reminder with values A created
2. Go routine inside startReminder that adds reminder with values A scheduled (not executed)
3. Reminder with values B create request comes in
4. Try to delete reminder by calling a.activeReminders.Load(reminderKey) but entry not found
5. Go routine inside startReminder that adds reminder with values B scheduled (not executed)
and so on

Issue#2: Every time a reminder is registered with new values, a.activeReminders is updated with a new stop channel. However, the DeleteReminder that is called to cancel the old reminder, calls close on the old value of stop channel. Since the reminders were registered in quick succession, **after fixing Issue#1**, the order of events was:-
1. Reminder with values A created with stopChannelA
2. Go routine inside startReminder that adds reminder with values A scheduled (not executed)
3. Reminder with values B create request comes in
4. DeleteReminder deleted a.activeReminders(reminderKey) and closed stopChannelA
5. CreateReminder logic proceeded and updated a.activeReminders with stopChannel B
5. Go routine inside startReminder that adds reminder with values B scheduled (not executed)
6. Go routine for reminder with values A started execution. It gets the stop channel by looking up a.activeReminders which is now stopChannelB. This channel is not closed and therefore, reminder gets fired
7. Go routine for reminder with values B started execution. It gets the stop channel by looking up a.activeReminders which is now stopChannelB. This channel is not closed and therefore, reminder gets fired
