### ISSUE TITLE
Get state API returns data quoted instead of original value

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#974]
## In what area(s)?

 /area runtime

## What version of Dapr?

0.3.x

## Expected Behavior

In actor state store, the save API receives data as String but the get API returns it between quotes.
Saved data: "My String Data"
Retrieved data: "\"My String Data\""

## Actual Behavior
Get exactly as it was saved:
Saved data: "My String Data"
Retrieved data: "My String Data"

**Comment by youngbupark** [comment]
@artursouza what's the raw value in redis? I wonder if getactorstate returns the response after json-serializing `"My String Data"`.

**Comment by youngbupark** [comment]
@yaron2 I think we talked about this issue before. We need to have a time to revisit state data type. Also add more tests inside dapr core repo.

cc/ @amanbha

**Comment by dev-drprasad** [comment]
I suspect issue is in redis store implementation

https://github.com/dapr/components-contrib/blob/4433e605f1fec0488d40e8eebae5d59869470868/state/redis/redis.go#L202-L208

we are json-marshalling  `req.Value` except of type `[]byte`

One solution i can think of is cast `req.Value` to `string` and if operation succeed, then covert directly to byte array

Another solution is change `state.SetRequest.Value` from `interface{}` to `[]byte`. Now its store's client job to pass byte array. At current moment i see three parties using store: http-api, grpc-api, actors-api. With this change i think only actors-api will break as we are passing `struct` data to `state.SetRequest.Value` in some places

**Comment by youngbupark** [comment]
> I suspect issue is in redis store implementation
> 
> https://github.com/dapr/components-contrib/blob/4433e605f1fec0488d40e8eebae5d59869470868/state/redis/redis.go#L202-L208
> 
> we are json-marshalling `req.Value` except of type `[]byte`
> 
> One solution i can think of is cast `req.Value` to `string` and if operation succeed, then covert directly to byte array
> 
> Another solution is change `state.SetRequest.Value` from `interface{}` to `[]byte`. Now its store's client job to pass byte array. At current moment i see three parties using store: http-api, grpc-api, actors-api. With this change i think only actors-api will break as we are passing `struct` data to `state.SetRequest.Value` in some places

@dev-drprasad actor state uses transactional api - [Multi()](https://github.com/dapr/components-contrib/blob/4433e605f1fec0488d40e8eebae5d59869470868/state/redis/redis.go#L243-L258). I added the code which is similar to setValue, but we found the edge case and remove it. Unless we pass exact state datatype, we cannot find the right solution for this. 

I think we need to revisit state api set.

**Comment by amanbha** [comment]
@artursouza Does it needs to be fixed in runtime or state store impl?

**Comment by artursouza** [comment]
I just reran the integration tests for the Java SDK and read the keys via redis-cli. The Java SDK (currently) does not add quotes on insert or removes quotes on read but the state store still shows them as quoted strings. This seems to be a fix in the runtime. The comments from @dev-drprasad seems to be in that direction as well.

```
Last login: Wed Apr  1 13:51:27 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
[14:07:10] ~
$ redis-cli
127.0.0.1:6379> KEYS
(error) ERR wrong number of arguments for 'keys' command
127.0.0.1:6379> MGET
(error) ERR wrong number of arguments for 'mget' command
127.0.0.1:6379> list
(error) ERR unknown command `list`, with args beginning with:
127.0.0.1:6379> keys
(error) ERR wrong number of arguments for 'keys' command
127.0.0.1:6379> keys *
(empty list or set)
127.0.0.1:6379> keys *
1) "ActorStateIT_StatefulActorService||StatefulActorTest||1585775328261||message"
2) "ActorStateIT_StatefulActorService||StatefulActorTest||1585775328261||mydata"
127.0.0.1:6379> MGET "ActorStateIT_StatefulActorService||StatefulActorTest||1585775328261||message"
1) "\"This is a message to be saved and retrieved.\""
127.0.0.1:6379> MGET "ActorStateIT_StatefulActorService||StatefulActorTest||1585775328261||mydata"
1) "{\"value\":\"My data value.\"}"
```

**Comment by artursouza** [comment]
This issue still exists today and should be addressed prior to 1.0. It causes the data to be read to be different from what is written. The SDK sends it as part of a payload in a JSON request but is returned "JSONnized" data back.

Reproduced in https://github.com/artursouza/dapr-issues/tree/master/dapr/974

This is how the data is persisted in Redis:
```
$ ./read.sh 
"\"Hello World!\""
"{\"name\":\"Lamp\"}"
"\"AQ==\"
```

**Comment by yaron2** [comment]
Are string quoted when saving with gRPC also?

**Comment by artursouza** [comment]
This is for actors, it is over HTTP only.

**Comment by yaron2** [comment]
> This is for actors, it is over HTTP only.

I fear this is not only for actors though.

**Comment by youngbupark** [comment]
I think we fixed this issue in 0.11.0. Transactional api no longer use SET. If you use `GET` or `MGET` to see the data, the data would be the old data. Can you please try with HGETALL or Hxx command?

@mukundansundar didn't you validate this last time?

**Comment by mukundansundar** [comment]
@youngbupark The change was done by @tcnghia and validation unit tests were added. Though I do not know if it was locally viewed via the Redis console.

**Comment by yaron2** [comment]
> I think we fixed this issue in 0.11.0. Transactional api no longer use SET. If you use `GET` or `MGET` to see the data, the data would be the old data. Can you please try with HGETALL or Hxx command to get the data.
> 
> @mukundansundar didn't we validate this last time?

I was talking about the non transactional API..

**Comment by youngbupark** [comment]
non transaction state api is fixed by @mukundansundar

**Comment by mukundansundar** [comment]
I worked on the transaction state api only. https://github.com/dapr/dapr/commit/afbe726a56a3f165d8a86681ae9e1f608047a7a9

**Comment by youngbupark** [comment]
In sum, 

* transactional api serialization issue (actor state, non-actor transactional api) was fixed by [this pr](https://github.com/dapr/components-contrib/commit/d2ee3200cdf585d0bd67f89250512013b7fd9938#diff-8d6dfcfc7936e603c26a2ae1a53c245f16cbdf7bf44dabc35c240fa5d1edf93f) and [this pr](https://github.com/dapr/dapr/commit/afbe726a56a3f165d8a86681ae9e1f608047a7a9) 
* transactional api has used HSET instead of SET since 0.11.0 fixed by @tcnghia 
   So to get the correct value by using redis cmd, we need to use HGETxxx command instead of GETxxx commands
* non transactional state api has been fixed by @mukundansundar 's pr - [this pr](https://github.com/dapr/components-contrib/commit/d2ee3200cdf585d0bd67f89250512013b7fd9938#diff-8d6dfcfc7936e603c26a2ae1a53c245f16cbdf7bf44dabc35c240fa5d1edf93f)
   redis state store doesn't have that problem because it was handling bytes data properly, but the other state component always serialized it regardless of the type of data. @mukundansundar fixed this issue. 

I think we can double-check the serialization issue to close this issue.

**Comment by youngbupark** [comment]
@mukundansundar and I ran some test with python actor sdk and java actor-sdk.

**Dapr runtime doesn't add double-quotation to the string data**, but python-sdk adds double-quotation because python json serializer serializes `teststr` to `"teststr"` based on the [json spec](https://www.json.org/json-en.html).

Technically, if user calls save state api to save single string state via http api, user needs to pass double-quotation-added string(`"teststr"`) to save string state with `application/json` content-type.

Actor State API uses Transactional HTTP API which accepts the array of multiple operations with data and the entire payload is application/json content type. 

When user app calls HTTP get state to get the state saved by transaction API, the api needs to return double-quotation added string (`"teststr"`), which is json-serialized because the response body is application/json.

So to me, dapr runtime is working as expected.

@mukundansundar will share the test result with java-sdk.

**Comment by youngbupark** [comment]
> Dapr runtime doesn't add double-quotation to the string data, but python-sdk adds double-quotation because python json serializer serializes teststr to "teststr" based on the json spec.

This is wrong. Sorry for the confusion @artursouza 

I debugged the runtime code to double-check the value. sdk doesn't add double-quotation. redis state component json-serializes string value. This component saves data which is json-serialized. it bypassed only bytes array without any serialization.

gRPC API uses only bytes array as a value. redis component will save it as is without any serialization because it bypasses byte array. So to make the data value stored by http and gRPC api compatible, user app or SDK must pass json-serialized data to HTTP API and gRPC API. Otherwise, the values stored by two protocols are different.

BTW, if the stored data format in redis state store is JSON, then double-quotation added string behavior makes sense based on json spec. 

@artursouza @yaron2 @mukundansundar any thoughts?

**Comment by artursouza** [comment]
After talking to Young Bu, it is clear that this behavior is correct because redis is serializing into JSON consistently. In my example, the double quotation is expected because the string is serialized once and redis displays it with quotation. The object is also serialized once but redis (again) quotes in order to display.

Closing this issue.
